### ISSUE TITLE
关于运行 weex/examples

### ISSUE THREAD

**Issue by 7nights** [apache/incubator-weex-cli#10]
发现很多 demo 代码并不能跑起来，
比如写了一个非常简单的页面想尝试下 web 标签，结果直接报错了。
example 里的 web-demo.html 也同样跑不起来。
想问一下 weex-toolkit 对这些的支持是不是还是比较落后的？

**Comment by lvscar** [comment]
请具体帖一下跑不起来的例子?  

example里的的we文件如果依赖了weex-components , 需要专门安装下。

**Comment by lvscar** [comment]
如果某个we文件中require了weex-components , 你可以在终端中进入到该文件所在目录，然后执行

```
npm install weex-components 
```

安装依赖。 然后就能通过weex-toolkit预览了.
