### ISSUE TITLE
weex init 与weex create

### ISSUE THREAD

**Issue by tanrich** [apache/incubator-weex-cli#107]
请问这两个有什么却别？如果用init创建工程，就没办法platform add Android/IOS，请问如何支持？

**Comment by JackPu** [comment]
后面发的版本会抹平掉这个差异。

**Comment by acathur** [comment]
@JackPu 如何选择？`init` or `create`?

**Comment by JackPu** [comment]
@Acathur  建议用weex create

**Comment by sunsunyongjiu** [comment]
@JackPu create的项目怎么在pc上看效果，和手机联调，可以像weex-toolkit一样么
