### ISSUE TITLE
weex出错

### ISSUE THREAD

**Issue by gggggaochao** [apache/incubator-weex-cli#108]
![12](https://cloud.githubusercontent.com/assets/22069593/25689488/0f77c6ec-30bb-11e7-9ff1-7a02d42908a9.png)
![13](https://cloud.githubusercontent.com/assets/22069593/25689505/4509eb64-30bb-11e7-8eef-8482cb1a59e7.png)

我更新nodejs会显示第一张图的错误，npm安装weex-toolkit会显示第二张图的错误，求帮忙解决下

**Comment by casperSNSN** [comment]
遇到了同样的问题啊

**Comment by JackPu** [comment]
@gggggaochao  你重新安装node的最新的文档版本吧，7以上不用安装 n 模块，n 模块是不支持windows平台的。
