### ISSUE TITLE
weex **.we 时报错

### ISSUE THREAD

**Issue by gggggaochao** [apache/incubator-weex-cli#109]
![14](https://cloud.githubusercontent.com/assets/22069593/25690172/1e36f58a-30c1-11e7-8121-782dffadc5fd.jpg)
如图，我在main目录下执行weex.main.we时出现以上错误，求解决！

**Comment by JackPu** [comment]
windows的版本号？

**Comment by gggggaochao** [comment]
win10系统 Microsoft Windows [版本 10.0.14393] @JackPu

**Comment by gggggaochao** [comment]
@JackPu

**Comment by gggggaochao** [comment]
我在照官方文档新建一个hello.we ,然后weex hello.we 编译  出现如图error
![18](https://cloud.githubusercontent.com/assets/22069593/25695044/2073bea0-30e4-11e7-980d-b316d640c4f1.png)
