### ISSUE TITLE
建议可以监听新 we 文件的产生

### ISSUE THREAD

**Issue by Jinjiang** [apache/incubator-weex-cli#11]
迁移自 https://github.com/alibaba/weex/issues/595

> 添加新的we文件example到项目后，新的we文件不会被编译

**Comment by lvscar** [comment]
we will start improve this feature next week

**Comment by lvscar** [comment]
最新版weex-toolkit 0.4.5 使用-o参数进行目录级转换时，如果配合--watch参数进行变更监听。 新增文件已经能被转换成JS Bundle
