### ISSUE TITLE
跑案例weex src/foo.vue的时候出现这个报错

### ISSUE THREAD

**Issue by mykurisu** [apache/incubator-weex-cli#111]
刚入门的小白，跑教程的时候遇到这个问题，有点摸不着头脑，麻烦大大们帮忙看一下。谢谢！
![image](https://cloud.githubusercontent.com/assets/12829211/25884398/9f882132-3584-11e7-85d4-d9ec796f5e1b.png)

**Comment by guoshengwang** [comment]
@mykurisu 
sudo weex src/foo.vue 这样试试

**Comment by JackPu** [comment]
@mykurisu  `sudo chmod -R 777 /Users/mykurisu` 你给你用户目录写权限放开吧。

**Comment by mykurisu** [comment]
上面两种方法都OK，谢谢！
顺带一句我的环境node 6.9.2    npm 4.5.0（供参考）
