### ISSUE TITLE
weex-toolkit  安装不上, 

### ISSUE THREAD

**Issue by LiMaoAtCD** [apache/incubator-weex-cli#112]
<img width="736" alt="2017-05-12 10 34 11" src="https://cloud.githubusercontent.com/assets/4811145/25980052/bd1cc83a-36fe-11e7-8ee4-61faa053ea4d.png">

**Comment by hongxiangWang** [comment]
我也是这样的问题，官方也不修复下，各种搜也没搜出结果

**Comment by JackPu** [comment]
@liamscofield  @hongxiangWang  这个不是包的问题，是安装的问题，@liamscofield 麻烦贴更详细的图片？

**Comment by erha19** [comment]
You can try
```
npm update npm -g
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
```
If the download speed is too slow, you can try to switch the origin of npm.
