### ISSUE TITLE
weex create 项目,编译运行之后无法在浏览器上显示

### ISSUE THREAD

**Issue by Origin-zhao** [apache/incubator-weex-cli#113]
weex create方式创建项目，在浏览器中浏览出现错误？

执行命令步奏如下：
weex create demo1
cd demo1
cnpm install
cnpm run build
cnpm run serve

异常：
[Vue warn]: Error in render function: "TypeError: Cannot read property '.wrapper[undefined]' of undefined"

found in

---> <WeexDiv>
       <Root>
warn @ vue.runtime.js:436
handleError @ vue.runtime.js:521
Vue._render @ vue.runtime.js:3899
updateComponent @ vue.runtime.js:2439
get @ vue.runtime.js:2776
Watcher @ vue.runtime.js:2759
mountComponent @ vue.runtime.js:2443
Vue$3.$mount @ vue.runtime.js:7099
init @ vue.runtime.js:3352
createComponent @ vue.runtime.js:4891
createElm @ vue.runtime.js:4834
patch @ vue.runtime.js:5332
Vue._update @ vue.runtime.js:2316
updateComponent @ vue.runtime.js:2439
get @ vue.runtime.js:2776
Watcher @ vue.runtime.js:2759
mountComponent @ vue.runtime.js:2443
Vue$3.$mount @ vue.runtime.js:7099
Vue._init @ vue.runtime.js:4000
Vue$3 @ vue.runtime.js:4085
(anonymous) @ index.web.js:3
t @ index.web.js:3
(anonymous) @ index.web.js:3
(anonymous) @ index.web.js:3
vue.runtime.js:525 TypeError: Cannot read property '.wrapper[undefined]' of undefined
    at getScopeStyle (style.js:157)
    at getStyle (style.js:169)
    at getComponentStyle (style.js:204)
    at extractComponentStyle (style.js:240)
    at Proxy.render (div.js:40)
    at VueComponent.Vue._render (vue.runtime.js:3897)
    at VueComponent.updateComponent (vue.runtime.js:2439)
    at Watcher.get (vue.runtime.js:2776)
    at new Watcher (vue.runtime.js:2759)
    at mountComponent (vue.runtime.js:2443)
handleError @ vue.runtime.js:525
Vue._render @ vue.runtime.js:3899
updateComponent @ vue.runtime.js:2439
get @ vue.runtime.js:2776
Watcher @ vue.runtime.js:2759
mountComponent @ vue.runtime.js:2443
Vue$3.$mount @ vue.runtime.js:7099
init @ vue.runtime.js:3352
createComponent @ vue.runtime.js:4891
createElm @ vue.runtime.js:4834
patch @ vue.runtime.js:5332
Vue._update @ vue.runtime.js:2316
updateComponent @ vue.runtime.js:2439
get @ vue.runtime.js:2776
Watcher @ vue.runtime.js:2759
mountComponent @ vue.runtime.js:2443
Vue$3.$mount @ vue.runtime.js:7099
Vue._init @ vue.runtime.js:4000
Vue$3 @ vue.runtime.js:4085
(anonymous) @ index.web.js:3
t @ index.web.js:3
(anonymous) @ index.web.js:3
(anonymous) @ index.web.js:3
vue.runtime.js:436 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'add' of undefined"

found in

---> <WeexDiv>
       <Root>
warn @ vue.runtime.js:436
handleError @ vue.runtime.js:521
callHook @ vue.runtime.js:2558
insert @ vue.runtime.js:3377
invokeInsertHook @ vue.runtime.js:5200
patch @ vue.runtime.js:5365
Vue._update @ vue.runtime.js:2316
updateComponent @ vue.runtime.js:2439
get @ vue.runtime.js:2776
Watcher @ vue.runtime.js:2759
mountComponent @ vue.runtime.js:2443
Vue$3.$mount @ vue.runtime.js:7099
Vue._init @ vue.runtime.js:4000
Vue$3 @ vue.runtime.js:4085
(anonymous) @ index.web.js:3
t @ index.web.js:3
(anonymous) @ index.web.js:3
(anonymous) @ index.web.js:3
vue.runtime.js:525 TypeError: Cannot read property 'add' of undefined
    at VueComponent.mounted (base.js:88)
    at callHook (vue.runtime.js:2556)
    at Object.insert (vue.runtime.js:3377)
    at invokeInsertHook (vue.runtime.js:5200)
    at Vue$3.patch [as __patch__] (vue.runtime.js:5365)
    at Vue$3.Vue._update (vue.runtime.js:2316)
    at Vue$3.updateComponent (vue.runtime.js:2439)
    at Watcher.get (vue.runtime.js:2776)
    at new Watcher (vue.runtime.js:2759)
    at mountComponent (vue.runtime.js:2443)

**Comment by Eden-Sun** [comment]
照这改下试试
https://github.com/weexteam/weex-toolkit/commit/5793aa32d120ff2b8b629f7b860862d7a31dfc6a

**Comment by erha19** [comment]
Please update your weex-toolkit version if your version is below 1.0.9 and recreate your project use `weex create` command.
Do not use cnpm to install your dependence module.,try to remove `node_modules` floder and run `npm i` again.
