### ISSUE TITLE
weex compile有没有配置文件

### ISSUE THREAD

**Issue by JuseChen** [apache/incubator-weex-cli#114]
我想在weex compile的时候对文件执行一下我自己的操作，就是在编译之前过滤一遍文件，开始我以为改webpack-config的配置可以，可发现没啥用，感觉自己理解错了weex-toolkit和webpack的关系，想知道weex compile的执行文件是哪个？

**Comment by erha19** [comment]
You can see the config file in the `weex-builder` module.
