### ISSUE TITLE
事例跑不通

### ISSUE THREAD

**Issue by limichange** [apache/incubator-weex-cli#117]
![image](https://cloud.githubusercontent.com/assets/1947344/26183944/8790bbc6-3bb4-11e7-8ba5-e2ef1533321c.png)

<details>

⛩  ~/testCode/weextest ⛩
$ weex init asdfasdf
prompt: Init your Project:  (asdfasdf)
file: /Users/limi/testCode/weextest/asdfasdf/.babelrc created.
file: /Users/limi/testCode/weextest/asdfasdf/.eslintrc created.
file: /Users/limi/testCode/weextest/asdfasdf/.gitignore created.
file: /Users/limi/testCode/weextest/asdfasdf/README.md created.
file: /Users/limi/testCode/weextest/asdfasdf/app.js created.
file: /Users/limi/testCode/weextest/asdfasdf/assets/phantom-limb.js created.
file: /Users/limi/testCode/weextest/asdfasdf/assets/qrcode.js created.
file: /Users/limi/testCode/weextest/asdfasdf/assets/qrcode.min.js created.
file: /Users/limi/testCode/weextest/asdfasdf/assets/style.css created.
file: /Users/limi/testCode/weextest/asdfasdf/assets/url.js created.
file: /Users/limi/testCode/weextest/asdfasdf/build/init.js created.
file: /Users/limi/testCode/weextest/asdfasdf/index.html created.
file: /Users/limi/testCode/weextest/asdfasdf/package.json created.
file: /Users/limi/testCode/weextest/asdfasdf/src/foo.vue created.
file: /Users/limi/testCode/weextest/asdfasdf/webpack.config.js created.
file: /Users/limi/testCode/weextest/asdfasdf/weex.html created.

⛩  ~/testCode/weextest ⛩
$ cd asdfasdf

⛩  ~/testCode/weextest/asdfasdf ⛩
$ weex platform add ios
Error: Current working directory is not a weexpack project.

⛩  ~/testCode/weextest/asdfasdf ⛩
$ weex -v
   v1.0.5
 - weex-builder : v0.2.6
 - weex-devtool : v0.2.80
 - weex-previewer : v1.3.8
 - weexpack : v0.4.0

</details>

**Comment by limichange** [comment]
我查了一下，貌似并行存在两个工具？感觉非常的奇怪，各种例子的结构都不太一样，也不知道哪个是真的。一头雾水。

↓RN的
```shell
react-native init AwesomeProject
cd AwesomeProject
react-native run-ios
```

**Comment by dmlzj** [comment]
遇到了同样的问题，，，也不知道怎么解决，，，卡在门口了

**Comment by erha19** [comment]
Weex init command has been removed, please use `weex create` to init your weex project.
