### ISSUE TITLE
一旦运行不通过，就直接停止监测

### ISSUE THREAD

**Issue by Jinjiang** [apache/incubator-weex-cli#12]
迁移自：https://github.com/alibaba/weex/issues/461

> 用的是--watch实时跟踪监测，代码修改，一但修改错误的 代码，直接中止当前运行环境

---

> 1. 按api文档，去test，weex hello.we，运行, 只出QR图，
> 2. 生成出 http://192.168.32.102:8081/weex_tmp/h5_render/hello.js
> 3. 页面只出编译过的脚本
> 4. 在foo/bar创建项目工程，修改hello.we，`<div>{{title}} </div>`，页面，只显示空白

**Comment by lvscar** [comment]
we will start improve this feature next week

**Comment by lvscar** [comment]
最新版weex-toolkit 0.4.5 , 运行不通过时(we文件格式问题产生编译错误时） ，已经不会造成整个进程终止. 只要修正格式问题，即可继续hot reload更新内容.
