### ISSUE TITLE
error koa-serve-static@0.0.1: The engine "node" is incompatible with this module. Expected version "1.x.x".

### ISSUE THREAD

**Issue by tomoat** [apache/incubator-weex-cli#121]
⬢  weex-app  ls
README.md*  app.js*  assets/  build/  index.html*  package.json*  src/  webpack.config.js*  weex.html*
⬢  weex-app  yarn install
yarn install v0.24.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning serve > jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
warning weex-devtool > koa-serve > koa-send > mz > native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
[2/4] 🚚  Fetching packages...
error koa-serve-static@0.0.1: The engine "node" is incompatible with this module. Expected version "1.x.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
⬢  weex-app  vim package.json
⬢  weex-app  node -v
v7.10.0
⬢  weex-app  npm -v
4.6.1

**Comment by JackPu** [comment]
Please use `npm` install the `weex-toolkit`. Yarn doesn't work well.

**Comment by daprahamian** [comment]
I'd like to second this issue. Yarn is picking up more and more steam, it should be supported.
