### ISSUE TITLE
安装后执行weex报错

### ISSUE THREAD

**Issue by WangYang-Rex** [apache/incubator-weex-cli#122]
执行weex -v，显示 v1.0.5
执行weex，报错：

![123](https://cloud.githubusercontent.com/assets/7553998/26335410/3f5b11d8-3f9e-11e7-9cd8-c03827b867f6.png)

**Comment by agoodcoolman** [comment]
我也是跟你相同的错误

**Comment by WangYang-Rex** [comment]
@agoodcoolman https://github.com/nowa-webpack/nowa/issues/48#issuecomment-303894783

**Comment by agoodcoolman** [comment]
解决了。我通过VPN，然后没有用那个国内镜像，装成功了。@WangYang-Rex

**Comment by WangYang-Rex** [comment]
我试了直接用npm安装，也用了翻墙软件，还是安装失败

**Comment by PawelLin** [comment]
Ubuntu用cnpm安装后，出现了一样的问题，进入node_modules/weex-toolkit这个文件夹下，把weex-toolkit下的node_modules文件夹删除，运行sudo npm install ，执行后会报错，继续运行sudo cnpm install后就碰巧成功，具体原因不太懂，希望对大家有点帮助。

**Comment by ckcsb** [comment]
遇到了相同问题，如何解决？

**Comment by sunzhongwei** [comment]
建议不要使用 cnpm，容易出现诡异的问题。

**Comment by WangYang-Rex** [comment]
@sunzhongwei 我用了ss翻墙，并且用npm安装的，试了2次，也是一样的问题....
我先uninstall然后再去试试看....坑爹

**Comment by sunzhongwei** [comment]
@WangYang-Rex 我们这边三个同事，之前都是 cnpm 安装的，weex 全部报错。
先 uninstall 再用 npm 安装，现在全部都正常

**Comment by fuhanwen** [comment]
儿童热tree儿童

**Comment by msevensun** [comment]
cnpm 可以安装，没有显示安装错误信息，但是在执行weex命令的时候报楼主这个错误；
最后用npm 重新安装 才解决这个问题！

**Comment by WangYang-Rex** [comment]
已解决，cnpm安装的包的路径不太一样，所以需要翻墙用npm安装

**Comment by 15697289437** [comment]
我是重复删除安装了几次，最后在bash下安装才成功 必须使用npm安装
如果`/usr/local/bin/`下有week先删除不然会报错

**Comment by agoodcoolman** [comment]
问题解决了，把管理员@出来close吧
