### ISSUE TITLE
weex 1.0.5版本weex.html文件引用的文件路径错误

### ISSUE THREAD

**Issue by bruceman** [apache/incubator-weex-cli#126]
自动生成的weex.html文件应用的路径是：
<script src="./node_modules/weex-vue-render/index.js"></script>
但是实际应该是（缺少dist目录）：
<script src="./node_modules/weex-vue-render/dist/index.js"></script>

请修复该问题，不然demo都不同。

另外请在mac等环境测试下安装过程，有很多permission denied错误。需要手动修复，希望也可以解决。

**Comment by JackPu** [comment]
这个PR已经提及修复了，等待新版，或者手动修改下，
