### ISSUE TITLE
安装 weex-toolkit 报错

### ISSUE THREAD

**Issue by jiankafei** [apache/incubator-weex-cli#128]
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by parryworld** [comment]
这部分是警告信息，不是错误信息
