### ISSUE TITLE
安装 weex -toolkit报错

### ISSUE THREAD

**Issue by lijianpingnice** [apache/incubator-weex-cli#129]
![2017-07-05 10 26 00](https://user-images.githubusercontent.com/29905963/27846811-64426600-616c-11e7-916b-ff31c99fb103.png)

**Comment by haoyuxingchen123** [comment]
同样遇到

**Comment by parryworld** [comment]
权限问题，可以在命令前面加 sudo

**Comment by JackPu** [comment]
@lijianpingnice  安装前先执行
``` bash
sudo chmod -R 777 /Users/lijiangpingnice 
```

**Comment by Jam1zhu** [comment]
@JackPu mac用户怎么处理？正常来说，sudo已经给了权限了吧。。。小白不是很理解。

**Comment by Juice007** [comment]
#136 这是我的解决办法

**Comment by erha19** [comment]
#137
