### ISSUE TITLE
希望可以有更友好的错误日志

### ISSUE THREAD

**Issue by Jinjiang** [apache/incubator-weex-cli#13]
如题，`*.we` 文件有错误时，目前命令行错误只有 `ERR! ModuleBuildError: Module build failed`
希望错误信息能详细一点对查错更有帮助

via @registernet

**Comment by lvscar** [comment]
we new version weex-toolkit will improve this ,  screenshot  :  

![weex-toolkit_feedback_improvement](https://cloud.githubusercontent.com/assets/1578838/18077855/da1ecc38-6eba-11e6-80a2-3f10085b99e8.JPG)
