### ISSUE TITLE
weex debug  之后安装 weex-devtool报错

### ISSUE THREAD

**Issue by leggod** [apache/incubator-weex-cli#131]
![1499325378 1](https://user-images.githubusercontent.com/20152324/27899738-161c8d5a-625e-11e7-81c9-cfcd1d7e9455.jpg)
   求解答

**Comment by erha19** [comment]
You can try:
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weex-devtool
```
Do not use cnpm to install your package, you can use `git config` command to change your origin of npm, such like taobao or cnpm origin.

**Comment by ouhaohui** [comment]
@erha19 i use the command you provide, but the error still appear

16912 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\weex-devtool\node_modules\weex-builder\node_modules\fsevents):
16913 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\xxx\.xtoolkit\node_modules\.staging\fsevents-36d7c932'
16914 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.

it seem the error relate to the fsevents

**Comment by TimeStarRipple** [comment]
My system is windows. I meeted the same problem. Did you solved it？
