### ISSUE TITLE
weex安装失败

### ISSUE THREAD

**Issue by gql1983** [apache/incubator-weex-cli#133]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'week-toolkit' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session 866c24b67daf205a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npm.taobao.org/week-toolkit 2850ms
8 silly fetchPackageMetaData error for week-toolkit@latest 404 Not Found: week-toolkit@latest
9 verbose stack Error: 404 Not Found: week-toolkit@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:800:20)
9 verbose stack     at tryOnImmediate (timers.js:762:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
10 verbose cwd C:\Users\Administrator
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "week-toolkit"
13 verbose node v8.1.3
14 verbose npm  v5.0.3
15 error code E404
16 error 404 Not Found: week-toolkit@latest
17 verbose exit [ 1, true ]

**Comment by parryworld** [comment]
你安装的是 week-toolkit，不是weex-toolkit
