### ISSUE TITLE
Screen was blank after init

### ISSUE THREAD

**Issue by mazipan** [apache/incubator-weex-cli#134]
I use weex-toolkit for generate my first project using weex, but when I `npm run serve` I got BLANK screen even in debugger I see the DOM, but not showing in my screen

I attach sreenshoot, and make red rectangle for debugging in chrome.
Need advice ! 
![weex_blank](https://user-images.githubusercontent.com/7221389/28053994-7470b22c-663d-11e7-8b66-e4b966d3be4f.PNG)

**Comment by erha19** [comment]
Please update your weex-toolkit to latest version and use `weex create` command to init a weex project.
