### ISSUE TITLE
安装之后执行weex报错，v1.0.5

### ISSUE THREAD

**Issue by mdchun** [apache/incubator-weex-cli#136]
![image](https://user-images.githubusercontent.com/7719710/28201473-c72029e0-68a3-11e7-805c-d0a649fefa2a.png)

**Comment by cjSound** [comment]
和你一样的问题，有解决么

**Comment by longye321** [comment]
一样的问题，这个说是淘宝国内镜像的问题

**Comment by Juice007** [comment]
建议执行(将npm源切到淘宝)
```
npm config set registry http://registry.npm.taobao.org/
```
再用npm安装：
```
npm install -g weex-toolkit
```

**Comment by Juice007** [comment]
另外，我使用
```
npm install -g weex-toolkit
```
安装好后，编译.we文件又会报错，推测可能是weex版本不对。
所以我从1.0.7s降级为1.0.5
```
npm install -g weex-toolkit@1.0.5
```
成功编译

最后，如果在安装过程中还遇到其他报错。建议将node.js也重装（建议在官网下载LTS版本）。
