### ISSUE TITLE
不管是npm还是cnpm都安装失败

### ISSUE THREAD

**Issue by hongxiangWang** [apache/incubator-weex-cli#137]
使用命令：**sudo npm install -g weex-toolkit**

<img width="841" alt="qq20170718-131248 2x" src="https://user-images.githubusercontent.com/17492881/28301640-d0a421d2-6bba-11e7-895c-7703725b6663.png">

使用命：**sudo cnpm install -g weex-toolkit**
<img width="900" alt="qq20170718-132206 2x" src="https://user-images.githubusercontent.com/17492881/28301857-5ee5c2b0-6bbc-11e7-9fab-bf0cc670870d.png">

这几天真是安装的生无可恋

**Comment by JackPu** [comment]
@hongxiangWang  嗯，知道了
``` bash 
sudo chmod -R 777 /Users/wanghongxiao
```

然后 再用 **npm** 安装，不太建议 cnpm 。

``` bash
npm install -g weex-toolkit
```

**Comment by hongxiangWang** [comment]
@JackPu 谢谢，按照你的方法我也试过了，我还用了root用户但是出来新问题，怎么解决？
<img width="872" alt="qq20170718-173114 2x" src="https://user-images.githubusercontent.com/17492881/28310771-16461a0e-6be0-11e7-9516-bd22e09cf4b4.png">


<img width="866" alt="qq20170718-173145 2x" src="https://user-images.githubusercontent.com/17492881/28310794-236f6dac-6be0-11e7-84d4-724b54703dde.png">

**Comment by JackPu** [comment]
@hongxiangWang  我本地安装试一下，

**Comment by hongxiangWang** [comment]
@JackPu 本地安装可行，谢谢啦 
对于向我一样的小白们，分享细一点操作：
1、下载weex-tolkit打包文件。
2、解压后执行 **sudo npm install [文件夹路径] -g**
如果你出现下面两种状况：
1、出现许多的 Missing write access to ....
请把 /usr/local/lib/node_modules/weex-toolkit 地下的 node_modules 文件删除，因为那是cnpm的残留（被毒害了，最好不要用cnpm，你可以改npm config镜像地址为淘宝）
2、.toolkit 文件夹没有权限创建
请手动创建此文件夹

最后感谢 @JackPu  回复很快，但是请忽略把自己账户执行 **chmod -R 777** 的建议 ，那样真不是好方法

**Comment by Juice007** [comment]
#136

**Comment by lvming6816077** [comment]
为什么一定要设置这个文件目录的权限的？chmod -R 777 /Users/wanghongxiao

**Comment by jsdocker** [comment]
成功了么？我也遇到同样问题，网上说的基本都试过
