### ISSUE TITLE
创建ios和安卓版本都不能使用啊，到底是怎么回事

### ISSUE THREAD

**Issue by bltcn** [apache/incubator-weex-cli#143]
我先weex init demo，然后进入目录，再调用weex platform add iOS或者weex platform add android，统统都报同样的错误，“Error: Current working directory is not a weexpack project.”，这是什么情况？

**Comment by jefflam** [comment]
Having the same problem...

**Comment by erha19** [comment]
You are creating project by using `weex init` command, the `platform` command does not support for a vue project.
Please use `weex create` to init your project instead.
