### ISSUE TITLE
安装 weex -toolkit没报错，npm install报错

### ISSUE THREAD

**Issue by Carnia** [apache/incubator-weex-cli#145]
在windows上安装weex toolkit，用cnpm跪了，改用淘宝镜像好了。初始化后npm install安装包失败了，大佬们知道为啥吗。。

![wenti](https://user-images.githubusercontent.com/22728375/29305757-eb3d794e-81cc-11e7-862b-0782c3f8bf05.jpg)

**Comment by firminochangani** [comment]
In english please, so you can receive help.

**Comment by erha19** [comment]
Try to update your npm version to lastest version.
`npm update npm -g`
Delete `node_modules` floder then run `npm i` again.
