### ISSUE TITLE
使用 `weex xxx.we` 在网页上预览时产生的尺寸计算错误，没有定义 `viewport`

### ISSUE THREAD

**Issue by jerrybendy** [apache/incubator-weex-cli#15]
你好，我在使用 weex-toolkit 在网页端预览调试时发现一个尺寸计算上的错误， 具体如下：

weex-toolkit 生成的 index.html 页面中没有对 `viewport` 的定义，导致在 chrome 下模拟手机调试时会按照 webkit 默认的 980px 的宽度渲染页面，并产生尺寸计算与预期不符的现象。

例如在 we 文件中定义 `padding: 20` ，实际预览时却是 `padding: 26.13` ，无论调试时设置的手机宽度是多少。

当然，在不使用模拟手机的方式调试时是没有问题的。

**Comment by vczero** [comment]
1) meta viewport 会在程序运行时添加添加，一般默认不手动添加
2）所有尺寸大小基于根节点计算。

**Comment by jerrybendy** [comment]
![image](https://cloud.githubusercontent.com/assets/7897384/17474931/1186a11e-5d8b-11e6-9f31-3ed6f92611c3.png)

我图中标注的部分，预览尺寸是 320，而计算出来的右半部分的尺寸却是 489.5， window.innerWidth 是 980， we 代码里面写的 padding: 20 而实际计算出来的盒模型中 padding 却是 26.133

![image](https://cloud.githubusercontent.com/assets/7897384/17475001/5c4bb478-5d8b-11e6-9901-13263fd20e8f.png)

viewport 信息并没有添加到 head 中

**Comment by jerrybendy** [comment]
window.innerWidth 是 980

window.outerWidth 是实际的 320

**Comment by vczero** [comment]
<img width="1002" alt="2" src="https://cloud.githubusercontent.com/assets/6133685/17475492/cf7c6b16-5d8d-11e6-8bb8-e94ac51d1083.png">

**Comment by jerrybendy** [comment]
好吧，似乎我们说的就不是同一个东西。。 你发的图里面引用的 script 来自 `./node_modules/weex-html5/dist/weex.js` ， 是 `weex-html5` 项目里的文件。我说的是 `weex-toolkit` 项目的问题，直接使用 `weex reading.we` 命令在浏览器中预览时出现的问题

**Comment by vczero** [comment]
@jerrybendy 明白了, @lvscar

**Comment by MrRaindrop** [comment]
貌似weex-toolkit依赖的npm发布版weex-html5的index页面没有加入viewport设置。这个会尽快修复 @jerrybendy

**Comment by jerrybendy** [comment]
@MrRaindrop   嗯，十分感谢

**Comment by lvscar** [comment]
@jerrybendy  , 你现在通过 npm 安装  weex-toolkit 最新版(0.4.6)

```
npm install  weex-toolkit@0.4.6
```

就已经能避免这个问题了

**Comment by jerrybendy** [comment]
@lvscar   嗯， 十分感谢  😊
