### ISSUE TITLE
Cannot read property 'assert-plus' of undefined

### ISSUE THREAD

**Issue by manjuk41** [apache/incubator-weex-cli#152]
Not able to install weex-toolkit.
:~$ sudo npm install -g weex-toolkit
[sudo] password for cmp: 
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'assert-plus' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'assert-plus' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'minimist' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'assert-plus' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'assert-plus' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'minimist' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'assert-plus' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'assert-plus' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.0

npm ERR! Cannot read property 'minimist' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cmp/npm-debug.log

**Comment by erha19** [comment]
see #137 #136

**Comment by erha19** [comment]
Also you can try:
```
rm -rf ~/.xtoolkit
npm update npm -g
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weex-devtool
``
