### ISSUE TITLE
npm ERR! sha1-ChrkjZkDxY00wYgeUWgUxwQOYYo= integrity checksum failed when using

### ISSUE THREAD

**Issue by fengweiqi** [apache/incubator-weex-cli#153]
![](https://raw.githubusercontent.com/fengweiqi/img/master/weex-toolkit/1.png)

**Comment by fengweiqi** [comment]
when I install weex-toolkit -g,it will hapen this wrong

**Comment by erha19** [comment]
If your npm version is bellow 3, please update your npm.
Try to install `weex-toolkit` again,if it still have some error,try command like this:
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
```
