### ISSUE TITLE
Cannot find element: #root

### ISSUE THREAD

**Issue by goodmanman** [apache/incubator-weex-cli#154]

**Comment by erha19** [comment]
According to the information you have provided, I can not know where the problem is.
I suggest you upgrade you weex-toolkit and your npm package.
```
npm i npm@5 -g
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit@latest -g
```
Re-create your weex project use `weex create xxx`, `cd xxx && npm i && npm start`

**Comment by NoraGithub** [comment]
Hi,@erha19 

I met a same issue, And it's already the newest version of weex (util yesterday).
I wonder how to solve it .Quite confusing and I don't know whether the error is related to this .
```
bash-4.4$ npm ls -g -depth=0
/Users/NoraChan/.nave/installed/weex/lib
├── npm@5.5.1
└── weex-toolkit@1.1.0-beta.6

npm ERR! missing: loader-utils@^1.1.0, required by vue-loader@12.2.0
npm ERR! peer dep missing: webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc, required by babel-loader@6.4.1
bash-4.4$ weex -v
   v1.1.0-beta.6
 - weexpack : v0.4.7-beta.19
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.8
 - toolkit-repair : v0.0.5
```

**Comment by NoraGithub** [comment]
@erha19 You can also get the same error in the console by running  the project.
https://github.com/zwwill/yanxuan-weex-demo

**Comment by erha19** [comment]
@NoraGithub see https://github.com/zwwill/yanxuan-weex-demo/pull/21
