### ISSUE TITLE
weex init always show error  "Invalid project name" !!!

### ISSUE THREAD

**Issue by heuuLZP** [apache/incubator-weex-cli#156]
Hi,  I use npm  installed weex-toolkit according to weex document.

node:       v6.11.3
npm:        5.4.2
system:   mac Sierra

## error
When I use `weex init weex-demo` to init a project, always show error `Invalid project name`.
But use `weex create weex-demo`  is success. 

please help me.

## weex info: 
![image](https://user-images.githubusercontent.com/18410118/31012414-53bf8606-a4d7-11e7-8a65-d8713ebe5074.png)

## error info 

![image](https://user-images.githubusercontent.com/18410118/31012639-1a3f6ada-a4d8-11e7-8c5e-b3a03c012e05.png)

**Comment by heuuLZP** [comment]
I got it.  

In this edition, init has removed ！！！
![image](https://user-images.githubusercontent.com/18410118/31041447-18932d10-a55b-11e7-9109-7fe36d50eab8.png)

**Comment by cristoferfb** [comment]
need to change the guide in the official site:

https://weex.incubator.apache.org/guide/tools/toolkit.html
