### ISSUE TITLE
weex-toolkit debug时无法指定具体IP

### ISSUE THREAD

**Issue by gzcz** [apache/incubator-weex-cli#16]
![qq 20160818155042](https://cloud.githubusercontent.com/assets/5310178/17766247/bdc2dfdc-655c-11e6-97f4-d079d30b5a72.png)

在使用 weex-toolkit debug时，笔记本电脑有两个IP，一个本地连接的IP( 10.20.12.37)，另一个是虚拟热点的IP（192.168.137.1），而debug的-h xxx.xxx.xxx.xxx是无效的。chrome打开的仍然是虚拟热点的IP，而不是本地连接。而手机是无法连接192.168.137.1的，而debug又没有指定IP的参数，类似于非debug时的-h

**Comment by lvscar** [comment]
thx，我们会开始着手改进debug的ip指定

**Comment by lvscar** [comment]
请 @exolution 帮忙完善这个feature  ;-)

**Comment by exolution** [comment]
好的，近期发版时增加这个功能~

**Comment by exolution** [comment]
@cdhjava 已增加该功能，你更新下试试，如果有问题及时反馈哈。

**Comment by gzcz** [comment]
效率很高，对Weex信心大增

在 2016-09-01 15:11:27，"exolution" notifications@github.com 写道：

Closed #16.

**Comment by gzcz** [comment]
在进行debug的时候，用playground扫描二维码报network error!
1、weex debug hello.we -h 10.20.12.37 打开chrome
![a](https://cloud.githubusercontent.com/assets/5310178/18239057/34328cbe-7375-11e6-94f7-5b6cba9a75d9.png)

2、在打开的chrome中扫描二维码，已确认对应的二维码的hello.js地址在手机浏览器上可以访问，但是playground返回network error!
![b](https://cloud.githubusercontent.com/assets/5310178/18239067/3b93f0ce-7375-11e6-81e4-bb15bf393f3b.jpg)

3、手机上访问之后如下图，已确认手机与电脑处于同一局域网（手机加入笔记本电脑的WIFI中）
![c](https://cloud.githubusercontent.com/assets/5310178/18239075/46d12006-7375-11e6-9b89-25703024f367.jpg)

**Comment by yuanzx** [comment]
扫描二维码出现network error的问题还没解决么？

**Comment by gzcz** [comment]
已经解决了，你的issue可以关闭了

在 2016-11-09 14:04:42，"Murphy Yuan" notifications@github.com 写道：

扫描二维码出现network error的问题还没解决么？
