### ISSUE TITLE
compile 错误

### ISSUE THREAD

**Issue by hongxiangWang** [apache/incubator-weex-cli#161]
`
wanghonangdeMBP:test wanghongxiang$ weex compile src/foo.vue dist
Build Failed!
[webpack errors]

Vue packages version mismatch:

- vue@2.2.4
- vue-template-compiler@2.4.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
`

删除了weex-toolkit，重新安装，还是报这个错误。 vue-template-compiler：2.4.4，vue-loader：13.0.5  vue 2.2.4

**Comment by erha19** [comment]
You can see this issues  #80
