### ISSUE TITLE
最新版工具新建项目不能正确显示内容

### ISSUE THREAD

**Issue by wucuida** [apache/incubator-weex-cli#163]
### weex-toolkit 版本
 v1.1.0-beta.1
### npm 版本
5.4.2
### node 版本
6.2.1
### 问题描述
按照官网安装weex-tool, 新创建项目后，运行`npm run serve`报错 `ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3700,4]`，google后把`new webpack.optimize.UglifyJsPlugin({minimize: true})`注释掉，不报错了，但浏览器没有显示任何内容，也不报错

**Comment by yqyily** [comment]
遇到同样的问题

**Comment by yukrain** [comment]
不要使用cnpm安装，删掉再用npm安装一遍

[#165](https://github.com/weexteam/weex-toolkit/issues/165)

**Comment by erha19** [comment]
Update your `weexpack` by `weex update weexpack`, re-create your project by `weex create demo`, It will be work!
