### ISSUE TITLE
啥时候weex compile支持import css

### ISSUE THREAD

**Issue by hongxiangWang** [apache/incubator-weex-cli#164]
在vue里面写css，最方便的也就是 <style src=''>方法
css的transition属性一有就报错。

**Comment by erha19** [comment]
Hi~,

Latest version of weex is support transition property,please upgrade your toolkit and weex sdk.

The `import` grammar we currently do not support, we will consider in the next version to support this feature

**Comment by erha19** [comment]
@hongxiangWang you can use `sass/less` to import your styles, see https://github.com/weex-templates/webpack#how-to-use-lesssasspug.
