### ISSUE TITLE
npm run serve 报错

### ISSUE THREAD

**Issue by FengHaiSheng** [apache/incubator-weex-cli#165]
1. weex create创建的全新项目
2. npm install
3. npm run serve
4. 然后，就报错了，页面是空白的

ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3700,4]

本地weex-toolkit版本:
   v1.1.0-beta.1
 - weexpack : v0.4.7-beta.4
 - weex-builder : v0.2.13-beta.1
 - weex-devtool : v0.3.2-beta.6
 - weex-previewer : v1.3.13-beta.1

**Comment by wucuida** [comment]
我也遇到完全一样的错误了，请问解决了吗

**Comment by FengHaiSheng** [comment]
@wucuida 还没

**Comment by erha19** [comment]
@wucuida @FengHaiSheng 

```
npm update npm -g
cd project_name
rm -rf node_modules
npm i 
npm run serve
```

**Comment by erha19** [comment]
I will fix this bug soon, please wait.

**Comment by erha19** [comment]
I have fixed this problem in the `weexpack` version of 0.4.7-beta.6., run 
```
weex update weexpack@0.4.7-beta.6
//re-create project
weex create project_name
cd project_name
npm i && npm serve
```
By the way, we have been in the weex initialization project to upgrade the reconstruction, to provide you with a better development experience!

**Comment by FengHaiSheng** [comment]
@erha19 ,好的，我这边OK了

**Comment by wucuida** [comment]
@erha19  谢谢，问题也解决了

**Comment by yqyily** [comment]
＠erha19 ,我的还是同样的问题：

ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3700,4]

   v1.1.0-beta.1
 - weexpack : v0.4.7-beta.6
 - weex-builder : v0.2.13-beta.1
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.1
版本号改为你推荐的，但问题依然存在

**Comment by yqyily** [comment]
@erha19 问题解决了，之前都是用cnpm ,后来在评论里我看有人说用镜像有问题，所以改为npm后，工程正常启动了。

**Comment by AdelMahjoub** [comment]
- node : 6.11.4
- npm : 5.4.2
- weex : v1.1.0-beta.1
- weexpack : v0.4.7-beta.8
- weex-builder : v0.2.13-beta.2
- weex-previewer : v1.3.13-beta.3
`$ npm start`
`ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3700,4]`

**Comment by erha19** [comment]
@AdelMahjoub After you upgrade your weexpack version, you need to re-create your project use `weex create` command.

**Comment by AdelMahjoub** [comment]
@erha19 
Same issue after re-creating, can't figure out how to fix it.
```
ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3700,4]
```
 - weexpack : v0.4.7-beta.8
 - weex-builder : v0.2.13-beta.2
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.

**Comment by erha19** [comment]
Is there has a `npm-shrinkwrap.json` file?
Make sure your npm version >=5 and do not use cnpm or other npm-wrap package to install dependence.
Remove node_modules and try `npm i `again~

**Comment by AdelMahjoub** [comment]
@erha19 
re-installed nodejs and updated npm to 5.5.1 before installing any global module, 
then changed npm [default directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions),
now it works, thanks
