### ISSUE TITLE
weex debug dist 

### ISSUE THREAD

**Issue by dehengxu** [apache/incubator-weex-cli#166]
使用最新版 weex 自动生成的demo，  weex compile 到 dist 后，无法进行debug，页面一片空白。

版本信息如下：
 weex -v
   v1.1.0-beta.1
 - weexpack : v0.4.7-beta2
 - weex-builder : v0.2.13-beta.1
 - weex-devtool : v0.3.2-beta.3
 - weex-previewer : v1.3.13-beta.1

**Comment by dehengxu** [comment]
第一次 build 的时候还需要手动安装 weexpack

**Comment by dehengxu** [comment]
weex debug src/index.vue

此方式也不行，虽然在页面上多出一个app 入口 
`http://192.168.101.193:8088/weex/index.js?_wx_tpl=http%3A%2F%2F192.168.101.193%3A8088%2Fweex%2Findex.js`，但是打开后是 js 代码。

**Comment by erha19** [comment]
You need weex playground to preview jsbundle,http://weex.apache.org/cn/playground.html

**Comment by dehengxu** [comment]
如何进行开发 debug ?

**Comment by erha19** [comment]
Android: https://weex.apache.org/cn/references/advanced/integrate-devtool-to-android.html#sidebar
iOS: https://weex.apache.org/cn/references/advanced/integrate-devtool-to-ios.html
