### ISSUE TITLE
weex init project_name failed

### ISSUE THREAD

**Issue by dehengxu** [apache/incubator-weex-cli#167]
weex init project_name
Invalid project name:

是否 init 命令已经取消了?

**Comment by FengHaiSheng** [comment]
取消了

**Comment by erha19** [comment]
Please use `weex create` command.

**Comment by codeliu6572** [comment]
still failed
** BUILD FAILED **


The following build commands failed:
	Check dependencies
	Write auxiliary files
(2 failures)

> fsevents@1.1.3 install /Users/Codeliu/Desktop/WeexTest/listlist/node_modules/fsevents
> node install

[fsevents] Success: "/Users/Codeliu/Desktop/WeexTest/listlist/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/Codeliu/Desktop/WeexTest/listlist/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js
