### ISSUE TITLE
fail to install weex-toolkit because invalid name '@f/defaults'

### ISSUE THREAD

**Issue by hygkui** [apache/incubator-weex-cli#17]
```
$node-gyp --version 
v3.4.0
```

when running the command `cnpm install -g weex-toolkit`, get the messages:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=http://registry.npm.taobao.org" "--cache=/Users/hygkui/.npm/.cache/tnpm" "--disturl=https://npm.taobao.org/dist" "--userconfig=/Users/hygkui/.tnpmrc" "install" "-g" "weex-toolkit"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! Invalid name: "@f/defaults"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

i have googled this problem, but cannot resolve it, so i put this issue here if anyone meet the same problem.

**Comment by hygkui** [comment]
Try to upgrade node & npm but it didn't work.

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=https://r.cnpmjs.org" "--cache=/Users/hygkui/.npm/.cache/cnpm" "--disturl=https://cnpmjs.org/mirrors/node" "--userconfig=/Users/hygkui/.cnpmrc" "install" "-g" "weex-toolkit"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3

npm ERR! Invalid name: "@f/defaults"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by hygkui** [comment]
try to use node5.3.0, it works!

```
$nvm ls
```

![2016-08-24 17 49 15](https://cloud.githubusercontent.com/assets/12526/17926335/286df05e-6a23-11e6-8ac3-8243cc686fcf.png)

```
$nvm use stable                             
Now using node v5.3.0 (npm v3.3.12)
```

```
$sudo npm install -g @f/defaults
```

![2016-08-24 17 48 24](https://cloud.githubusercontent.com/assets/12526/17926289/fd2d2bb2-6a22-11e6-9545-c7467992ec69.png)

```
$sudo npm install -g weex-toolkit
```

![2016-08-24 17 51 22](https://cloud.githubusercontent.com/assets/12526/17926389/70f2b0e4-6a23-11e6-8774-820257cc642e.png)

**Comment by lvscar** [comment]
@hygkui THX!  we will add this note to weex-toolkit npmjs page.

**Comment by lvscar** [comment]
have been linked to README

https://github.com/weexteam/weex-toolkit#invalid-name-fdefaults
