### ISSUE TITLE
if i want use weex debug .js file, what should i do?

### ISSUE THREAD

**Issue by 1gehunzi** [apache/incubator-weex-cli#179]
use the vue-router, the entry is` js` file, not `.vue` or `.we`.
debug fail, can't use the playground.

**Comment by erha19** [comment]
You can start a simple static server (using such as [serve](https://www.npmjs.com/package/serve)) by your self and render URL to a QR code, then use playground to preview your page.

**Comment by 1gehunzi** [comment]
恩  试了一下可以实现。  但是好麻烦，weextoolkit 应该加上该功能

**Comment by erha19** [comment]
Maybe you can use `weex debug xxx.js` to get a QR code.
