### ISSUE TITLE
About compilation of entry files

### ISSUE THREAD

**Issue by Lanceloft** [apache/incubator-weex-cli#180]
In the use of vuex && vue-router, the need to register in the entry file reference, in the packaging of the web side, the use of weex build web, will only compile the vue file, the entry file is not compiled, resulting in vue-router display is not registered, How to solve

**Comment by erha19** [comment]
If you just want to develop on web platform, we suggest you use `vue-cli` to develop vue project.
The weex is not support `vue-router` to manage your router, maybe you should find other solution such as `weex-router` to manage weex router.

**Comment by erha19** [comment]
I also recommend you to join in [weex maill list ](https://github.com/apache/incubator-weex/blob/master/CONTRIBUTING.md)  for suggestion or discussion, the weex official team should give you some advice on how to build your page router better
