### ISSUE TITLE
@click not working on <text>, <div> components on HTML URI

### ISSUE THREAD

**Issue by sushilparajuli** [apache/incubator-weex-cli#181]
on html5 Preview URI : http://dotwe.org/raw/htmlVue/8f4f21cabee879fab13daa626049f4d5?1509479282984

**Comment by erha19** [comment]
weex is supporting the `touch` event on the mobile side and does not support the `click` event if you are open your page on PC browser, you should open device mode to simulate the mobile end.If you have any problem about `weex`, I suggest you go to weex the [mailing list](https://github.com/apache/incubator-weex/blob/master/CONTRIBUTING.md) to ask questions.
