### ISSUE TITLE
lcoalhost:8080/index.html connection refused

### ISSUE THREAD

**Issue by ghost** [apache/incubator-weex-cli#182]
## node
` node version : latest `
` npm version : 5.4.2`

## weex version
`v1.0.7`
`- weex-builder:v0.2.7`
`- weex-previewer:v1.3.9`
`- weexpack:v0.4.3`

## there were some mistakes when i  followed to install and run dev&serve : `unexpected token:name<urlParts> [index.web.js:331,4], ERROR in index.web.js from UglifyJs , webpack: Faild to compile`.

**Comment by erha19** [comment]
You need to update `weex-toolkit` to latest version, try to run `npm i weex-toolkit@latest -g`,
then, try to update weexpack by `weex update weexpack`, after that, you can re-create your project and run `npm start` again.
If you have other problem while installing, see [FAQ](https://github.com/weexteam/weex-toolkit#faq) for some help.
