### ISSUE TITLE
`weex foo.bar.vue` would fail

### ISSUE THREAD

**Issue by xieguanglei** [apache/incubator-weex-cli#184]
`weex foo.bar.vue` would fail for not found `foo.js` (it should be `foo.bar.js`). seems that the toolkit split filename to basename and extname by first but not last dot.

**Comment by erha19** [comment]
@xieguanglei Fixed https://github.com/weexteam/weex-previewer/pull/5/commits/442504ab818ac8621c37c1ebc17d0a7c303bf6de, you can run `weex update weex-previewer` to update your `weex-toolkit`.

**Comment by erha19** [comment]
Let me know if there is no problem, I will close this issue.
