### ISSUE TITLE
weex-toolkit init的项目，switch和picker都不能在真机中使用

### ISSUE THREAD

**Issue by wulj04** [apache/incubator-weex-cli#185]
switch和picker在playground中扫码没有问题，但是只要是在weex run android中就有错误，switch是完全找不到，picker是报错

**Comment by erha19** [comment]
Try to update your weexpack and recreate your project. by `weex update weexpack`.

**Comment by wulj04** [comment]
@erha19 
<pre>
&lt;template>
  &lt;div class="wrapper">
    &lt;image :src="logoUrl" class="logo">&lt;/image>
    &lt;text class="title">Hello {{target}}&lt;/text>
    &lt;text class="desc">Now, let's use vue to build your weex app.&lt;/text>
    &lt;div class="wrapper">
      &lt;text>选项组&lt;/text>
      &lt;switch>&lt;/switch>
      &lt;switch class="switch-1">&lt;/switch>
      &lt;switch class="switch-2">&lt;/switch>
    &lt;/div>
    &lt;text @click="update">点击选择&lt;/text>
  &lt;/div>
&lt;/template>

&lt;style scoped>
.wrapper{
  width: 750px;
  background-color: green;
}
  .title { padding-top:40px; padding-bottom: 40px; font-size: 48px; }
  .logo { width: 360px; height: 156px; }
  .desc { padding-top: 20px; color:#888; font-size: 24px;}
  .switch-1 { width:100px;}
  .switch-2 { width:100px;height:60px;}
&lt;/style>

&lt;script>
  const picker = weex.requireModule('picker')
  export default {
    data: {
      logoUrl: 'http://img1.vued.vanthink.cn/vued08aa73a9ab65dcbd360ec54659ada97c.png',
      target: 'World'
    },
    methods: {
      update(){
        const items=[1,2,3,4,5]
        picker.pick({
          items:items
        }, event => {
          if (event.result === 'success') {
            this.target = items[event.data]
          }
        })
      }
    }
  }
&lt;/script>

</pre>

这是我的index.vue的代码
下面是weex-toolkit的版本
`C:\WINDOWS\system32>weex -v
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.20
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.10`
switch组件完全看不见，
picker.pick点了没有反应

**Comment by kk-duk** [comment]
It seems that there are some wrong with the <switch> and the <textarea> too
