### ISSUE TITLE
vue-router使用问题

### ISSUE THREAD

**Issue by kk-duk** [apache/incubator-weex-cli#186]
1、项目中使用vue-router，入口文件配置了router实例，run之后入口文件中我改动后的代码被还原成模板生成时的状态。
2、在上一条的情况下，安卓模拟器上app安装运行起来，白屏幕有一句错误码，render error: -2013
3、打包失败，生成了一个未签名的apk

补充:
我修改后的代码就是这一段: 
    new Vue(Vue.util.extend({ el: '#root', router,}, App))
    router.push('/')
run之后变成了:
    App.el = '#root'
    new Vue(App)

补充:
weex -v
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.20
 - weex-builder : v0.2.13-beta.4
 - weex-previewer : v1.3.13-beta.10

**Comment by erha19** [comment]
@yeanling-south  you can see https://github.com/zwwill/yanxuan-weex-demo.

**Comment by kk-duk** [comment]
@erha19 Thanks, i had already referred to this demo but not found any solution to solve this problem

**Comment by erha19** [comment]
@yeanling-south The default entry file is generated by `webpack` script,  I have explanate this on https://github.com/zwwill/yanxuan-weex-demo/pull/21, maybe it would be helped for you.

**Comment by kk-duk** [comment]
@erha19 
Thanks for your kindness, i have solved this mistake beyond your direction!
Wish the WEEX better, and a new WEEX prictice is now important.
I do looking forward to the new routing system too.
