### ISSUE TITLE
cannot find module xtoolkit

### ISSUE THREAD

**Issue by TimeStarRipple** [apache/incubator-weex-cli#188]
windows环境，nodev6.9.2，运行weex -v，报错cannot find module xtoolkit。
之前weex是正常的，因为weex debug报错，我找了一些资料，网上说吧xtoolkit删掉，然后使用cnpm重新安装weex-toolkit。我就把c盘下面的xtoolkit给删掉了，接着重装了。重装以后就报了这个错，我把node卸载了之后，重新安装，还是一样的错。

麻烦各位大神指导一下，困扰很多天了，好崩溃，谢谢！

**Comment by erha19** [comment]
Hi~ Firstly we advice you not to use`cnpm`, if you want to replace the`npm` origin you can switch by using `nrm`:
```
npm i nrm -g
nrm use cnpm
```
To fix your issue, you should make sure your npm version > = 5 and try to run the command below:
```
npm un weex-toolkit -g
npm i weex-tooklit -g --no-optional
```
