### ISSUE TITLE
weex debug报错

### ISSUE THREAD

**Issue by echoLC** [apache/incubator-weex-cli#189]
具体信息如下：Unable to save binary /Users/luochao/.xtoolkit/node_modules/weex-builder/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/luochao/.xtoolkit/node_modules/weex-builder/node_modules/node-sass/vendor'

**Comment by Rem486** [comment]
好像是没有权限，简单粗暴的办法是在命令行前面加上 sudo 
请问你的项目在ios端可以使用vue-router 吗？

**Comment by erha19** [comment]
Try to run the command with `sudo` or `chmod 777 ~/.xtoolkit`.

**Comment by erha19** [comment]
@echoLC If you have no other question, I will close this issue later.

**Comment by txyGithub** [comment]
我好想也除了这个错，后来又重新装了一遍node，按照node路径安装的所有依赖
