### ISSUE TITLE
关于 hot-reload

### ISSUE THREAD

**Issue by lmnsg** [apache/incubator-weex-cli#19]
当使用 weex --qr 预览我的 app 的时候，使用 weex playground 可以实时预览，且代码变动后会触发 hot-reload.  
同时可以通过  `http://xxxx:xxxx/weex_tmp/h5_render/?hot-reload_controller&page=main.js&loader=xhr`这个地址在网页上进行 h5预览。

这两个任意一个都没问题，但当两个同时开着的时候，手机上的 playground 就无法触发 hot-reload 了，
ios 上的 playground也不像安卓上一样有刷新按钮。。。要重新扫码才行，不知道是什么原因。
尝试通过抓包工具，发现确实开启了网页后，ios 上就没有请求发出了。

help...

**Comment by lvscar** [comment]
谢谢 @lmnsg 的反馈，我们会在下个版本的iOS Playground中增加扫码时的刷新按钮。  同时计划后续重构 weex-toolkit 时考虑多端同时刷新的场景.

**Comment by apuravchauhan** [comment]
Guys! english please. Weex is incubating in apache and it becomes difficult for international community to follow whats going on in discussions
