### ISSUE TITLE
weex create 报错 EACCES: permission denied

### ISSUE THREAD

**Issue by magickaito** [apache/incubator-weex-cli#190]
```
.xtoolkit/node_modules/weexpack/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '～/.config/configstore/insight-weexpack.json'
You don't have access to this file.
```

发生什么事？

Version 如下：

weex --version
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.21
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.10

**Comment by magickaito** [comment]
sudo chown -R [user name] ~/.config

**Comment by iosWeex** [comment]
sudo chown -R [user name] ~/.config   [user name]是什么吗？我用sudo chown -R [我名] ~/.config 报出chown: [我名]: illegal user name 。我名是/Users/我名/Desktop/weex里的
