### ISSUE TITLE
Weex Installation error

### ISSUE THREAD

**Issue by jhnpnzln** [apache/incubator-weex-cli#192]
I try to install weex tool using _'npm install -g weex-toolkit_'
![weaks](https://user-images.githubusercontent.com/24667101/33160987-9ab75eb2-d05b-11e7-9f8f-fe8c997ee9cb.PNG)
![weaks2](https://user-images.githubusercontent.com/24667101/33160988-9afafd52-d05b-11e7-9047-fbcee6982595.PNG)

 but then after that I got error when I type '_weex_'

**Comment by erha19** [comment]
Try `npm i weex-toolkit -g --no-optional`.

**Comment by jhnpnzln** [comment]
![weaks](https://user-images.githubusercontent.com/24667101/33170641-f3ff304e-d083-11e7-9e0d-52f3f3261a2c.PNG)

I tried that but I still got error :(

**Comment by erha19** [comment]
Please provide your npm and node version.

**Comment by jhnpnzln** [comment]
![weaks](https://user-images.githubusercontent.com/24667101/33231641-cb8eb2b8-d233-11e7-9f1c-6188e4cadad4.PNG)

**Comment by erha19** [comment]
@jhnpnzln  You should update your `npm` version and reinstall `weex-toolkit`, maybe you need to 
manually remove `weex-toolkit` installed previously.

**Comment by DWangHua** [comment]
win7 nvm node 8.9.0 也碰到这个问题，后来换了cnpm安装就好了
