### ISSUE TITLE
反馈一个BUG

### ISSUE THREAD

**Issue by frank9172** [apache/incubator-weex-cli#195]
用当前最新版生成一个项目 自动生成的webpack.config.js文件格式错误 少了一个","
![qq20171125-151438](https://user-images.githubusercontent.com/9987114/33228334-88f81b3c-d1f3-11e7-9c08-3021a5166ff0.png)
![qq20171125-151420](https://user-images.githubusercontent.com/9987114/33228337-b7783cbc-d1f3-11e7-8cc9-a446b3349dc5.png)

**Comment by riseno** [comment]
this `,` is the champion of hide & seek

**Comment by erha19** [comment]
Thanks! I have fixed it on https://github.com/weexteam/weexpack-create/commit/24d502b2c4f645c72ea82931b18a29ddddc7b8dd.
Run `weex update weexpack`, you can update to the latest version.
