### ISSUE TITLE
error:'npm run serve'

### ISSUE THREAD

**Issue by hxyoo1990** [apache/incubator-weex-cli#196]
npm run dev
npm run serve
然后，报错
ERROR in components\topChannel.web.js from UglifyJs 
Unexpected token: name (urlParts) [components\topChannel.web.js:320,4]

node:8.9.1
npm:5.5.1
weex-toolkit@1.1.0-beta.7
weex-builder@0.2.13-beta.4
weex-devtool : v0.3.2-beta.9
weex-previewer : v1.3.13-beta.10

**Comment by erha19** [comment]
Maybe you have an old version of `weexpack` plugin, run `weex update weexpack` and recreate your project.
