### ISSUE TITLE
安装时出错

### ISSUE THREAD

**Issue by caizhitong** [apache/incubator-weex-cli#197]
![error](https://user-images.githubusercontent.com/29909494/33415850-5ba1c798-d5d4-11e7-846f-808057f467e2.jpg)

**Comment by caizhitong** [comment]
win7*64位下，nodejs版本为8.9.1，npm版本为5.5.1

**Comment by erha19** [comment]
Please provide the key error log and you can try `npm i weex-toolkit -g --no-optional`.

**Comment by caizhitong** [comment]
使用了 npm i weex-toolkit -g --no-optional.  还是报同样的错误；请问错误日志在哪里能够找到？

**Comment by caizhitong** [comment]
-
![install_pic](https://user-images.githubusercontent.com/29909494/33707173-7ab8f870-db71-11e7-8084-45d5d2b17846.png)
这是安装的过程
