### ISSUE TITLE
为什么只有打开了weex debug才能发送网络请求

### ISSUE THREAD

**Issue by zeusro** [apache/incubator-weex-cli#198]
使用webpack编译的js文件,同样的文件,只有在开启了weex debug之后才能对外发送网络请求,如果不打开debug,直接使用安卓端weex扫码,则无法发送网络请求

**请问如何解决?**

**Comment by erha19** [comment]
You need to put your bundle on a static server and provide an accessible QR code, and I need more information about your situation~

**Comment by erha19** [comment]
@zeusro If you have no other question, I will close this issue later.

**Comment by zeusro** [comment]
Sorry ,I am tired of weex.I give up.
