### ISSUE TITLE
<switch> @chang  一次点击，执行两次 

### ISSUE THREAD

**Issue by Rem486** [apache/incubator-weex-cli#200]
使用weex 提供组件，<switch> 绑定@change 事件

**代码地址：** http://dotwe.org/vue/25a25c722a26eb9689c0d61199a3f26c

这个代码在浏览器上执行会执行两次，但是扫码在手机上又可以。
而我的本地代码在手机上也不可以。

weex -v
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.12

**Comment by Rem486** [comment]
weex-vue-render 版本从 0.12.21 > 0.11.17 。事件交互正常，但是整个样式渲染就乱掉了。
![image](https://user-images.githubusercontent.com/22462424/33467321-aa1b12c0-d68e-11e7-8af2-88160c27a800.png)

**Comment by erha19** [comment]
@Rem486 You can update your preview by `weex update weex-previewer` and preview your page by `weex xxx.vue`, I check it is ok. The `weex-vue-render` in `dotwe` is an old version, I suggest you upgrade your `weex-vue-render` to at least `0.12.21`. 

About the layout issue, can you provide a`dotwe` demo?

**Comment by Rem486** [comment]
**Thanks a lot**. It works well after updating weex-vue-render into the 0.12.21 version. There is no problem to use single document on dotwe anymore, but something occasionally goes wrong with layout when using **vue-router** or **component**. 

See the issue as: https://github.com/zwwill/yanxuan-weex-demo/issues/32

**Comment by Rem486** [comment]
**image 1**
![image](https://user-images.githubusercontent.com/22462424/33510139-6ed413b4-d743-11e7-9e60-e5c111ead679.png)


**image 2**
![image](https://user-images.githubusercontent.com/22462424/33510125-4d66aa8e-d743-11e7-8359-56759cb6dc42.png)


**The first time the page is loaded, as Figure 1, after switching the route, return as figure two.** 

**router config:**
![image](https://user-images.githubusercontent.com/22462424/33510322-f29b9670-d745-11e7-833b-55eb9914ff2a.png)


If part of the code is extracted from the component and loaded in, the whole page can be rendered as normal.

`dotwe`  demo
http://dotwe.org/vue/81577cfef166ec40045dc4d0182c0b38

**Comment by erha19** [comment]
@Rem486 I see, that's a very strange rendering mechanism, maybe you can join in the [mail list of weex](http://mail-archives.apache.org/mod_mbox/incubator-weex-dev/) to discuss this issue, I will help you to promote the solution of this problem.

**Comment by erha19** [comment]
@Rem486 If you have no other question, I will close this issue later.
