### ISSUE TITLE
X5浏览器内核组件开发，替换webview，提示异常

### ISSUE THREAD

**Issue by padro1617** [apache/incubator-weex-cli#202]
我目前希望安卓端使用 【腾讯TBS的x5内核】，来替换安卓原生webview 组件
目前我仿照weex中web组件源码编写了 对应X5的 component控件和组件
发现出现异常，提示 “add component failed”

“Calling View methods on another thread than the UI thread.”
在另一个线程上调用视图方法，而不是UI线程。

项目中已引入了tbs_sdk.jar
模仿weex sdk源码中 web组件写法
代码中 webview 命名空间均是 com.tencent.smtt.sdk.WebView

![image](https://user-images.githubusercontent.com/7707804/33595219-2f7afa02-d9d2-11e7-9cde-d757a52e66f9.png)

**Comment by padro1617** [comment]
问题原因不是很清楚，但是我不仿照web源码那么继承IWebView接口编写的话，可以正常运行
下面是组件实现代码

package com.alibaba.weex.ui.component;

import android.app.Activity;
import android.content.Context;
import android.net.Uri;
import android.support.annotation.NonNull;
import android.text.TextUtils;
import android.view.View;

import com.alibaba.weex.ui.view.WXWebViewX5;
import com.taobao.weex.WXSDKInstance;
import com.taobao.weex.adapter.URIAdapter;
import com.taobao.weex.annotation.Component;
import com.taobao.weex.common.Constants;
import com.taobao.weex.dom.WXDomObject;
import com.taobao.weex.ui.component.WXComponent;
import com.taobao.weex.ui.component.WXComponentProp;
import com.taobao.weex.ui.component.WXVContainer;
import com.taobao.weex.utils.WXUtils;



import com.tencent.smtt.export.external.interfaces.SslError;
import com.tencent.smtt.export.external.interfaces.SslErrorHandler;
import com.tencent.smtt.export.external.interfaces.WebResourceError;
import com.tencent.smtt.export.external.interfaces.WebResourceRequest;
import com.tencent.smtt.export.external.interfaces.WebResourceResponse;
import com.tencent.smtt.sdk.QbSdk;
import com.tencent.smtt.sdk.WebChromeClient;
import com.tencent.smtt.sdk.WebSettings;
import com.tencent.smtt.sdk.WebSettings.LayoutAlgorithm;
import com.tencent.smtt.sdk.WebView;
import com.tencent.smtt.sdk.WebViewClient;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by Administrator on 2017/12/4.
 */

public class WxX5Web extends WXComponent<WebView> {
    protected WebView mWebView;

    private WebViewClient client = new WebViewClient() {
        /**
         * 防止加载网页时调起系统浏览器
         */
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
            view.loadUrl(url);
            return true;
        }
    };

    public WxX5Web(WXSDKInstance instance, WXDomObject dom, WXVContainer parent, boolean isLazy) {
        super(instance, dom, parent);
    }

    @Override
    protected WebView initComponentHostView(@NonNull Context context) {
        mWebView = new WebView(context);
        WebSettings webSetting = mWebView.getSettings();
        webSetting.setJavaScriptEnabled(true);
        webSetting.setJavaScriptCanOpenWindowsAutomatically(true);
        webSetting.setAllowFileAccess(true);
        webSetting.setLayoutAlgorithm(LayoutAlgorithm.NARROW_COLUMNS);
        webSetting.setSupportZoom(true);
        webSetting.setBuiltInZoomControls(true);
        webSetting.setUseWideViewPort(true);
        webSetting.setSupportMultipleWindows(true);
        // webSetting.setLoadWithOverviewMode(true);
        webSetting.setAppCacheEnabled(true);
        // webSetting.setDatabaseEnabled(true);
        webSetting.setDomStorageEnabled(true);
        webSetting.setGeolocationEnabled(true);
        webSetting.setAppCacheMaxSize(Long.MAX_VALUE);
        // webSetting.setPageCacheCapacity(IX5WebSettings.DEFAULT_CACHE_CAPACITY);
        webSetting.setPluginState(WebSettings.PluginState.ON_DEMAND);
        // webSetting.setRenderPriority(WebSettings.RenderPriority.HIGH);
        webSetting.setCacheMode(WebSettings.LOAD_NO_CACHE);
        mWebView.setWebViewClient(client);
        return mWebView;
    }

    @WXComponentProp(name = Constants.Name.SRC)
    public void setUrl(String url) {
        if (TextUtils.isEmpty(url) || getHostView() == null) {
            return;
        }
        if (!TextUtils.isEmpty(url)) {
            mWebView.loadUrl(getInstance().rewriteUri(Uri.parse(url), URIAdapter.WEB).toString());
//            loadUrl(getInstance().rewriteUri(Uri.parse(url), URIAdapter.WEB).toString());
        }
    }

}`
`

**Comment by erha19** [comment]
Hi~@padro1617 , Sorry for the late reply，and here is where to discuss the `weex-toolkit`, I suggest you join [weex mail list](http://mail-archives.apache.org/mod_mbox/incubator-weex-dev/) to describe your problem in detail, there will be much developments of weex team to discuss this issue with you, thanks~

**Comment by erha19** [comment]
@padro1617 If you have no other question, I will close this issue later.

**Comment by padro1617** [comment]
@erha19  thinks ,please close this issue.

**Comment by padro1617** [comment]
@erha19  thanks ,please close this issue later
