### ISSUE TITLE
项目初始化错误

### ISSUE THREAD

**Issue by CiaoSom** [apache/incubator-weex-cli#204]
Error: Cannot find module 'strip-ansi'

![image](https://user-images.githubusercontent.com/30862529/34087844-ae74df54-e3e0-11e7-9a71-2ec7aca30990.png)
包已经装好了，也是一直初始化不成功

**Comment by erha19** [comment]
@calvinCar calvinCar We suggest you not to use`cnpm` because the different version of `npm` may cause many problems, you can see the issues [here](https://github.com/npm/npm/issues/16991). You can try:
```
npm i npm@latest -g
npm i nrm -g --registry=https://registry.npm.taobao.org
nrm use taobao
npm i weex-toolkit -g
```

**Comment by erha19** [comment]
@calvinCar If you have no other question, I will close this issue later.
