### ISSUE TITLE
stuck when install

### ISSUE THREAD

**Issue by Achilles1988** [apache/incubator-weex-cli#205]
node -v
v9.3.0
npm -v
5.6.0

WARN tar zlib error: unexpected end of fileextract inflight@1.0.6
WARN tar zlib error: unexpected end of fileill extract socket.io@1.7.3
WARN tar zlib error: unexpected end of filell extract constants-browserify@1.0.0
WARN tar zlib error: unexpected end of filese: sill extract to-fast-properties@1.0.3
WARN tar zlib error: unexpected end of file: sill extract es6-iterator@2.0.1
⸨            ░░░░░░⸩ ⠼ extract:core-js: sill extract decamelize@1.2.0          <---freeze

**Comment by erha19** [comment]
@Achilles1988  Try:
```
npm i nrm -g --registry=https://registry.npm.taobao.org
nrm use taobao
npm i weex-toolkit -g
```

**Comment by erha19** [comment]
@Achilles1988 If you have no other question, I will close this issue later.
