### ISSUE TITLE
请教版本对应问题

### ISSUE THREAD

**Issue by ellisez** [apache/incubator-weex-cli#210]
经测试,weex-toolkit上的版本为v1.1.0

使用的是weex2.x的内置实例
http://weex.apache.org/cn/references/weex-variable.html
如weex.supports和weex.document等等

但非常遗憾的是weex_sdk v0.17.0仍是使用的是weex1.x的语法
https://github.com/apache/incubator-weex/releases

佐证如下: 生成的weexpack platform add android引入的**weex_sdk.0.16.0.aar**或**weex_sdk.0.17.0.aar**
运行时仍报错**weex.supports与weex.document找不到对象**

那么将会造成一个问题,一份weex1.x用于android/ios运行, 一份weex2.x用于web版运行
无法做到一份代码通用.

有没有什么特别好的解决办法?

比如说: weex-toolkit降级到weex1.x的版本,或者weex_sdk升级到weex2.0的版本
weex-toolkit降级,就需要提供weex1.x所对应的版本号,目前发现weex-toolkit, npm search没有合适的版本

清务必给予解决方案,谢谢

**Comment by ellisez** [comment]
补充几个细节weex2.x对于weex1.x的支持问题
* 2.x有而1.xm没有
weex.supports, weex.document

* 1.x有而2.x没有
__weex_define__

**Comment by erha19** [comment]
@anyly Thank you for your feedback. Recently, we are upgrading the whole toolkit system. I will take into account the issues you mentioned. It is estimated that a new project template will be released next week which will support the latest weex sdk and some new features such as Hot updates, plug-ins and more.
