### ISSUE TITLE
有没有web开发说明文档

### ISSUE THREAD

**Issue by ellisez** [apache/incubator-weex-cli#211]
有没有web方面开发说明文档？

我注意到，官网一直没有对web方面的开发做任何描述，
只是简单的说web的开发与vue一致。

但我读完通篇配置项之后，深深的质疑，我们weex-toolkit开发团队是否真的，自己通篇把一个完整的web开发出来过。

就我的理解，现在的weex的web开发就是一个半成品，说是和vue一样，但里边存在各种配置和路径完全对不上的情况，难道你要用户对此容忍？我觉得索性就不提供，vue本身开发体系也不错。如果提供就保证能运作，一个路径对不上难道要开发者帮你们读配置改路径吗？
真心希望weex能1份代码多出运行，别变成各种鸡肋。

话不多说，下面罗列我读到的bug：
* npm run dev的问题：
读到**npm run dev**，实际操作命令为**webpack --config webpack.config.js --watch -d**（参照package中scripts的定义）
此命令问题是，没有指定webpack生成的jsbundle目录，那么默认目录就是dist了。
dist是什么鬼？你有没有发现，没有任何地方要调用这个目录的，那么我作为用户怎么在pc浏览器中使用他呢？

好吧，你是不是希望我自己写入口文件index.html来加载jsbundle?
当然我注意到web/index.html也有一个入口文件，但是这个文件是有问题的。下面马上要说到

* web/index.html文件名的查找规则有错误：
web/index.html中末尾：
============
<script>
  (function () {
    function getUrlParam (key) {
      var reg = new RegExp('[?|&]' + key + '=([^&]+)')
      var match = location.search.match(reg)
      return match && match[1]
    };
    var page = getUrlParam('page') || '/dist/index.js';
    var bundle = document.createElement('script')
    // only for web
    bundle.src = page.replace(/\.js$/, '.web.js')
    document.body.appendChild(bundle)
  })();
</script>
=========
注意看到**page.replace(/\.js$/, '.web.js')**
换言之，如果，url应当是index.html?page=**xxx.js**，那么实际加载的是**xxx.web.js**
请问这个**xxx.web.js**命名来自于哪里，这么隐晦，开发者只会一推报错。如果需要就用文档说明好。
而且jsbundle生成的是xxx.js不是xxx.web.js，这个半自动化，谁受得了？

* npm run serve实际执行命令是，webpack-dev-server --config webpack.dev.js --watch --open
我注意看到浏览器localhost:8080实际上访问的是index.dev.html页面并且把所有页面当作script来引用。
我觉得这样做不好，不便于调试，如果做成列表选择加载更好。
而且配套的文档也应该要有，其中任何一个界面报错，势必早上空白页面。

上边罗列肯定不全，我认为，既然明显的差异这么多，就该出文档说明。
还有建议我们的开发团队，是否真的自己按照一个开发者的角色创建项目到web版，android版，ios版，一份代码通用，真的跑起来了？**特别是常用插件weex-gcanvas等**

如weex-gcanvas
现在插件这边说platform/android模板错误，找不到weexplugin目录。
然后npm run serve时又报错__weex__define__ is not function，
两边都没有联系起来，就无解了，问题就会继续存在

如果造车的人不开车，那么怎么能造好车呢？
相信像许多开发者，像我一样，充满信心的到来，你们总不希望充满失败的回去吧。
我们中许多人，还在等待一个机会，比如说weex market的插件市场。
希望官方开发团队快速的，做出定版稳定版本，完善的说明文档

**Comment by ellisez** [comment]
补充一下， npm run dev可以将***.vue**文件生成***.web.js**和***.js**两份文件，
问题主要集中在***.we**的bundle上，首先*.we只能生成*.js，那么index.html中要求的*.web.js没有。无法使用。
第二，*.we所编译出来的jsBundle可以在android和ios上正常运行，但是npm run serve到浏览器中，会出现**__weex_define__**等**__weex_xxx__**,**全局函数变量undefined错误**。

难道***.we**已经被定义成不能在浏览器中运行了？我觉得这样有违背“一分代码多处运行的原则”吧

**Comment by erha19** [comment]
@anyly Hi~ Here's a new `weex` development template (see https://github.com/weexteam/weexpack-create) that is currently in the test verification stage, and I've been following up on these issues for a long time, based on the question you mentioned, sync some information with you:
1. The new `weex-toolkit` will release before weexConf.
2. The .we syntax will be gradually abandoned(The new version of the toolkit will no longer support `.we` syntax).
3. There will be a new plug-in mechanism to accommodate the introduction of third-party components.
4. New documents are being developed at [incubator-weex-site](https://github.com/apache/incubator-weex-site).

Please be patient, but also welcome you through the pr contribution code, thanks.

**Comment by erha19** [comment]
@anyly now you can upgrade your toolkit to the latest version, it will create a better weex project for you.

**Comment by ellisez** [comment]
感谢erha19更新了版本，但新版本中npm run android
仍然出现下列错误提示：
\platforms\android\app\build\intermediates\classes\debug\assets\weex_plugin does not exist.

据分析\build\intermediates\classes目录来自android studio的编译结果，
换言之仍然需要将android系统在android studio上跑起来。

我想你总不能要求weex开发者一定要会android studio吧，就要求weex开发者同时具备android能力了。
这样有weex的初衷，望修正此问题

**Comment by ellisez** [comment]
另外npm run android出现下列错误：
 => Install app ...
adb: failed to stat app/build/outputs/apk/playground.apk: No such file or directory

而在目录下，生成的apk是
app-release-unsigned.apk和weex-app.apk

也就是说adb安装的apk名字对不上，请修正

**Comment by erha19** [comment]
@anyly Please provide your `weex` version.
