### ISSUE TITLE
SDWebImage 是否能更新到最新呢？

### ISSUE THREAD

**Issue by scholar-ink** [apache/incubator-weex-cli#212]
现在weex platform add ios 生成的代码，SDWebImage还是3.7.5，不是最新的，导致ios 的代码和其他原生的组件冲突，因为其他原生的组件使用了最新的SDWebImage，在最新的SDWebImage中downloadImageWithURL方法有做修改。

**Comment by acton393** [comment]
hi @scholar-ink  新版本SDWebImage里面改动的行为相对较大， 比如关于GIF的支持可能需要重新兼容
