### ISSUE TITLE
android 运行本地js 报错

### ISSUE THREAD

**Issue by scholar-ink** [apache/incubator-weex-cli#214]
使用navigator的时候 android报错  android.os.FileUriExposedException: file://assets/dist/assets/views/main.js exposed beyond app through Intent.getData()

**Comment by erha19** [comment]
@scholar-ink That's because the old project does not support the platform below android 7.0. Already fixed, it will publish this week. see https://github.com/weexteam/weexpack-android/commit/9d8f7358ba03ba8836c7129b5092364ce09eb1ef

**Comment by erha19** [comment]
@scholar-ink The new toolkit has been published, you can upgrade your `weex-toolkit` and run `weex update weexpack@latest` to create a better template.
