### ISSUE TITLE
onMouseClick中报错

### ISSUE THREAD

**Issue by Stone-Wang** [apache/incubator-weex-cli#216]
在weex debug 时，点击debugger后的页面，点击任意位置都会触发`onMouseClick`事件，在两次`e.nodeName.toUpperCase() != "A"`判断之后，e变为了`null`,所以后边`e.nodeName`报错了。
`TypeError: Cannot read property 'nodeName' of null`

**Comment by erha19** [comment]
@Stone-Wang  I'm not sure what you talking about, can you provide more information?

**Comment by erha19** [comment]
@Stone-Wang  If you have no other question, I will close this issue later:D
