### ISSUE TITLE
升级“weex-previewer”，显示错误

### ISSUE THREAD

**Issue by chenyinlong** [apache/incubator-weex-cli#217]
控制台键入“weex”，显示：
"Update available 1.3.13-beta.10 → 1.3.20-beta.1
 Run weex update weex-previewer@1.3.20-beta.1 to update"

控制台键入“weex update weex-previewer@1.3.20-beta.1”
显示：
“
npm ERR! code EINTEGRITY
npm ERR! sha1-hUNzx/XCMVkU/Jv8a9gjj92h7Cc= integrity checksum failed when using
sha1: wanted sha1-hUNzx/XCMVkU/Jv8a9gjj92h7Cc= but got sha1-Y/xMzuXS13Y9Jrv4YBB4
5sLgBE8=. (1593 bytes)
”

**Comment by erha19** [comment]
@chenyinlong Upgrade your npm to 5+, try:
```
rm -rf ~/.xtoolkit/node_modules/weex-previewer
weex update weex-previewer
```
If you are using `npm` below 5, and the command did not work, you should try to re-install `weex-toolkit`.

**Comment by erha19** [comment]
@chenyinlong  If you have no other question, I will close this issue later:D
