### ISSUE TITLE
weex run android 成功，但是adb安装安装包失败

### ISSUE THREAD

**Issue by chenyinlong** [apache/incubator-weex-cli#218]
最终显示为：
“BUILD SUCCESSFUL

Total time: 20.298 secs
 => Install app ...
adb: failed to stat app/build/outputs/apk/playground.apk: No such file or direct
ory”
现在在文件夹中的文件名为“weex-app.apk”，所以找不到；
请问weex run的配置文件在哪，怎么修改这个名字

**Comment by erha19** [comment]
@chenyinlong The new `weexpack` will release this week or next week, you can config the app name by edit `android.config.json`. For now, you have no way but edit source code to change it.

**Comment by woodstream** [comment]
@erha19 how to edit it？

 `android.config.json` like this，but “playground” not found
>{
  "AppName":"WeexApp",
  "AppId":"com.alibaba.weex",
  "SplashText":"Hello\nWeex",
  "WeexBundle":"index.js"
}

**Comment by momokoudai** [comment]
感谢楼主提示。
生成的apk是 weex-app.apk 和 app-release-unsigned.apk  而 weexpack 去运行playground.apk 肯定是失败的。
windows 的配置目录在 C:\Users\xxx\.xtoolkit\node_modules\weexpack 我把里面所有的playground.apk都改成了 weex-app.apk  然后就可以了。
**或者**
修改build.gradle 里的 输出包名 
看起来weexpack 是读取了android.config.json。 然而，生成的Android项目里一切都是写死的。包名是com.weex.app。运行的是写死的playground.apk。希望可以改进。

**Comment by HereChen** [comment]
just install weex yestoday. I met the same problem.

```
adb: failed to stat app/build/outputs/apk/playground.apk: No such file or directory
```

you can change `weex-app.apk` in  file `platforms\android\app\build.gradle` to `playground.apk`.

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
