### ISSUE TITLE
npm安装问题

### ISSUE THREAD

**Issue by xuedingesmiao** [apache/incubator-weex-cli#219]
软件环境：windows10，node：8.9.4
通过 npm install -g weex-toolkit 命令安装，结果如图
![snipaste_20180103_173818](https://user-images.githubusercontent.com/25097637/34515422-fe46eb02-f0ac-11e7-8546-40ff0559e93f.png)
 只安装了weex-builder 和weex-previewer，且都不是最新版本，
通过weex create app可以安装weexpack，
但是weex debug 安装不上weex-devtool，报错
![snipaste_20180103_174212](https://user-images.githubusercontent.com/25097637/34515548-858f8f06-f0ad-11e7-877e-71c8881568b1.png)
卸载了重新安装还是这样，node也重新安装也没用，不知道出了什么问题。

**Comment by erha19** [comment]
@xuedingesmiao I just release a version that removes some gyp lib dependencies.
Try to remove `C:\.......\.xtoolkit\node_modules\weex-devtool`, then run `weex update weex-devtool@0.3.2` again.

**Comment by erha19** [comment]
@xuedingesmiao  If you have no other question, I will close this issue later:D
