### ISSUE TITLE
Enhancement about error message

### ISSUE THREAD

**Issue by Jinjiang** [apache/incubator-weex-cli#22]
``` html
<template>
  <div></div>
</template>
<style>
/style>
```

When we miss a `<` at `</style>` code. No more error message except `ERR! ModuleBuildError: Module build failed:` only. It should better be more friendly.

**Comment by xu17** [comment]
对 遇到过这个err，但是我代码是直接复制的，貌似涉及到组件的例子都打不开，不知道哪里出问题了，能解释一下吗？我上图
![filehelper_1474551234750_17](https://cloud.githubusercontent.com/assets/20675437/18757026/af18db10-8124-11e6-8251-cd11be2305d9.png)
但是在网页上显示helloworld的例子我又能正常运行，是不是缺少了什么组件？谢谢

**Comment by lvscar** [comment]
latest version of weex-toolkit  ( @0.5.6) improved error information ,  please try it.
'''
npm install -g weex-toolkit@0.5.6  
'''
