### ISSUE TITLE
运行 weex debug  ./src --entry ./src/entry.js   成功但是没有文件

### ISSUE THREAD

**Issue by YafXe** [apache/incubator-weex-cli#220]
运行weex debug  ./src --entry ./src/entry.js 显示调用成功，但是调试页面的入口文件点进去的话显示的是not found

**Comment by erha19** [comment]
Please provide your version info.

**Comment by YafXe** [comment]
v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.11
 - weex-previewer : v1.3.13-beta.10

**Comment by YafXe** [comment]
我npm run build 之后进行单文件调试是没有问题的，也就是说，在我运行debug的命令时，我的整个目录下的文件或者说某个.vue文件没有被编译为native代码并且映射，因为没有报错，所以我不太清楚是哪里的问题，

**Comment by YafXe** [comment]
我已经找到问题了，原因是我更新了工具，新的工具是不支持我那种写法的，在定义入口文件的时候不应该从目录文件夹开始，直接写入口文件的名字就行。

**Comment by YafXe** [comment]
谢谢您的帮助，希望weex越来越好，官方文档能更完善和详细一点。
