### ISSUE TITLE
weex debug时用安卓手机扫码会提示network render error

### ISSUE THREAD

**Issue by YafXe** [apache/incubator-weex-cli#221]
this is my weex-toolkit version:
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.11
 - weex-previewer : v1.3.13-beta.10

when i use android  scan the qrcode to start Debugger and i open the remote debug,  it tips is a 'network render error .......'

**Comment by erha19** [comment]
@417606028 
1.Check if the device and pc are on the same LAN。
2.Close your VPN connection.

**Comment by erha19** [comment]
@417606028 If you have no other question, I will close this issue later:D
