### ISSUE TITLE
weexpack create project出来的项目为什么没有entry.js入口文件了？

### ISSUE THREAD

**Issue by hxyoo1990** [apache/incubator-weex-cli#222]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
 - weex-builder : v0.2.13-beta.6
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.13
 - npm 5.5.1
- node v8.9.1

- platform (Win)

## The key error stack message.
用weexpack create project出来的项目为什么没有entry.js入口文件了，想要集成vue-router完成页面跳转、页面间传参，是要自己配置webpack.config.js吗？如果是，该如何配置呢？

**Comment by erha19** [comment]
@hxyoo1990 You can see the examples:
https://github.com/zwwill/yanxuan-weex-demo
https://github.com/weexteam/weex-hackernews

**Comment by erha19** [comment]
@hxyoo1990 If you have no other question, I will close this issue later.:D
