### ISSUE TITLE
weex debug 安装weex-devtool失败

### ISSUE THREAD

**Issue by liushuhui** [apache/incubator-weex-cli#223]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

**Comment by liushuhui** [comment]
![image](https://user-images.githubusercontent.com/26155477/34613343-6490f594-f268-11e7-820f-f892097bad3a.png)

**Comment by liushuhui** [comment]
这个问题怎么解决

**Comment by liushuhui** [comment]
How to solve this problem？

**Comment by AugTang** [comment]
同问，这个问题怎么解决，求大佬解决

**Comment by erha19** [comment]
@liushuhui @AugTang Please provide your env, try to run `weex -v` and `npm -v`.

**Comment by liushuhui** [comment]
应该是网络原因，需要翻墙吧，有的人在翻墙情况下很顺利，但是有的用mac也能顺利安装，具体原因不太清楚。希望有大佬指点一二

**Comment by liushuhui** [comment]
Does anyone know how to solve this problem?

**Comment by AugTang** [comment]
@erha19 
E:\wxnew>weex -v
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.7
 - weex-previewer : v1.3.20

E:\wxnew>npm -v
5.6.0

**Comment by liushuhui** [comment]
@erha19
 $ weex -v
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.4
 - weex-previewer : v1.3.13-beta.10
$ npm -v
5.6.0
$ node -v
v9.3.0

**Comment by AugTang** [comment]
@erha19 大佬，我项目已经延期两周了，钟爱阿里，看到邮件还望能在百忙之中，出来指导，感激不尽

**Comment by erha19** [comment]
@AugTang @liushuhui Sorry for the late reply，try this:
```
weex config registry https://registry.npm.taobao.org/
```
It will change the registry to `taobao`,  hope this would help.

**Comment by liushuhui** [comment]
@erha19 大神您好， 一开始就是用的淘宝镜像安装的。

**Comment by AugTang** [comment]
@erha19 我也是的

**Comment by erha19** [comment]
@AugTang @liushuhui show me you `weex config`, and I 'm should know there may be some problem on windows, I do not test the whole toolkit on windows,  this week I will try to fix the issues after I release a new weex-toolkit.

**Comment by liushuhui** [comment]
weex config
registry = https://registry.npm.taobao.org/

**Comment by liushuhui** [comment]
@erha19 因为我的英语水平属于看得懂，写不出来，所以用中文了。一开始用的是淘宝镜像安装的，但是会出现错误，能查看weex版本号 但是不能使用weex命令，结果就换了npm安装就没问题了，但是安装weex-devtool始终不成功。谢谢您百忙之中为我解疑。

**Comment by liushuhui** [comment]
@erha19 大佬，因为电脑故障，重装了 win10系统，安装weex-toolkit时，weex -v没问题，但是 启动weex 命令时会报错。无论是npm 还是 cnpm都是这样。能帮忙看看吗？
![image](https://user-images.githubusercontent.com/26155477/34975340-5fa1fb98-facc-11e7-9e89-98b32543366f.png)

**Comment by erha19** [comment]
@liushuhui Please re-install `weex-toolkit` and show me your install log text.

**Comment by liushuhui** [comment]
@erha19 麻烦您了
 
![image](https://user-images.githubusercontent.com/26155477/34978994-00035272-fadb-11e7-80d8-c5baa0eea5a0.png)

**Comment by erha19** [comment]
@liushuhui try `npm i weex-toolkit --no-optional --registry https://registry.npm.taobao.org/ -g`

**Comment by liushuhui** [comment]
@erha19 谢谢大神，我刚刚重新装了系统，这个问题没有了，但是weex debug仍然还是这个错误，开始是win7的，现在这个是win10的，但是依然是这个错误呢。是要翻墙吗？

**Comment by erha19** [comment]
@liushuhui is the same error log? please show me detail

**Comment by liushuhui** [comment]
@erha19  大神，谢谢您百忙之中为我解疑。
![image](https://user-images.githubusercontent.com/26155477/34994574-fb334bec-fb0e-11e7-9baf-ab69a565543d.png)
![image](https://user-images.githubusercontent.com/26155477/34994676-45661b72-fb0f-11e7-89ba-38d829b01769.png)

**Comment by AugTang** [comment]
@liushuhui 你这个是环境没装好，用命令把这个卸载，然后去c盘删除相关的文件，重新装就好了

**Comment by liushuhui** [comment]
@AugTang  开始就是这么做的，结果没用，所以我才换的win10呢，我再试一遍

**Comment by liushuhui** [comment]
@AugTang  @erha19   试了这个办法 ，还是报这个错误。。。。。。。

**Comment by liushuhui** [comment]
@erha19 大神，希望您百忙之中帮我看看，感谢!

**Comment by erha19** [comment]
Merge issues to #256

**Comment by iizhangchao** [comment]
@liushuhui  前辈 你的环境搭建好了么，我也是遇到这个问题，一直解决不了
