### ISSUE TITLE
运行 weex src/index.vue 后，扫描QR码，却无法打开页面。

### ISSUE THREAD

**Issue by y-cares** [apache/incubator-weex-cli#227]
运行 weex src/index.vue 后，扫描QR码，却无法打开页面，显示 network error，更换多个 wifi 后，依然无效...   但是扫描 weex-ui 的QR码，却能正常显示...
## Your development environment
weex -v ：
![image](https://user-images.githubusercontent.com/20083236/34811589-919c4c6e-f6dc-11e7-8304-d5b215b12708.png)
已为最新，
node 及 npm 版本：
![image](https://user-images.githubusercontent.com/20083236/34811637-c2e0b2ec-f6dc-11e7-80b8-83ec3317ec36.png)
也符合相关版本要求...
操作系统为： win7 系统
## The key error stack message.
暂无报错信息...

**Comment by erha19** [comment]
@y-cares You should scan the QR-code in the same LAN, please confirm playground and pc under the same LAN and the closure of the agent like VPN.

**Comment by y-cares** [comment]
@erha19  是在同一局域网下面的，并且代理什么的均关闭，但是升级到最新版本后，的确扫描后，为network error ，而且修改代码时，没有热更新，而把 weex-previewer 的版本降到 1.3.13 却能正常使用...  但却无法引入 weex-ui 引入后报 unexpected token export 。（配置文件和依赖，均已安装）

**Comment by erha19** [comment]
@y-cares wait a moment, I will fix it.

**Comment by y-cares** [comment]
@erha19   好的  谢谢

**Comment by myronlee** [comment]
@y-cares 请教一下，如何降weex-previewer版本

**Comment by y-cares** [comment]
@myronlee  我是卸了重装的...

**Comment by erha19** [comment]
@y-cares @myronlee 
I have been fixed this issue on `weex-previewer@1.4.0` and `weex-devtool@0.3.3`, that caused by a big change of webpack 3+ compile logic. you can upgrade it by:
```
weex update weex-previewer@1.4.0
weex update weex-devtool@0.3.3
```

**Comment by y-cares** [comment]
@erha19   升级报错了......
npm ERR! code EINTEGRITY
npm ERR! sha512-GxMpax8a/VgcfRrVy0gXD6yLd5ePYbXX/5zGgTVYp4wXtJklS8Z2VaUArJgc//f6/Dzil7BaJObdSv8eKKCPgg== integrity checksum failed when using sha512: wanted sha512-GxMpax8a/VgcfRrVy0gXD6yLd5ePYbXX/5zGgTVYp4wXtJklS8Z2VaUArJgc//f6/Dzil7BaJObdSv8eKKCPgg== but got sha512-BpErUP1CcAdW8IQ0834qG+5yGMzCRKEXH+HmJ/rXNAfOeOY4GwNDOG16Oil7G7MpeP+1QQ9NGCjzI6MebqO+rA==. (9652 bytes)
npm ERR! code EINTEGRITY
npm ERR! sha512-jRwlFbINAeyDStqK6Dd5YuY0k5YuzQUvlz2ZamuXrXmxav3pNqe9vfJ402+2G+OmlJSXxCOpB6Uz0INM7RQe2A== integrity checksum failed when using sha512: wanted sha512-jRwlFbINAeyDStqK6Dd5YuY0k5YuzQUvlz2ZamuXrXmxav3pNqe9vfJ402+2G+OmlJSXxCOpB6Uz0INM7RQe2A== but got sha512-hHvbCsXtwKIznu5Qmqfe/IwZ4O5frqe+j04fN/5u/9Rg48dpWIKyYqAN68N1wwqGSMToo4FhU9/MrH+QZlFdkQ==. (8868 bytes)
npm ERR! code EINTEGRITY
npm ERR! sha512-IsORQDpaaSwcDP4ZZnHxgE85werpo34VYn1Ud3mq+eUsF593faR8oCZNXrROVkpFu2TsbrNhHin0aUrTsQ9vNw== integrity checksum failed when using sha512: wanted sha512-IsORQDpaaSwcDP4ZZnHxgE85werpo34VYn1Ud3mq+eUsF593faR8oCZNXrROVkpFu2TsbrNhHin0aUrTsQ9vNw== but got sha512-B6ww/BgkeBIfyIaOKPMW2zteXdAeXSfOTPv6kGhl3luYw4BOTopQ0EjdGFePGdajvBjLQZq12axGLtHnrp+/Pg==. (5787 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-01-16T11_24_56_382Z-debug.log

**Comment by erha19** [comment]
That's a knowing problem by `npm5`, see https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=code+EINTEGRITY,  try to re-install the `weex-toolkit` and update again.

**Comment by y-cares** [comment]
@erha19   已经卸载重装过了 还是一样的情况...

**Comment by erha19** [comment]
@y-cares I will upgrade a beta version of `weex-toolkit`, you can just install by `npm i weex-toolkit@1.1.0-beta.8 -g`.

**Comment by y-cares** [comment]
@erha19    这个测试版  weex-v 看不到当前各个包版本
C:\Users\Lenovo>weex -v

Usage: weex <command>

where <command> is one of:

  debug         Start weex debugger
  config        Configure the global configuration file
  compile       Compile we/vue file
  create        Create a weexpack project
  preview       Preview a weex page
  platform      Add/remove ios/android platform
  plugin        Add/remove weexplugin
  run           Build your ios/android app and run
  update        Update weex package version
  xbind         Binding a thrid-part tool

  weex <command> --help      help on <command>

而且： weex update weex-previewer@1.4.0 之后，在输入 weex -v 还是一样的结果...

**Comment by erha19** [comment]
@y-cares try 1.1.0-beta.9

**Comment by wyh497823256** [comment]
#224

**Comment by y-cares** [comment]
@erha19    完美  谢谢啦...

**Comment by erha19** [comment]
Latest stable  version is `v1.2.2`.
