### ISSUE TITLE
Fresh created project directory list is not same as given.

### ISSUE THREAD

**Issue by arifhussain353** [apache/incubator-weex-cli#228]
Hi,
I created fresh project with following steps:
1) `$ npm install -g weex-toolkit`
2) `$ weex init your_project_name`

After these steps, I got directory structure look like this : 
![image](https://user-images.githubusercontent.com/12670763/34917479-d6ef249c-f968-11e7-8ba9-632de74ff000.png)

Instead of this: 
```
 |—— .gitignore
    |—— README.md
    |—— .eslintrc
    |—— .babelrc
    |-- app.js
    |—— assets
    |—— /src
    |     |—— foo.vue
    |—— /build
    |—— weex.html
    |—— index.html
```
Directory structure is different. Did i miss any step ?

**Comment by arifhussain353** [comment]
```Since the 1.0.9 version, the ` weex init` command has been removed. If you want to create the weex project, create it with the `weex create` command.```
But what about project directory structure?

**Comment by erha19** [comment]
@arifhussain353 You can use `vue-cli` to create `vue` project as the old `weex init` command.
The project directory structure will be change soon, but for now, the directory structure is like the directory created by `weex init`.

**Comment by arifhussain353** [comment]
Ok thanks @erha19
