### ISSUE TITLE
按照文档，创建新的工程，debug index.vue，页面渲染不出来

### ISSUE THREAD

**Issue by myronlee** [apache/incubator-weex-cli#229]
## Your development environment
   v1.1.0-beta.7
 - weexpack : v0.4.1
 - weex-builder : v0.2.13-beta.7
 - weex-devtool : v0.3.2
 - weex-previewer : v1.3.20

  npm -v
  5.0.3 

  node -v
  v8.1.0

## The key error stack message.
没有报错

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

cnpm install -g weex-toolkit

weex create someProject
//切到someProject根目录
npm install
weex debug src/index.vue

另外请教如何降低版本，
执行cnpm install -g weex-toolkit@v1.1.0-beta.2，之后weex -v得到依旧是
 - weexpack : v0.4.1
 - weex-builder : v0.2.13-beta.7
 - weex-devtool : v0.3.2
 - weex-previewer : v1.3.20

**Comment by korman** [comment]
去看下 #227 的问题，已经在修复了，但是没看到commit里面有 #227 的修复提交，应该还没有修复完成

**Comment by erha19** [comment]
#227 has been fixed.
