### ISSUE TITLE
今晚这个新版本出来，win10系统重新安装weex-toolkit，安装成功，能够运行weex -v，但是运行weex报错？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#231]
重装好几次了，还是不成功

![weex](https://user-images.githubusercontent.com/31499235/35111943-86d730ba-fcb7-11e7-91bf-36fc00a097ca.png)

**Comment by AugTang** [comment]
@erha19 今晚这个新版本出来，win10系统重新安装weex-toolkit，安装成功，能够运行weex -v，但是运行weex报错？

**Comment by y-cares** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/20083236/35131817-487a1a3e-fd03-11e7-9f3e-ded29e8a8f5c.png)
win 10 电脑重装 weex-toolkit  安装失败，是什么原因？！

**Comment by juneleaf** [comment]
我也一样叻，他在依赖的xtoolkit里又依赖这个iosdeploy，但这个不能在mac以外装所以安装失败

**Comment by erha19** [comment]
Try `npm i --no-optional weex-toolkit@1.2.2 -g`

**Comment by y-cares** [comment]
@erha19  
![image](https://user-images.githubusercontent.com/20083236/35134286-49c55040-fd10-11e7-93b5-0fee4360929c.png)
已经卸载删除重装了 还是不行啊...

**Comment by erha19** [comment]
@y-cares  Try version `v1.2.3`,  `ios-deploy` is useless, I have been removed it. https://github.com/weexteam/xtoolkit/commit/e0a5959d2b29bbdb950bf6bd561cab3c762cbbb8

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/35135862-d5195218-fd1a-11e7-85bd-6a9b57b1f894.png)
npm i --no-optional weex-toolkit@1.2.2 -g          还是报错啊


我的node,npm版本如下：
![image](https://user-images.githubusercontent.com/31499235/35135886-02c38ecc-fd1b-11e7-8590-2cca2fb2a861.png)
@erha19

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/35136263-8cdfa53a-fd1d-11e7-8ac3-a6777381b8fa.png)
`npm i --no-optional weex-toolkit@1.2.2 -g `安装之后，运行weex命令，出现这个错误
@erha19

**Comment by erha19** [comment]
@AugTang  latest version is 1.2.3, and maybe you can create the `config.json` manually,  it would be a permission problem.

**Comment by y-cares** [comment]
@erha19    大佬 又遇到个问题
![image](https://user-images.githubusercontent.com/20083236/35137845-735c7c74-fd26-11e7-9896-bdc070350fbe.png)
安装了 1.2.3 之后，运行 weex -v 或 weex 都会出现一些选项，选完之后，就结束了，即没有生成版本信息，也没生成新的项目

**Comment by erha19** [comment]
@y-cares you need admin permission.
