### ISSUE TITLE
Missing English strings for /platforms/android/app/src/main/res/values-zh-rCN/strings.xml

### ISSUE THREAD

**Issue by fumpierrez** [apache/incubator-weex-cli#232]
## Your development environment
weex-toolkit version:
v1.1.0-beta.9
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.3.12
 - weex-devtool : v0.3.3
 - weex-previewer : v1.4.3

- platform (Win/Mac/Ubuntu..)
Mac Sierra 10.12.4 

## The key error stack message.
data/frontend/platforms/android/app/src/main/res/values-zh-rCN/strings.xml:21: Error: The resource string "cpu_not_support_tip" has been marked as translatable="false" [ExtraTranslation]
  <string name="cpu_not_support_tip">对不起,您当前的设备是X86架构.\n我们只支持ARM架构的设备!</string>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.).

   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.

2 errors, 0 warnings

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

Right after creating a new project and trying to build the android version, I get that error
```
weexpack build android
```

The workaround is to edit the file and remove those two lines but this might be annoying for new users of Weex so please fix, thanks

**Comment by erha19** [comment]
That's lint error, it will be removed on next version.

**Comment by erha19** [comment]
@fumpierrez now  you can update `weexpack` to the latest version, it will create a more better project. try `weex update weexpack@latest`
