### ISSUE TITLE
win7 64bit  yarn 安装的时候报2个错：

### ISSUE THREAD

**Issue by yurizhang** [apache/incubator-weex-cli#233]
win7 64bit  yarn 安装的时候报2个错：

![image](https://user-images.githubusercontent.com/20555332/35132135-aedb8a5a-fd04-11e7-8cc9-2aa7a9da8404.png)

我的node是8.9， yarn 1.2.1

**Comment by erha19** [comment]
@yurizhang Try to install with `npm@5`, I have not test it with yarn, and the latest version is `v1.2.3`.

**Comment by Aibric** [comment]
我刚刚升级的 `v1.2.3`我的 `npm@5.0.3`， 运行 `weex `命令报 SyntaxError: Unexpected token ..
\weex-toolkit\src\utils\logger.js:115  
```
module.exports = {
  ...logger,
  events,
  LOGLEVELS
};
```
...logger 为115行
@erha19 请问如何解决，谢谢。

**Comment by yurizhang** [comment]
我也报这个错： mac和win7都是的
\weex-toolkit\src\utils\logger.js:115

module.exports = {
  ...logger,
  events,
  LOGLEVELS
};
...logger 为115行
@erha19 请问如何解决，谢谢。

**Comment by Aibric** [comment]
改成这种方式就可以了，应该是`ES2015`不支持 对象里使用 ` ...` @yurizhang 
```
module.exports = {
  setLevel,
  subscribe,
  verbose: log('verbose'),
  log: log('log'),
  info: log('info'),
  warn: log('warn'),
  error: log('error'),
  success: log('success'),
  events,
  LOGLEVELS
};
```

当然这不是最少的解决办法。

**Comment by erha19** [comment]
@yuanyan please upgrade to `v1.2.5`.

**Comment by yurizhang** [comment]
这个是安装weex-toolkit时报的错，新安装包有问题，在等解决~

**Comment by rockstone20** [comment]
`odule.js:538
    throw err;
    ^

Error: Cannot find module '../src/create'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/shipeng/.xtoolkit/node_modules/weexpack/bin/weexpack-create.js:9:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)`

————————————————



weex create 报错怎么解啊， 在线等

运行weex已经没问题了 , 出现下面的信息，就是创建项目的时候报错！ 
Usage: weex <command>
where <command> is one of:
  debug         Start weex debugger
  config        Configure the global configuration file
......
  weex <command> --help      help on <command>

**Comment by erha19** [comment]
@rockstone20 `weex update weexpack@latest`, latest version is `v1.0.2`
