### ISSUE TITLE
执行 weex -v失败

### ISSUE THREAD

**Issue by mayichaocc** [apache/incubator-weex-cli#234]
提示  May weex-toolkit anonymously report usage statistics to improve the tool over time?

**Comment by mayichaocc** [comment]
选y后提示
? Which npm registry you perfer to use? npm
12:53:55 : Set telemetry => true
12:53:55 : Set registry => http://registry.npmjs.org
(node:870) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/Users/c/.xtoolkit/config.json'
(node:870) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by erha19** [comment]
@mayichaocc `npm i weex-toolkit@latest -g`, latest version is `v1.2.3`

**Comment by mayichaocc** [comment]
@erha19 Thanks
