### ISSUE TITLE
安装1.2.3版本的成功，总提示：接受匿名统计吗？选择y，下面就报错

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#235]
![image](https://user-images.githubusercontent.com/31499235/35137760-ea4b0cde-fd25-11e7-813c-5f7b226ce3da.png)
@erha19

**Comment by momokoudai** [comment]
C:\Users\your name>mkdir .xtoolkit

**Comment by yurizhang** [comment]
![image](https://user-images.githubusercontent.com/20555332/35138741-eadaf8a8-fd2a-11e7-894a-898f0571998c.png)


![image](https://user-images.githubusercontent.com/20555332/35138751-f488ca06-fd2a-11e7-9fb0-5ab578c36b66.png)

**Comment by erha19** [comment]
@AugTang @DamingLake @yurizhang please use admin cmd and ensure you have the vc6++ environment. The latest version is `1.2.6`.

**Comment by y-cares** [comment]
@erha19   以管理员的身份运行cmd  还是一样的结果

**Comment by erha19** [comment]
Let me find a windows mechine and I will try to fix it.
