### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by xu17** [apache/incubator-weex-cli#24]
![filehelper_1474783682878_93](https://cloud.githubusercontent.com/assets/20675437/18813337/b7291066-8329-11e6-9f87-f416d77fb747.png)

version： 0.4.0

**Comment by Jinjiang** [comment]
Seems you require `weex-components` in `tech_list.we`. Please just remove that part.
Thanks.

More discussion about the usage please go to gitter https://gitter.im/weexteam/cn
