### ISSUE TITLE
win10环境下，安装weex-debugger报错！

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#243]
![image](https://user-images.githubusercontent.com/31499235/35201884-d861dfc6-ff59-11e7-8a05-e2dc9fd8b63b.png)
@erha19 按照#240里面的操作了，还是这错误。大佬，麻烦给我看看

**Comment by erha19** [comment]
#224

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/35204888-2833a0e0-ff6c-11e7-9f74-e7865e301832.png)
@erha19

**Comment by erha19** [comment]
@AugTang try this `npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org` and run `weex debug` in a new shell (the Environment Variables may not take effect immediately )

**Comment by AugTang** [comment]
感谢，已解决 @erha19
