### ISSUE TITLE
weex-debugger模式，仅支持ios设备吗？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#244]
![image](https://user-images.githubusercontent.com/31499235/35206208-04febc04-ff76-11e7-9982-2294510c1fb0.png)
@erha19

**Comment by erha19** [comment]
@AugTang Not, you can use [weex playground](http://weex.apache.org/tools/playground.html) to scan the QR-code, but now the latest playground has turned off the debug mode, I have told the playground developer to fix it. It will be fix before 6.00 pm.

**Comment by erha19** [comment]
@AugTang The playground developer is too busy, the problem is fix but the release will be tomorrow.

**Comment by AugTang** [comment]
此时还做回复，感激，weexteam真的敬业，对之前的唠叨，向你们道歉，辛苦了，大佬们 @erha19

**Comment by liushuhui** [comment]
@erha19 感谢大佬们，辛苦了

**Comment by erha19** [comment]
@AugTang @liushuhui latest playground has been released on [weex playground](http://weex.apache.org/tools/playground.html) .
