### ISSUE TITLE
如何删除weex-toolkit 生成项目中的Devtools

### ISSUE THREAD

**Issue by junhaotong** [apache/incubator-weex-cli#245]

**Comment by erha19** [comment]
@junhaotong please show me more detail, I don't know which `Devtools` you talk.

**Comment by junhaotong** [comment]
@erha19 
![18b458dfaaf9516472fa9cad52641960](https://user-images.githubusercontent.com/20011131/35259294-0204d716-0040-11e8-9dd8-98b4c4cda35e.jpeg)

**Comment by erha19** [comment]
@junhaotong I think it should be removed too, and i will remove it on next template.

**Comment by junhaotong** [comment]
收到！感谢马里奥大神~哈哈

**Comment by junhaotong** [comment]
最好是有一个控制它的开关,开发者可以自行关闭 😀😀😀

**Comment by erha19** [comment]
@junhaotong you can use the module like:
```
let titleBar = weex.requireModule('titleBar');
titleBar.showTitleBar(false);
```
