### ISSUE TITLE
ios手机 扫描生成的QR码，显示空白页....

### ISSUE THREAD

**Issue by y-cares** [apache/incubator-weex-cli#246]
## Your development environment
- weex-toolkit verison (Run `weex -v`)
  C:\Users\htuser>weex -v
     v1.2.6
    - weexpack : v1.0.2
    - weex-debugger : v1.0.0
    - weex-builder : v0.3.12
    - weex-previewer : v1.4.4
- platform (Win/Mac/Ubuntu..)
win 10
## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
weex create 新创建的一个项目，无添加任何内容。 运行 npm start 后，生成的QR码，ios手机用 weex playground 扫描QR码后，为空白页面，安卓手机 扫描 QR 码后，能正常生成 初始页面。

**Comment by y-cares** [comment]
@erha19 
老的项目 运行weex preview src/index.vue  报错  什么原因？
![image](https://user-images.githubusercontent.com/20083236/35261621-fd72657c-004b-11e8-8657-beab3abaa849.png)

**Comment by erha19** [comment]
#250
