### ISSUE TITLE
执行weex create 命令出现错误

### ISSUE THREAD

**Issue by jsasdw1991** [apache/incubator-weex-cli#247]
![image](https://user-images.githubusercontent.com/6205001/35256601-879e24c4-002f-11e8-84fe-2a559f01ee31.png)

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Ricky/.xtoolkit/node_modules/npm/node_modules/ansistyles' -> '/Users/Ricky/.xtoolkit/node_modules/npm/node_modules/.ansistyles.DELETE'

weex 版本
![image](https://user-images.githubusercontent.com/6205001/35256624-a50c277c-002f-11e8-85da-a70c7050fe5c.png)

node版本
![image](https://user-images.githubusercontent.com/6205001/35256634-b0a6f40e-002f-11e8-9e6b-c5c9152b3891.png)

npm版本
![image](https://user-images.githubusercontent.com/6205001/35256640-bafea424-002f-11e8-828a-47906e267a67.png)

**Comment by erha19** [comment]
@jsasdw1991 Try to delete the cache file by `rm -rf ~/.xtoolkit/node_module/weexpack`, and tell me if you upgrade to `1.2.7` or new developer with `weex-toolkit`, after that, run`weex create vue-app --verbose` if there still have some wrong and show me the detail log.

**Comment by jsasdw1991** [comment]
@erha19 thank you.The problem has been solved.

**Comment by NoraGithub** [comment]
`weex update weexpack@xxx` met a similiar issue and it's solved by this solution
