### ISSUE TITLE
关于最新版toolkit，debug模式，android手机扫码，空白问题？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#248]
我的项目是新建的，操作步骤：
1.npm run dev
2.weex debug src -e index.vue
3.此时会看到以下页面：
![image](https://user-images.githubusercontent.com/31499235/35257964-7bbf3e56-0037-11e8-9118-05bfe2ea6415.png)
4.playground扫码，进入debug页面：
![image](https://user-images.githubusercontent.com/31499235/35257992-aab8be76-0037-11e8-9629-461ce8804780.png)
5.使用playground，扫项目外层二维码：
![image](https://user-images.githubusercontent.com/31499235/35258257-246fe52c-0039-11e8-9b6b-f36e6d825567.png)
此时手机出现这样：
![image](https://user-images.githubusercontent.com/31499235/35258207-e670dd94-0038-11e8-9173-ace5992ef588.png)
6.点击右侧二维码，出现这样：
![image](https://user-images.githubusercontent.com/31499235/35258273-387ae90e-0039-11e8-8885-49e5278945d5.png)
此时手机，会出现空白，报错：
![image](https://user-images.githubusercontent.com/31499235/35258308-63cbc5ba-0039-11e8-8b85-205e595ab8cd.png)

综合上面的问题，请问是我的操作步骤有问题吗？能否告知解决方案，感谢！
@erha19

**Comment by SadaHaruTyan** [comment]
手机代理设了吗？我这边手机连上电脑之后就正常了，你可以试一下

**Comment by erha19** [comment]
@AugTang Looks like it is a network problem and you do not scan right file that can be rendered by weex.

**Comment by AugTang** [comment]
网络没有问题，是在同一个局域网下。 @erha19

**Comment by liushuhui** [comment]
@erha19 为什么有时启动weex bug后一会就自己退了。然后有这个警告。这是网络原因还是怎么回事，感觉不太稳定。有时扫描又出现devtool。
![image](https://user-images.githubusercontent.com/26155477/35315823-80bf54f4-0109-11e8-8c3f-642f423e3114.png)
![image](https://user-images.githubusercontent.com/26155477/35315508-abf96666-0107-11e8-9596-eb8940a4a255.png)

**Comment by JaredCen** [comment]
@erha19 Does the debuger only support Mac now?

**Comment by erha19** [comment]
@liushuhui you can install the `weex playground` to debug on android.

**Comment by erha19** [comment]
see #265
