### ISSUE TITLE
Weex-toolkit  1.2.7版本 weex build android 打包APP 失败

### ISSUE THREAD

**Issue by ghostrune** [apache/incubator-weex-cli#249]
在weex-toolkit 1.2.7 版本 环境如下
![4t mxu4c x d_1mzhb 4by](https://user-images.githubusercontent.com/22071449/35260914-c6ed141e-0048-11e8-8dd1-d7a6b5bcd83a.png)

在打包Android app的时候 出现了以下错误
![vy 7 q54w2_e92 p m7mxs](https://user-images.githubusercontent.com/22071449/35260894-a43dcb16-0048-11e8-9d9c-980fb772efc7.png)
针对这个情况 我去找到这个文件 在45行代码  缺了个 = 号  

接下来继续打包 发现又出现另外的错误，这下就看不懂了，说接收到undefined   路径必须是字符串
![eiwpykf6_ ofdwh 6w 1mw](https://user-images.githubusercontent.com/22071449/35260962-fd2d3cf2-0048-11e8-8b34-1104cd03d3b4.png)

**Comment by erha19** [comment]
@sghuangrihuang you can run `weex update weexpack@1.0.3` to fix this problem.

**Comment by erha19** [comment]
@sghuangrihuang If there is no other question, I will close this issues late :)

**Comment by ghostrune** [comment]
安装是安装成功了 build successful
![6b kzuqsvo plfa mzu8g6](https://user-images.githubusercontent.com/22071449/35270745-fab92946-006a-11e8-999b-b6e7dff81276.png)

问题是生成出来的apk 是app-release-unsigned.apk 文件  安装之后 报安装包解析错误
![9ek1m gd 3k uik8 6l x](https://user-images.githubusercontent.com/22071449/35270777-13756936-006b-11e8-9711-4dfc11c2a732.png)


所以我卸载了week-toolkit 并且手动删除.xtoolkit 文件
重新安装 最新的版本 
![vd459t1jtss x c8jry ks](https://user-images.githubusercontent.com/22071449/35270709-ea436004-006a-11e8-86c9-612ae114487b.png)


但是 在安装weex platform add android 报错
![aj73c 6x1 k7 v13ev 03](https://user-images.githubusercontent.com/22071449/35270729-ef87198e-006a-11e8-8f4d-20f3a88dec5a.png)

**Comment by sghuangrihuang** [comment]
更新1.0.5  上面的问题解决了  然后 出现了 新的bug
![image](https://user-images.githubusercontent.com/22071449/35273532-dbe4ab18-0073-11e8-8e88-65b7fa98b9b4.png)

**Comment by sghuangrihuang** [comment]
更新weexpack1.0.6  上面的问题解决了 又出现了新的bug
![ni5 3 5zqkxqsfrxf 42jfu](https://user-images.githubusercontent.com/22071449/35273656-4ba8fc4c-0074-11e8-8ddf-9236bb88d914.png)

**Comment by erha19** [comment]
@sghuangrihuang latest version is `1.0.6`.

**Comment by ghostrune** [comment]
坐等1.0.7 
![yywk ec a zzh g 1he4](https://user-images.githubusercontent.com/22071449/35273746-a3dab2b6-0074-11e8-8ba9-7059055caf0f.png)

**Comment by erha19** [comment]
@sghuangrihuang Release v 1.0.7, I'm refactoring the `weexpack` code, there is the much more useless thing in it,  recent updates will be more frequent.

**Comment by ghostrune** [comment]
大佬 辛苦了， 最后一个问题
![image](https://user-images.githubusercontent.com/22071449/35275257-20f0da28-007a-11e8-9c2a-4f16b4f62484.png)
这算是打包成功么？ 还是说我没弄签名 毕竟我直接打包的
