### ISSUE TITLE
覆盖命令行单元测试

### ISSUE THREAD

**Issue by xudafeng** [apache/incubator-weex-cli#25]
避免基础命令挂掉，影响weex产品可用性。
## 提供如下示例，欢迎采纳
- [macacajs/macaca-cli](//github.com/macacajs/macaca-cli/)
- [macacajs/app-inspector](//github.com/macacajs/app-inspector/)
- [xudafeng/startserver](//github.com/xudafeng/startserver/)
- [xudafeng/detect-port](//github.com/xudafeng/detect-port/)
- [reliablejs/reliable-master](//github.com/reliablejs/reliable-master/)
- [reliablejs/reliable-macaca-slave](//github.com/reliablejs/reliable-macaca-slave)

@lvscar

**Comment by xudafeng** [comment]
@jinjiang

**Comment by lvscar** [comment]
收到, 好多可用的例子.  😀
