### ISSUE TITLE
新建项目 npm start 之后，用ios版weex playground扫描二位码之后成空白页

### ISSUE THREAD

**Issue by jsasdw1991** [apache/incubator-weex-cli#250]
项目启动没问题
![image](https://user-images.githubusercontent.com/6205001/35266359-0f88f2aa-005e-11e8-91d6-58a91aafd615.png)
然后二维码页面也有
![image](https://user-images.githubusercontent.com/6205001/35266390-2d40ddda-005e-11e8-9595-b001f813e9dd.png)
然后手机扫描之后变成空白页
后来点开日志有一个报错
![image](https://user-images.githubusercontent.com/6205001/35266429-46d09222-005e-11e8-9ba0-b67e484a6552.png)

**Comment by erha19** [comment]
@jsasdw1991 It will be fixed soon.

**Comment by erha19** [comment]
@jsasdw1991  you can run `weex update weexpack@latest` to upgrade weexpack and then re-create your project, or you can change the file on `web/preview.html`, modify `url += '?_wx_tpl=' + url + '&wh_weex=true'` to `url += '?_wx_tpl=' + url`.

**Comment by y-cares** [comment]
@erha19   将url += '?_wx_tpl=' + url + '&wh_weex=true' 改为 url += '?_wx_tpl=' + url.后，重新运行 debug 依然是空白页面
![2](https://user-images.githubusercontent.com/20083236/35308925-e6eb311e-00e4-11e8-99a7-5e3585a3868b.png)

![1](https://user-images.githubusercontent.com/20083236/35308918-e0effcb8-00e4-11e8-91e1-b902624bae05.png)

weexpack 升级到1.0.3版本后，创建的新项目，依旧是空白页

**Comment by erha19** [comment]
latest version is 1.0.8

**Comment by y-cares** [comment]
@erha19   但是  我按照你说的 改了url += '?_wx_tpl=' + url + '&wh_weex=true' 这个 怎么还是没效果？！

**Comment by y-cares** [comment]
@erha19  weexpack 升级到1.0.8之后，新创建的一个项目，启动debug 扫描二维码，依旧是空白页面

**Comment by erha19** [comment]
@y-cares the iOS debug sdk may have a problem with the `iOS weex playground`, the new release will be published soon.

**Comment by acton393** [comment]
hi @y-cares  for iOS  playground, I remove the preprocess definition about DEBUG  https://github.com/apache/incubator-weex/commit/a557b79ae50151f30eae3fd164b81330296da6ac

but you can still build from source code when using.

**Comment by y-cares** [comment]
@erha19   问一下   以前的 weex src --entry src/index.vue  这个预览整个文件夹的命令 改成什么了？

**Comment by erha19** [comment]
@y-cares `weex preview [directory | file]`, you don't need `--entry` anymore.

**Comment by erha19** [comment]
@y-cares If you use `directory` mode, notice that the `entry.js` could not be rendered, it just an entry file for `web`.

**Comment by y-cares** [comment]
@erha19  但是我对父组件运行这个命令后，通过父组件打开子组件页面，点击子组件上的一个按钮，触发的事件改变了页面上的值，却无法渲染到子组件上，而用这个命令直接打开子组件，触发相同的事件，更改的数据就能渲染到子组件上。
而以前的 weex src --entry src/index.vue  却没有这个问题。

**Comment by codeliu6572** [comment]
@erha19 我的情况是扫描后，只能出现图片和文字，list和cell出不来，请问是怎么回事？

**Comment by yoking-shi** [comment]
![image](https://user-images.githubusercontent.com/39612025/47236865-f54f1a00-d40f-11e8-99a4-dd4cb75ff398.png)
![image](https://user-images.githubusercontent.com/39612025/47236876-fbdd9180-d40f-11e8-9986-af26a337127a.png)
@erha19 也是扫码后，无显示

**Comment by erha19** [comment]
Please use the latest weex playground app and weex official template, this issue should be fixed a long time ago.

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
