### ISSUE TITLE
每跑一次weex命令就询问一次

### ISSUE THREAD

**Issue by woodstream** [apache/incubator-weex-cli#251]
版本v1.2.7，每执行一次命令，如weex --version，就弹出下面的询问，烦不烦啊？

> ? May weex-toolkit anonymously report usage statistics to improve the tool over
> time? No
> ? Which npm registry you perfer to use? taobao

**Comment by erha19** [comment]
@woodstream Please show me more log message with `--verbose` tag.

**Comment by rupertqin** [comment]
我的也是，刚升级就这样



```
weex config --help --verbose
? May weex-toolkit anonymously report usage statistics to improve the tool over time? Yes
? Which npm registry you perfer to use? taobao
13:48:5 : Set telemetry => true
13:48:5 : Set registry => http://registry.npm.taobao.org
13:48:5 : You can config this configuration again by using `weex config [key] [value]`
13:48:5 : Enjoying your coding time!
```

```
weex -v
? May weex-toolkit anonymously report usage statistics to improve the tool over time? No
? Which npm registry you perfer to use? taobao
13:44:5 : Set telemetry => false
13:44:5 : Set registry => http://registry.npm.taobao.org
13:44:5 : You can config this configuration again by using `weex config [key] [value]`
13:44:5 : Enjoying your coding time!

   v1.2.7
 - weexpack : v1.0.10
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
````

**Comment by woodstream** [comment]
@erha19 Whenever I run command, it alway ask the same question.It should ask me only once.

> StreamdeMacBook-Pro:my-app woodstream$ sudo weex --version --verbose
> ? May weex-toolkit anonymously report usage statistics to improve the tool over
> time? No
> ? Which npm registry you perfer to use? taobao
> 17:28:13 : Set telemetry => false
> 17:28:13 : Set registry => http://registry.npm.taobao.org
> 17:28:13 : You can config this configuration again by using `weex config [key] [value]`
> 17:28:13 : Enjoying your coding time!
> 
>    v1.2.7
>  - weexpack : v1.0.7
>  - weex-builder : v0.3.12
>  - weex-previewer : v1.4.4

> StreamdeMacBook-Pro:my-app woodstream$ sudo weex --version --verbose
> ? May weex-toolkit anonymously report usage statistics to improve the tool over
> time? No
> ? Which npm registry you perfer to use? taobao
> 17:28:22 : Set telemetry => false
> 17:28:23 : Set registry => http://registry.npm.taobao.org
> 17:28:23 : You can config this configuration again by using `weex config [key] [value]`
> 17:28:23 : Enjoying your coding time!
> 
>    v1.2.7
>  - weexpack : v1.0.7
>  - weex-builder : v0.3.12
>  - weex-previewer : v1.4.4
>
>StreamdeMacBook-Pro:my-app woodstream$

**Comment by erha19** [comment]
@woodstream @rupertqin  If there has a `config.json` on your local `~/.xtoolkit` path?  Please show the content to me.

**Comment by woodstream** [comment]
@erha19 Yes，the content is this：

> {
>   "registry": "http://registry.npm.taobao.org",
>   "telemetry": false
> }

**Comment by rupertqin** [comment]
@erha19 

just after I'v edited  the global `weex` file, and change nothing, it never prompt the message again. 

```json
{
  2   "registry": "http://registry.npm.taobao.org",
  3   "telemetry": true
  4 }
```

**Comment by woodstream** [comment]
@rupertqin Where is the file?How to edit it?

**Comment by rupertqin** [comment]
@woodstream   in my case, it's in `/Users/rupert/.n/bin/weex`

**Comment by rupertqin** [comment]
@woodstream I wanted to debug it, so edit it and change to original, as I said, I'd changed nothing, it's queer.

**Comment by woodstream** [comment]
@rupertqin 我看了这个项目一个多月的维护情况，只有erha19在更新维护，真难为他了

**Comment by ZhengShouDong** [comment]
直到你选择了Yes.. 它就消失了,我不想也不需要这种匿名数据统计!

**Comment by woodstream** [comment]
会不会看？你看别人的，无论选什么都是重复询问

在2018年01月31日 18:48，0x00 写道：

直到你选择了Yes.. 它就消失了,我不想也不需要这种匿名数据统计!

**Comment by 0x973** [comment]
@woodstream  Too lazy to spray you!
已经提交pull requests来解决这个bug
https://github.com/weexteam/xtoolkit/pull/2

**Comment by erha19** [comment]
@ZhengShouDong @woodstream @rupertqin That's  my fault, I have fixed this issue above `v1.2.8`, see https://github.com/weexteam/xtoolkit/commit/25b30424e41a81f248e0ff4e26a4ad39bf3b0bb3.

**Comment by ZhengShouDong** [comment]
@woodstream 在我电脑运行的时候是选N会每次都提示,选Y就好了!
另外,我会不会看,反正我不会只提个issue就完事儿,有本事你提交代码修Bug去啊!

**Comment by erha19** [comment]
#274

**Comment by woodstream** [comment]
@ZhengShouDong  你连回复都没看完没看懂就发表意见，如果是Y/N这么个简单的问题，不是bug我会反馈？而且你逻辑本来就有问题，无论我想不想它统计，拒绝和同意都不应该再问！给我个手指，什么态度？而且你所谓的fix it根本是乱搞！有本事不删评论不改个人信息？Too lazy to spray you!shit!!!
