### ISSUE TITLE
每次运行weex run或者build命令都会弹出找不到文件‘C:\Program’，win7系统中

### ISSUE THREAD

**Issue by loong-moon** [apache/incubator-weex-cli#253]
![image](https://user-images.githubusercontent.com/24216623/35309822-33729582-00e9-11e8-8894-6486d3ddcd38.png)

**Comment by erha19** [comment]
@loong-moon please run it again with `--verbose` option and show me the log.

**Comment by loong-moon** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/24216623/35310432-52e09fe2-00ec-11e8-9062-410d9e723f60.png)
觉得不一定有帮助

**Comment by erha19** [comment]
@loong-moon  you can see https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87

**Comment by loong-moon** [comment]
@erha19 不知道什么意思，我看了该文档上面并没有我描述的错误，我只是提出一个问题，希望你们能够修改，这个问题对于我来说并不迫切，因为我不运行weex命令在android studio里面直接build or run也能生成apk包

**Comment by erha19** [comment]
@loong-moon your local environment isn't correct, as the log report, you need to set `JAVA_HOME` on your platform to init java command.

**Comment by loong-moon** [comment]
@erha19 这个我知道，我没有安装java环境，这是之后报的错。我提的错误是
![image](https://user-images.githubusercontent.com/24216623/35316447-90b850c4-010c-11e8-8b35-593c4583ac9a.png)
这个警告在运行weex run或者 weex build命令的开始会出现，运行weeex -v就不会出现。这个警告不会影响命令的继续执行，比如我换成weexpack run或weexpack build，这个警告就不会出现了，我安装了java环境后这个警告还是存在

**Comment by loong-moon** [comment]
@erha19 我安装java环境后，除了上面的警告外还报了这个错误，我猜测是jdk的版本问题
![image](https://user-images.githubusercontent.com/24216623/35316836-b7b3fad2-010e-11e8-896e-48e09f3ee4c8.png)

**Comment by loong-moon** [comment]
@erha19 这个警告在我刚刚安装week-toolkit时已经有了，当时我连android环境都没设置

**Comment by erha19** [comment]
@loong-moon My local java version is 1.8.*, you can try to re-config your `java` environment.

**Comment by liushuhui** [comment]
@erha19  playground扫描时会出现network error， debug时出现devtool。有时正常，但是多数时候都会出现这个问题，感觉用这个东西要看运气，请问是怎么回事呢

**Comment by erha19** [comment]
@liushuhui #265
