### ISSUE TITLE
大神这什么情况，babel-core存在啊

### ISSUE THREAD

**Issue by gqdtl** [apache/incubator-weex-cli#255]
![j7h1bdlk 8xel_sgi7gp_0b](https://user-images.githubusercontent.com/14305510/35317772-4a97cb54-0113-11e8-8df0-7a99f2ecc689.png)

**Comment by erha19** [comment]
@gqdtl Maybe you need to re-install the `weex-tookit`, there should have some error while you install the `weex-toolkit`.

**Comment by liangklfangl** [comment]
运行weex preview命令出错，weex toolkit是最新版本
