### ISSUE TITLE
weex debug 工具装不上啊？

### ISSUE THREAD

**Issue by gqdtl** [apache/incubator-weex-cli#256]
![otv 1 2xhbz13o a4 t bf](https://user-images.githubusercontent.com/14305510/35317897-e96aed7e-0113-11e8-9122-dcb40306de16.png)

**Comment by junhaotong** [comment]
@gqdtl 我只执行`npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org`然后再执行`weex debug`就没问题了

**Comment by gqdtl** [comment]
@junhaotong 还是这样，没起作用啊

**Comment by erha19** [comment]
@gqdtl remove cache form `C:\Users\<username>\.xtoolkit\node_modules\weex-debugger` and run the command again.

**Comment by gqdtl** [comment]
@erha19 我weex-debugger不存在啊？
![t1c js d4 9pihpp sox](https://user-images.githubusercontent.com/14305510/35323701-6cac998e-0129-11e8-89c9-641a17fb1648.png)

**Comment by erha19** [comment]
provide your npm and node version

**Comment by gqdtl** [comment]
@erha19 

![7v pxe7n0r8rpjd z852 k](https://user-images.githubusercontent.com/14305510/35324186-f8aeb66e-012a-11e8-9fc4-1a9052448070.png)

**Comment by erha19** [comment]
@gqdtl try `weex config registry https://registry.npm.taobao.org/` and run `weex debug --verbose` again, if there still have some error, please show me the log detail and the `debug.log` file from the npm.

**Comment by y-cares** [comment]
@erha19  启动 weex debug 报：
![image](https://user-images.githubusercontent.com/20083236/35428361-8b7e6e88-02a9-11e8-825e-4e771da0812d.png)
weex版本时：
![image](https://user-images.githubusercontent.com/20083236/35428393-b384ae38-02a9-11e8-9efb-550ba8fb0a31.png)
这是什么原因？  weex-toolkit 版本，已经重新安装过了...

**Comment by erha19** [comment]
@y-cares run `weex debug --verbose` and show me the log.

**Comment by y-cares** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/20083236/35428477-3c06ad4c-02aa-11e8-9f3d-f0e0bc91a3c6.png)
 就这些，然后就停了

**Comment by y-cares** [comment]
@erha19 
创建新项目时，会报这个错，不知道有影响吗？
![image](https://user-images.githubusercontent.com/20083236/35428526-8a14a9ee-02aa-11e8-85c1-b4483ee06a0c.png)
按了回车，依然可以创建成功

**Comment by gqdtl** [comment]
@erha19 
![h6u0ithadrf4vgnli j8sq4](https://user-images.githubusercontent.com/14305510/35428744-bbdd6942-02ab-11e8-8f03-bfe1161db02b.png)

**Comment by JenningFan** [comment]
when installing weex-debbuger, it always stucked at this step that failed to download Chromium, does it has any way to resolve this problem? thanks a lot. 
![image](https://user-images.githubusercontent.com/22371994/35492289-11b1c10a-04e7-11e8-81a6-7f373d040dc6.png)

**Comment by erha19** [comment]
@gqdtl @JenningFan you can solve this by the fellow steps:
1. Check if you have the latest `node` > 6 and `npm` > 5, if not, download it.
2. As a Chinese with not a VPN tool, you should use the `taobao` mirror of `npmjs.org`, run `weex config registry https://registry.npm.taobao.org/`.
4. Because of not have a VPN tool, you'd also need to set `PUPPETEER_DOWNLOAD_HOST` by `npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org`.
5. As result, if you are on windows platform, you need to run `weex debug` in a new shell because the environment variable settings cannot take effect immediately

Hope this should be helpful for you.

**Comment by liuhai07** [comment]
@JenningFan 我和你差不多的问题，你的解决没,能告知一下方法么？
@erha19 我尝试了上面所说的所有方法都没能成功，即使使用sudo也还是不行
<img width="1311" alt="2018-01-29 22 04 43" src="https://user-images.githubusercontent.com/15108471/35514294-b032f070-0540-11e8-9633-d7d42cf09905.png">

**Comment by erha19** [comment]
@liuhai07 I suggest you do not use `sudo` command with  `weex-toolkit` anymore, that will cause many permission problems, you can run `chmod -R 777 ~/.xtoolkit` to fix this issue.

**Comment by liuhai07** [comment]
chmod: Unable to change file mode on /Users/liuhai/.xtoolkit/node_modules/weexpack/node_modules/weexpack-create/node_modules/is-extendable: Operation not permitted
if I do not use sudo command ,I have no permission to use those commands.

**Comment by erha19** [comment]
@liuhai07 I'm sorry, the `chmod` command needs run with `sudo` command,  but other commands should be not always using with it.

**Comment by iizhangchao** [comment]
楼主解决了么，我试了前面提供的这些方法 都不行 @gqdtl

**Comment by erha19** [comment]
@iizhangchao provide your environment and your error log.

**Comment by iizhangchao** [comment]
@erha19  
没想到回复得这么快，感谢大神！
win10  64
![qq 20180201094256](https://user-images.githubusercontent.com/19889539/35657024-47ab7206-0735-11e8-9abf-4074b0908c50.png)
之前报错跟楼主一样，现在报这个错 是权限问题
![qq 20180201095632](https://user-images.githubusercontent.com/19889539/35657201-44d0922c-0736-11e8-8963-5ddcb809c35e.png)

我以管理员身份运行 还是报权限问题 
![qq 20180201102914](https://user-images.githubusercontent.com/19889539/35658134-d51f4306-073a-11e8-9e47-1c380b4c428c.png)

**Comment by erha19** [comment]
@iizhangchao maybe you should to delete the files which permission denied manually, and try it again.

**Comment by iizhangchao** [comment]
@erha19  
![qq 20180201131735](https://user-images.githubusercontent.com/19889539/35662318-752d01b4-0752-11e8-85b7-245aa9d77ccb.png)

重新 run weex debug 现在报这个错 又回到原点了

**Comment by erha19** [comment]
@iizhangchao you should remove the cache file of `weex-debugger`, it may be on the `C:\Users\xxx\.xtoolkit\node_modules\weex-debugger`.

**Comment by iizhangchao** [comment]
@erha19   文件夹里没有 weex-debugger 
![qq 20180201153106](https://user-images.githubusercontent.com/19889539/35666427-017a2888-0765-11e8-92f7-c390893704f9.png)

真不知道是什么原因，我看到很多人都跟我一样遇到这个问题，在https://segmentfault.com/ 上也看到，却一直没有人回答去解决

**Comment by erha19** [comment]
@iizhangchao please provide your npm and node version, maybe you can try to remove `.staging` folder and run `weex debug` again.

**Comment by tong3jie** [comment]
@iizhangchao 
我也遇到这个问题，最后在.xtoolkit目录下执行npm install weex-debugger就没问题了

**Comment by ghost** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/9859902/36712890-ee0ca896-1bc5-11e8-9a34-488372f9a9b2.png)
上面方法都用了根本都没用啊，求大佬帮忙解决，下面是详细log
[2018-02-27T05_52_08_288Z-debug.log](https://github.com/weexteam/weex-toolkit/files/1761404/2018-02-27T05_52_08_288Z-debug.log)

**Comment by erha19** [comment]
@yongganShaonian see https://github.com/weexteam/weex-toolkit/issues/256#issuecomment-361131007

**Comment by crazyyoung1020** [comment]
@erha19 大神，weex debug报错，帮我看下问题
 node和npm版本以及weex -v信息如下
![image](https://user-images.githubusercontent.com/20656885/47775704-61445300-dd2b-11e8-8e9c-72ab1eb58858.png)
我执行了 
weex config registry https://registry.npm.taobao.org/
npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org
但是仍然报错
![image](https://user-images.githubusercontent.com/20656885/47775629-23472f00-dd2b-11e8-9da5-b1c890f43a16.png)
帮忙看下怎么办，已经在网上找个各种方法都不行
