### ISSUE TITLE
can't use any command with weex

### ISSUE THREAD

**Issue by Z-Seven** [apache/incubator-weex-cli#258]
weex-toolkit verison: 1.2.7
os: macOS high Sierra 10.13.2

the terminal log:

![wechatimg210](https://user-images.githubusercontent.com/5781494/35320807-1124d85a-0120-11e8-871b-0e70e61ae1e7.jpeg)

**Comment by erha19** [comment]
@Z-Seven run `sudo chmod -R 777 ~/.xtoolkit`

**Comment by erha19** [comment]
@Z-Seven If you have no other questions, I will close this issue later :)

**Comment by Z-Seven** [comment]
Thanks
