### ISSUE TITLE
when i run command weex build ios,it shows following error

### ISSUE THREAD

**Issue by smart1024** [apache/incubator-weex-cli#260]
## Your development environment
 - npm : 5.6.0
 - node : v9.3.0
 - weex  v1.1.0-beta.9
 - weexpack : v1.0.8
 - weex-builder : v0.3.11
 - weex-devtool : v0.3.3
 - weex-previewer : v1.4.0
 - Mac
## The key error stack message.

![image](https://user-images.githubusercontent.com/3794956/35326986-44b3c920-0133-11e8-9db3-5de1dbe888a5.png)

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
weex build ios

Please tell me how to config the file ios.config.json,thanks

**Comment by erha19** [comment]
@lilin666 it needs `CodeSign` and `Profile` to bundle release package, we suggest that you open `platform/ios` directory using the `Xcode` and package it as a normal ios project.

**Comment by smart1024** [comment]
@erha19 I just want to run release package on real device by Xcode,but before the environment updated , I can run command weex build ios, then open Xcode to run the  app on real device by release mode

**Comment by smart1024** [comment]
@erha19  I realized that the new version supports hot loading，I have recreated the project. it works thank you all the same
