### ISSUE TITLE
Can use pug ?

### ISSUE THREAD

**Issue by lzdyes** [apache/incubator-weex-cli#262]
我安装了 npm install pug 

<template lang="pug" src="./index.pug"></template>

npm run start : web 模式下一切正常使用
但是 npm run build 的就报错了

    ERROR in ./node_modules/._weex-vue-loader@0.5.13@weex-vue-loader/lib/template-compiler.js?id=data-v-1a4d8e3c!./src/index.pug
    (Emitted value instead of an instance of Error) template syntax error Component template requires a root element, rather than just text.
     @ ./src/index.vue?entry=true 12:23-129

还有个问题，为什么一定要先 npm run build 后再 weex build android，这时候 build 的才是最新的？不然永远是老的

**Comment by erha19** [comment]
@lzdyes yes, that's right, the bundle should be always newly.
