### ISSUE TITLE
Can't find variable: InstanceService

### ISSUE THREAD

**Issue by yklszm** [apache/incubator-weex-cli#263]
## my development environment
node v8.9.4
npm 5.6.0
weex v1.2.6
 - weexpack : v1.0.2
 - weex-debugger : v1.0.0
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4

 - platform Win

## The key error stack message.
E/jsengine(12429):  ReportException : Exception: ReferenceError: Can't find variable: InstanceService
E/jsengine(12429): (global function):498:43
E/jsengine(12429): __webpack_require__@(global function):24:34
E/jsengine(12429): (global function):698:38
E/jsengine(12429): __webpack_require__@(global function):24:34
E/jsengine(12429): (global function):67:37
E/jsengine(12429): (global function):68:12
E/jsengine(12429): anonymous@(global function):735:4
E/jsengine(12429): a@(weex framework):3:30112
E/jsengine(12429): (weex framework):8:22648
V/WindowManager(  911): Adding window Window{2de529ca u0 com.weex.app/com.weex.app.WXPageActivity} at 5 of 13 (before Window{102769e6 u0 Starting com.weex.app})
E/weex    (12429): reportJSException >>>> instanceId:3, exception function:createInstance, exception:Exception: ReferenceError: Can't find variable: InstanceService
E/weex    (12429): (global function):498:43
E/weex    (12429): __webpack_require__@(global function):24:34
E/weex    (12429): (global function):698:38
E/weex    (12429): __webpack_require__@(global function):24:34
E/weex    (12429): (global function):67:37
E/weex    (12429): (global function):68:12
E/weex    (12429): anonymous@(global function):735:4
E/weex    (12429): a@(weex framework):3:30112
E/weex    (12429): (weex framework):8:22648

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
code in andriod WXApplication::onCreate()
`  @Override
  public void onCreate() {
    super.onCreate();

    StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
    StrictMode.setVmPolicy(builder.build());
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
      builder.detectFileUriExposure();
    }

    WXSDKEngine.addCustomOptions("appName", "WXSample");
    WXSDKEngine.addCustomOptions("appGroup", "WXApp");
    WXSDKEngine.initialize(this,
        new InitConfig.Builder().setImgAdapter(new ImageAdapter()).build()
    );
    try {
      WXSDKEngine.registerModule("event", WXEventModule.class);
      WXSDKEngine.registerModule("utils", WXUtilsModule.class);

      HashMap<String, String> options = new HashMap<>();
      String jsCode =   WXFileUtils.loadAsset("dist/service/imService.js", WXEnvironment.getApplication());
      Log.e("jsCode",jsCode);
      options.put("version", "1");
      String SERVICE_NAME = "IMService";
      String SERVICE_JS_CODE = "SERVICE_JS_CODE";
      WXSDKEngine.registerService(SERVICE_NAME, SERVICE_JS_CODE, options);
    } catch (WXException e) {
      e.printStackTrace();
    }

    AppConfig.init(this);
    WeexPluginContainer.loadAll(this);
  }`

code in weex
`<script>
var _InstanceService = new InstanceService(weex)
var _NormalService = new service.normalService(weex)

module.exports = {
  created: fucntion() {
    // called modal module to toast something
    _InstanceService.toast('Instance JS Service')
    _NormalService.toast('Normal JS Service')
  }
}
</script>`

**Comment by erha19** [comment]
@yklszm where's the `InstanceService` class come from?

**Comment by erha19** [comment]
@yklszm We need a feature to support debugging with `JSService`, I will create a new issue to discuss this issue.
