### ISSUE TITLE
 weex-toolkit安装失败

### ISSUE THREAD

**Issue by zhangzhiyang1988** [apache/incubator-weex-cli#264]
![1516946157 1](https://user-images.githubusercontent.com/8512396/35426954-9bcea0f8-02a1-11e8-81f4-7c7e0832438d.png)

node 版本是8.9.4
npm 版本是5.6.0
请问为什么安装总报这个错？

**Comment by rwaiting** [comment]
我也出现这个问题


F:\>npm install --no-optional weex-toolkit -g
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\commander-68f5115f\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-ae1c6b73\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-964a31fb\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\commander-68f5115f\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-ae1c6b73\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-964a31fb\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\commander-68f5115f\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-ae1c6b73\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-ae1c6b73\CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-964a31fb\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\commander-68f5115f\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-964a31fb\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\commander-68f5115f\Readme.md'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\chai-ffd8420c\lib\chai\interface'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\chai-a40f0abc\lib\chai\interface'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\acorn-2c62f647\dist\acorn.es.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-a3f74905\lib\util\patterns'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\yoda.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-mixed-requires.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-mixed-spaces-and-tabs.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-multi-assign.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-mixed-operators.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-multi-str.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-multiple-empty-lines.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-native-reassign.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-negated-condition.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-negated-in-lhs.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-magic-numbers.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-nested-ternary.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-loop-func.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-new-func.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-lonely-if.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-new-object.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-lone-blocks.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-new-require.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-labels.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-new-symbol.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-label-var.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-new-wrappers.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-iterator.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-new.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-irregular-whitespace.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-obj-calls.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-invalid-this.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-octal-escape.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-invalid-regexp.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-octal.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-inner-declarations.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-param-reassign.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-inline-comments.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-path-concat.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-implied-eval.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-plusplus.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-implicit-globals.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-process-env.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-implicit-coercion.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-process-exit.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-global-assign.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-proto.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-func-assign.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-prototype-builtins.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-floating-decimal.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-redeclare.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-fallthrough.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-regex-spaces.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-extra-semi.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-restricted-globals.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-457b8c81\lib\rules\no-extra-parens.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\ignore_transform_key\node_modules\a\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\ignore_transform_key\node_modules\a\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\autoconfig.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\config-cache.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\config-file.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\config-initializer.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\config-ops.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\config-rule.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\config-validator.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\environments.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\config\plugins.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\backward-token-comment-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\cursors.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\decorative-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\filter-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\forward-token-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\limit-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\padded-token-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\skip-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\backward-token-cursor.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\utils.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1\lib\token-store\forward-token-comment-cursor.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\global\node_modules\robot'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\error_code\src.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\shared_symlink\shared\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\double_buffer\explicit.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\double_buffer\implicit.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\double_buffer\main.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6\test\stream'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint-plugin-jsx-a11y@4.0.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\eslint-plugin-jsx-a11y):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...a11y","version":"1.0.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: color-convert@1.9.1 (node_modules\weex-toolkit\node_modules\color-convert):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\color-convert-6658f3bc'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babylon@7.0.0-beta.36 (node_modules\weex-toolkit\node_modules\babel-eslint\node_modules\babylon):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-964a31fb'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: commander@2.13.0 (node_modules\weex-toolkit\node_modules\commander):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\commander-68f5115f'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babylon@7.0.0-beta.36 (node_modules\weex-toolkit\node_modules\@babel\traverse\node_modules\babylon):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-35025072'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.0.3 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\babel-eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babel-eslint-542b1de0'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.0.1 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\babel-eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babel-eslint-93e9e6cf'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.0.3 (node_modules\weex-toolkit\node_modules\weex-builder\node_modules\babel-eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babel-eslint-53ae347a'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint-plugin-promise@3.6.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\eslint-plugin-promise):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-plugin-promise-671a62f1'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint-config-airbnb-base@11.3.2 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\eslint-config-airbnb-base):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-config-airbnb-base-58838700'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint-plugin-import@2.7.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\eslint-plugin-import):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-plugin-import-dc559704'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mocha@3.5.3 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\mocha):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\mocha-d6264f11'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mocha@4.0.1 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\mocha):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\mocha-379ab6c8'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mocha@4.0.1 (node_modules\weex-toolkit\node_modules\weex-builder\node_modules\mocha):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\mocha-ec895cc4'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint@4.13.1 (node_modules\weex-toolkit\node_modules\weex-builder\node_modules\eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-5c164677'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint@4.13.1 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-346ae961'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.2.1 (node_modules\weex-toolkit\node_modules\babel-eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babel-eslint-c32fcb49'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-styles@3.2.0 (node_modules\weex-toolkit\node_modules\@babel\code-frame\node_modules\ansi-styles):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\ansi-styles-f8c98ae9'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: arr-flatten@1.1.0 (node_modules\weex-toolkit\node_modules\arr-flatten):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\arr-flatten-e25afef4'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babylon@7.0.0-beta.36 (node_modules\weex-toolkit\node_modules\@babel\template\node_modules\babylon):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\babylon-1b18392e'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chai@4.1.2 (node_modules\weex-toolkit\node_modules\weex-builder\node_modules\chai):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...version":"1.0.4","dep'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chai@4.1.2 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\chai):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...version":"1.0.4","dep'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rimraf@2.6.2 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\rimraf):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\rimraf-ea29be05'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: glob@7.1.2 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\glob):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\glob-6f12bf3a'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint@3.19.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-a3f74905'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: karma@1.7.1 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\karma):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\karma-419cd667'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint@4.9.0 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\eslint-f477c1f1'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browserify@13.3.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\browserify):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\.staging\browserify-48450fe6'

npm ERR! Unexpected end of JSON input while parsing near '...,"hashish":"0.0.4","m'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-01-26T09_33_09_415Z-debug.log

F:\>node -v
v8.9.4

F:\>npm -v
5.6.0

**Comment by hongz1125** [comment]
npm uninstall -g weex-toolkit
npm i -g weex-toolkit

**Comment by zhangzhiyang1988** [comment]
@hongz1125 试了不行啊

**Comment by erha19** [comment]
@zhangzhiyang1988 try `npm i weex-toolkit -g --no-optional`

**Comment by zhangzhiyang1988** [comment]
@erha19 不行啊

**Comment by zhangzhiyang1988** [comment]
@rwaiting 你的好了么？

**Comment by rwaiting** [comment]
@zhangzhiyang1988 没有，我准备把电脑重置下，然后重新安装试试。

**Comment by zhangzhiyang1988** [comment]
@rwaiting 我用mac成功了，但是npm install又报错了。唉~！

**Comment by rwaiting** [comment]
@zhangzhiyang1988 我用没有装过的笔记本安装可以正常用。应该是电脑之前安装别的东西冲突了。

**Comment by cityapartment** [comment]
WINDOWS一样遇到了，之前装过RN，不知道是不是这个问题，有谁现在有解决方案呢？

**Comment by imfenghuang** [comment]
@zhangzhiyang1988 `delete /user/xxx/.xtoolit `  and  `npm uninstall -g weex-toolkit` and `npm i -g weex-toolkit`

**Comment by jackdizhu** [comment]
npm 安装失败的 可以尝试 cnpm 安装 . . .
