### ISSUE TITLE
weex debug可以扫描连上devtool，但扫描具体页面二维码时playground报network error

### ISSUE THREAD

**Issue by jaredlam** [apache/incubator-weex-cli#265]
平台：Windows
版本：
    $ weex -v
       v1.2.7
      - weex-debugger : v1.0.0
      - weex-builder : v0.3.12
      - weex-previewer : v1.4.4

问题复现步骤：
      1. 执行 weex debug xxxx.vue

      2. 扫描页面中二维码，playground app提示debug server connected

      3. 浏览器跳转到debug页面，点击右上角二维码

      4. 扫描二维码，playground app提示network error

问题初步调查：

      1.由于同样weex toolkit版本的OSX系统无上述问题，所以怀疑是平台兼容性导致

      2.将第二个页面二维码转换为url，发现值为：
         http://192.168.2.180:8088\weex\help_center.js?_wx_tpl=http://192.168.2.180:8088\weex\help_center.js&wh_weex=true
        **注意其中正、反斜线问题**

      3.把上述url中反斜线全部替换为正斜线后，生成二维码，再次用playground扫描，可以正常打开页面

**Comment by erha19** [comment]
@jaredlam Your idea should be right, thanks for your feedback, and I'll fix it in the next version of `weex-debugger`.

**Comment by erha19** [comment]
@jaredlam now you can upgrade your `weex-debugger` to the latest version by `weex update weex-debugger@latest`, I had fixed this issue on the version `v1.0.1`, see the changelog at https://github.com/weexteam/weex-debugger/blob/master/CHANGELOG.md.

**Comment by jaredlam** [comment]
@erha19 debug is working nicely on v1.0.1, thanks for your fast response.

**Comment by bitqiang** [comment]
I use the command weex debug
chrome Open the web page
Then my cell phone scanned the two-dimensional code, and there was no reaction

weex -v
   v1.2.8
 - weexpack : v1.0.15
 - weex-debugger : v1.0.2
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4

**Comment by JenningFan** [comment]
@erha19 when i use weex debug , it seems like working right, like this:
![image](https://user-images.githubusercontent.com/22371994/35722753-7efc5d80-0832-11e8-8ee4-cace36a4e07b.png)
but when i turn on the js debug button, the screen truns to white, is it related to that i have not install chromium? 
how could i solve the problem? thanks for helping.
btw，when scaning the QR-code, the weex-playground  app crash frequently...
![image](https://user-images.githubusercontent.com/22371994/35722839-dedd2428-0832-11e8-9388-946c384505d1.png)
![image](https://user-images.githubusercontent.com/22371994/35722966-73ebf22e-0833-11e8-84ec-7ef35dfb2f39.png)

**Comment by jaredlam** [comment]
@JenningFan You need to run  'npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org', then reinstall weex-debugger。

here is more details: 
https://github.com/weexteam/weex-toolkit/blob/1fd94d927278964a263d82d4d2ea1aed1f57ca5c/README-zh.md#failed-to-install-chromium-r515411-224

**Comment by hiXing** [comment]
这个问题怎么解决？
![image](https://user-images.githubusercontent.com/9985104/39466987-49efda24-4d5e-11e8-9214-cfa64eed77bf.png)

![image](https://user-images.githubusercontent.com/9985104/39467034-8b75134c-4d5e-11e8-9a1d-541230308ab2.png)

**Comment by erha19** [comment]
@hiXing looks like there are some issues with url generation on windows, the QRcode url should be `.../assets/view/home.js`, I will fix it on next version, please wait a moment.

**Comment by erha19** [comment]
@hiXing Please run `weex update weex-debugger@latest` to fix this issue,  I have published `1.0.12` version to fix it.

**Comment by lzq4047** [comment]
进入Vue所在的目录可以正常调试

**Comment by fanlvwen** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/36951996/51900827-34b6da80-23f1-11e9-895f-1e124ada5e12.png)

debug v1.2.8
又变成了反斜杠

**Comment by fanlvwen** [comment]
> @erha19
> ![image](https://user-images.githubusercontent.com/36951996/51900827-34b6da80-23f1-11e9-895f-1e124ada5e12.png)
> 
> debug v1.2.8
> 又变成了反斜杠

![image](https://user-images.githubusercontent.com/36951996/51901284-3f25a400-23f2-11e9-9140-3f7a56a70232.png)
![image](https://user-images.githubusercontent.com/36951996/51901310-4e0c5680-23f2-11e9-94a6-b7569b0bed97.png)
