### ISSUE TITLE
mac npm install 失败

### ISSUE THREAD

**Issue by zhangzhiyang1988** [apache/incubator-weex-cli#267]
![351465861777794910](https://user-images.githubusercontent.com/8512396/35547098-1c53f1b6-05b2-11e8-9760-1508dc6e61a1.jpg)
报这个错是为什么？

**Comment by erha19** [comment]
@zhangzhiyang1988 your `npm` registry may be wrong, try `npm set registry https://registry.npm.taobao.org` and run it again.

**Comment by zhangzhiyang1988** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/8512396/35547505-635e5360-05b4-11e8-89b0-ea042db7d898.png)
重新设置了，现在又报这个错。

**Comment by erha19** [comment]
@zhangzhiyang1988 please provide your environment, and check your environment with this [中文文档](https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md), maybe your `npm` version is too low, try to remove `node_module` from your project and reinstall the project after you upgrade your `npm` version.

**Comment by zhangzhiyang1988** [comment]
@erha19 
13679 warn awesome-project@1.0.0 No repository field.
13680 verbose type SyntaxError
13681 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...nes":{"node":">= 0.4.'
13681 verbose stack     at JSON.parse (<anonymous>)
13681 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
13681 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
13681 verbose stack     at process._tickCallback (internal/process/next_tick.js:109:7)
13682 verbose cwd /Users/zzy/awesome-project
13683 verbose Darwin 16.0.0
13684 verbose argv "/usr/local/Cellar/node/7.7.2/bin/node" "/usr/local/bin/npm" "install"
13685 verbose node v7.7.2
13686 verbose npm  v5.6.0
13687 error Unexpected end of JSON input while parsing near '...nes":{"node":">= 0.4.'
13688 verbose exit [ 1, true ]

**Comment by erha19** [comment]
@zhangzhiyang1988 there may be some format error on your `package.json`, please provide your `package.json` or re-create a project using `weex create [projectname]`,  you need to upgrade your `weexpack` to the latest version by `weex update weexpack@latest`.

**Comment by zhangzhiyang1988** [comment]
@erha19 
{
  "name": "awesome-project",
  "version": "1.0.0",
  "description": "A weex project",
  "main": "index.js",
  "scripts": {
    "start": "npm run serve",
    "build": "webpack --env.NODE_ENV=common",
    "build:prod": "webpack --env.NODE_ENV=production",
    "build:plugin": "webpack --env.NODE_ENV=plugin",
    "clean": "rimraf ./web/build",
    "dev": "webpack --env.NODE_ENV=common --progress --watch",
    "unit": "karma start test/unit/karma.conf.js",
    "test": "npm run unit",
    "lint": "eslint --ext .js,.vue src",
    "serve": "webpack-dev-server --env.NODE_ENV=development --progress",
    "ios": "weex run ios",
    "web": "npm run serve",
    "android": "weex run android",
    "pack:ios": "npm run clean && weex build ios",
    "pack:android": "npm run clean && weex build android",
    "pack:web": "npm run clean && npm run build:prod"
  },
  "keywords": [
    "weex"
  ],
  "author": "zzysmn <*zzy@0802>",
  "license": "MIT",
  "dependencies": {
    "vue": "^2.5.11",
    "weex-html5": "^0.4.1",
    "weex-vue-render": "^0.12.26"
  },
  "devDependencies": {
    "babel-core": "^6.21.0",
    "babel-eslint": "^8.0.3",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "^6.9.2",
    "chai": "^4.1.2",
    "css-loader": "^0.28.8",
    "eslint": "^4.13.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "fs-extra": "^5.0.0",
    "html-webpack-plugin": "^2.30.1",
    "ip": "^1.1.5",
    "karma": "^1.7.1",
    "karma-coverage": "^1.1.1",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-phantomjs-shim": "^1.5.0",
    "karma-sinon-chai": "^1.3.3",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.31",
    "karma-webpack": "^2.0.6",
    "node-notifier": "^5.1.2",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.9",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.2",
    "script-ext-html-webpack-plugin": "^1.8.5",
    "sinon": "^4.1.3",
    "sinon-chai": "^2.14.0",
    "vue-loader": "^12.2.0",
    "vue-style-loader": "^3.0.3",
    "vue-template-compiler": "^2.5.11",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7",
    "webpack-merge": "^4.1.0",
    "webpack-uglify-parallel": "^0.1.4",
    "weex-loader": "^0.6.7"
  },
  "optionalDependencies": {
    "ios-deploy": "^1.9.0"
  }
}

**Comment by erha19** [comment]
@zhangzhiyang1988 I test it can be installed on my platform with `node >= 6.0 npm >= 5.0`, 
my local environment is : 
```
$ node -v
v7.10.1
$ npm -v
4.2.0
```
Try to upgrade it your `node` and remove `node_modules` from your project, then try `npm i` again.

**Comment by erha19** [comment]
@zhangzhiyang1988 If you have no other questions, I will close this issue later :)

**Comment by yyhinbeijing** [comment]
sudo chown -R $USER /usr/local
试试这个

**Comment by QSFan** [comment]
bogon:~ qishifan$ node -v
v10.4.1
bogon:~ qishifan$ npm -v
6.1.0
bogon:~ qishifan$ 

bogon:~ qishifan$ npm install -g weex-toolkit
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/package.json'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/README.md'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/LICENSE'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/align.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: engine.io-client@1.8.3 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/engine.io-client):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...nbul":"^1.1.1","gulp-'

npm ERR! Unexpected end of JSON input while parsing near '...st":{"shasum":"6a0cf5'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qishifan/.npm/_logs/2018-06-20T18_27_46_280Z-debug.log
bogon:~ qishifan$
