### ISSUE TITLE
webpack添加loader不起作用

### ISSUE THREAD

**Issue by seanxux** [apache/incubator-weex-cli#269]
- webpack配置无效 (我这里是添加了一个url-loader)
在webpack.common.conf.js里面追加了loader，但是weex debug或者weex compile的时候并没有起作用。
简单调查了下，好像weex命令使用的是weexBuilder.js里面写死的webpack配置，并不会使用自己工程下面的webpack配置。直接修改weexBuilder.js里面的webpack配置追加loader，是有效的。

- **想问一下正确的配置webpack的方式是什么？**

- webpack.common.conf.js里面的module配置如下：
``` module: {
    rules: [
    {
      test: /\.js$/,
      use: [{
        loader: 'babel-loader'
      }]
    },
    {
      test: /\.vue(\?[^?]+)?$/,
      use: [{
        loader: 'weex-loader',
        options: vueLoaderConfig({useVue: false})
      }]
    },
    {
        test: /\.(png|jpg|gif)$/,
        use: [{
            loader: 'url-loader?limit=81920'
        }]
    }]
```

## Your development environment
- weex-toolkit verison
```
 v1.2.7
 - weexpack : v1.0.11
 - weex-debugger : v1.0.0
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
```

- platform
```
Mac (macOS 10.13.2)
```

## The key error stack message.
```./src/st.png
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ /usr/local/lib/node_modules/weex-toolkit/node_modules/_weex-vue-loader@0.5.13@weex-vue-loader/lib/script-loader.js!/usr/local/lib/node_modules/weex-toolkit/node_modules/_babel-loader@7.1.2@babel-loader/lib!/usr/local/lib/node_modules/weex-toolkit/node_modules/_weex-vue-loader@0.5.13@weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 20:12-31
 @ ./src/index.vue?entry=true
```

**Comment by erha19** [comment]
@seanxux The `weex-builder` is a sandboxed environment compiler, it's suitable for a single file without project structure. If you want to config your personal `webpack` config, you can modify the scripts in the `configs` folder, and use the QR-code generate by the`weex` project (use `npm start` to start the static server )but not a compiler.

**Comment by jaredlam** [comment]
@erha19 is there any further plan to support custom webpack config when we use weex compile/debug command?

**Comment by erha19** [comment]
@jaredlam It‘s a good feature, but a short time I have not considered supporting this feature as you can config the loader on your own project, maybe you can push a pull request for this feature :)

**Comment by jaredlam** [comment]
#https://github.com/weexteam/weex-builder/pull/11

**Comment by erha19** [comment]
@jaredlam Thank you for submit，I will check it out later.

**Comment by Vincevii** [comment]
@erha19 
Has this feature been added ? I have to use my custom babel-plugin.If this feature has been added,please let me konw.thx :)

**Comment by erha19** [comment]
@Vincevii @seanxux @jaredlam latest version of `weex-builder` has supported this feature, you can use `weex compile src dist --config webpack.config.js` to compile with your local webpack config now.

**Comment by seraphlee** [comment]
运行weex compile src dist --config webpack.config.js命令后报错：

/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/webpack/lib/webpack.js:19
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property '0'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           0: ...
         }
       })
     ]
    at webpack (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/webpack/lib/webpack.js:19:9)
    at WeexBuilder.build (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/src/webpackBuilder.js:44:22)
    at Object.exports.build (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/index.js:9:51)
    at Command.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/bin/weex-builder.js:21:17)
    at Command.listener (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/commander/index.js:300:8)
    at Command.emit (events.js:127:13)
    at Command.parseArgs (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/commander/index.js:637:12)
    at Command.parse (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-builder/bin/weex-builder.js:51:9)
    at Module._compile (module.js:662:30)

**Comment by mario-huang** [comment]
weex debug 依旧不支持外部config
