### ISSUE TITLE
XcodeVersion 9.2 (9C40b) ： library not found for -lSDWebImage（a new project）

### ISSUE THREAD

**Issue by clotee** [apache/incubator-weex-cli#270]
## Your development environment
- node  v6.11.3
- npm 5.6.0
- weex-toolkit verison   v1.2.7
 - weexpack : v1.0.13
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
- platform (Mac)

## The key error stack message.
I create a new project   and `weexpack add platform ios `  and   `weexpack build ios `. It will show that.
  "  Buiding project...
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration PROD -sdk iphoneos -derivedDataPath build clean build
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

Error: You should config `CodeSign` and `Profile` in the `ios.config.json`

    We suggest that you open the `platform/ios` directory.

    Package your project as a normal ios project!
"
  When click WeexDemo.xcodeproj file to open with Xcode(9.2) sign on fill my Bundle Identifiter and Team ,then click run on Simulators .It shows that:
"

ld: warning: directory not found for option '-L/Users/USERNAME/Library/Developer/Xcode/DerivedData/WeexDemo-fnhzgtwcigqnsvfdwnzacvpkrflk/Build/Products/Debug-iphonesimulator/SDWebImage'
ld: warning: directory not found for option '-L/Users/USERNAME/Library/Developer/Xcode/DerivedData/WeexDemo-fnhzgtwcigqnsvfdwnzacvpkrflk/Build/Products/Debug-iphonesimulator/SocketRocket'
ld: warning: directory not found for option '-L/Users/USERNAME/Library/Developer/Xcode/DerivedData/WeexDemo-fnhzgtwcigqnsvfdwnzacvpkrflk/Build/Products/Debug-iphonesimulator/WeexSDK'
**ld: library not found for -lSDWebImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
"

**Comment by acton393** [comment]
https://stackoverflow.com/questions/23539147/xcode-ld-library-not-found-for-lpods   you can try  these case
