### ISSUE TITLE
Can not use pug

### ISSUE THREAD

**Issue by mdsb100** [apache/incubator-weex-cli#272]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- 1.2.7
- Mac

## The key error stack message.
```
<template lang="pug">
  div.wrapper
    image(:src="logo" class="logo")
</template>
```
ERROR in ./node_modules/weex-vue-loader/lib/template-compiler.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue
    (Emitted value instead of an instance of Error) template syntax error Component template requires a root element, rather than just text.
     @ ./src/index.vue?entry=true 12:23-187

**Comment by erha19** [comment]
@mdsb100 now we do not support `pug`, you can create an issue or pull request on https://github.com/weexteam/weex-loader, it would be solved.

**Comment by mdsb100** [comment]
@erha19 
why does 1.0.7 can use pug?
I update weex-toolkit to 1.2.7 and create a awesome-project today, I found it not support pug.
So can u tell me the difference between 1.0.7 and 1.2.7?

**Comment by mdsb100** [comment]
By the way, May I use jade?

**Comment by erha19** [comment]
@mdsb100 The template compile depends on `weex-vue-loader`,  I saw it doesn't have logic to compile the `pug` lang, see https://github.com/weexteam/weex-vue-loader/blob/master/lib/loader.js#L171, I suggest you use `index.pug` and add `pug-loader` into the `webpack` configuration, it should be work on your project.

**Comment by mdsb100** [comment]
@erha19 
I try it , but not work
Can you give me more detail or a simple example?
Thank you so much!

**Comment by mdsb100** [comment]
Any update?

**Comment by mdsb100** [comment]
weex-vue-loader do not maintain ？

**Comment by erha19** [comment]
@mdsb100 I just found that your example runs well on my platform using the project created by `weex create`.
`weex` version here:
```
   v1.2.8
 - weex-debugger : v1.0.2
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
 - weexpack: v1.0.15
```

**Comment by mdsb100** [comment]
@erha19 How can I upgrade to v1.2.8?
1. install weex-toolkit@1.2.8
2. rm templage
3. create a new project
4. copy package.json from new to old
5. npm install?

The version of weex-toolkit upgrade so busy, How can I migrate to new version?

**Comment by erha19** [comment]
@mdsb100 you can just use the command `npm i weex-toolkit@latest -g` to upgrade your package to the latest version, and maybe you just need to put your source code like `src` from old to new.

**Comment by erha19** [comment]
@mdsb100 The `weexpack` should be upgraded to the latest version using `weex update weexpack@latest` command that you can create a new weex project.

**Comment by mdsb100** [comment]
@erha19 
I try it:
1: I update weex-toolkit to 1.2.8 and update weexpack
2: weex create test
3: copy src
4: npm start, work fine
5: npm run dev work failed
6: npm run build work failed

If weex start, and use qrcode with device. the device got nothing, jus white background!

got 
```
ERROR in ./node_modules/weex-vue-loader/lib/template-compiler.js?id=data-v-2964abc9!./node_modules/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue
    (Emitted value instead of an instance of Error) template syntax error Component template requires a root element, rather than just text.
     @ ./src/index.vue?entry=true 12:23-187
```

so what`s deference between ```npm run start``` and ```npm run dev```?

PS. 
not copy src,  just modify template to pug, got same error.

**Comment by mdsb100** [comment]
Is this a bug? 
Any update?

**Comment by mdsb100** [comment]
This pull request work fine.

**Comment by mdsb100** [comment]
Update ```"weex-loader": "^0.7.2"``` then fix it

**Comment by mdsb100** [comment]
@erha19 
I am so sorry.
```
weex preview src --entry src/test-ytx-vue-loading.vue --port 9091
```

this command do not work well, It seems weex-toolkit need to release new version to use weex-loader@0.7.2

error
```
./node_modules/_weex-vue-loader@0.6.1@weex-vue-loader/lib/template-compiler.js?id=data-v-2964abc9!./node_modules/_weex-vue-loader@0.6.1@weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue
```

this same project run ```npm run dev```and get well after I update weex-loader@0.7.2

**Comment by erha19** [comment]
@mdsb100 wait a moment, I will upgrade all toolkit which dependence on the `weex-loader`.

**Comment by erha19** [comment]
@mdsb100 I have been upgrading `weex-builder` and `weex-previewer` to the latest version and the `pug` module is not a default module set into the package, if you want to use it, you need to install `pug` module into your project. 
You can run `weex update weex-builder` to upgrade your package.
The `weex-debugger` latest release will be later because there was something more need to be changed.

**Comment by mdsb100** [comment]
@erha19  Thank you so much for your work. I will try it later and give you a feedback.

**Comment by mdsb100** [comment]
@erha19 
I already Installed pug and pug-loader in my project(YTXDTNWeexUI).

My steps:
```
weex update weex-builder && weex updateweex-previewer
```
```
weex -v 

   v1.2.8
 - weexpack : v1.0.15
 - weex-debugger : v1.0.3
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.7
```

```
weex preview src --entry src/test-ytx-vue-loading.vue --port 9091

weex JS bundle saved at /Users/caojun/project/rjhy/DynamicTeam/NewBee/weex/YTXDTNWeexUI/.weex_tmp
11:48:29 : Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
```

```
cd /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/
sudo npm install pug pug-loader --save
```
It works well finally. But I got a question, why does```weex update weex-previewer``` not work well? Is version@1.4.7  not a latest version?

**Comment by erha19** [comment]
@mdsb100 please look carefully at my reply above, as I just say, `pug` module isn't a default module setting on the `weex-previewer` package, If you want to use `pug` or other loaders on your project,  you need to install the dependence on where you use the command.

**Comment by mdsb100** [comment]
@erha19 Thank you, I understand!

The easy way is installing global.
```
npm install -g pug pug-loader
```
work well! Thank u for your greate job!
