### ISSUE TITLE
weex debug error: AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"

### ISSUE THREAD

**Issue by mdsb100** [apache/incubator-weex-cli#275]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- v1.2.7
- mac

## The key error stack message.
Launching Dev Tools...
11:21:5 : Starting inspector on port 9222
11:21:5 : Error: AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
    at Console.assert (console.js:191:23)
    at Function.launch (/Users/caojun/.xtoolkit/node_modules/weex-debugger/node_modules/puppeteer/lib/Launcher.js:92:15)
    at <anonymous>
Joined entry hub joined
[terminal]page.entry-de2c75ca-48f2-4bec-8c11-705b5dce45b8 joined
0#[page.entry@de2c75ca-*]-->reply-->[page.entry@de2c75ca]:

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

**Comment by erha19** [comment]
@mdsb100 you must be not installed `weex-debugger` successful, maybe a low-speed network cause this, try to remove the `weex-debugger` by `rm -rf ~/xtoolkit/node_modules/weex-debugger`, before you run `weex debug`, config your  npm `npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org`, maybe you also need to change npm registry to `taobao` mirror use `weex config registry https://registry.npm.taobao.org/` . same issues here #256

**Comment by mdsb100** [comment]
Follow erha10`s solution, I solve it.
Thanks a lot

```
rm -rf ~/.xtoolkit/node_modules/weex-debugger
```

Open VPN or ``npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org```

try again ```weex debug```

**Comment by zjcat** [comment]
我的不仅遇到上面所有问题，mac怎么翻墙也安装不了，即使二维码生成点击二维码弹出调试器不可用，首页扫一扫devtool弹出无法跳转页面

**Comment by TonyZPW** [comment]
同上,全都试过了没用. node :v10.11.0,npm 6.4.1

**Comment by max-level** [comment]
macOS Mojave的问题吗？更新系统后问题挺多

**Comment by caozhiyong** [comment]
我用10.13的系统安装成功了，但是10.14一直失败。

**Comment by jengeo18** [comment]
It maybe puppeteer installed with some problems.
`puppeteer ` with dependence of  Chromium
```
npm uninstall  puppeteer
npm install puppeteer
```
I solve it.

**Comment by caozhiyong** [comment]
> It maybe puppeteer installed with some problems.
> `puppeteer ` with dependence of Chromium
> 
> ```
> npm uninstall  puppeteer
> npm install puppeteer
> ```
> I solve it.

依然提示这个错误。虽然提示控件安装成功了，运行weex debug依然报之前的错误。

**Comment by zdpdsy** [comment]
用的10.14系统，一直不成功。直接安装puppeteer后在运行weex debug还是报 Chromium revision is not downloaded

**Comment by TonyZPW** [comment]
哎,这个问题我其实早就解决了,其实就是路径问题引起的。weex debug --verbose 注意用这个命令查看下你的路径然后看看Chromium安在哪了

**Comment by zdpdsy** [comment]
@TonyZPW 
你这路径是怎么设置的，兄弟。
我这边报错是这样的。
![image](https://user-images.githubusercontent.com/7123339/50125979-05676680-02a6-11e9-8031-069e8753f164.png)
weex-debugger的目录是这样的
/Users/zdp/.xtoolkit/node_modules/weex-debugger

puppeteer目录要在weex-deugger里面的？

**Comment by erha19** [comment]
@zdpdsy try 

```
npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org
rm -rf ~/.xtoolkit/node_modules/weex-debugger
weex debug
```

**Comment by zdpdsy** [comment]
@erha19 这个试过了，不行。

**Comment by zdpdsy** [comment]
解决了，在~/.xtoolkit/node_modules/weex-debugger下执行npm install puppeteer后。在执行weex debug就正常了

**Comment by han-xiaowei** [comment]
> 解决了，在~/.xtoolkit/node_modules/weex-debugger下执行npm install puppeteer后。在执行weex debug就正常了

我用你的方法也解决了
