### ISSUE TITLE
logger.wran is not a function

### ISSUE THREAD

**Issue by baixiaodu** [apache/incubator-weex-cli#277]
![image](https://user-images.githubusercontent.com/22970149/35663669-5f622538-0759-11e8-92ad-63bfb2160c86.png)
![image](https://user-images.githubusercontent.com/22970149/35663682-6fc7e08e-0759-11e8-8e08-5544b00e3cb3.png)

**Comment by erha19** [comment]
@baixiaodu now you can upgrade your `weex-debugger` to latest `v1.0.2` version to fix this issue.
