### ISSUE TITLE
对于vue transition组件的支持问题

### ISSUE THREAD

**Issue by Rem486** [apache/incubator-weex-cli#278]
你好，阅读官方文档发现

![image](https://user-images.githubusercontent.com/22462424/35665092-92f0c71e-075f-11e8-892c-06961882becd.png)

文档中提及移动端不支持transition组件，但是如果我只用于web端的话应该怎么配置呢，因为在开发环境是可以的，dotwe上面也不可以，打包后也是不行。

## Your development environment
weex -v
   v1.1.0-beta.9
 - weexpack : v1.0.10
 - weex-builder : v0.3.11
 - weex-previewer : v1.4.4

- platform Mac

开发环境
![qq20180201-151230-hd](https://user-images.githubusercontent.com/22462424/35665758-683e9f66-0762-11e8-9810-7edbc81bc57c.gif)

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

http://dotwe.org/vue/39858cb52433ee8742bdbb7d133222bf

**Comment by erha19** [comment]
@Rem486  The weex does not support `transition` component but the weex SDK above `v0.17.0` has supported the transition property on stylesheet, you can see document here https://weex.apache.org/wiki/common-styles.html#transition-v0-17-0,
the example you can see here: http://dotwe.org/vue/ff9c8216e399d5e3b05e4902ae5bdda0

**Comment by Rem486** [comment]
Thanks a lot! 非常感谢！完美解决了。
