### ISSUE TITLE
weex debug 指定mapping目录

### ISSUE THREAD

**Issue by and80506** [apache/incubator-weex-cli#28]
$weex debug your/we/path  -e index.we
this command will build every file in your/we/path and deploy them on the bundle server. your directory will mapping to http://localhost:port/weex/ use -e to set the entry of these bundles. and the url of "index.we" will display on device list page as another qrcode

mapping to http://localhost:port/weex/ ,   "/weex"这个目录不能自己指定么?

**Comment by exolution** [comment]
嗯 不能，现在是固定的映射到这个路径下
你有什么特别的需求么

**Comment by MaryWu** [comment]
The issue closed here...any more question on "Debug", pls feel free to submit at devtool site   https://github.com/weexteam/weex-devtool/issues. Thanks!
