### ISSUE TITLE
Three Problem, Build, debug and weex-playground

### ISSUE THREAD

**Issue by TecladistaProd** [apache/incubator-weex-cli#280]
Win: 10 x64
node -v
v9.3.0
weex -v
   v1.2.8
 - weexpack : v1.0.2
 - weex-debugger : v1.0.2
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4

when i try use build android or run android i get this error. Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file C:\Users\Vitor Tecladista\Documents\development\Vue\Weex - Nativescript\appgit\platforms\android\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\26.1.0\res\drawable-xxhdpi-v4\abc_text_select_handle_middle_mtrl_light.png into C:\Users\Vitor Tecladista\Documents\development\Vue\Weex - Nativescript\appgit\platforms\android\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\abc_text_select_handle_middle_mtrl_light.png
:app:mergeDebugResources FAILED

BUILD FAILED

Total time: 2 mins 15.834 secs
0:44:2 : Error: Error: Command failed: call gradlew.bat  assembleDebug
isLibProject: false, isAppProject: true
weex_plugin: []

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: com.android.builder.internal.aapt.AaptException: Failed to crunch file C:\Users\Vitor Tecladista\Documents\development\Vue\Weex - Nativescript\appgit\platforms\android\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\26.1.0\res\drawable-xxhdpi-v4\abc_text_select_handle_middle_mtrl_light.png into C:\Users\Vitor Tecladista\Documents\development\Vue\Weex - Nativescript\appgit\platforms\android\app\build\intermediates\res\merged\debug\drawable-xxhdpi-v4\abc_text_select_handle_middle_mtrl_light.png

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

when i try use debug i recive this error. AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"

and when i try start to use playground on my cellphone, i get the network error.

**Comment by erha19** [comment]
@TecladistaProd see #275

**Comment by TecladistaProd** [comment]
Hi Dear @erha19 how i use debug,
 weex debug
   
   │   Start debugger server!                                                      │
   │                                                                               │
   │   - Websocket Address For Native:  ws://192.168.56.1:8088/debugProxy/native   │
   │   - Debug Server:                  http://192.168.56.1:8088                   │
   │                                                           

12:52:6 : Launching Dev Tools...
12:52:6 : Starting inspector on port 9222

i put in browser this address http://192.168.56.1:8088 , when i use playground just appear toast "devtools" or an network render error, and about the other problems how i resolve ^?

**Comment by erha19** [comment]
@TecladistaProd you need to put your PC and phone on the same LAN with no other proxy connections.

**Comment by TecladistaProd** [comment]
@erha19 exactly, i try this but don't work, appear 'network erro', i tried in two different wifi, but had the same problem.

**Comment by jeryqwq** [comment]
how do you reslove this problems ,i have the same bug, and  already deleted weex-debuger and npm,weex changed the taobao also ,
it is my error message when i run: weex run android:
 Error: Error: Command failed: call gradlew.bat  assembleDebug
isLibProject: false, isAppProject: true
weex_plugin: []
