### ISSUE TITLE
使用 weex platform add android，无法实现navigator的页面跳转

### ISSUE THREAD

**Issue by heiren0926** [apache/incubator-weex-cli#281]
报ActivityNotFoundException错误，
添加拦截器后
<intent-filter>
    <action android:name="com.taobao.android.intent.action.WEEX"/>

    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="com.taobao.android.intent.category.WEEX"/>
    <action android:name="android.intent.action.VIEW"/>

    <data android:scheme="http"/>
    <data android:scheme="https"/>
    <data android:scheme="file"/>
    <data android:scheme="wxpage" />
  </intent-filter>
又总是打开重复的当前页面
使用的是navigator.push，使用的是本地js地址，file://assets/index2.js

**Comment by erha19** [comment]
see #273
