### ISSUE TITLE
list  cell 组件结合使用，在本地开发，使用playgroundapp预览，android，ios两套设备效果不一致？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#282]
1.源码：
`<template>
  <div>
  <div class="asss">
    <text>234</text>
  </div>
   
  <list class="list" @loadmore="fetch" loadmoreoffset="10">
    <cell class="cell" v-for="num in lists">
      <div class="panel">
        <text class="text">{{num}}</text>
      </div>
    </cell>
  </list>
  <div class="asss"><text>234</text></div>
</div>
</template>

<script>
  const modal = weex.requireModule('modal')
  const LOADMORE_COUNT = 4

  export default {
    data () {
      return {
        lists: [1, 2, 3, 4, 5]
      }
    },
    methods: {
      fetch (event) {
        modal.toast({ message: 'loadmore', duration: 1 })

        setTimeout(() => {
          const length = this.lists.length
          for (let i = length; i < length + LOADMORE_COUNT; ++i) {
            this.lists.push(i + 1)
          }
        }, 800)
      }
    }
  }
</script>

<style scoped>
  .asss{
    height: 200px;
    background-color: #eeeeee;
  }
  .panel {
    width: 600px;
    height: 250px;
    margin-left: 75px;
    margin-top: 35px;
    margin-bottom: 35px;
    flex-direction: column;
    justify-content: center;
    border-width: 2px;
    border-style: solid;
    border-color: rgb(162, 217, 192);
    background-color: rgba(162, 217, 192, 0.2);
  }
  .text {
    font-size: 50px;
    text-align: center;
    color: #41B883;
  }
</style>`

2.android环境效果：
![image](https://user-images.githubusercontent.com/31499235/35725721-525870b0-083d-11e8-8927-4ea11fcec66c.png)

3.ios效果：
![image](https://user-images.githubusercontent.com/31499235/35725749-6a71856a-083d-11e8-8e7a-740b18feebdb.png)

4.在线playground正常。
![image](https://user-images.githubusercontent.com/31499235/35725811-9fbbdd56-083d-11e8-891e-c0ebf22266c4.png)

问题描述：在本地预览扫码，显示样式不一样。同样的代码，复制到在线playground，然后扫码，没问题？
@erha19

**Comment by erha19** [comment]
@AugTang Please provide a`dotwe` link.
