### ISSUE TITLE
weex 引入weex-chart在native端展示图表问题

### ISSUE THREAD

**Issue by cykl4451** [apache/incubator-weex-cli#283]
npm后添加的依赖node_modules找到weex-chart还是we文件，运行的时候报错，而且报的错就是we文件是的写法，weex-chart需要怎么升级？目前项目weex文件是从we升到vue版本；有什么插件可以实现weex在手机端展示动态图表
![image](https://user-images.githubusercontent.com/30775058/35846758-d938f948-0b52-11e8-9406-1a9108aca6b3.png)

**Comment by erha19** [comment]
#241
