### ISSUE TITLE
v1.2.9  weex platform add 等命令报异常

### ISSUE THREAD

**Issue by zilonger** [apache/incubator-weex-cli#284]
![image](https://user-images.githubusercontent.com/18158326/35895654-58391cfa-0bf3-11e8-85d7-ae47d31bed66.png)
如图上所示，当weex platform add ios/android 添加平台时，会执行失败，实在没找到解决办法，才过来这里

**Comment by devjiangzhou** [comment]
same problem @erha19

**Comment by zilonger** [comment]
`cat ~/.xtoolkit/config.json`
{
  "telemetry": "true",
  "registry": "http://registry.npmjs.org"
}

将 config.json 文件telemetry 改为 false后 命令可以正常执行了

**Comment by erha19** [comment]
@zilonger @devjiangzhou That's a muti-options bug on `commander`, I will fix it on next version of `weexpack`, maybe `v1.0.16`, for now, you can use `weex config telemetry false` command to set `telemetry` flag to be `false.`

**Comment by erha19** [comment]
@zilonger @devjiangzhou This issue has been fixed on `1.0.17` version of `weexpack`, see https://github.com/weexteam/weex-pack/commit/3571bf810b1e95f350bd242d1873dd6404a47a12.
You can run `weex update weexpack` upgrade your `weexpack` to the latest version.
If there have any other questions, you can comment here.
