### ISSUE TITLE
How does the latest version integrate vue-router?

### ISSUE THREAD

**Issue by zhangzhenfei** [apache/incubator-weex-cli#285]
I used the version 1.2.9, which was created using veex create, and I found that in webpack.common.conf. js

````js
 contents += `\nconst App = require('${relativeVuePath}');\n`;
 contents += `App.el = '#root';\n`;
 contents += `new Vue(App);\n`;
````

 how do I introduce vue-router and vuex?

## Your development environment
- weex-toolkit verison (Run `weex -v`) 1.2.9
- platform (Win/Mac/Ubuntu..) Mac

**Comment by dtdths** [comment]
I have the same question,Have you already solved it？

**Comment by zhangzhenfei** [comment]
@dtdths  Not yet, I feel that this cli document is too few, many directory structures and plug-ins  don't know how to expand

**Comment by zhangzhenfei** [comment]
@erha19 Can you give us a solution?

**Comment by erha19** [comment]
@zhangzhenfei The next `weex` project template will support you to create a `vue-router` template for `weex`.
For now, if you want to use `vue-router`, you need to change the webpack config by yourself, you can see this document [use-vuex-and-vue-router](http://weex.apache.org/guide/advanced/use-vuex-and-vue-router.html).

> NOTE: Weex is using native navigator to manage instance pages, the context of them are isolated. That means, Both Vuex and vue-router can only effect the single page, they can’t share state between different pages.
