### ISSUE TITLE
收集通过 Weex playground app 扫码查看页面信息是空白

### ISSUE THREAD

**Issue by fantasysea** [apache/incubator-weex-cli#286]
我今天刚刚开始搭建环境运行demo
经过一番努力百度和google,终于通过代理的形式装上了weex.然后npm start 成功在页面运行demo
http://192.168.3.204:8081/web/preview.html
在网页上能看到:
The environment is ready!

Now, let's use Vue.js to build your Weex app

这个界面
**但是通过收集扫码只能看到一片空白.不知道什么情况.**

## 运行环境
-win7
-手机: ios 11.2.5
- weex-toolkit verison 
   v1.2.7
 - weexpack : v1.0.18
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4

**Comment by erha19** [comment]
@fantasysea You should make sure your phone and PC are both on the same LAN without other proxy connections.

**Comment by fantasysea** [comment]
@erha19 首先,谢谢你的回答,我关闭了代理依然不成功,我不知道是什么原因.我本地打开了一个 tomcat测试,用手机能打开我PC的tomcat主页,我可以确认他们是在一个域下.没有报错,这样我觉得很尴尬.对于一个刚刚希望入门的新手这样太尴尬了.

**Comment by erha19** [comment]
@fantasysea please show me the link of qr_code, you can click it to open the qr_code in a new tab, then copy the URI and contents to me.
