### ISSUE TITLE
weex-toolkit WIN7下安装失败

### ISSUE THREAD

**Issue by cityapartment** [apache/incubator-weex-cli#287]
windows 7 环境：
node -v
v8.9.3
npm -v
5.5.1
步骤：
执行: npm install -g weex-toolkit@latest
报错类似于#246：
ERR! Unexpected end of JSON input while parsing near '...":1340811789363},"1.2'

尝试：
npm i weex-toolkit -g --no-optional
一样报错。

npm ERR! Unexpected end of JSON input while parsing near '...time":1353836305720},'

偶尔是'...p", 偶尔是'...time", 偶尔是'..."

请问是什么问题，能帮忙解决么，谢谢。

**Comment by erha19** [comment]
@cityapartment please show me your full log.

**Comment by cityapartment** [comment]
@erha19  the full log:

npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\uuid\v
4.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\uuid\.
travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\uuid\L
ICENSE.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babylon@7.0.0-beta.36 (node_modules\weex-toolkit\node_modules\@babel\template\node_modules\babylon):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...ines":{"node":">=4.2.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babylon@7.0.0-beta.36 (node_modules\weex-toolkit\node_modules\@babel\traverse\node_modules\babylon):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...ines":{"node":">=4.2.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babylon@7.0.0-beta.36 (node_modules\weex-toolkit\node_modules\babel-eslint\node_modules\babylon):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...ines":{"node":">=4.2.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babylon@6.18.0 (node_modules\weex-toolkit\node_modules\babylon):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...ines":{"node":">=4.2.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-plugin-syntax-async-generators@6.13.0 (node_modules\weex-toolkit\node_modules\babel-plugin-synta
x-async-generators):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...abel-plugin-syntax-as'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: punycode@1.4.1 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\fsevents\node_modules\pun
ycode):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...":1340811789363},"1.2'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.0.3 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\no
de_modules\babel-eslint):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...,"lodash.assign":"^3.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: eslint-plugin-promise@3.6.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\eslint
-plugin-promise):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...a040a0c1ec9e182c66bc6'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@7.2.3 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\babel-eslint):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...,"lodash.assign":"^3.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.0.3 (node_modules\weex-toolkit\node_modules\weex-builder\node_modules\babel-eslint):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...,"lodash.assign":"^3.'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.5.0 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\semver-9be77d33'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request@2.83.0 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\request-41603ac4'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: hawk@6.0.2 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request\node_modules\hawk):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\hawk-27616dad'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sntp@2.1.0 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request\node_modules\sntp):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\sntp-e529630c'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: qs@6.5.1 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request\node_modules\qs):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\qs-c2c7f8a8'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.1 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request\node_modules\s
afe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\safe-buffer-1d75eadf'

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: boom@5.2.0 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request\node_modules\cryptile
s\node_modules\boom):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\boom-63e3692c'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: hoek@4.2.0 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request\node_modules\hoek):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\hoek-7254440f'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browserify@13.3.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\browserify):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\browserify-0daf6938'

npm ERR! Unexpected end of JSON input while parsing near '...":1340811789363},"1.2'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\userName\AppData\Roaming\npm-cache\_logs\2018-02-11T01_01_31_369Z-debug.log

**Comment by cityapartment** [comment]
再次尝试，先执行npm cache --force clean， 再执行npm i weex-toolkit -g --no-optional，报错LOG：

C:\Users\userName>npm i weex-toolkit -g --no-optional
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\hoek\
test'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\test.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\.travis.yml'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\Makefile'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\isarra
y\component.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\jsonif
y\test\parse.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\jsonif
y\test\stringify.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\jsprim
\node_modules\assert-plus\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\jsprim
\node_modules\assert-plus\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\jsprim
\node_modules\assert-plus\assert.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\jsprim
\node_modules\assert-plus\AUTHORS'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5\node_modules\jsprim
\node_modules\assert-plus\CHANGES.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\fsevents\node_module
s\object-assign):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '..."noattachment":false,'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimatch@3.0.4 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\fsevents\node_modules\mi
nimatch):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...de":"*"},"_hasShrinkw'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chai@4.1.2 (node_modules\weex-toolkit\node_modules\weex-builder\node_modules\chai):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...c436fcc78f9ddf8e795f6'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chai@4.1.2 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modul
es\chai):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...ncher":"^1.0.0","karm'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wordwrap@https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz (node_modules\weex-toolkit\node_modu
les\xtoolkit\node_modules\wordwrap):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\wordwrap-0393947b'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: which@https://registry.npmjs.org/which/-/which-1.3.0.tgz (node_modules\weex-toolkit\node_modules\xtool
kit\node_modules\which):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\which-8ba32a2b'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optionator@https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz (node_modules\weex-toolkit\nod
e_modules\xtoolkit\node_modules\optionator):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\optionator-23c381ab'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jsprim@https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz (node_modules\weex-toolkit\node_modules\xt
oolkit\node_modules\jsprim):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\jsprim-d6e3d97d'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chokidar@https://registry.npmjs.org/chokidar/-/chokidar-1.7.0.tgz (node_modules\weex-toolkit\node_modu
les\xtoolkit\node_modules\chokidar):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\chokidar-0990521a'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: del@https://registry.npmjs.org/del/-/del-2.2.2.tgz (node_modules\weex-toolkit\node_modules\xtoolkit\no
de_modules\del):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\del-0d96c98d'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request@https://registry.npmjs.org/request/-/request-2.16.6.tgz (node_modules\weex-toolkit\node_module
s\xtoolkit\node_modules\winston\node_modules\request):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\request-0c00ad05'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: buffercursor@https://registry.npmjs.org/buffercursor/-/buffercursor-0.0.12.tgz (node_modules\weex-tool
kit\node_modules\xtoolkit\node_modules\buffercursor):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\buffercursor-946f3837
'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: normalize-package-data@https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.4.
0.tgz (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\normalize-package-data):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\normalize-package-dat
a-32f24a15'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: readdirp@https://registry.npmjs.org/readdirp/-/readdirp-2.1.0.tgz (node_modules\weex-toolkit\node_modu
les\xtoolkit\node_modules\readdirp):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\readdirp-bfeab3a3'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: verror@https://registry.npmjs.org/verror/-/verror-1.10.0.tgz (node_modules\weex-toolkit\node_modules\x
toolkit\node_modules\verror):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\verror-973d264c'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: native-dns-cache@https://registry.npmjs.org/native-dns-cache/-/native-dns-cache-0.0.2.tgz (node_module
s\weex-toolkit\node_modules\xtoolkit\node_modules\native-dns-cache):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\native-dns-cache-5337
8a28'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: native-dns-packet@https://registry.npmjs.org/native-dns-packet/-/native-dns-packet-0.1.1.tgz (node_mod
ules\weex-toolkit\node_modules\xtoolkit\node_modules\native-dns-packet):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\native-dns-packet-42c
3e6b5'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: v8flags@https://registry.npmjs.org/v8flags/-/v8flags-2.1.1.tgz (node_modules\weex-toolkit\node_modules
\xtoolkit\node_modules\v8flags):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\v8flags-a37da56b'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.0.3 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\no
de_modules\babel-eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\babel-eslint-95a26ec1
'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-eslint@8.2.1 (node_modules\weex-toolkit\node_modules\babel-eslint):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\babel-eslint-14118cd8
'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: normalize-package-data@2.4.0 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\yargs\node_
modules\normalize-package-data):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '..._time":1365510110597}'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz (node_modules\weex-toolkit\node_modu
les\xtoolkit\node_modules\fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\fsevents-2144dbc5'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: babel-cli@6.26.0 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\babel-cli):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\babel-cli-d6f3abd7'

npm ERR! Unexpected end of JSON input while parsing near '...inkwrap":false,"publi'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\bo
ld.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\tr
im-right.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\bl
ink.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\tr
im-start.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\bi
g.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\tr
im.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\at
.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\un
escape-html.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\userName\AppData\Roaming\npm\node_modules\.staging\core-js-6be45696\fn\string\virtual\li
nk.js'

**Comment by cityapartment** [comment]
@erha19   我的配置文件
C:\Users\userName>npm config get
; cli configs
metrics-registry = "https://registry.npm.taobao.org/"
scope = ""
user-agent = "npm/5.5.1 node/v8.9.3 win32 x64"

; globalconfig C:\Users\userName\AppData\Roaming\npm\etc\npmrc
disturl = "https://npm.taobao.org/dist"
registry = "https://registry.npm.taobao.org/"

; builtin config undefined
prefix = "C:\\Users\\userName\\AppData\\Roaming\\npm"

; node bin location = C:\nodejs\node.exe
; cwd = C:\Users\userName
; HOME = C:\Users\userName
; "npm config ls -l" to show all defaults.

**Comment by erha19** [comment]
@cityapartment try to remove `weex-toolkit` installed files on your global `node_modules`  and try `npm i weex-toolkit -g --no-optional`, looks like the `--no-optional` tag doesn't work.

**Comment by cityapartment** [comment]
@erha19 我不知道是不是安装了yarn的问题，但是我现在使用yarn，会有版本不兼容问题，不知道yarn能成功么?

C:\Users\userName>yarn add weex-toolkit -g --no-optional
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning weex-toolkit > weex-builder > babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read b
abeljs.io/env to update!
warning weex-toolkit > xtoolkit > dns > winston > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by erha19** [comment]
@cityapartment try `yarn add weex-toolkit -g --no-optional --ignore-engines`.

**Comment by cityapartment** [comment]
@erha19 安装是没报错了，但是下载完找了半天没看到在哪里，WIN是否要配置环境变量或者什么之类的
├─ yargs-parser@4.2.1
└─ yargs@6.6.0
warning No license field
Done in 908.95s.

C:\Users\userName>weex help
'weex' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by erha19** [comment]
@cityapartment you need run  `yarn global add weex-toolkit --no-optional --ignore-engines`.

**Comment by cityapartment** [comment]
@erha19  
1. 运行yarn weex可以，但是直接运行weex不行， 我现在尝试yarn weex create awesome-project
C:\Users\uerName>weex
'weex' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

2. 换其它目录有问题报错，是不是要切换到目录再重新安装一遍 yarn global add weex-toolkit --no-optional --ignore-engines？
E:\WeexProject>yarn weex create awesome-project
yarn run v1.3.2
error Couldn't find a package.json file in "E:\\WeexProject"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by erha19** [comment]
@cityapartment maybe you should find the `npm` to install the package.
