### ISSUE TITLE
weex-toolkit install fail on osx

### ISSUE THREAD

**Issue by elevenkey** [apache/incubator-weex-cli#288]
node -v: v8.9.1
npm -v: 5.6.0
osx: 10.13.3
command: 
npm i -g weex-toolkit
or 
npm cache clear --force & npm i -g weex-toolkit 
error msg:
![2018-02-09 10 14 49](https://user-images.githubusercontent.com/5429062/36008397-2495d092-0d82-11e8-9296-4d87d9ecfd01.png)

the same environment run : npm i -g weex-toolkit@1.2.8 succeed。

**Comment by erha19** [comment]
@elevenkey Try to remove the cache file on your global `node_modules` and try to install again.

**Comment by elevenkey** [comment]
@erha19 I use nvm manage node version.  So i clear '~/.nvm/versions/node/v9.2.0/lib/node_modules/' folder except 'npm' folder . 
run: nvm use 9.2.0 & npm cache clear --force &  npm i -g weex-toolkit
fail again...
![2018-02-11 3 14 13](https://user-images.githubusercontent.com/5429062/36070817-437c97ee-0f3e-11e8-9f74-c00d8d8f8d44.png)

**Comment by bonustrack** [comment]
I have the same issue, i cleared the cache it doesn't change anything.

**Comment by dariarse** [comment]
Hi! I'm having the same issue. Did you managed to install it somehow?
Thank you!

**Comment by erha19** [comment]
@elevenkey @bonustrack @dariarse try to use `npm@4` to install the package, maybe it's the bug on `npm@5`.

**Comment by dariarse** [comment]
Thanks I tried to, but no success yet.

**Comment by erha19** [comment]
@dariarse try to remove cache files on your global `node_modules`, then try it again.

**Comment by dariarse** [comment]
Yeah, thanks just tried and then install with `npm@4`, but another error is beign thrown instead:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

```

I've read that this might be a node issue, but I'm not sure how to fix it yet.
