### ISSUE TITLE
升级到最新版0.6.2之后，运行调试命令报错

### ISSUE THREAD

**Issue by jingxin2015** [apache/incubator-weex-cli#29]
weex --version 显示版本为 0.6.2

运行命令：weex debug -h 192.168.2.108 src/view/index.we 报错，如下图：

![qq 20161103052218](https://cloud.githubusercontent.com/assets/16143766/19948143/1d1a72aa-a186-11e6-9339-c020a19c6340.jpg)

**Comment by exolution** [comment]
可能是node版本过低 请升级下尝试 建议6.0+

**Comment by MaryWu** [comment]
this issue closed. if you had further problem, pls feel free to open new one. thanks
