### ISSUE TITLE
There is no qrcode when run weex debug

### ISSUE THREAD

**Issue by ruoshui1314** [apache/incubator-weex-cli#291]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
awesome-app$ weex -v
   v1.2.9
 - weexpack : v1.0.18
 - weex-debugger : v1.0.5
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6
``
ubuntu

## The key error stack message.
![image](https://user-images.githubusercontent.com/18414978/36130688-ff0ad58c-10a8-11e8-90a8-d41098b1bf53.png)

``
## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
There is no information either run weex debug or weex debug xxx.vue or xxx.js

someone would like to help or get the same problem ?

**Comment by erha19** [comment]
@ruoshui1314 Try to run `weex update weex-debugger` upgrade your `weex-debugger` to `v1.0.6`, these issues have been fixed now. The case of resources caused by the problem, also you can rename the file `~/.xtoolkit/node_modules/weex-debugger/frontend/lib/App.js` to `app.js` and run it again.

**Comment by ruoshui1314** [comment]
3q
