### ISSUE TITLE
使用 weex platform add android添加android模板报错？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#295]
![image](https://user-images.githubusercontent.com/31499235/36650130-a54f877a-1adc-11e8-9695-4b2cb33773e1.png)
@erha19

**Comment by erha19** [comment]
@AugTang you need to upgrade your `weexpack` by `weex update weexpack`.

**Comment by AugTang** [comment]
@erha19 谢谢，已解决
