### ISSUE TITLE
weex-toolkit安装失败node8.9.1  npm5.5.1

### ISSUE THREAD

**Issue by codeliu6572** [apache/incubator-weex-cli#296]
bogon:WeexTest Codeliu$ sudo cnpm i weex-toolkit -g --no-optional
Downloading weex-toolkit to /usr/local/lib/node_modules/weex-toolkit_tmp
Copying /usr/local/lib/node_modules/weex-toolkit_tmp/_weex-toolkit@1.2.9@weex-toolkit to /usr/local/lib/node_modules/weex-toolkit
Installing weex-toolkit's dependencies to /usr/local/lib/node_modules/weex-toolkit/node_modules
[1/5] chalk@^1.1.3 installed at node_modules/_chalk@1.1.3@chalk

WARN node unsupported "node@v8.9.1" is incompatible with xtoolkit@0.2.23 › dns@^0.2.2, expected node@>= 0.10.0 < 0.11.0

WARN node unsupported "node@v8.9.1" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6, expected node@>= 0.8.0 < 0.11.0
[2/5] check-node-version@^2.1.0 installed at node_modules/_check-node-version@2.1.0@check-node-version
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-parser@2.2.0 › emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz] install emitter from remote http://github.com/component/emitter/archive/1.0.1.tar.gz, may be very slow, please keep patience
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 100ms, retry left 4, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":22,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":799,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":8},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":1,"registry.npm.taobao.org:443:::::::false::":2},"requests":{"cdn.npm.taobao.org:443:::::::false::":84}})
headers: {}
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-adapter@0.2.0 › socket.io-parser@2.1.2 › emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz] install emitter from remote http://github.com/component/emitter/archive/1.0.1.tar.gz, may be very slow, please keep patience

WARN node unsupported "node@v8.9.1" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@~0.10.2, expected node@0.8.x
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 200ms, retry left 3, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":24,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":891,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":5},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":2,"registry.npm.taobao.org:443:::::::false::":5},"requests":{"cdn.npm.taobao.org:443:::::::false::":52}})
headers: {}
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-client@1.0.6 › engine.io-client@1.3.1 › xmlhttprequest@https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz] install xmlhttprequest from remote https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz, may be very slow, please keep patience

WARN node unsupported "node@v8.9.1" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › cryptiles@0.1.x, expected node@0.8.x

WARN node unsupported "node@v8.9.1" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › sntp@0.1.x, expected node@0.8.x

WARN node unsupported "node@v8.9.1" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › boom@0.3.x, expected node@0.8.x
[npminstall:get] retry GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz after 100ms, retry left 4, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":26,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":981,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":10},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":3},"requests":{"cdn.npm.taobao.org:443:::::::false::":52}})
headers: {}
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 100ms, retry left 4, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":26,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":984,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":10},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":2},"requests":{"cdn.npm.taobao.org:443:::::::false::":50}})
headers: {}

WARN node unsupported "node@v8.9.1" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › hoek@0.7.x, expected node@0.8.x
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-client@1.0.6 › engine.io-client@1.3.1 › has-cors@1.0.3 › global@https://github.com/component/global/archive/v2.0.1.tar.gz] install global from remote https://github.com/component/global/archive/v2.0.1.tar.gz, may be very slow, please keep patience
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 300ms, retry left 2, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":30,"createSocketErrorCount":0,"closeSocketCount":5,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1058,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":8},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":4,"registry.npm.taobao.org:443:::::::false::":2},"requests":{"cdn.npm.taobao.org:443:::::::false::":30}})
headers: {}
[npminstall:get] retry GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz after 200ms, retry left 3, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":30,"createSocketErrorCount":0,"closeSocketCount":6,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1070,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":7},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":3,"registry.npm.taobao.org:443:::::::false::":3},"requests":{"cdn.npm.taobao.org:443:::::::false::":26}})
headers: {}
[npminstall:get] retry GET https://github.com/component/global/archive/v2.0.1.tar.gz after 100ms, retry left 4, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/global/archive/v2.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":31,"createSocketErrorCount":0,"closeSocketCount":7,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1099,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":9},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":3,"registry.npm.taobao.org:443:::::::false::":1},"requests":{"cdn.npm.taobao.org:443:::::::false::":35}})
headers: {}
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 200ms, retry left 3, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":33,"createSocketErrorCount":0,"closeSocketCount":8,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1145,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":8},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":4,"registry.npm.taobao.org:443:::::::false::":2},"requests":{"cdn.npm.taobao.org:443:::::::false::":39}})
headers: {}
[npminstall:get] retry GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz after 300ms, retry left 2, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":33,"createSocketErrorCount":0,"closeSocketCount":9,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1191,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":9},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":3,"registry.npm.taobao.org:443:::::::false::":1},"requests":{"cdn.npm.taobao.org:443:::::::false::":38}})
headers: {}
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 400ms, retry left 1, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":33,"createSocketErrorCount":0,"closeSocketCount":10,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1198,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":7},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":2,"registry.npm.taobao.org:443:::::::false::":3},"requests":{"cdn.npm.taobao.org:443:::::::false::":32}})
headers: {}
[npminstall:get] retry GET https://github.com/component/global/archive/v2.0.1.tar.gz after 200ms, retry left 3, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/global/archive/v2.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":33,"createSocketErrorCount":0,"closeSocketCount":11,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1208,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":5},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":1,"registry.npm.taobao.org:443:::::::false::":5},"requests":{"cdn.npm.taobao.org:443:::::::false::":30}})
headers: {}
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 300ms, retry left 2, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":36,"createSocketErrorCount":0,"closeSocketCount":12,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1278,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":10},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":3},"requests":{"cdn.npm.taobao.org:443:::::::false::":44}})
headers: {}
[npminstall:get] retry GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz after 400ms, retry left 1, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":37,"createSocketErrorCount":0,"closeSocketCount":13,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1281,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":10},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":3},"requests":{"cdn.npm.taobao.org:443:::::::false::":51}})
headers: {}
[npminstall:get] retry GET https://github.com/component/global/archive/v2.0.1.tar.gz after 300ms, retry left 2, error: ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/global/archive/v2.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":37,"createSocketErrorCount":0,"closeSocketCount":14,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1290,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":10},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":2},"requests":{"cdn.npm.taobao.org:443:::::::false::":52}})
headers: {}
Install fail! ResponseError: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:
 (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":40,"createSocketErrorCount":0,"closeSocketCount":16,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1334,"freeSockets":{"registry.npm.taobao.org:443:::::::::":1,"registry.npm.taobao.org:443:::::::false::":9},"sockets":{"cdn.npm.taobao.org:443:::::::false::":10,"github.com:443:::::::false::":3,"registry.npm.taobao.org:443:::::::false::":1},"requests":{"cdn.npm.taobao.org:443:::::::false::":31}})
headers: {}
Error: write EPROTO 140736244773696:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:800:

    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
npminstall version: 3.3.0
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/Codeliu/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org weex-toolkit -g --no-optional

**Comment by codeliu6572** [comment]
找了网上很多方法，都不可以，唯一安装成功的是一个0.6的weex版本，但是很多东西太老了不能用

**Comment by codeliu6572** [comment]
糊里糊涂的，竟然就好了，不知道发生了什么

**Comment by Kingbultsea** [comment]
我和你是同一个问题 也是安装0.6的就好了  然后我现在还在烦恼
