### ISSUE TITLE
list标签在playaground显示正常，在模拟器和真机却显示空白，请教怎么回事

### ISSUE THREAD

**Issue by codeliu6572** [apache/incubator-weex-cli#298]
如题，配置好后，写入代码，即使从官网复制来的代码，list就是无法显示在模拟器和真机，请教这是为什么？

**Comment by codeliu6572** [comment]
这个问题真的困扰我好久了，还望大神能解答，指点迷津。

**Comment by codeliu6572** [comment]
@sospartan @Tancy

**Comment by codeliu6572** [comment]
我通过weex preview手动编辑后扫描可以了，想知道怎么做可以不用每次都一个个文件的编译？还请大神能解答下迷惑。

**Comment by erha19** [comment]
@codeliu6572 you can just go to your source folder and run `npm start`, it will compile all the source code.
