### ISSUE TITLE
sudo weex init lists 这信息到底是成功了还是失败了？该怎么解决？

### ISSUE THREAD

**Issue by codeliu6572** [apache/incubator-weex-cli#299]
bogon:WeexTest Codeliu$ sudo weex init lists
Password:
? Project name lists
? Project description A weex project
? Author 刘浩浩 <liuhaohao@jianbing.com>
? weex build lts
? babel compiler (https://babeljs.io/docs/plugins/#stage-x-experimental-presets)
 stage-0
? Use vue-router to manage your view router? (not recommended) Yes
? Use ESLint to lint your code? No
? Set up unit tests No
? Should we run `npm install` for you after the project has been created? (recom
mended) npm
22:26:07 : Generated lists

# Installing project dependencies ...
# ========================

npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 

> ios-deploy@1.9.2 preinstall /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy
> ./src/scripts/check_reqs.js && xcodebuild

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!! WARNING: You are on OS X 10.11 El Capitan or greater, you may need to add the
!!!! WARNING:   `--unsafe-perm=true` flag when running `npm install`
!!!! WARNING:   or else it will fail.
!!!! WARNING: link:
!!!! WARNING:   https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2018-02-26 22:26:36.214 xcodebuild[81363:1757592] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ZLXCodeLine.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-26 22:26:36.215 xcodebuild[81363:1757592] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XFunnyEditor.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-26 22:26:36.216 xcodebuild[81363:1757592] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-26 22:26:36.217 xcodebuild[81363:1757592] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-26 22:26:36.217 xcodebuild[81363:1757592] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ActivatePowerMode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-02-26 22:26:37.097 xcodebuild[81363:1757770]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: You don’t have permission to save the file “ios-deploy-lib.build” in the folder “Release”.
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7f9b629d7a00>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-02-26 22:26:37.098 xcodebuild[81363:1757771]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13756/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: You don’t have permission to save the file “ios-deploy.build” in the folder “Release”.
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7f9b629d7b70>{number = 11, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
=== BUILD TARGET ios-deploy-lib OF PROJECT ios-deploy WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build (Permission denied)
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build (Permission denied)

Write auxiliary files
/bin/mkdir -p /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build (Permission denied)
/bin/mkdir -p /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build (Permission denied)
/bin/mkdir -p /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build (Permission denied)
/bin/mkdir -p /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build/Objects-normal/x86_64
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build/Objects-normal/x86_64 (Permission denied)
/bin/mkdir -p /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build (Permission denied)
/bin/mkdir -p /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build (Permission denied)
/bin/mkdir -p /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build
error: Unable to create directory: /Users/Codeliu/Desktop/WeexTest/lists/node_modules/ios-deploy/build/ios-deploy.build/Release/ios-deploy-lib.build (Permission denied)

** BUILD FAILED **

The following build commands failed:
	Check dependencies
	Write auxiliary files
(2 failures)

> fsevents@1.1.3 install /Users/Codeliu/Desktop/WeexTest/lists/node_modules/fsevents
> node install

[fsevents] Success: "/Users/Codeliu/Desktop/WeexTest/lists/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/Codeliu/Desktop/WeexTest/lists/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.2 (node_modules/ios-deploy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 65

added 1239 packages in 33.159s

Success! Created lists at /Users/Codeliu/Desktop/WeexTest/lists

Inside that directory, you can run several commands:

  npm start
  Starts the development server for you to preview your weex page on browser
  You can also scan the QR code using weex playground to preview weex page on native

  npm run dev
  Open the code compilation task in watch mode

  npm run ios
  (Mac only, requires Xcode)
  Starts the development server and loads your app in an iOS simulator

  npm run android
  (Requires Android build tools)
  Starts the development server and loads your app on a connected Android device or emulator

  npm run pack:ios
  (Mac only, requires Xcode)
  Packaging ios project into ipa package

  npm run pack:android
  (Requires Android build tools)
  Packaging android project into apk package

  npm run pack:web
  Packaging html5 project into `web/build` folder

  npm run test
  Starts the test runner

To get started:

  cd lists
  npm start

Enjoy your hacking time!

**Comment by codeliu6572** [comment]
@amdgigabyte @yyx990803

**Comment by erha19** [comment]
@codeliu6572 go to the `lists` folder, and run `npm start`.

**Comment by codeliu6572** [comment]
not npm install?  i tried and alert the html, but how can i use npm run serve?
