### ISSUE TITLE
支持自动端口配置

### ISSUE THREAD

**Issue by xudafeng** [apache/incubator-weex-cli#30]
如果开启多个实例，可以从8081，8082(socket) 两个端口基础上递增，react-native脚手架大多这么做的，详见https://www.npmjs.com/package/detect-port

**Comment by Jinjiang** [comment]
恩，不错的建议，值得考虑 @lvscar

**Comment by zhuyali** [comment]
建议使用多个端口，现在在运行weex时，还需要保证8081端口不被占用，感觉808x 这种端口是最经常被占用的了，还需要关掉其他的服务。
https://github.com/vuejs-templates/webpack/pull/385
@Jinjiang @lvscar
