### ISSUE TITLE
Not able to run weex src/index.vue, canot find module 'webpack-sources'

### ISSUE THREAD

**Issue by bonustrack** [apache/incubator-weex-cli#301]
When i run `weex src/index.vue` i have this issue:

![image](https://user-images.githubusercontent.com/16245250/36687245-9e44fff8-1b5b-11e8-9d70-e345b9514499.png)

It's blocking me to do anything, even if i add the dependancy `webpack-sources` i have additional error which tell me to add another deps.

This is the versions i'm using:
```
v1.1.0-beta.7
 - weexpack : v1.1.1
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.4.8
```

**Comment by erha19** [comment]
@bonustrack try to upgrade your `weex-toolkit` by `npm i weex-toolkit@latest -g` and use `weex preview xxx.vue` command to preview your pages.

**Comment by bonustrack** [comment]
When  i run `npm i weex-toolkit@latest -g` i have adionnal errors:
![image](https://user-images.githubusercontent.com/16245250/36723592-4d9b1d52-1be3-11e8-84cb-7b5ae6140a4c.png)
The request does not resolve for me and keep loading even after waiting more than 30 min.

**Comment by erha19** [comment]
@bonustrack please use `npm@4` to install the package, that's a bug on `npm@5`, you can run `npm i npm@4 -g` and install `weex-toolkit` again.

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
