### ISSUE TITLE
weex bundle 的入口文件在哪？src/entry.js只是web bundle的入口文件

### ISSUE THREAD

**Issue by wen911119** [apache/incubator-weex-cli#302]
node -v 
v8.9.0
weex -v 
 v1.2.9
 - weexpack : v1.1.1
 - weex-builder : v0.3.15
 - weex-previewer : v1.4.7

用weex-toolkit生成的项目，在看webpack.common.conf.js配置文件时候很困惑，
weex的enrty指向的是一个*.vue？entry=true的文件，entry不应该是js文件吗，那么我要加上vuex要在哪里加？
难道weex-loader内置了一个默认的weex-entry.js?

**Comment by erha19** [comment]
@wen911119 yes, you are right, when you add query about `entry=true`, the `weex-loader` will generate an entry file for weex bundle.

**Comment by wen911119** [comment]
@erha19 了解了！也就是说我要有些定制需求就得自己准备weex-entry.js文件了。非常感谢回复！

**Comment by asd8855** [comment]
@erha19  你好，怎么把dist中的文件导出到 jsbundle中，我的dist文件夹中有多个js文件，但jsbundle中只有一个index.js 文件。我应该怎么配置？
