### ISSUE TITLE
weex-toolkit 1.2.9版本运行npm run serve 报异常 

### ISSUE THREAD

**Issue by Hyman4810** [apache/incubator-weex-cli#303]
![image](https://user-images.githubusercontent.com/23622246/36709438-d7de83ae-1bb2-11e8-9b9b-16a524ab228b.png)
![image](https://user-images.githubusercontent.com/23622246/36709472-f9d2b0ac-1bb2-11e8-972e-7b0ef9c03cfc.png)

**Comment by erha19** [comment]
@MrxiaoxiWEB  see https://github.com/weexteam/weex-toolkit/issues/304#issuecomment-368816759
