### ISSUE TITLE
通过 weex create awesomeapp 项目，执行npm start 报webpack.common.conf.js:95 ...webEntry 语法错误

### ISSUE THREAD

**Issue by DevForrestWang** [apache/incubator-weex-cli#304]
## Your development environment
appledeMac-mini-2:awesomeapp wd$ node -v
v6.11.3
appledeMac-mini-2:awesomeapp wd$ npm -v
5.6.0

appledeMac-mini-2:awesomeapp wd$ weex -v
   v1.2.9
 - weexpack : v1.1.1
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

- platform (Mac)

## The key error stack message.
![image](https://user-images.githubusercontent.com/5129517/36717273-67d71ab4-1bd8-11e8-825b-afceebd29e3d.png)

![image](https://user-images.githubusercontent.com/5129517/36717291-79fc0704-1bd8-11e8-84e0-f69f698f9fc3.png)

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
1、安装完node环境；
2、安装完 npm install weex-toolkit -g
3、执行 weex create awesomeapp
4、进入awesomeapp 执行npm start 报下面错误
awesomeapp/configs/webpack.common.conf.js:95
    ...webEntry,
    ^^^

**Comment by erha19** [comment]
@DevForrestWang The `...` syntax need `node 9+` environment, I have been remove the usage of it, please re-create your project by `weex create app`, it should be fixed.

**Comment by DevForrestWang** [comment]
thank you，support；it is ok。
