### ISSUE TITLE
用weex create出来的项目直接启动报错

### ISSUE THREAD

**Issue by iori0758** [apache/incubator-weex-cli#305]
VM69:1 Uncaught SyntaxError: Unexpected token \ in JSON at position 1
    at JSON.parse (<anonymous>)
    at preview.html?page=index.js^&entrys=[\components\\HelloWorld\,\index\]:60
    at preview.html?page=index.js^&entrys=[\components\\HelloWorld\,\index\]:76

weex版本为v1.2.9,   weexpack v1.1.1

**Comment by erha19** [comment]
@iori0758 please re-create your project again, this bug has been fixed.

**Comment by MountainHill** [comment]
also has this error
![20180321140931704](https://user-images.githubusercontent.com/7063621/37696452-914467ea-2d11-11e8-9de1-3ae5c6c50840.png)

environment:
node:v8.10.0
npm:5.6.0
week-toolkit:v1.2.9
weexpack : v1.1.6
weex-builder : v0.3.14
weex-previewer : v1.4.6
