### ISSUE TITLE
运行weex create报错

### ISSUE THREAD

**Issue by tanwenchao** [apache/incubator-weex-cli#306]
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanwenchao/.npm/_logs/2018-02-27T13_54_01_716Z-debug.log
21:54:01 : Error: fatal error!
21:54:01 : Error: EACCES: permission denied, open '/Users/tanwenchao/.xtoolkit/config.json'
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),

**Comment by erha19** [comment]
@tanwenchao run `sudo chmod -R 777 ~/.xtoolkit` then run your command again.
