### ISSUE TITLE
Cannot find module './platformApiPoly'

### ISSUE THREAD

**Issue by des1roer** [apache/incubator-weex-cli#307]
➜  awesome-project git:(master) ✗ weex platform add android

   ┌──────────────────────────────────────────────┐
   │                                              │
   │                                              │
   │   Update available 1.0.13 → 1.1.1            │
   │   Run weex update weexpack@1.1.1 to update   │
   │                                              │
   │                                              │
   └──────────────────────────────────────────────┘

19:54:50 : Error: Cannot find module './platformApiPoly'

**Comment by erha19** [comment]
@des1roer please upgrade your weexpack by `weex update weexpack@latest`.
