### ISSUE TITLE
npm run build:prod, the output js can not run in native.

### ISSUE THREAD

**Issue by mdsb100** [apache/incubator-weex-cli#309]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- v1.2.8
- Mac

## The key error stack message.
webpack.prod.conf.js should add a plugin like this after Uglify
```
new webpack.BannerPlugin({
      banner: '// { "framework": "Vue"} \n',
      raw: true,
      exclude: 'Vue'
    }),
```
Because Uglify will remove all annotation, but native must need```// { "framework": "Vue"} ```

**Comment by erha19** [comment]
@mdsb100 yes you are right, I have been fixed it on the latest version of [weex-template](https://github.com/weex-templates/webpack).
