### ISSUE TITLE
升级到0.6.2后，android的slider过渡效果没有了，ios的还在

### ISSUE THREAD

**Issue by yuanzx** [apache/incubator-weex-cli#31]
详情可以查看playgroundApp里面的slider，是故意去掉了还是什么原因？将来是否会修复，如果会修复，希望加上过渡效果时间参数，或者能自己写过渡函数

**Comment by Jinjiang** [comment]
能提供一个在线的例子吗？方便我们定位：http://dotwe.org/weex
谢谢
另外这个应该是主仓库本身的问题，和 toolkit 关系不大，所以我这里先关掉了，具体问题可以在准备好在线例子后到 Weex 的主仓库另开 issue
感谢理解
