### ISSUE TITLE
win10 node 8.9.4 npm5.6.0 安装警告，这是成了吗

### ISSUE THREAD

**Issue by muchakaka** [apache/incubator-weex-cli#311]
C:\Users\CT>npm install -g weex-toolkit
C:\Users\CT\AppData\Roaming\npm\weex -> C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\bin\weex.js

> ws@0.4.31 install C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

> ws@0.4.31 install C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

> ws@0.4.31 install C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

> ws@0.4.31 install C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modules\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modules\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

> ws@https://registry.npmjs.org/ws/-/ws-0.4.31.tgz install C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

> ws@https://registry.npmjs.org/ws/-/ws-0.4.31.tgz install C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\CT\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-builder\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> spawn-sync@1.0.15 postinstall C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\inquirer\node_modules\spawn-sync
> node postinstall

> spawn-sync@https://registry.npmjs.org/spawn-sync/-/spawn-sync-1.0.15.tgz postinstall C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\spawn-sync
> node postinstall

(node:6068) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit

> weex-previewer@1.4.6 postinstall C:\Users\CT\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer
> node ./lib/hook/post-install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ weex-toolkit@1.2.9
added 3864 packages from 1272 contributors in 176.175s

**Comment by muchakaka** [comment]
这是成了还是没成啊？

**Comment by erha19** [comment]
@muchakaka you can run `weex -v` to check if it is installed success.
