### ISSUE TITLE
weex -v 出现的提示信息，这里的选择对实际开发有啥作用？

### ISSUE THREAD

**Issue by 15826954460** [apache/incubator-weex-cli#312]
? May weex-toolkit anonymously report usage statistics to improve the tool over time? No
? Which npm registry you perfer to use? taobao
00:46:01 : Set telemetry => false
00:46:01 : Set registry => http://registry.npm.taobao.org
Set telemetry = false
Set registry = "http://registry.npm.taobao.org"
00:46:01 : You can config this configuration again by using `weex config [key] [value]`
00:46:01 : Enjoying your coding time!

   v1.2.9
 - weex-builder : v0.3.16
 - weex-previewer : v1.4.8

只有选择完了之后才出现版本号

**Comment by erha19** [comment]
@15826954460 Is the prompt always show while you run `weex -v`?

**Comment by 15826954460** [comment]
@erha19  the first to run weex -v will show the prompt
else will show  like
 >weex -v
   v1.2.9
 - weex-builder : v0.3.16
 - weex-previewer : v1.4.8

**Comment by erha19** [comment]
@15826954460 As the description mention, one is used to determine whether to collect user track or not, one is used to choose `npm` remote for installing package.
