### ISSUE TITLE
cnpm install -g weex-toolkit  出现的警告，不知如何避免，也不知到后期会不会出现什么意外，求大神告知一二

### ISSUE THREAD

**Issue by 15826954460** [apache/incubator-weex-cli#313]
Downloading weex-toolkit to C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\weex-toolkit_tmp
Copying C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\weex-toolkit_tmp\_weex-toolkit@1.2.9@weex-toolkit to C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\weex-toolkit
Installing weex-toolkit's dependencies to C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\weex-toolkit/node_modules
[1/5] chalk@^1.1.3 installed at node_modules\_chalk@1.1.3@chalk
[2/5] check-node-version@^2.1.0 installed at node_modules\_check-node-version@2.1.0@check-node-version

**WARN node unsupported "node@v6.11.5" is incompatible with xtoolkit@0.2.23 › dns@^0.2.2, expected node@>= 0.10.0 < 0.11.0**

**WARN node unsupported "node@v6.11.5" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6, expected node@>= 0.8.0 < 0.11.0**

[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-parser@2.2.0 › emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz] install emitter from remote http://github.com/component/emitter/archive/1.0.1.tar.gz, may be very slow, please keep patience
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-adapter@0.2.0 › socket.io-parser@2.1.2 › emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz] install emitter from remote http://github.com/component/emitter/archive/1.0.1.tar.gz, may be very slow, please keep patience
exist cache: "copy:C:\\Users\\baiyunsong\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_emitter@1.0.1@emitter" {"done":true}

**WARN node unsupported "node@v6.11.5" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@~0.10.2, expected node@0.8.x**

**WARN node unsupported "node@v6.11.5" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › cryptiles@0.1.x, expected node@0.8.x**

**WARN node unsupported "node@v6.11.5" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › sntp@0.1.x, expected node@0.8.x**
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-client@1.0.6 › engine.io-client@1.3.1 › xmlhttprequest@https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz] install xmlhttprequest from remote https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz, may be very slow, please keep patience

**WARN node unsupported "node@v6.11.5" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › hoek@0.7.x, expected node@0.8.x**

**WARN node unsupported "node@v6.11.5" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › boom@0.3.x, expected node@0.8.x**

[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-client@1.0.6 › engine.io-client@1.3.1 › has-cors@1.0.3 › global@https://github.com/component/global/archive/v2.0.1.tar.gz] install global from remote https://github.com/component/global/archive/v2.0.1.tar.gz, may be very slow, please keep patience
[3/5] xtoolkit@^0.2.23 installed at node_modules\_xtoolkit@0.2.23@xtoolkit
[4/5] weex-previewer@^1.4.6 installed at node_modules\_weex-previewer@1.4.8@weex-previewer
fsevents@1.1.3 download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://npm.taobao.org/mirrors/fsevents"}
platform unsupported weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › watchpack@1.5.0 › chokidar@2.0.2 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
[5/5] weex-builder@^0.3.14 installed at node_modules\_weex-builder@0.3.16@weex-builder
execute post install 4 scripts...
[1/4] scripts.postinstall xtoolkit@0.2.23 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@^1.0.15 run "node postinstall"
[1/4] scripts.postinstall xtoolkit@0.2.23 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@^1.0.15 finished in 881ms
[2/4] scripts.install xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › engine.io@1.3.1 › ws@0.4.31 run "(node-gyp rebuild 2> builderror.log) || (exit 0)"

C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_ws@0.4.31@ws>node "C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
[2/4] scripts.install xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › engine.io@1.3.1 › ws@0.4.31 finished in 2s
[3/4] scripts.postinstall weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › uglifyjs-webpack-plugin@^0.4.6 run "node lib/post_install.js"
[3/4] scripts.postinstall weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › uglifyjs-webpack-plugin@^0.4.6 finished in 329ms
[4/4] scripts.postinstall weex-previewer@^1.4.6 run "node ./lib/hook/post-install.js"
[4/4] scripts.postinstall weex-previewer@^1.4.6 finished in 844ms
peerDependencies WARNING weex-builder@0.3.16 › babel-loader@^7.1.2 requires a peer of babel-core@6 but none was installed
peerDependencies WARNING weex-builder@0.3.16 › weex-loader@0.7.2 › babel-loader@^6.2.4 requires a peer of babel-core@^6.0.0 but none was installed
peerDependencies WARNING weex-builder@0.3.16 › weex-loader@0.7.2 › babel-loader@^6.2.4 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but webpack@3.11.0 was installed
deprecate weex-builder@0.3.16 › babel-preset-es2015@^6.9.0 ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
deprecate xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › node-uuid@~1.4.0 Use uuid module instead
Recently updated (since 2018-02-24): 20 packages (detail see file C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\.recently_updates.txt)
  2018-03-02
    → xtoolkit@0.2.23 › boxen@1.3.0 › chalk@2.3.1 › supports-color@^5.2.0(5.3.0) (17:07:59)
    → xtoolkit@0.2.23 › boxen@1.3.0 › chalk@2.3.1 › ansi-styles@^3.2.0(3.2.1) (17:40:00)
  2018-03-01
    → xtoolkit@0.2.23 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@1.0.15 › concat-stream@^1.4.7(1.6.1) (22:35:25)
    → weex-builder@0.3.16 › weex-loader@0.7.2 › weex-scripter@0.1.6 › browserify@13.0.1 › insert-module-globals@^7.0.0(7.0.2) (00:39:00)
  2018-02-28
    → xtoolkit@0.2.23 › yargs@6.6.0 › read-pkg-up@1.0.1 › read-pkg@1.1.0 › normalize-package-data@2.4.0 › validate-npm-package-license@^3.0.1(3.0.3) (02:18:49)
    → xtoolkit@0.2.23 › yargs@6.6.0 › read-pkg-up@1.0.1 › read-pkg@1.1.0 › normalize-package-data@2.4.0 › validate-npm-package-license@3.0.3 › spdx-correct@^3.0.0(3.0.0) (02:16:36)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › watchpack@^1.4.0(1.5.0) (23:31:38)
  2018-02-27
    → xtoolkit@0.2.23 › request@2.83.0 › tough-cookie@~2.3.3(2.3.4) (06:29:25)
    → xtoolkit@0.2.23 › yargs@6.6.0 › read-pkg-up@1.0.1 › read-pkg@1.1.0 › normalize-package-data@2.4.0 › validate-npm-package-license@3.0.3 › spdx-expression-parse@^3.0.0(3.0.0) (08:14:18)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › acorn@^5.0.0(5.5.0) (15:46:26)
    → weex-builder@0.3.16 › weex-loader@0.7.2 › weex-vue-loader@0.6.1 › weex-template-compiler@2.5.13-weex.3 › escodegen@^1.8.1(1.9.1) (01:49:12)
  2018-02-26
    → weex-builder@^0.3.14(0.3.16) (14:06:43)
    → weex-builder@0.3.16 › babel-loader@^7.1.2(7.1.3) (01:10:42)
    → xtoolkit@0.2.23 › request@2.83.0 › har-validator@5.0.3 › ajv@5.5.2 › fast-deep-equal@^1.0.0(1.1.0) (04:45:49)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › ajv@^6.1.0(6.2.0) (16:23:58)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › escope@3.6.0 › esrecurse@^4.1.0(4.2.1) (23:47:34)
    → weex-previewer@^1.4.6(1.4.8) (14:54:18)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › watchpack@1.5.0 › chokidar@2.0.2 › upath@^1.0.0(1.0.4) (08:13:26)
  2018-02-24
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › watchpack@1.5.0 › chokidar@2.0.2 › anymatch@2.0.0 › micromatch@^3.1.4(3.1.9) (15:56:12)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › watchpack@1.5.0 › chokidar@2.0.2 › braces@2.3.1 › to-regex@^3.0.1(3.0.2) (16:29:32)
All packages installed (917 packages installed from npm registry, 4 packages installed from remote url, used 1m, speed 335kB/s, json 772(10.27MB), tarball 18.69MB)
[weex-toolkit@1.2.9] link C:\Users\baiyunsong\AppData\Roaming\npm\weex@ -> C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\weex-toolkit\bin\weex.js

以下为淘宝镜像的 cnpm 版本
cnpm@5.2.0 (C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@5.7.1 (C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@6.11.5 (D:\AboutJavaScript\nodejs\node.exe)
npminstall@3.3.0 (C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\baiyunsong\AppData\Roaming\npm
win32 x64 10.0.16299
registry=https://registry.npm.taobao.org

**Comment by erha19** [comment]
@15826954460 we suggest you use `npm@4` to install the package on windows platforms and you can run `weex -v` to check if it is installed success.

**Comment by 15826954460** [comment]
@erha19  
官方文档说 要升级到 npm >= 5 啊   I try to do it at npm@4
 在weex-toolkit1.0.8版本后添加了npm5规范的npm-shrinkwrap.json用于锁定包依赖，故npm版本<5的用户需要通过npm i npm@latest -g更新一下npm的版本，使用前请确认版本是否正确。

**Comment by erha19** [comment]
@15826954460 using `npm@5` may cause many problems on windows, so I suggest you to use `npm@4`.

**Comment by dariarse** [comment]
Hi! You are right, using npm5 to install weex toolkit on windows is causing many problems. But how are we supposed to install it with npm4 if now Node is 8 so npm is already upgraded to 5? Do you have any other suggestions a part from using npm4? 
Thank you!

**Comment by erha19** [comment]
@dariarse You can follow the known issues with npm 5 at: https://github.com/npm/npm/issues/16991
