### ISSUE TITLE
input[type=number] 不能限制maxlength？

### ISSUE THREAD

**Issue by Rem486** [apache/incubator-weex-cli#314]
## Your development environment
 weex -v
   v1.1.0-beta.9
 - weexpack : v1.0.10
 - weex-builder : v0.3.11
 - weex-previewer : v1.4.4

## The key error stack message.

你好，
在使用input组件，type=number 的时候，似乎无法通过maxlength 属性来限制输入长度？

要实现限制整数输入应该怎么设置呢？没有了step
如果使用正则在input阶段进行replace，输入   **11....**    由于由于不合法，input的event.value 就会为空

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

[dotwe Demo](http://dotwe.org/vue/fd3ac6ca88823efe6ebc97f07774e86d)

**Comment by erha19** [comment]
@Rem486 question you can go to the mail list for discussing, see http://weex-project.io/contributing.html#join-in-discussions.

**Comment by Rem486** [comment]
ok
