### ISSUE TITLE
最新的模板。运行npm start webpack asset optimization  花很长时间

### ISSUE THREAD

**Issue by scholar-ink** [apache/incubator-weex-cli#315]
最新的模板。运行npm start webpack asset optimization  花很长时间，并且更新一个文字，感觉会所有文件全部打包。

**Comment by erha19** [comment]
Maybe it can be faster after replace with `webpack@4`.

**Comment by 3330847720** [comment]
我也碰到了， 主要是因为 没有使用vue 的 router

**Comment by hacke2** [comment]
@scholar-ink 已解决，看一下 https://github.com/weex-templates/webpack/pull/5
