### ISSUE TITLE
npm install weex-toolkit -g安装警告，weex不能使用

### ISSUE THREAD

**Issue by NicInvade** [apache/incubator-weex-cli#316]
WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@^0.2.2, expected node@>= 0.10.0 < 0.11.0

**Comment by NicInvade** [comment]
安装日志
$ cnpm i -g weex-toolkit
Downloading weex-toolkit to C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit_tmp
Copying C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit_tmp\_weex-toolkit@1.2.9@weex-toolkit to C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit
Installing weex-toolkit's dependencies to C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit/node_modules
[1/5] chalk@^1.1.3 installed at node_modules\_chalk@1.1.3@chalk
[2/5] check-node-version@^2.1.0 installed at node_modules\_check-node-version@2.1.0@check-node-version

WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@^0.2.2, expected node@>= 0.10.0 < 0.11.0

WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6, expected node@>= 0.8.0 < 0.11.0
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-parser@2.2.0 › emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz] install emitter from remote http://github.com/component/emitter/archive/1.0.1.tar.gz, may be very slow, please keep patience
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-adapter@0.2.0 › socket.io-parser@2.1.2 › emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz] install emitter from remote http://github.com/component/emitter/archive/1.0.1.tar.gz, may be very slow, please keep patience

WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@~0.10.2, expected node@0.8.x

WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › cryptiles@0.1.x, expected node@0.8.x
exist cache: "copy:C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\weex-toolkit\\node_modules\\_emitter@1.0.1@emitter" {"done":false}
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-client@1.0.6 › engine.io-client@1.3.1 › xmlhttprequest@https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz] install xmlhttprequest from remote https://github.com/LearnBoost/node-XMLHttpRequest/archive/0f36d0b5ebc03d85f860d42a64ae9791e1daa433.tar.gz, may be very slow, please keep patience

WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › sntp@0.1.x, expected node@0.8.x

WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › boom@0.3.x, expected node@0.8.x

WARN node unsupported "node@v6.11.3" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › hoek@0.7.x, expected node@0.8.x
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-client@1.0.6 › engine.io-client@1.3.1 › has-cors@1.0.3 › global@https://github.com/component/global/archive/v2.0.1.tar.gz] install global from remote https://github.com/component/global/archive/v2.0.1.tar.gz, may be very slow, please keep patience
[3/5] xtoolkit@^0.2.23 installed at node_modules\_xtoolkit@0.2.23@xtoolkit
[4/5] weex-previewer@^1.4.6 installed at node_modules\_weex-previewer@1.4.8@weex-previewer
fsevents@1.1.3 download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://npm.taobao.org/mirrors/fsevents"}
platform unsupported weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › watchpack@1.5.0 › chokidar@2.0.2 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
[5/5] weex-builder@^0.3.14 installed at node_modules\_weex-builder@0.3.16@weex-builder
execute post install 4 scripts...
[1/4] scripts.postinstall xtoolkit@0.2.23 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@^1.0.15 run "node postinstall"
[1/4] scripts.postinstall xtoolkit@0.2.23 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@^1.0.15 finished in 139ms
[2/4] scripts.install xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › engine.io@1.3.1 › ws@0.4.31 run "(node-gyp rebuild 2> builderror.log) || (exit 0)"

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\_ws@0.4.31@ws>node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
[2/4] scripts.install xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › engine.io@1.3.1 › ws@0.4.31 finished in 251ms
[3/4] scripts.postinstall weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › uglifyjs-webpack-plugin@^0.4.6 run "node lib/post_install.js"
[3/4] scripts.postinstall weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › uglifyjs-webpack-plugin@^0.4.6 finished in 118ms
[4/4] scripts.postinstall weex-previewer@^1.4.6 run "node ./lib/hook/post-install.js"
[4/4] scripts.postinstall weex-previewer@^1.4.6 finished in 231ms
peerDependencies WARNING weex-builder@0.3.16 › babel-loader@^7.1.2 requires a peer of babel-core@6 but none was installed
peerDependencies WARNING weex-builder@0.3.16 › weex-loader@0.7.2 › babel-loader@^6.2.4 requires a peer of babel-core@^6.0.0 but none was installed
peerDependencies WARNING weex-builder@0.3.16 › weex-loader@0.7.2 › babel-loader@^6.2.4 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but webpack@3.11.0 was installed
deprecate weex-builder@0.3.16 › babel-preset-es2015@^6.9.0 ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
deprecate xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › node-uuid@~1.4.0 Use uuid module instead
Recently updated (since 2018-02-27): 14 packages (detail see file C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\.recently_updates.txt)
  Today:
    → weex-builder@0.3.16 › css-loader@0.28.10 › cssnano@3.10.0 › autoprefixer@6.7.7 › browserslist@1.7.7 › electron-to-chromium@^1.2.7(1.3.36) (13:02:22)
    → weex-builder@0.3.16 › css-loader@0.28.10 › cssnano@3.10.0 › autoprefixer@6.7.7 › caniuse-db@^1.0.30000634(1.0.30000813) (14:17:14)
  2018-03-05
    → weex-builder@0.3.16 › vue-loader@12.2.2 › postcss-load-config@1.2.0 › cosmiconfig@2.2.2 › js-yaml@^3.4.3(3.11.0) (23:52:52)
  2018-03-04
    → xtoolkit@0.2.23 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@1.0.15 › concat-stream@1.6.1 › readable-stream@^2.2.2(2.3.5) (00:22:07)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › ajv@^6.1.0(6.2.1) (05:22:14)
  2018-03-03
    → xtoolkit@0.2.23 › boxen@1.3.0 › chalk@^2.0.1(2.3.2) (01:43:52)
  2018-03-02
    → xtoolkit@0.2.23 › boxen@1.3.0 › chalk@2.3.2 › supports-color@^5.3.0(5.3.0) (17:07:59)
    → xtoolkit@0.2.23 › boxen@1.3.0 › chalk@2.3.2 › ansi-styles@^3.2.1(3.2.1) (17:40:00)
  2018-03-01
    → xtoolkit@0.2.23 › inquirer@2.0.0 › external-editor@1.1.1 › spawn-sync@1.0.15 › concat-stream@^1.4.7(1.6.1) (22:35:25)
    → weex-builder@0.3.16 › weex-loader@0.7.2 › weex-scripter@0.1.6 › browserify@13.0.1 › insert-module-globals@^7.0.0(7.0.2) (00:39:00)
  2018-02-28
    → xtoolkit@0.2.23 › yargs@6.6.0 › read-pkg-up@1.0.1 › read-pkg@1.1.0 › normalize-package-data@2.4.0 › validate-npm-package-license@^3.0.1(3.0.3) (02:18:49)
    → xtoolkit@0.2.23 › yargs@6.6.0 › read-pkg-up@1.0.1 › read-pkg@1.1.0 › normalize-package-data@2.4.0 › validate-npm-package-license@3.0.3 › spdx-correct@^3.0.0(3.0.0) (02:16:36)
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › watchpack@^1.4.0(1.5.0) (23:31:38)
  2018-02-27
    → weex-builder@0.3.16 › babel-loader@7.1.3 › webpack@3.11.0 › acorn@^5.0.0(5.5.0) (15:46:26)
All packages installed (917 packages installed from npm registry, 4 packages installed from remote url, used 49s, speed 601.43kB/s, json 772(10.28MB), tarball 18.69MB)
[weex-toolkit@1.2.9] link C:\Users\Administrator\AppData\Roaming\npm\weex@ -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\bin\weex.js

**Comment by erha19** [comment]
@NicInvade do not use `cnpm` but use `npm@4` to install the package.
