### ISSUE TITLE
weex -v 和weex create 都报错

### ISSUE THREAD

**Issue by chunhuigao** [apache/incubator-weex-cli#317]
node版本7.8.0   npm版本5.6.0
![qq 20180306181126](https://user-images.githubusercontent.com/21995539/37026585-d1bc990e-2169-11e8-959b-d03ba9df0950.jpg)

![qq 20180306180848](https://user-images.githubusercontent.com/21995539/37026465-6db3e3cc-2169-11e8-8e33-abbc4c8e180f.jpg)

**Comment by erha19** [comment]
@chunhuigao try to delete file on your `~/.nvm/.../node_modules/weex-toolkit`, run `npm i npm@4 -g`, then install `weex-toolkit` by `npm i weex-toolkit -g` again.

**Comment by chunhuigao** [comment]
You are right, according to your method, has been good, thank you
