### ISSUE TITLE
使用weex create xx  创建项目卡死？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#318]
问题：
`E:\>weex create yixin

   ┌──────────────────────────────────────────────┐
   │                                              │
   │                                              │
   │   Update available 1.1.1 → 1.1.5             │
   │   Run weex update weexpack@1.1.5 to update   │
   │                                              │
   │                                              │
   └──────────────────────────────────────────────┘

? Project name yixin
? Project description A weex project
? Author username <username@email.com>
? Select weex web render latest
? Babel compiler (https://babeljs.io/docs/plugins/#stage-x-experimental-presets) stage-0
? Use vue-router to manage your view router? (not recommended) No
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Set up unit tests Yes
? Should we run `npm install` for you after the project has been created? (recommended) npm
22:15:41 : Generated yixin

# Installing project dependencies ...
# ========================

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-4E/be5eW2K2snI9kwUg3sjEzeLA= integrity checksum failed when using sha1: wanted sha1-4E/be5eW2K2snI9kwUg3sjEzeLA= but got sha512-kkpcKNlmQan9Z5ZmgqKH/SMbSmjxQ7QjyNqfXVc8VJcoBV2UEg+sxQD15GQofGRh2hfpwUb70VC31DR7Rq5Hdw==. (8519 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> phantomjs-prebuilt@2.1.16 install E:\yixin\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\myth\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
  [========--------------------------------] 19%`

**# 此处一直卡在19%进度**！！！
@erha19

**Comment by erha19** [comment]
maybe you should. not select unit test

**Comment by AugTang** [comment]
应该怎么操作？
@erha19

**Comment by erha19** [comment]
when you create your project, choice N while you see `? Set up unit tests`

**Comment by AugTang** [comment]
创建项目之后，运行npm start命令，为什么无法自动打开？
@erha19
