### ISSUE TITLE
今晚创建新项目之后，使用weex preview src/index.vue  预览命令，报错？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#319]
环境：
windows 10系统；
weex版本：
![image](https://user-images.githubusercontent.com/31499235/37042793-1bce7b7c-219a-11e8-942a-21d0f0902931.png)
问题图：
![image](https://user-images.githubusercontent.com/31499235/37042675-e9581022-2199-11e8-8aa8-c2029313b92d.png)

注：之前都是可以创建项目，并且运行没有问题，我什么也没改，就这样了。
@erha19

**Comment by erha19** [comment]
@AugTang you need to change `./components/HelloWorld` to `./components/HelloWorld.vue` because the `previewer` doesn't know what ext you have imported.
