### ISSUE TITLE
win10下安装weex-toolkit报警，weex报错 Cannot find module 'npm'

### ISSUE THREAD

**Issue by NicInvade** [apache/incubator-weex-cli#324]
$ node -v
v8.9.3

$ npm -v
5.5.1

Administrator@PC-20170927CWSD MINGW32 /f/projects
$ npm install -g weex-toolkit
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellane                                                            ous Warning EINTEGRITY: sha1-Nm47w1FHchtpAJ+AOQfE1TIS6I0= integrity checksum fai                                                            led when using sha1: wanted sha1-Nm47w1FHchtpAJ+AOQfE1TIS6I0= but got sha512-/SG                                                            POyifPf20iTrMN+WdlY2MbKa7/o4j7B/4IAsdOusASp2icT+Wcdjf4tjJHaXNX8Pe9bpgVxLNxhRvcf8                                                            E5w==. (1808 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due                                                             to a request error during revalidation.
C:\Users\Administrator\AppData\Roaming\npm\weex -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\bin\weex.js

> ws@0.4.31 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk  \node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk\node_modules\socket  .io\node_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\no  de_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> ws@0.4.31 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk  \node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\tomahawk\node_modules\socket  .io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "D:\nodejs\node_m  odules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> ws@0.4.31 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modul  es\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modules\tomahawk\node_mod  ules\socket.io\node_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bi  n\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> ws@0.4.31 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modul  es\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\dns\node_modules\tomahawk\node_mod  ules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "D:\no  dejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> ws@https://registry.npmjs.org/ws/-/ws-0.4.31.tgz install C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modul  es\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\no  de_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod  ules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> ws@https://registry.npmjs.org/ws/-/ws-0.4.31.tgz install C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modul  es\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\no  de_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules  \npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-builder  \node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-preview  er\node_modules\weex-builder\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

> spawn-sync@1.0.15 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\in  quirer\node_modules\spawn-sync
> node postinstall

> spawn-sync@https://registry.npmjs.org/spawn-sync/-/spawn-sync-1.0.15.tgz postinstall C:\Users\Administrator\AppData\Roaming\npm\node_mod  ules\weex-toolkit\node_modules\xtoolkit\node_modules\spawn-sync
> node postinstall

> weex-previewer@1.4.6 postinstall C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\weex-previewer
> node ./lib/hook/post-install.js

(node:5468) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListener  s() to increase limit
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz (node_modules\weex-toolk  it\node_modules\xtoolkit\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz:   wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevent  s):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os"  :"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os"  :"win32","arch":"x64"})

+ weex-toolkit@1.2.9
added 4096 packages in 541.811s

Administrator@PC-20170927CWSD MINGW32 /f/projects
$ weex -v
   v1.2.9
 - weexpack : v1.1.5
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

Administrator@PC-20170927CWSD MINGW32 /f/projects
$ weex create testweex
module.js:538
    throw err;
    ^

Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\lib\utils\index.js:7:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\.xtoolkit\node_modules\weexpack\lib\create\index.js:28:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

**Comment by erha19** [comment]
@NicInvade delete `C:\Users\Administrator.xtoolkit\node_modules\weexpack` then run create command again.

**Comment by NicInvade** [comment]
删除后可以create命令了，但是有报错
$ weex create testweex
This command need to install weexpack. Installing...
npm ERR! path C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\fsevents\node_modules\getpass\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\fsevents\node_m                                                            odules\getpass\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'C:\Users\Administrator\.xtoolkit\node_modules\weexpack\node_modules\fsevents\nod                                                            e_modules\getpass\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\Administrator\\.xtoolkit\\node_modules\\weexpack\\node_module                                                            s\\fsevents\\node_modules\\getpass\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'C:\\Users\\Administrator\\.xtoolkit\\node_modules\\weexpack\\node_modules\\fsevents\\node_modules\\getpass\\node_modules'                                                             }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-03-08T10_41_23_125Z-debug.log
? Project name (testweex)
? Project name testweex
? Project description (A weex project)
? Project description A weex project
? Author (hupingzhi <805152858@qq.com>)
? Author hupingzhi <805152858@qq.com>
? Select weex web render (Use arrow keys)
? Select weex web render latest
? Babel compiler (https://babeljs.io/docs/plugins/#stage-x-experimental-presets
? Babel compiler (https://babeljs.io/docs/plugins/#stage-x-experimental-presets
) stage-0
? Use vue-router to manage your view router? (not recommended) (y/N) y
? Use vue-router to manage your view router? (not recommended) Yes
? Use ESLint to lint your code? (Y/n) n
? Use ESLint to lint your code? No
? Set up unit tests (Y/n) n
? Set up unit tests No
? Should we run `npm install` for you after the project has been created? (reco
? Should we run `npm install` for you after the project has been created? (reco
mmended) npm
18:42:32 : Generated testweex


# Installing project dependencies ...
# ========================

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/e                                                            nv to update!

**Comment by NicInvade** [comment]
@erha19 可以帮忙看看是什么情况吗？
