### ISSUE TITLE
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null

### ISSUE THREAD

**Issue by yinshipeng** [apache/incubator-weex-cli#327]
## My development environment
- weex-toolkit verison (Run `weex -v`)

   v1.2.9
   weexpack : v0.4.7-beta.20
   weex-builder : v0.3.14
   weex-previewer : v1.4.6

- platform (Win/Mac/Ubuntu..)

   Mac
   node : v8.7.0

## The key error stack message.
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null

![](http://ow3sf64ph.bkt.clouddn.com/18-3-8/76041105.jpg)
![](http://ow3sf64ph.bkt.clouddn.com/18-3-8/42145224.jpg)

**Comment by erha19** [comment]
@yinshipeng Firstly, do not use `sudo` command to install an npm package, it's unsafe and easy to cause permission problems. To fix this problem you can try to delete files from `/usr/local/lib/node_modules/weex-toolkit`, then try to install `weex-toolkit` again.
