### ISSUE TITLE
运行 weex debug 后，自动安装 weex-debugger 报错

### ISSUE THREAD

**Issue by imfenghuang** [apache/incubator-weex-cli#330]
npm ERR!  notsup unsupport platform for ios-deploy@1.9.2 want {"os": "darwin:,"arch":"any"} current {"os":"win32","arch":"x64:}

**Comment by erha19** [comment]
@imfenghuang please provide your `npm` version, it should be an `npm` bug, try `npm i npm@5 -g`, then try `weex debug` again.

**Comment by imfenghuang** [comment]
@erha19 `npm`  version is 5.5.1

**Comment by erha19** [comment]
@imfenghuang go to the folder `C:\\User\xxx\.xtoolkit` in the terminal, then run `npm i weex-debugger --no-optional`, it will install the `weex-debugger` without optional dependence, and if you do not have the proxy to install package outside the china wall, you need to config your npm config like this:
```
$ npm config set registry https://registry.npm.taobao.org/
$ npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org
```

**Comment by imfenghuang** [comment]
use this code
```
$ npm config set registry https://registry.npm.taobao.org/
$ npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org
```

but get the error   puppeteer

```
error:read ECONNRESET

npm ERR!  code ELIFECYCLE ...
```


```
verbose Windows_NT 6.1.7601
verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "weex-debugger" "--loglevel=error" "--registry=https://registry.npm.taobao.org/"
verbose node v8.9.4
verbose npm  v5.5.1
error code ELIFECYCLE
error errno 1
error puppeteer@1.0.0 install: `node install.js`
error Exit status 1
error Failed at the puppeteer@1.0.0 install script.
error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by imfenghuang** [comment]
@erha19 
in the `.xtoolkit` folder 
i run `npm install weex-debugger`
it work but the qrcode is always loading 
and after one minute, the debug server is closed automatically

![_20180313152617](https://user-images.githubusercontent.com/20472384/37327863-e7057830-26d2-11e8-8246-46a4f1b0be27.png)

**Comment by imfenghuang** [comment]
an other question
![_20180313160740](https://user-images.githubusercontent.com/20472384/37329416-b8457daa-26d8-11e8-9a6b-9553bdc81d43.png)

weex-debugger cannot be used on the windows plateform？ @erha19

**Comment by imfenghuang** [comment]
in the `.xtoolkit` folder
delete the `node_modules`
run `npm install weex-debugger` again 

weex debug works
