### ISSUE TITLE
Not file playground.apk

### ISSUE THREAD

**Issue by Kency1013** [apache/incubator-weex-cli#331]
When use "weex build android" I not see file playground.apk
![error](https://user-images.githubusercontent.com/32979458/37280606-da9cd366-2620-11e8-884f-883330e5737e.png)

Please support me, Thanks.

**Comment by erha19** [comment]
@MinhPhuong1310 It should be in the `release/android` folder.

**Comment by Kency1013** [comment]
@erha19 Yes, I see the file app-release-unsigned.apk, but it does not install on android, as I know when build will be 2 files app-release-unsigned.apk and playground.apk but i have only file app-release-unsigned.apk

**Comment by erha19** [comment]
@MinhPhuong1310 right, there should be two files, maybe you can see your file on `projectpath/platforms/android/app/build/outputs/apk/` folder or there has some error while you build the project.

**Comment by Kency1013** [comment]
thanks @erha19 , I only "weex create awesome-app" -> " add platform android" -> "build android".
