### ISSUE TITLE
 cnpm install -g weex-toolkit  出错，说是node的版本不兼容

### ISSUE THREAD

**Issue by LCattle** [apache/incubator-weex-cli#333]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
window7 64位
- platform (Win/Mac/Ubuntu..)

##version
node: 8.9.0
npm: 5.51

## The key error stack message.
Downloading weex-toolkit to C:\Users\ghlina\AppData\Roaming\npm\node_modules\weex-toolkit_tmp
Copying C:\Users\ghlina\AppData\Roaming\npm\node_modules\weex-toolkit_tmp\_weex-toolkit@1.2.9@weex-toolkit to C:\Users\ghlina\AppData                                \Roaming\npm\node_modules\weex-toolkit
Installing weex-toolkit's dependencies to C:\Users\ghlina\AppData\Roaming\npm\node_modules\weex-toolkit/node_modules
[1/5] chalk@^1.1.3 installed at node_modules\_chalk@1.1.3@chalk
[2/5] check-node-version@^2.1.0 installed at node_modules\_check-node-version@2.1.0@check-node-version

WARN node unsupported "node@v8.9.0" is incompatible with xtoolkit@0.2.23 › dns@^0.2.2, expected node@>= 0.10.0 < 0.11.0

WARN node unsupported "node@v8.9.0" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6, expected node@>= 0.8.0 < 0.11.                                0
[xtoolkit@0.2.23 › dns@0.2.2 › tomahawk@0.1.6 › socket.io@1.0.6 › socket.io-parser@2.2.0 › emitter@http://github.com/component/emitte                                r/archive/1.0.1.tar.gz] install emitter from remote http://github.com/component/emitter/archive/1.0.1.tar.gz, may be very slow, pleas                                e keep patience
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 100ms, retry left 4, error: ResponseError:                                 read ECONNRESET (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: f                                alse, agent status: {"createSocketCount":12,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount"                                :0,"requestCount":370,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":10,"github.com:443:::::::true::":1},"requests                                ":{"cdn.npm.taobao.org:443:::::::true::":71}})
headers: {}
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 200ms, retry left 3, error: ResponseError:                                 read ECONNRESET (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: f                                alse, agent status: {"createSocketCount":13,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount"                                :0,"requestCount":388,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":10,"github.com:443:::::::true::":1},"requests                                ":{"cdn.npm.taobao.org:443:::::::true::":81}})
headers: {}
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 300ms, retry left 2, error: ResponseError:                                 read ECONNRESET (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: f                                alse, agent status: {"createSocketCount":14,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount"                                :0,"requestCount":403,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":10,"github.com:443:::::::true::":1},"requests                                ":{"cdn.npm.taobao.org:443:::::::true::":77}})
headers: {}

WARN node unsupported "node@v8.9.0" is incompatible with xtoolkit@0.2.23 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@~0.10.2,                                 expected node@0.8.x
[npminstall:get] retry GET http://github.com/component/emitter/archive/1.0.1.tar.gz after 400ms, retry left 1, error: ResponseError:                                 read ECONNRESET (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connected: true, keepalive socket: f                                alse, agent status: {"createSocketCount":15,"createSocketErrorCount":0,"closeSocketCount":4,"errorSocketCount":0,"timeoutSocketCount"                                :0,"requestCount":411,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":10,"github.com:443:::::::true::":1},"requests                                ":{"cdn.npm.taobao.org:443:::::::true::":71}})
headers: {}
Install fail! ResponseError: read ECONNRESET (req "error"), GET https://github.com/component/emitter/archive/1.0.1.tar.gz -1 (connect                                ed: true, keepalive socket: false, agent status: {"createSocketCount":16,"createSocketErrorCount":0,"closeSocketCount":5,"errorSocket                                Count":0,"timeoutSocketCount":0,"requestCount":425,"freeSockets":{},"sockets":{"cdn.npm.taobao.org:443:::::::true::":10,"github.com:4                                43:::::::true::":1},"requests":{"cdn.npm.taobao.org:443:::::::true::":68}})
headers: {}
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:615:25)
npminstall version: 3.2.1
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\ghlina\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\i                                nstall.js --china --userconfig=C:\Users\ghlina\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.t                                aobao.org -g weex-toolkit

[](url)
## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

因电脑上还有别的项目，也是依赖node 8.9.0的版本，怕更新版本会出现问题 ，所以没有更新，不知道有哪位大哥遇到过这样的问题，能否提供一下解决方案？谢谢！

**Comment by imfenghuang** [comment]
使用npm官方的源，然后使用 `npm install -g weex-toolkit`

**Comment by erha19** [comment]
@LCattle we recommend you to use `npm` and you can see [here](https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) to know how to config your `npm`
