### ISSUE TITLE
运行Weex plugin create weex-foo命令后，缺少start文件，导致项目无法正常运行

### ISSUE THREAD

**Issue by super-chen** [apache/incubator-weex-cli#335]
## Your development environment
- weex-toolkit verison (v1.2.9)
- platform (Mac)
- Node (8.10.0)
- NPM (5.6.0)

## The key error stack message.
我在运行Weex plugin create weex-foo命令后生成的文件中，运行/playground/ios中的代码，返回如下错误。
<img width="711" alt="1" src="https://user-images.githubusercontent.com/1482026/37386843-176858b8-2795-11e8-9e60-7c99c274d384.png">
如下是我运行Weex plugin create weex-foo命令后生成的文件目录，缺少start文件
<img width="241" alt="2" src="https://user-images.githubusercontent.com/1482026/37386999-b4d20a72-2795-11e8-86e5-7cfb990cbd0c.png">

**Comment by super-chen** [comment]
问题补充：
在运行Weex plugin create weex-foo期间，提示如下错误。我通过cnpm i 可以继续按照成功，但还是缺少start文件
<img width="648" alt="1" src="https://user-images.githubusercontent.com/1482026/37387118-3089b476-2796-11e8-87a9-cd40fe380e87.png">

**Comment by erha19** [comment]
@super-chen you can run `npm start` to start your development and the template of plugin will be upgrading soon.

**Comment by erha19** [comment]
@super-chen that's shell command should be removed.

**Comment by erha19** [comment]
@super-chen now you can upgrade your `weexpack` and use the latest template by the command `weex plugin create [project_name]`.
