### ISSUE TITLE
为什么安装weex-toolkit后里面的weexpack不是最新版，部分功能也不能用

### ISSUE THREAD

**Issue by rockstone20** [apache/incubator-weex-cli#339]
MAC安装weex-toolkit 运行  weex -v  查看后 的版本
   v1.2.9
 - weexpack : v1.0.2
 - weex-builder : v0.3.17
 - weex-previewer : v1.4.8

且 **weex platform add ios  不能用**
报错   error: unknown option `--telemetry'
weex update weexpack@1.1.5   升级也会报错！   

删除后清除NPM缓存，重装什么的都试了还是一样，这会是什么原因呢。

但是在公司的win10上安装后 weexpack  都是1.1.5的版本，两台电脑创建的DEMO文件都不一样，好纠结

**Comment by erha19** [comment]
@rockstone20 you can run `weex update weexpack` to upgrade your `weexpack`.
