### ISSUE TITLE
安装完成以后创建项目的时候出现error

### ISSUE THREAD

**Issue by changbibi** [apache/incubator-weex-cli#341]
Failed to download repo weex-templates/webpack: EPERM: operation not permitted, utime '/Users/changsir/.weex-templates/weex-templates-webpack/.circleci'、、

![image](https://user-images.githubusercontent.com/20316212/37650688-9d90d6f6-2c70-11e8-83fb-01f75dbe0f98.png)
运行 weex create test-weex2
18:56:50 : Failed to download repo weex-templates/webpack: EPERM: operation not permitted, utime '/Users/changsir/.weex-templates/weex-templates-webpack/.circleci

求各位帮忙解答下

**Comment by erha19** [comment]
@changbibi run `sudo chmod 777 -R ~/.weex-templates`, and then run your `create` command again.

**Comment by changbibi** [comment]
@erha19  您好 感谢您的回复，当我按照您说的运行时出现了如下的情况
![image](https://user-images.githubusercontent.com/20316212/37693733-aa24259e-2cfc-11e8-8eec-3fd6e827808f.png)
于是我还尝试着进入到对应的.weex-templates中运行sudo chmod 777  ~完了出现了跟上面运行以后相同的结果如下图
![image](https://user-images.githubusercontent.com/20316212/37693774-e86cad26-2cfc-11e8-88fe-9e516e9d8bf6.png)

**Comment by changbibi** [comment]
@erha19 您好 我尝试着关掉了我的iTerm重新打开 运行 sudo chmod 777 -R 成功了 然后可以正常初始化项目了，It's incredible！It's incredible！It's incredible！It's incredible！

**Comment by Fundebug** [comment]
I have the same problem, solved by just delete **.weex-templates**:

```bash
 sudo rm -rf /Users/kiwenlau/.weex-templates
```
