### ISSUE TITLE
执行 weex create awesome-project 后报错

### ISSUE THREAD

**Issue by MountainHill** [apache/incubator-weex-cli#343]
**错误如图：**
![20180321140931704](https://user-images.githubusercontent.com/7063621/37696535-4197f314-2d12-11e8-8ccf-e359f0ebe82b.png)

**环境：**

- node:v8.10.0

- npm:5.6.0

- weex-toolkit:v1.2.9

- weexpack : v1.1.6

- weex-builder : v0.3.14

- weex-previewer : v1.4.6

- macOS High Sierra:10.13.3 (17D102)

- Xcode:9.2 (9C40b)

**Comment by erha19** [comment]
@MountainHill still not work? I can't find this error in the same environment, maybe you are using no-official templates?

**Comment by MountainHill** [comment]
@erha19  It works.Thanks.
