### ISSUE TITLE
week run ios 错误

### ISSUE THREAD

**Issue by codeliu6572** [apache/incubator-weex-cli#344]
21:48:19 : If you want to change build config.please modify ios.config.json
21:48:19 : pod update
21:48:19 : Hot Reload socket: ws://192.168.1.102:8080
/Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:47:in `run'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
        from /Users/Codeliu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/Codeliu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
21:48:20 : Error: Command failed: pod update
/Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:47:in `run'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
        from /Users/Codeliu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/Codeliu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

21:48:20 : Maybe you are not setup CocoaPods or see if you have the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
21:48:20 : Error:Error: Command failed: pod update
/Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:47:in `run'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
        from /Users/Codeliu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
        from /Users/Codeliu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/Codeliu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

it happend just now, 我还是说汉语吧，我在终端运行了pod，但是pod没问题，用weex run ios就报上面的错，这是怎么回事啊？

**Comment by codeliu6572** [comment]
@Jinjiang @sospartan @Tancy 说明下，不是Xcode里那个pod check xxx那个问题，那个问题是我最先问出来的，我已经删除那一项了，但是今天忽然就weex run ios不行了（在这之前我升级了webpack到最新版本应该是1.1.6吧，运行了weex platform update ios,但应该不是后者的问题，重新生成platform的项目也不行，同时也删除了pod check那一项），在终端cd到文件里运行pod update/install可以跑，希望能看下是什么问题，下面是报错开始的地方信息，
22:23:44 : Move JSbundle to dist
22:23:44 : start iOS app
============Build Config============
AppName      : WeexApp
Version      : 0.1
BuildVersion : 0.1.0
AppId        : Codeliu.Fire.weex
WeexBundle   : index.js
Ws           : ws://192.168.1.102:8080
CodeSign     :
Profile      :
22:23:44 : If you want to change build config.please modify ios.config.json
22:23:44 : pod update
22:23:44 : Hot Reload socket: ws://192.168.1.102:8080
/Users/Codeliu/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)
这里开始的
多了这两项，不知道干嘛的，不知道是否是这个导致的  emped pods framework    copy pods resources

**Comment by codeliu6572** [comment]
不使用sudo命令我发现了新的报错信息，在43%处报错（wxc-rich-text/wxc-rich-text-text.vue），您看下,这时候模拟器已经被吊起来正常运行了。。。。

$ /usr/local/bin/git -C /Users/Codeliu/.cocoapods/repos/master reset --hard origin/master
  12% [  12%  1           12% [1] building modules 37/38 modules 1 active ...简易项目/mytabbar/src/components/home.v 1 13% [  13%  1  13% [     13% [0] building modules 16/22 modules 6 active ...目/mytabbar/src/components/setting.vu      13% 13% [   1         14% [0] building modules 30/31 modules 1 active ...目/mytabbar/src/components/setting.vu 14% 14% [   1          14% [0] building modules 41/45 modules 4 active ...op/weex练习/简易项目/mytabbar/src/config. 15% 15% [   1  15% [ 15%   15% [0] building modules 55/63 modules 8 active ...项目/mytabbar/src/components/mylist.v   43% [0] building modules 283/305 modules 22 active .../wxc-rich-text/wxc-rich-text-text.vue22:43:02 : Error: stderr maxBuffer exceeded
22:43:02 : Maybe you are not setup CocoaPods or see if you have the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
22:43:02 : Error: stderr maxBuffer exceeded
    at Socket.onChildStderr (child_process.js:346:14)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
  HEAD is now at f772514 [Add] SJVideoPlayerAssetCarrier 1.1.0.1
Analyzing dependencies
Downloading dependencies
Installing BindingX (1.0.1)
Using SDWebImage (3.7.5)
Using SocketRocket (0.4.2)
Using WeexPluginLoader (0.0.1.9.1)
Using WeexSDK (0.18.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.

**Comment by erha19** [comment]
@codeliu6572 try https://github.com/weexteam/weex-toolkit/issues/337 to fix your cocopod.

**Comment by codeliu6572** [comment]
@erha19 升级过ruby之后报下面的错，但是我cd到文件夹pod install/update都是成功的
15:15:08 : If you want to change build config.please modify ios.config.json
15:15:08 : pod update
15:15:08 : Hot Reload socket: ws://192.168.1.140:8080
env: ruby_executable_hooks: No such file or directory
15:15:09 : Error: Command failed: pod update
env: ruby_executable_hooks: No such file or directory

15:15:09 : Maybe you are not setup CocoaPods or see if you have the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
15:15:09 : Error:Error: Command failed: pod update
env: ruby_executable_hooks: No such file or directory

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by erha19** [comment]
see https://github.com/weexteam/weex-toolkit/issues/337#issuecomment-375280748

**Comment by codeliu6572** [comment]
因为weex-toolkit执行编译的时候日志的buffer区不够导致的问题,已经确定

**Comment by ilhamfadllah** [comment]
Hi @codeliu6572, have you solved this issue? I have same issue as well.

**Comment by codeliu6572** [comment]
@positiveneutron question have been solved,you can update to lastest version.
