### ISSUE TITLE
weex build android/weex run android （ 没有把src/dist下面的文件夹内的文件copy到安卓模板中  ）

### ISSUE THREAD

**Issue by wilson-0422** [apache/incubator-weex-cli#345]
weex build android （
没有把src/dist下面的文件夹内的文件copy到安卓模板中
'platforms/android/app/src/main/assets/dist'
）

**Comment by wilson-0422** [comment]
![image](https://user-images.githubusercontent.com/26596057/37747173-e548b574-2db8-11e8-89c2-be38a60898c0.png)
![image](https://user-images.githubusercontent.com/26596057/37747197-fa0d21ca-2db8-11e8-81f1-d8627744fa54.png)

**Comment by erha19** [comment]
@wilson-0422 version `1.0.8` has fixed this issue https://github.com/weexteam/weex-pack/commit/28f1586d1768977ce3fc8d2b651babc58694e48a#diff-4d5b473685d59f117bbf35d5ed6fdd30L23.
