### ISSUE TITLE
weex debug 开启 Network 后，控制面板 network 看不到数据

### ISSUE THREAD

**Issue by imfenghuang** [apache/incubator-weex-cli#346]
weex debug 开启 Network Monitor 后，控制面板 network 看不到数据
![_20180322171225](https://user-images.githubusercontent.com/20472384/37761301-3d256bda-2df4-11e8-9e96-7ed6496b1483.png)

**Comment by erha19** [comment]
@imfenghuang that's a bug in `Android playground`, it will fix in next version.

**Comment by AugTang** [comment]
现在修复好了吗 @erha19

**Comment by erha19** [comment]
@AugTang @imfenghuang it needs to extend image adapter on android, it will be fixed later,  and the document will tell you how to extend this feature, maybe next month.

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/38548239-dd92b11a-3ce3-11e8-97be-058af664efd4.png)
network还是看不到数据，大佬，这个是还没修复好，对吧
@erha19

**Comment by lijing666** [comment]
weex本身是一个很好的框架，但是更新和维护有种跟不上的节奏，用起来问题挺多，特别是playground希望能够做的更完善一下，network无法显示数据，样式无法编辑，切换vdom和native会失效等等，对于一个调试工具这些必备功能有太多的bug；另外对于Vue的一些功能，文档说支持，其实在web正常，在android和ios都无法使用，比如slot-scope还有事件冒泡行为 @erha19  不知道weex是怎么在规划呢？下一个版本会解决这些问题么？真心不想这个框架慢慢就做死了呀

**Comment by erha19** [comment]
@lijing666 That's right, there are problems with the tool or language support at Weex, the SDK team is busy with the next release, but the playground problem has already been scheduled to be repaired, and soon a new playground will come out. The roadmap of `weex` will be published next month, we are working on Apache way, you can follow the Apache mail list to subscribe to notifications and participate in discussions, see https://issues.apache.org/jira/projects/WEEX/issues/WEEX-367?filter=allopenissues.

**Comment by shangxinbo** [comment]
apache 的通讯方式就是落后

**Comment by delsedin** [comment]
@erha19  你好，请问安卓看不到network内容这个bug修复了吗

**Comment by cnryb** [comment]
I fix it in this pr https://github.com/weexteam/android-devtools-for-Apache-Weex/pull/75
