### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by Walker2020** [apache/incubator-weex-cli#347]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

node -version v8.9.3  npm version 5.7.1 
macbookpro 10.13.3
yarn add weex-toolkit 
error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".
error An unexpected error occurred: "Found incompatible module

**Comment by erha19** [comment]
@Walker2020 please use `npm` to install `weex-toolkit`.
