### ISSUE TITLE
Android设备安装Weex Playground App扫码weex debug没反应

### ISSUE THREAD

**Issue by chenkezhao** [apache/incubator-weex-cli#348]
weex-toolkit版本信息：
...>weex -v
   v1.2.9
 - weexpack : v1.1.7
 - weex-debugger : v1.0.7
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

**Comment by chenkezhao** [comment]
Weex Playground App版本：
![image](https://user-images.githubusercontent.com/15662369/37821287-2779d94a-2ebe-11e8-9274-9ddb1ee7faf3.png)

**Comment by erha19** [comment]
@chenkezhao you need to make sure your phone and the pc to be on the same LAN.

**Comment by chenkezhao** [comment]
谢谢！
