### ISSUE TITLE
外部引入js文件是否能使用es6

### ISSUE THREAD

**Issue by WangXiZhu** [apache/incubator-weex-cli#35]
外部  index.js

```
  export function log(){
     console.log('log info')
  }
```

.we文件中引入

```
require("./index.js");
module.exports = {
  init: function(){
    log();
  }
}

```

浏览器显示error : Unexpected token export

看到 weex-toolkit中 gulp的task中有 babel，不知道哪里有问题。  谢谢

**Comment by scyllarusllc** [comment]
weex.js的loaders 那里要配置一下

**Comment by Jinjiang** [comment]
是的，看这里 http://babeljs.io/docs/setup/#installation

**Comment by zjuwjf** [comment]
@Jinjiang 能否请教下 具体应该是如何配置 来支持
