### ISSUE TITLE
npm ERR! write after end

### ISSUE THREAD

**Issue by unclekitty** [apache/incubator-weex-cli#350]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

```
wsh9729@BZ37YZ1M2 MINGW64 ~/workspace
$ npm -v
5.8.0

wsh9729@BZ37YZ1M2 MINGW64 ~/workspace
$ node -v
v8.9.1

wsh9729@BZ37YZ1M2 MINGW64 ~/workspace
$ npm install -g weex-toolkit
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
```

**Comment by erha19** [comment]
@unclekitty you can delete the cache file on `/usr/local/lib/node_modules/weex-toolkit`, and then install `weex-toolkit` again, or try `npm i npm@4 -g`, that's a bug on `npm@5`.
