### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by zjxpcyc** [apache/incubator-weex-cli#352]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

weex version:  I have not installed
platform : win10
node:  v8.7.0
npm: 5.5.1

## The key error stack message.
```bash
C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\nan\nan.h(549): error C2039: 'New': is not a member of 'v8::String' (compiling source file ..\src\bufferutil.cc) 

[C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws\build\bufferutil.vcxproj]
  C:\Users\Administrator\.node-gyp\8.7.0\include\node\v8.h(2443): note: see declaration of 'v8::String' (compiling source file ..\src\bufferutil.cc)

C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\tomahawk\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\nan\nan.h(721): note: type is 'unknown-type' (compiling source file ..\src\bufferutil.cc)
```

```bash
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(403,5): error MSB3191: 无法创建目录“Release\obj\bufferutil\bufferutil.tlog\”。指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符。
```

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
`npm install --no-optional weex-toolkit -g`

**Comment by erha19** [comment]
@zjxpcyc see https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md#windows%E7%8E%AF%E5%A2%83%E4%B8%8Bnode-gyp-rebuild-%E9%94%99%E8%AF%AF-236.

**Comment by zjxpcyc** [comment]
@erha19 not use
