### ISSUE TITLE
npn run serve   提示语法错误？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#353]
我的语法按照weex标准来写的，为什么还报错，很不解。求指导。。。。
下面是我的代码与报错提示比较：
![image](https://user-images.githubusercontent.com/31499235/38186297-e01797bc-3684-11e8-84cd-d32b8ad7c03e.png)
@erha19

**Comment by erha19** [comment]
@AugTang That's `eslint` tips to helping you write code more verbally, you can change `useEslint` to be `{}`, like `const useEslint = {}` in `configs/webpack.common.js`.
