### ISSUE TITLE
'weex run ios' throw an error

### ISSUE THREAD

**Issue by HazySoda** [apache/incubator-weex-cli#354]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

```
$ weex -v

 v1.2.9
 - weexpack : v1.1.8
 - weex-builder : v0.3.18
 - weex-previewer : v1.4.8

$ node -v

v9.5.0

$ npm -v

5.8.0
```
Platform: MacOS 10.13.4

## The key error stack message.
$ weex run ios
18:46:17 : npm run build
/bin/sh: /Users/wildnode/.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/: No such file or directory
18:46:17 : Command run error, please check if there has the same issue here: https://github.com/weexteam/weex-toolkit/issues/337
18:46:17 : Error:Error: Command failed: /Users/wildnode/.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/ --unsafe-perm=true --allow-root
/bin/sh: /Users/wildnode/.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/: No such file or directory

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:562:12)

**Comment by li1xu1bin** [comment]
the same problem😂..any solution??

**Comment by MandyZhangMeng** [comment]
I also have this problem, can anyone help?

**Comment by erha19** [comment]
@KidneyFlower @li1xu1bin @MandyZhangMeng Try to run `weex update weexpack@latest`, version `1.1.10` should fix this issue.
