### ISSUE TITLE
weex-debugger 最新版，控制台信息

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#355]
优化建议：控制台这些无用信息能不能隐藏，这么多东西列出来，输出个东西，要去翻半天...

![image](https://user-images.githubusercontent.com/31499235/38225486-a42883f0-36e4-11e8-8ef3-f2d4bae1e235.png)
@erha19

**Comment by erha19** [comment]
It can be filter on next version.

**Comment by AugTang** [comment]
现在处理好了吗，控制台无法显示输出的信息，请求的接口无法在network查看
@erha19 
![image](https://user-images.githubusercontent.com/31499235/38464303-072fdaae-3b3e-11e8-8170-4d88f2421bd3.png)

**Comment by erha19** [comment]
@AugTang please upgrade to `v1.0.8`, you can filter log order the log level.

**Comment by ifelseboyxx** [comment]
@AugTang 能帮看看 #390  这个问题吗？
