### ISSUE TITLE
Vue Router + Device Back Button

### ISSUE THREAD

**Issue by ukik** [apache/incubator-weex-cli#359]
I've tried creating an application from weex-toolkit using vue-router. I am very happy with the results. but I found a strange performance on a real-device android phone.

when I go to the About page (vue-router) then press the BACK DEVICE button instead of returning to the Home page, weex application minimizes itself when pressed the BACK DEVICE button, should weex back to Home page.

**Comment by erha19** [comment]
@ukik using `vue-router` to build your page can only manage your page on a single instance context of `weex`, it isn't a good way to build an App on complex scene, so we do not recommend you to use this, as our suggestion, we recommend you to manage router on your own App router system.
