### ISSUE TITLE
无法打包mixin内容

### ISSUE THREAD

**Issue by finnome** [apache/incubator-weex-cli#360]
用这个脚手架生成的项目，无法打包mixin内容，请问如何解决吗？

**Comment by erha19** [comment]
@pcwang0205 please show your demo and describe in detail how to reproduce your problem.

**Comment by finnome** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/10112141/38654358-6b5df37a-3e41-11e8-9806-aed072c938b0.png)
This is old project, which can package the mixin.
But I use the new version of weex-toolkit, I can't package the mixin.
![image](https://user-images.githubusercontent.com/10112141/38654388-9cd12544-3e41-11e8-9a89-b4844dcc5cea.png)
![image](https://user-images.githubusercontent.com/10112141/38654396-a8fa1d08-3e41-11e8-99c7-f8d7ba2cdaf3.png)
