### ISSUE TITLE
weex-toolkit failed to install

### ISSUE THREAD

**Issue by ZhanweiXing** [apache/incubator-weex-cli#362]
i have installed node.js with the version of v8.11.1.when i execute " npm install weex-toolkit -g" in my macbookpro i received the errors as follows,anybody has met this error?

WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/webpack-92796c6e/package.json'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/webpack-92796c6e/LICENSE'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/webpack-92796c6e/README.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: karma@1.7.1 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/karma):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...dy-parser":"^1.12.4",'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esrecurse@4.2.1 (node_modules/weex-toolkit/node_modules/xtoolkit/node_modules/esrecurse):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/usr/local/lib/node_modules/.staging/esrecurse-dbf9307b'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: glob@7.1.2 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/globby/node_modules/glob):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/usr/local/lib/node_modules/.staging/glob-4be9a53d'

**Comment by erha19** [comment]
@ZhanweiXing These are npm warnings that do not affect the use of specific features, any details? like  `npm ERR ....`.

**Comment by ZhanweiXing** [comment]
thanks,here are the npm errors :
npm ERR! Unexpected end of JSON input while parsing near '..."memory-fs":"^0.4.1",'
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xing/.npm/_logs/2018-04-13T01_36_08_895Z-debug.log

**Comment by erha19** [comment]
@ZhanweiXing it looks like the `npm` installing issue, you can try to use `npm i npm@4 -g` to update your `npm` to version 4, then try to install `weex-toolkit` again.

**Comment by ZhanweiXing** [comment]
i have installed with the npm's version of 4.6.1
