### ISSUE TITLE
weex debug Error: Cannot find module 'ora'

### ISSUE THREAD

**Issue by guo-meng-jie** [apache/incubator-weex-cli#364]

**Comment by erha19** [comment]
@guo-meng-jie 
run following command to remove cache file:
```
rm -rf ~/.xtoolkit/node_modules/weex-debugger
```
then run the command `weex debug` again, you may not install the `weex-debugger` correctly.

**Comment by erha19** [comment]
Same issues here https://github.com/weexteam/weex-toolkit/issues/363#issuecomment-381468285.

**Comment by erha19** [comment]
@guo-meng-jie I found the `ora` source index is missing on `npm-shrinkwrap.json`, it may cause the module not installed correctly with npm@4, I fix it on version `weex-debugger@1.0.11`.

**Comment by guo-meng-jie** [comment]
@erha19  The npm4.6 I installed before, I later changed to a pure system, and then reinstalled it successfully.
