### ISSUE TITLE
Vuex 在 web 上和原生机器上使用冲突

### ISSUE THREAD

**Issue by you85630** [apache/incubator-weex-cli#365]
在store/index.js中
```
import Vue from 'vue'    // 这一句
import Vuex from 'vuex'
Vue.use(Vuex)
```
如果import Vue，那么就web正常，原生报错 
```
jsLog:TypeError:undefined is not an object (evaluating 'this.$store.state')
```

如果不import Vue，那么就原生正常，web报错
```
ReferenceError: Vue is not defined
```

具体原因，分析不出,求解答

**Comment by erha19** [comment]
@you85630  you can see the latest weex official project, try to install `weex-toolkit`, use `weex create` command to create a `vue-router` project, you can see the project to learn how to do this, the native do not need `Vue` environment, it should be removed on native entry file.

**Comment by you85630** [comment]
解决了，自己找到了答案，需要在整体先注入store.js，在页面中使用的时候加上`default`

**Comment by leaven** [comment]
解决办法

修改webpack.common.js中的`getEntryFile`，对store.js进行处理，加入vue的依赖，参考webpack.common.js中的`getRouterFileContent`或者`getEntryFileContent`代码。

作为一个新人很容易遇到这个bug，建议readme.md中加一下说明。

另外这种处理方式有些黑盒，缺少规范，更好的方式是加入一个规范，比如`requireWeb、requireNA`这样的词法，在编译阶段进行统一处理。

**Comment by erha19** [comment]
@you85630 @leaven Your suggestion is good, maybe you can create a pull request to [weex-templates](https://github.com/weex-templates/webpack) and show your changes, and you can be one of a contributor of weexteam, thanks!
