### ISSUE TITLE
Cannot find module 'ora'

### ISSUE THREAD

**Issue by chendongMarch** [apache/incubator-weex-cli#366]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] node -v 8.8.0 npm -v 4.6.1 and 5.8.0 
- [x] weex update weex-debugger@latest 
- [x] have same issue but not work for me

## Your development environment
- weex-toolkit  v1.3.3
- platform Mac

![image](https://user-images.githubusercontent.com/11373923/38845932-62abb002-422c-11e8-97bb-30d6d4b92fb7.png)

## The key error stack message.

command `weex debug src/home-index-weex.vue` Error: Cannot find module 'ora'

weex -v warning me: npm 5 is not supported yet!  but npm@4 also not work

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

run command `weex debug src/home-index-weex.vue`

**Comment by erha19** [comment]
@chendongMarch same issue https://github.com/weexteam/weex-toolkit/issues/364.
