### ISSUE TITLE
weex-builder webpack config parameter

### ISSUE THREAD

**Issue by seanxux** [apache/incubator-weex-cli#369]
I found `weex-builder` have added new feature: specify webpack config file parameter. 
> weex-builder.js
> option('-c,--config [path]', 'compile with a config file')

Only `weex-preview` support this feature right now. 
When will `weex compile` and `weex debug` support this parameter.
We really need this feature.

**Comment by erha19** [comment]
@seanxux `weex compile` command supports this option, and I will support this feature on `weex debug` on next version, it should be released on this week.

**Comment by erha19** [comment]
@seanxux Upgrade your packages, it's supported on all toolkit now.
