### ISSUE TITLE
继续讨论，webstorm集成的terminal里生成的二维码太大太大了，希望能小一点。

### ISSUE THREAD

**Issue by mqhe2007** [apache/incubator-weex-cli#37]
不仅太大，而且变形，导致手机的playground一直扫描不成功。
[预览图](http://qingjin.me/wp-content/uploads/2016/12/QQ%E6%88%AA%E5%9B%BE20161223111146.png)

如果在命令行里生成二维码有局限，是否可以考虑弹出带二维码的网页呢？

**Comment by exolution** [comment]
beta版已经废弃了该功能 变成了弹出带二维码的网页 近期会发正式版
