### ISSUE TITLE
weex create plugin: Cannot find module 'generator-weex-plugin'

### ISSUE THREAD

**Issue by tralves** [apache/incubator-weex-cli#371]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [X] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [X] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [X] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
```
$ weex -v
   v1.3.4
 - weexpack : v1.2.1
 - weex-debugger : v1.0.11
 - weex-builder : v0.3.19
 - weex-previewer : v1.5.0
```
- platform (Win/Mac/Ubuntu..)
Mac

## The key error stack message.
```
11:51:33 : Error: Cannot find module 'generator-weex-plugin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at init (/Users/tralves/.xtoolkit/node_modules/weexpack/lib/plugin/create.js:13:24)
    at Command.program.command.option.description.action (/Users/tralves/.xtoolkit/node_modules/weexpack/bin/weexpack-plugin.js:33:5)
    at Command.listener (/Users/tralves/.xtoolkit/node_modules/weexpack/node_modules/commander/index.js:315:8)
(...)
```

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
```
weex plugin create weex-my-plugin
```

I tried:
- Using with both npm 4 and 5
- Installing `generator-weex-plugin` globally
- Re-installing weex-toolkit

I don't know how to fix it. Help?
Thanks!

**Comment by erha19** [comment]
@tralvesHI, you can upgrade `weexpack` to v1.2.2, the project has been refactored, you can using `weex update weexpack` command to upgrade your weexpack.

**Comment by tralves** [comment]
@erha19 It upgraded to 1.2.3 and is working now. 

BTW, I had to manually delete `~/.xtoolkit` in order to install... weird.

Anyway, thanks!

**Comment by tralves** [comment]
@erha19 Where is the template coming from? It doesn't seem like the one in `weexteam/generator-weex-plugin`.

I found some things that could be improved like "WeexLottie" references, missing .podspec and maybe add some scripts that existed in the previous version (e.g. `npm run start:native`).

I want to PR stuff!
