### ISSUE TITLE
新创建的weex工程  运行weex preview src/index.vue  直接报错......

### ISSUE THREAD

**Issue by y-cares** [apache/incubator-weex-cli#372]
weex的版本：
![image](https://user-images.githubusercontent.com/20083236/38908005-fb0b1c1a-42f0-11e8-8a98-984add1c0c51.png)

报错信息：
![image](https://user-images.githubusercontent.com/20083236/38908166-94fc4f24-42f1-11e8-8c90-0c20dcced580.png)

请问  这是什么情况？！

**Comment by erha19** [comment]
@y-cares the preview cannot know the `@` alias, maybe you can process your `webpack` config file using `-c ./webpack.conf.js` or change the alias to a relative path.

**Comment by y-cares** [comment]
@erha19 
木有 @ 符号
![image](https://user-images.githubusercontent.com/20083236/38909690-4ad5e930-42f8-11e8-92b1-9ede8cc5653c.png)

**Comment by erha19** [comment]
@y-cares it is in your source code, like `./src`.

**Comment by y-cares** [comment]
@erha19   新创建的项目  没有填写任何代码
是生成的项目就自动带有的吧？
那你们改一下项目模板，岂不是更好啊？
大佬
