### ISSUE TITLE
weex-playground打开2个不同的链接，却显示同一个页面

### ISSUE THREAD

**Issue by y-cares** [apache/incubator-weex-cli#373]
安卓手机打开2个不同的链接  却显示同一个项目的页面，这是为什么？
链接分别是：
1. http://192.168.99.122:8081/?hot-reload_controller&page=index.js&loader=xhr&wsport=8082&type=vue
页面为：
![image](https://user-images.githubusercontent.com/20083236/38909046-7cf78bba-42f5-11e8-8075-c4afa687c556.png)

2. http://192.168.99.122:8083/?hot-reload_controller&page=index.js&loader=xhr&wsport=8084&type=vue
页面为：
![image](https://user-images.githubusercontent.com/20083236/38909065-91cbf472-42f5-11e8-9514-1a60ee307eec.png)

用同yi一个手机打开这2个链接，却都显示：
![image](https://user-images.githubusercontent.com/20083236/38909202-356f1640-42f6-11e8-83ca-816027086498.png)

ios手机也是同样的结果...
这是怎么回事？？？

**Comment by erha19** [comment]
@y-cares this two page has the same name? The preview page will detect the URL params on `page=index.js`, you choose the same bundle name, so the QR code will get the same result.

**Comment by y-cares** [comment]
@erha19  但是如果我只启动一个项目的服务   应该就不会出现这种情况吧？
我只启动第一个链接的服务，而不启动第二个链接的服务，但是用weex playground 扫出来的页面依然是第二个链接的页面？   这是怎么回事？？？

**Comment by y-cares** [comment]
@erha19    就算我都命名index.vue  但是端口号是不一样的啊......

**Comment by erha19** [comment]
@y-cares it using the same system file folder, so the new one will replace the old one.

**Comment by y-cares** [comment]
@erha19    那  按照你的说法   我们现在没想创建一个新的项目，都要把新创建的项目下自动生成的index.vue文件重新命名？   那岂不是很麻烦...
如果我要改之前的老的项目，岂不是要全改？  而且用手机打开还是空白，在同一个WiFi下的...

**Comment by y-cares** [comment]
@erha19   新的会取代旧的话   我又新建的一个新项目，运行起来，还是没有取代旧的页面。同样都为index.vue的命名

**Comment by y-cares** [comment]
@erha19   大佬  这个问题怎么搞？！  求解答...

**Comment by y-cares** [comment]
@erha19      改了文件名，打开之后，报这个错是什么原因？
![image](https://user-images.githubusercontent.com/20083236/38965292-6aa5fd84-43ae-11e8-95c7-1d7a9c3ddbb7.png)
