### ISSUE TITLE
新创建的项目，weex-playground apps扫描QR码后，报错...

### ISSUE THREAD

**Issue by y-cares** [apache/incubator-weex-cli#375]
weex版本：
![image](https://user-images.githubusercontent.com/20083236/38973839-3a52a278-43da-11e8-9454-1b815c88e563.png)

已将“@”改成相对路径
![image](https://user-images.githubusercontent.com/20083236/38973846-47d7a146-43da-11e8-851f-6048627a6819.png)

页面显示正常，无报错...
![image](https://user-images.githubusercontent.com/20083236/38973864-537c3188-43da-11e8-8e8d-8aa0332b8e0b.png)
![image](https://user-images.githubusercontent.com/20083236/38973914-8a7b4084-43da-11e8-9fca-d74703c77616.png)

但是点击QR码之后，却显示异常
![image](https://user-images.githubusercontent.com/20083236/38973955-b045c0c8-43da-11e8-9bdb-bc793d9729bd.png)

weex-playground扫描QR码之后，显示异常：
![image](https://user-images.githubusercontent.com/20083236/38974081-3f602910-43db-11e8-9239-f3b48de6b562.png)

请问，这是什么原因？？？

**Comment by erha19** [comment]
@y-cares If you are using project create by `weex-toolkit`, you don't need to use `weex preview` anymore, you can just run `npm start` on your project, it will generate a better page for you to preview.

**Comment by y-cares** [comment]
@erha19   那么说，以后的项目预览，都是通过npm run start就可以了？ 用weex-playground预览，也是可以的？？！！！

**Comment by y-cares** [comment]
@erha19  对了  npm run start 不是默认打开index.vue页面的吗？
如果我想打开这个项目里面的另一个vue页面
请问怎么打开？ 用navigator模块跳转跳的是个js
而且  我怎么在weex-playground预览效果？
