### ISSUE TITLE
weex中.vue子组件（一级组件）再引用别的组件（二、三级组件）打包报错问题。

### ISSUE THREAD

**Issue by y-cares** [apache/incubator-weex-cli#380]
weex版本：
![image](https://user-images.githubusercontent.com/20083236/39110892-7b4a1788-4705-11e8-82ca-0e803c43e831.png)

bug重现：
我给一级vue子组件，引用二级vue子组件，运行 npm run start 时，展示正常，但是打包时（weex compile src/index.vue bundle），报错：
![image](https://user-images.githubusercontent.com/20083236/39111001-e9134f96-4705-11e8-93b2-97741e585b5d.png)
请问，这是为什么？  难道不支持一级子组件再引用二三级子组件？？？

**Comment by erha19** [comment]
@y-cares maybe you should use `./components/switch-btn.vue` while using `weex-builder`, and you can run `npm run build` or `npm run build:prod` to bundle your source code.
