### ISSUE TITLE
weex-toolkit 安装失败

### ISSUE THREAD

**Issue by JS-mark** [apache/incubator-weex-cli#381]
全局安装weex-toolkit 失败
![image](https://user-images.githubusercontent.com/31335385/39168067-01ea57ca-47c5-11e8-8f1a-bb13d5c64ca0.png)
node版本：8.9.4
npm：5.6.0

**Comment by erha19** [comment]
@Jack-In Try to use `npm@4` to install `weex-toolkit`, run `npm i npm@4 -g` first, then run `npm i weex-toolkit -g --no-optional` again.

**Comment by JS-mark** [comment]
@erha19 能阐述下 出现这种情况的原因吗 ？  之前使用过npm5.6版本安装成功，为什么这次不行呢？

**Comment by erha19** [comment]
@Jack-In The `npm@5` is easy to meet mismatch problem while upgrading your package from an old version, otherwise you are using a clean `npm` environment. You can see the knowing issue from here https://github.com/npm/npm/issues/16991.
