### ISSUE TITLE
weex -v提示未安装

### ISSUE THREAD

**Issue by JimmyKent** [apache/incubator-weex-cli#382]
![2018-04-24 20-37-19](https://user-images.githubusercontent.com/17265973/39187289-7b9e51d6-47ff-11e8-8dc8-4b78f829d48f.png)
![2018-04-24 17-28-45](https://user-images.githubusercontent.com/17265973/39178746-101bd7d6-47e5-11e8-98f4-fca82830fe77.png)
node -v
v8.11.1
npm -v
6.0.0

**Comment by erha19** [comment]
@JimmyKent Try to use `npm@4` to install `weex-toolkit` or re-install your node environment, that seems your environment cause it.
