### ISSUE TITLE
weex build android 没反应

### ISSUE THREAD

**Issue by Aibric** [apache/incubator-weex-cli#383]
## Your development environment
$ weex -v
   v1.3.4
 - weexpack : v1.2.3
 - weex-builder : v0.3.19
 - weex-previewer : v1.5.0

- platform (Win/Mac/Ubuntu..)
win 10
## The key error stack message.
无错。

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

$ weex build android

![image](https://user-images.githubusercontent.com/2859844/39225673-46f8776e-4880-11e8-80e7-cee32154e5ad.png)

不动了，没有任何反应。。。

**Comment by erha19** [comment]
@Aibric you can run `weex build android --verbose` to see the detail log message.

**Comment by Aibric** [comment]
@erha19 `weex build android --verbose` 没有反应一样卡死不动。。。

**Comment by erha19** [comment]
@Aibric you can run `npm run build:prod` success on your project?

**Comment by Aibric** [comment]
![image](https://user-images.githubusercontent.com/2859844/39280989-03d0dffc-4935-11e8-8cfa-90db3e4569b1.png)

@erha19 谢谢，还是卡死不动。。。没有任何提示。 是不是 platform android  源文件有问题。。。

`weex run android` 是没有问题。。。

**Comment by erha19** [comment]
@Aibric can you share your project on a GitHub repo? maybe your project is too large for the webpack to compile with a little times.

**Comment by Aibric** [comment]
@erha19 ` https://github.com/Aibric/weex-m.git `  谢谢，还有files://assets/ 本地图片读取不到。谢谢。

**Comment by CiaoSom** [comment]
![image](https://user-images.githubusercontent.com/30862529/45339721-5f310400-b5c6-11e8-864c-4f701590d2e7.png)
![image](https://user-images.githubusercontent.com/30862529/45339749-73750100-b5c6-11e8-82fe-0cbba2f34128.png)
这里已经把安卓的配置文件改了，但是执行weex run android的之后最后下载的路径错误了，这是为什么，在哪里可以改这个路径

**Comment by hejinalex** [comment]
升级Node.js,我的Node.js在8.x的时候和你一样的情况，升级到11.x就可以了。

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
