### ISSUE TITLE
weex-debugger能否支持直接调试目录？

### ISSUE THREAD

**Issue by seraphlee** [apache/incubator-weex-cli#384]
例如dist目录下有很多已经打包好的js文件（没有通过weexbuilder打包），但是运行weex debug dist会报错，能否支持一下这个功能？

**Comment by erha19** [comment]
@seraphlee this feature will be considered in next version and if you have some idea to fit the code, you can create a pull request to [weexteam/weex-debugger](https://github.com/weexteam/weex-debugger) and I will review it as soon as possible.
