### ISSUE TITLE
关于weex支持ios版本问题

### ISSUE THREAD

**Issue by y-cares** [apache/incubator-weex-cli#385]
请问一下，weex支不支持ios9.3的系统？
为什么我写的逻辑安卓和ios10以上的手机上，都能正常触发点击事件和计算逻辑，但是在ios9.3上面却没有任何的效果？
普通安卓机：
![image](https://user-images.githubusercontent.com/20083236/39235685-2e62d54a-48a9-11e8-9c83-46f9f4eb640c.png)

ios9.3
![image](https://user-images.githubusercontent.com/20083236/39235711-408733a6-48a9-11e8-94bd-a85e709cfbf6.png)

**Comment by erha19** [comment]
@y-cares weex bug report, see http://weex.apache.org/bug-report-guidelines.html.
