### ISSUE TITLE
weex-toolkit 1.3.5 安装报错 Node@8.11.1

### ISSUE THREAD

**Issue by rawbin-** [apache/incubator-weex-cli#388]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`). 
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

## The key error stack message.
$ npm install -g weex-toolkit
events.js:183░░░░░░⸩ ⠴ extract:ajv: sill extract signal-exit@3.0.2
      throw er; // Unhandled 'error' event
      ^

Error: sha512-0aP01LLIskjKs3lq52EC0aGBAJhLq7B2Rd8HC/DR/PtNNpcLilNmHC12O+hu0usQpo7wtHNRqtrhBwtDb0+dNg== integrity checksum failed when using sha512: wanted sha512-0aP01LLIskjKs3lq52EC0aGBAJhLq7B2Rd8HC/DR/PtNNpcLilNmHC12O+hu0usQpo7wtHNRqtrhBwtDb0+dNg== but got sha512-rKC3+DyXWgK0ZLKwmRsrkyHVZAjNkfzeehuFWdGGcqGDTZFH73+RH6S/RDAAxl9GusSjZSUWYLmT9N5pzXFOXQ==. (2875 bytes)
    at Transform.on (/Users/zhangliao/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
WARN tarball tarball data for sntp@https://registry.npmjs.org/sntp/-/sntp-0.1.4.tgz (sha512-FL1b58BDrqS3A11lJ0zEdnJ3UOKqVxawAkF3k7F0CVN7VQ34aZrV+G8BZ1WC9ZL7NyrwsW0oviwsWDgRuVYtJg==) seems to be corrupted. Trying one more time.
WARN notice [SECURITY] lodash has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.17.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] hawk has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=hawk&version=0.10.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN tarball tarball data for babel-eslint@8.2.1 (sha512-Qt2lz2egBxNYWqN9JIO2z4NOOf8i4b5JS6CFoYrOZZTDssueiV1jH/jsefyg+86SeNY3rB361/mi3kE1WK2WYQ==) seems to be corrupted. Trying one more time.
WARN notice [SECURITY] hoek has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=0.7.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN tarball tarball data for request@https://registry.npmjs.org/request/-/request-2.83.0.tgz (sha512-8H7Ehijd4js+s6wuVPLjwORxD4zeuyjYugprdOXlPSqaApmL/QOy+EB/beICHVCHkGMKNh5rvihb5ov+IDw4mg==) seems to be corrupted. Trying one more time.
WARN tarball tarball data for supports-color@https://registry.npmjs.org/supports-color/-/supports-color-4.4.0.tgz (sha512-0aP01LLIskjKs3lq52EC0aGBAJhLq7B2Rd8HC/DR/PtNNpcLilNmHC12O+hu0usQpo7wtHNRqtrhBwtDb0+dNg==) seems to be corrupted. Trying one more time.

$ npm install -g weex-toolkit
events.js:183░░░░░░⸩ ⠦ extract:babylon: sill extract signal-exit@3.0.2
      throw er; // Unhandled 'error' event
      ^

Error: sha512-0aP01LLIskjKs3lq52EC0aGBAJhLq7B2Rd8HC/DR/PtNNpcLilNmHC12O+hu0usQpo7wtHNRqtrhBwtDb0+dNg== integrity checksum failed when using sha512: wanted sha512-0aP01LLIskjKs3lq52EC0aGBAJhLq7B2Rd8HC/DR/PtNNpcLilNmHC12O+hu0usQpo7wtHNRqtrhBwtDb0+dNg== but got sha512-rKC3+DyXWgK0ZLKwmRsrkyHVZAjNkfzeehuFWdGGcqGDTZFH73+RH6S/RDAAxl9GusSjZSUWYLmT9N5pzXFOXQ==. (2875 bytes)
    at Transform.on (/Users/zhangliao/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
WARN notice [SECURITY] hawk has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=hawk&version=0.10.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN tarball tarball data for babel-eslint@8.2.1 (sha512-Qt2lz2egBxNYWqN9JIO2z4NOOf8i4b5JS6CFoYrOZZTDssueiV1jH/jsefyg+86SeNY3rB361/mi3kE1WK2WYQ==) seems to be corrupted. Trying one more time.
WARN notice [SECURITY] lodash has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.17.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN tarball tarball data for hawk@https://registry.npmjs.org/hawk/-/hawk-0.10.2.tgz (sha512-miowhl2+U7Qle4vdLqDdPt9m09K6yZhkLDTWGoUiUzrQCn+mHHSmfJgAyGaLRZbPmTqfFFjRV1QWCW0VWUJBbQ==) seems to be corrupted. Trying one more time.
WARN tarball tarball data for sntp@https://registry.npmjs.org/sntp/-/sntp-0.1.4.tgz (sha512-FL1b58BDrqS3A11lJ0zEdnJ3UOKqVxawAkF3k7F0CVN7VQ34aZrV+G8BZ1WC9ZL7NyrwsW0oviwsWDgRuVYtJg==) seems to be corrupted. Trying one more time.
WARN notice [SECURITY] hoek has 1 moderate vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=0.7.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN tarball tarball data for hoek@https://registry.npmjs.org/hoek/-/hoek-0.7.6.tgz (sha512-QLg82fGkfnJ/4iy1xZ81/9SIJiq1NGFUMGs6ParyjBZr6jW2Ufj/snDqTHixNlHdPNwN2RLVD0Pi3igeK9+JfA==) seems to be corrupted. Trying one more time.
WARN tarball tarball data for babel-eslint@8.2.1 (sha512-Qt2lz2egBxNYWqN9JIO2z4NOOf8i4b5JS6CFoYrOZZTDssueiV1jH/jsefyg+86SeNY3rB361/mi3kE1WK2WYQ==) seems to be corrupted. Trying one more time.
WARN tarball tarball data for supports-color@https://registry.npmjs.org/supports-color/-/supports-color-4.4.0.tgz (sha512-0aP01LLIskjKs3lq52EC0aGBAJhLq7B2Rd8HC/DR/PtNNpcLilNmHC12O+hu0usQpo7wtHNRqtrhBwtDb0+dNg==) seems to be corrupted. Trying one more time.

**Comment by erha19** [comment]
@rawbin- looks like you have been install `weex-toolkit` before? try to uninstall it or remove it manually,  or using `npm@4` to install our toolkit would be a better choice.

**Comment by rawbin-** [comment]
@erha19 yes, I have installed weex@1.2.9  and I want to install 1.3.5 and it fails on npm 5.x and npm 6.x
I am using the npm-check to update global packages all the time,but fail on weex; 
I uninstall the previous version and reinstall 1.3.5, and it works.
