### ISSUE TITLE
weex不支持echarts吗？

### ISSUE THREAD

**Issue by you85630** [apache/incubator-weex-cli#389]
项目中需要用到图表，但是发现Weex Market中的weex-chart已经不维护了，echarts引入后只支持web端，ios端报``` this.dom.getContext is not a function```，想求助下，有weex可用的图表库或者插件吗？

**Comment by erha19** [comment]
@you85630 that's not a toolkit issue, you can go to weex mail list to asking for help, as I know, `echarts` can be work on `<web>` components on weex.
