### ISSUE TITLE
weex debug 命令空白，weex debug xx.vue 可以正常调试

### ISSUE THREAD

**Issue by ifelseboyxx** [apache/incubator-weex-cli#390]
![](http://p0kmbfoc8.bkt.clouddn.com/77777.gif)

**Comment by ifelseboyxx** [comment]
`npm` - 4.61
`node` - v8.11.1
![](http://p0kmbfoc8.bkt.clouddn.com/xx1.png)

**Comment by erha19** [comment]
@ifelseboyxx If you want to see the view all the time, you need to click on `Element` panel and reload the page.
