### ISSUE TITLE
 npm install -g weex-toolkit 报错

### ISSUE THREAD

**Issue by cccisbug** [apache/incubator-weex-cli#391]
macOS Serria 10.12.6
source:taobao
node -v
v10.1.0
npm -v
6.0.1

when in node v9,exec error

npm ERR! Unexpected end of JSON input while parsing near '...ze":6182,"noattachmen'

then i  upgrade node v10
but  exec  that

33868 timing action:extract Completed in 2686ms
33869 verbose unlock done using /Users/***/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
33870 timing stage:rollbackFailedOptional Completed in 4ms
33871 timing stage:runTopLevelLifecycles Completed in 10501ms
33872 warn optional SKIPPING OPTIONAL DEPENDENCY: eslint@4.17.0 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/eslint):
33873 warn optional SKIPPING OPTIONAL DEPENDENCY: cancel after 1 retries!
33874 verbose type ProcessTerminatedError
33875 verbose stack ProcessTerminatedError: cancel after 1 retries!
33875 verbose stack     at Farm.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:87:25)
33875 verbose stack     at Array.forEach (<anonymous>)
33875 verbose stack     at Farm.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:81:36)
33875 verbose stack     at ontimeout (timers.js:427:11)
33875 verbose stack     at tryOnTimeout (timers.js:289:5)
33875 verbose stack     at listOnTimeout (timers.js:252:5)
33875 verbose stack     at Timer.processTimers (timers.js:212:10)
33876 verbose cwd /Users/***
33877 verbose Darwin 16.7.0
33878 verbose argv "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "weex-toolkit"
33879 verbose node v10.1.0
33880 verbose npm  v6.0.1
33881 error cancel after 1 retries!
33882 verbose exit [ 1, true ]

**Comment by cccisbug** [comment]
after chomd777 and  unuse sudo ，that error also

**Comment by erha19** [comment]
@cccisbug try to delete `/usr/local/lib/node_modules/weex-toolkit` or using `npm@4` to install the package, you can downgrade by `npm i npm@4 -g`.

**Comment by cccisbug** [comment]
@erha19 thanks, change computer then done
