### ISSUE TITLE
weex-toolkit 在docker中create一个demo项目命令行会卡住

### ISSUE THREAD

**Issue by luckzhiwei** [apache/incubator-weex-cli#392]
我是一个weex的初学者,
然后根据 [官方教程](https://weex.incubator.apache.org/cn/guide/index.html) 
我pull 了一个node的docker image,tag是8.1.0,然后用这个命令启动了一个容器,在容器中输入
npm config set registry http://registry.npm.taobao.org/ 
npm install weex-toolkit -g
weex create awesome-app
然后会提示我输入项目的名称,然后就卡住了，ctrl+c都不能动,截图如下
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fren994ox0j30v8094k0b.jpg)

我后来换了node:6.14.2 镜像就可以了,想请问下weex团队这是为什么,是weex-toolkit在node 8.0有问题吗？谢谢

**Comment by erha19** [comment]
@luckzhiwei I have tested on my platform using node@8.1.0, it can be work fine, maybe that's a docker issue, hope you can provide more information about this issue.

**Comment by erha19** [comment]
@luckzhiwei I found the issue here https://github.com/SBoudrias/Inquirer.js/issues/547, that's because the Node 8.1.0 breaks the behavior when using nested/subsequent calls, you should not use this version and it has been fixed on Node@8.1.2.

**Comment by luckzhiwei** [comment]
Yes,I try the node:@8.1.2 , the problem is sloved.Thankyou
