### ISSUE TITLE
指定src下特定目录作为页面目录，发生了异常

### ISSUE THREAD

**Issue by overarchingSky** [apache/incubator-weex-cli#394]
现想尝试在项目src目录下指定pages文件夹（其中包含index.vue）作为页面目录，本欲通过在webpack.common.conf.js中给getEntryFile 方法传递参数‘pages’来实现，但发现最终生成的js bundle路径为pages\index.js，导致到playground中预览失败：
```
fs.readdirSync(directory).forEach(file => {
...
   if (stat.isFile() && extname === ".vue") {
	const name = path.join(dir, path.basename(file, extname));
...
```
在将name 中\替换为/即能正常工作。望能修复！

**Comment by erha19** [comment]
@overarchingSky you can re-create your project, it would be work now.
