### ISSUE TITLE
weex run web 无法自动打开浏览器Google Chrome

### ISSUE THREAD

**Issue by wuqingnan** [apache/incubator-weex-cli#395]
node: v8.11.2
npm: 5.6.0

## Your development environment
platform: win7 / win10
weex: v1.3.5
weexpack: v1.2.3
weex-builder: v0.4.0
weex-previewer: v1.5.1

执行命令：weex run web
无法自动打开浏览器Google Chrome

信息：
activeUnable to open browser. If you are running in a headless environment, please do not use the open flag.

**Comment by erha19** [comment]
@wuqingnan maybe you don't have the right permission to control your browser with command, try to fix it or you can copy the link from console to the browser then open it by manually.

**Comment by wuqingnan** [comment]
已经找到原因：是由于自动调起浏览器的打开地址中有“|”导致的。
具体文件：configs/webpack.dev.conf.js  --->postMessageToOpenPage 使用“|"拼接entry
`
  if(entrys.length > 1) {
    openpage += `&entrys=${entrys.join('|')}`
  }
`
可以修改devServer中的openPage为encodeURI(openPage)解决问题
`
openPage: encodeURI(openPage),
`

**Comment by erha19** [comment]
@wuqingnan thanks for your report, maybe you can create a pull request to fix this issue.,https://github.com/weex-templates/webpack.
