### ISSUE TITLE
修改 config 设置项时发生误操作, 会有何影响? 若有则如何消除影响?

### ISSUE THREAD

**Issue by parrotdance** [apache/incubator-weex-cli#396]
## Your development environment
- weex-toolkit verison (Run `weex -v`)
```
$ weex -v
   v1.3.6
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
- platform (Win/Mac/Ubuntu..)
Mac
## The key error stack message.
Not error happend, temporarily.

## Steps to reproduce the problem.
I am a chinese developer, when I **first time** run <code>weex -v</code> it shows 2 options to choose package source, and I select npm, now I want to toggle the source to cnpm but input wrong parameters, like <code>weex config set registry "https://www.example.com"</code>. After that, when I run <code>weex config</code>, it shows: 
```
$ weex config
telemetry = true
registry = "https://www.example.com"
set = "registry"
```
It seems like affects nothing? But now I hope to remove the 'useless' option: 'set'.

**Comment by erha19** [comment]
@parrotdance the registry should be `https://registry.npm.taobao.org/` or `https://registry.npmjs.org/`, you can run `weex config registry https://registry.npm.taobao.org/` or go to `~/.xtoolkit/config.json` to edit it by manually.

**Comment by parrotdance** [comment]
@erha19 Thanks for help, I have solve this problem.
