### ISSUE TITLE
执行weex run ios 报错

### ISSUE THREAD

**Issue by iOSGL** [apache/incubator-weex-cli#398]
报错信息：
Error:You may had custome your XCode Deviced Data path, please use `--iosBuildPath` to set your path.

**Comment by erha19** [comment]
@geng199200 As the error says, you may customise your `XCode Derived Data` path, you can figure out at the `Preferences->Locations->Derived Data` setting of `XCode`, then put the path into the `--iosBuildPath` option, like `weex run ios --iosBuildPath /User/xx/....`.

**Comment by iOSGL** [comment]
@erha19 好的 谢谢
