### ISSUE TITLE
安卓运行时 异常

### ISSUE THREAD

**Issue by menkeydyvh** [apache/incubator-weex-cli#399]
这个 vue的引用没了   import Vue from 'vue';  缺少了；

weex -v
   v1.3.8
 - weexpack : v1.2.3
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

![image](https://user-images.githubusercontent.com/20472494/40482158-5669f246-5f86-11e8-8c52-b9229e0d28bf.png)

![image](https://user-images.githubusercontent.com/20472494/40482124-3d879ce2-5f86-11e8-802f-4450b37f803f.png)

**Comment by erha19** [comment]
@menkeydyvh you can re-create your project now, it was a mistake by the last commit, solved now.
