### ISSUE TITLE
执行weex run ios 报错

### ISSUE THREAD

**Issue by mario-huang** [apache/incubator-weex-cli#400]
项目名称已经不是默认的WeexDemo。但是weex还是去找该名字的项目。
Error:Error: ENOENT: no such file or directory, open '/Users/xxx/Documents/xxx/platforms/ios/WeexDemo/WeexDemo-Info.plist'
是否有配置文件可以自定义项目名？

- weex-toolkit verison (v1.3.8)
- platform (Mac)

**Comment by erha19** [comment]
@myeveryheart for now, the platform project that creates by `weex-toolkit` just use to preview your page on the device, we have the plan to rebuild it, but for now, if you want to change it, you need to control the project by yourself.

**Comment by mario-huang** [comment]
@erha19 I see, thank you. Hope to see it soon.
