### ISSUE TITLE
'payment.js from UglifyJs\nUnexpected token: punc (() 

### ISSUE THREAD

**Issue by ho2xing** [apache/incubator-weex-cli#404]
weex-toolkit  v1.3.8
 weexpack : v1.2.3
 weex-builder : v0.4.0
 weex-previewer : v1.5.1

 weex compile D:/android/workspace/weex-src/ D:/www/vue/weex/ -m

执行以上指令报错
'payment.js from UglifyJs\nUnexpected token: punc (() [payment.js:1138,5]',

如何解决？

**Comment by fumpierrez** [comment]
What's the content of your .babelrc file? looks like you might not have the right preset sets at all.

**Comment by erha19** [comment]
@ho2xing  as same as @fumpierrez  say, maybe you should config a `.babelrc` on your file path, like:

```
{
  "presets": [
    "es2015",
    "stage-0"
  ]
}
```
It works well on the mac without this configuration, maybe that's an issue on windows, try it and I need your feedback.
