### ISSUE TITLE
Plans to support Vue CLI 3.0 ?

### ISSUE THREAD

**Issue by n3ps** [apache/incubator-weex-cli#405]
Now that Vue CLI 3.0 is in beta and closer to getting "production ready", any plans to support it with Weex? Perhaps as a plugin?

Just some of the features of the latest Vue CLI:

- No lock in, as plugins can be added at any point in the development lifecycle
- Zero config plugins allow you to spend time developing rather than configuring
- Easy to upgrade, as configuration can be customized without “ejecting”
- Allows developers to make their own plugins and presets

**Comment by erha19** [comment]
@n3ps Yes, currently I am developing the 2.0 version of `weex-toolkit`. This version is expected to implement the features you mentioned above. At the same time, it will also make our plugin more stable and reliable (by adding tests).

I will push the code next week, maybe you can join us in some design of the tool.

**Comment by yordis** [comment]
@erha19 is there any reason why `@vue/cli` and `weex-toolkit` can't be merge together?

In terms of architecture from CLI perspective both projects could follow something like https://github.com/infinitered/gluegun plugin system and so on

**Comment by yordis** [comment]
@erha19 is there any reason why `@vue/cli` and `weex-toolkit` can't be merge together?

In terms of architecture from CLI perspective both projects could follow something like https://github.com/infinitered/gluegun plugin system and so on.

cc: @yyx990803

**Comment by erha19** [comment]
@yordis That's a great idea, but as the @yyx990803 say, the `vue-cli` tool is currently a command line tool designed for the web, merging command-line tools on all platforms is not yet on vuecli's plan.

The plug-in mechanism you mentioned is exactly what I plan to implement, after this transformation, my expectation is to abstract all functions into plug-ins or modules. In addition to working in weexcli, it can also be run in other command-line tools by providing a simple container environment.

After vue completes its plan, maybe we can also abstract out a bunch of plugins or a `@vue/cli/weex` core for use in `vue-cli`.

Thanks a lot!

**Comment by xfront** [comment]
How about  this progress? working on?

**Comment by erha19** [comment]
@xfront you can see the`dev` branch, I'm working on this branch.

**Comment by xfront** [comment]
@erha19  Does master version support TypeScript and How? I see dev branch, but when to release a beta test version on npm? I really want to use typescript in weex. I found vue/cli support it now.

**Comment by erha19** [comment]
@xfront now we do not support to using TypeScript in `weex`, and we have plans to implement him at a later time. At present, the cost of writing is higher and the profit is smaller, so we will spend more time on the necessary tools.
when I complete the transformation of all the tools, I will publish a beta version, there is no exact time, maybe next month.

**Comment by erha19** [comment]
@xfront @n3ps work is done

**Comment by n3ps** [comment]
Thanks for the update @erha19. Do you mind sharing the details on how the weex CLI changed? Has it been "aligned" or "integrated" with the official Vue CLI?

**Comment by erha19** [comment]
@n3ps  I am sorry to reply later.
It's not aligned with the official Vue CLI, but provide the ability to expand plugins or extensions that support Vue CLI，I'v learned a lot from the [gluegun](https://github.com/infinitered/gluegun),  and  I built a plugin system like it to support this feature.

I will write the docs about this on these days.

**Comment by erha19** [comment]
@n3ps here you can see how to extend `weex-toolkit` to support other cli, see https://weexteam.github.io/weex-toolkit.
