### ISSUE TITLE
weex debug 

### ISSUE THREAD

**Issue by ifelseboyxx** [apache/incubator-weex-cli#406]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

**Comment by haixing1302** [comment]
node 8.12.0   npm  6.5.0  weex   2.0.0-beta.24(core 2.0.0-beta.23)   weex debug 启动之后 不动几分钟之后会自动断线  地址直接变成http://192.168.0.71:8089/    page提示There is no preview page yet, you can compile the page with the following command
