### ISSUE TITLE
weex debug js code with chrome failed, chrome died everytime

### ISSUE THREAD

**Issue by ifelseboyxx** [apache/incubator-weex-cli#408]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
```
npm - 6.1.0
node  - v8.11.2
chrome - 66.0.3359.170
```
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
```
   v1.3.8
 - weexpack : v1.2.3
 - weex-debugger : v1.0.16
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
- platform (Win/Mac/Ubuntu..)

```
Mac
```

## The key error stack message.

![777777](https://user-images.githubusercontent.com/24642787/40917130-bbcc1f9a-6834-11e8-9b9d-63f0b8e1d0fd.gif)

<img width="2122" alt="snipaste_2018-06-04_19-13-18" src="https://user-images.githubusercontent.com/24642787/40916066-ec28f2e8-6830-11e8-9841-178ef62366bb.png">

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

I want to debug `js` code with below command:

```
weex debug src/index.vue -p 8099
```
then my chrome die every time, I can't debug my `js` code.

I don't know how to fix it. Help?
Thanks!

**Comment by lyuku** [comment]
Got the same issure, does anybody know how to fix it.

**Comment by waterfly** [comment]
我也遇到这个问题，希望尽快帮忙排查一下，非常感谢！！！

**Comment by ifelseboyxx** [comment]
@erha19  

⚠️⚠️⚠️

- 我尝试了下，如果我使用 `console.log()` 形式，前提是不打断点（因为一打断点就卡死），在 Console 里面是可以看到日志输出的：
![6666](https://user-images.githubusercontent.com/24642787/40950565-e4e98798-68a5-11e8-81c5-2d291e19d5cf.gif)

-  然后我还发现，有的时候我是可以打上断点的，并且也可以调试，但是之后还是卡死：
![99999](https://user-images.githubusercontent.com/24642787/40950850-0a0567ee-68a7-11e8-9b0c-0a36737b0198.gif)

有的时候还会存在这种情况：比如我想在断点在**25**行，却老是强制断在**其它行，比如26或者27行**，接着还是会**卡死**。

- 能帮看看什么原因么？还是我这边用的方式不对？

**Comment by erha19** [comment]
@ifelseboyxx @waterfly @wuhen0929 since version `1.0.7`, we have merge device log into the devtool, and I found it will generate a lot of log information during program debugging, leading to chrome memory leak problems. Before solving this problem, I will temporarily close this features until it's been fixed in the `1.0.17` release.

**Comment by ifelseboyxx** [comment]
@erha19 Thanks for your reply. if i want to work normal, it's i need to update my weex-toolkit or do nothing ?

**Comment by erha19** [comment]
@ifelseboyxx after I publish `1.0.17`, you just need to run `weex update weex-debugger`.

**Comment by ifelseboyxx** [comment]
@erha19 OK. 3ks so much!

**Comment by erha19** [comment]
@ifelseboyxx I have published `1.0.17`, you can upgrade it now. After a few days later, I will make it can be controlled by the user.

**Comment by ifelseboyxx** [comment]
@erha19 3ks so much again.

**Comment by ifelseboyxx** [comment]
@erha19  
the problem seems to be still there, i had upgarde `weex-debugger` to `v1.0.17`:

```
   v1.3.8
 - weexpack : v1.2.3
 - weex-debugger : v1.0.17
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
![5555](https://user-images.githubusercontent.com/24642787/40957066-f54a5a7a-68c5-11e8-961d-6df3549028a7.gif)

**Comment by erha19** [comment]
@ifelseboyxx You can hit `cmd+R` to reload the page or `alt+R` to reload the full runtime and you can restart your browser to make chrome work well.

Also, I will try to upgrade the devtool inspector in the debugger tool, maybe it would be fixed after upgraded.

**Comment by ifelseboyxx** [comment]
@erha19 ok... looking forward to

**Comment by erha19** [comment]
@ifelseboyxx work is done, you can using latest verison of `weex-toolkit` to upgrade your `weex-debugger` to the latest version by `weex update weex-debugger@latest`.

Or using the beta version, installed by `npm i weex-toolkit@beta -g`, it will download the latest version of the `@weex-cli/debug` module to open the debugger.
