### ISSUE TITLE
Warning: npm 5 is not supported yet!

### ISSUE THREAD

**Issue by cccisbug** [apache/incubator-weex-cli#409]
## Your development environment
- weex-toolkit verison v1.3.5
- platform Mac

when typing weed -v, then hint this message，but
注意: 在weex-toolkit1.0.8版本后添加了npm5规范的npm-shrinkwrap.json用于锁定包依赖，故npm版本<5的用户需要通过npm i npm@latest -g更新一下npm的版本，使用前请确认版本是否正确。
should i ignore ？

Warning: npm 5 is not supported yet!

It looks like you're using npm 5 which was recently released.
Weex Toolkit doesn't work well with npm 5 yet, unfortunately.

We recommend using npm 4 until some bugs are resolved.
To install npm 4, you can just run `npm i npm@4 -g` or use `n` to manage your npm version with node.

You can follow the known issues with npm 5 at https://github.com/npm/npm/issues/16991

**Comment by cccisbug** [comment]
npm -v 5.6.0 
node -v 9.8.0

**Comment by erha19** [comment]
@cccisbug The `npm@5` may cause may upgrade issue while you using `weex-toolkit`, and `npm@4` is a better version to use, you should follow the tip from the command line, and I will change the document on the website.

Thanks.
