### ISSUE TITLE
 weex 支持使用自己的客户端来调试么？

### ISSUE THREAD

**Issue by leeeisok** [apache/incubator-weex-cli#410]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
```
npm - 6.1.0
node  - v8.11.2
```
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
```
  v1.3.8
 - weexpack : v1.2.3
 - weex-debugger : v1.0.16
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
- platform (Win/Mac/Ubuntu..)

## The key error stack message.

执行命令：
```
weex debug src/index.vue
```
弹出二维码，使用官方的 WeexplayGround 客户端扫码后勉强可以 debug 断点调试。
现在我想使用我自己的**客户端**来想 WeexplayGround 那样调试，但是失败了，一直白屏。

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

1. 我按照文档使用 cocospod 引入 WXDevtool 这个库：
```
pod  'WXDevtool', '0.15.3', :configurations => ['Debug']
```
2. 我自己的客户端入口处调用 `weex debug ` 命令后，终端显示的地址：

![image](https://user-images.githubusercontent.com/40003195/41083416-be3188b6-6a63-11e8-8d2b-a250f93bc4eb.png)

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.backgroundColor = [UIColor whiteColor];
    
    [WXDevTool setDebug:YES];
    [WXDevTool launchDevToolDebugWithUrl:@"ws://10.101.56.43:1314/debugProxy/native"];
    
    [WeexSDKManager setup];
    
    [self.window makeKeyAndVisible];
    
    return YES;
}
```
3. 空白一片，不能像 WeexplayGround 扫码那样调试。

想请教下：
> weex 支持使用自己的客户端来调试么？
> 支持的话，上面我的使用步骤是不是有问题？
> `WXSDKInstance` 最后 `renderWithURL:` 方法调用的地址是什么呢？ 是不是就是二维码里的那个链接内容？

望有空能帮助下，非常感谢！！🙏🙏

**Comment by honeybadger-Hadoop** [comment]
@leeeisok 楼主解决了么？我也想知道怎么使用自己的 APP 来调试，因为我们自己实现了很多 module，想基于我们自己的客户端，像 weexplayground 扫码那样断点调试

**Comment by erha19** [comment]
@leeeisok @lxs091021119 
Examples here: 
- [Android Playground](https://github.com/apache/incubator-weex/tree/master/android/playground)
- [iOS Playground](https://github.com/apache/incubator-weex/tree/master/ios/playground)

Also, you can see the document here: 
- [Integrate devtool to iOS](http://weex.apache.org/guide/integrate-devtool-to-ios.html)
- [Integrate devtool to Android](http://weex.apache.org/guide/integrate-devtool-to-android.html)

**Comment by leeeisok** [comment]
@erha19 感谢回复，我看看先
