### ISSUE TITLE
Cannot find module 'chokidar', 试验了网上的各种方法，无果，遂求助

### ISSUE THREAD

**Issue by rurusmoon** [apache/incubator-weex-cli#412]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=5(Run `npm --version` and `node --version`).
- npm --version
6.1.0

- node --version
v10.0.0

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).

- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.
关键字搜索‘chokidar’，无果

## Your development environment
- weex-toolkit verison (Run `weex -v`)
   v1.3.8
 - weexpack : v1.2.3
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

- platform (Win/Mac/Ubuntu..)
Mac

## The key error stack message.
Error: Cannot find module 'chokidar'
1. npm调整为5.1，问题依旧；
2. npm调整为4.1，问题依旧；
3. 使用yarn，问题依旧；
4. chmod 777 ， 问题依旧；
5. 手动安装chokidar，问题依旧
6. 其它各种命令，抱歉此时头脑有点乱，没记住，问题依旧

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
新手搭建weex初始工程：
1. weex create weexApp;
2. cd weexApp;
3. npm install;
4. weex platform add ios;
5. npm run ios

 哦耶， Error: Cannot find module 'chokidar'
抱歉无法提供dotwe，因为工程都没搭建成功。

**Comment by erha19** [comment]
@rurusmoon looks like the `weexpack` module didn't install well, you can run `weex remove weexpack` then run `npm run ios` again, if there still have some problem, please show me the detail log on your terminal.

**Comment by rurusmoon** [comment]
@erha19 多谢回复，按照你说的方法跑了一遍，还是同样的问题，步骤如下：
1. 翻墙；
2. weex remove weexpack；
3. npm run ios

详情截图如下：麻烦了

<img width="561" alt="wx20180611-171157 2x" src="https://user-images.githubusercontent.com/5362142/41223124-81f522fa-6d9b-11e8-99a0-ca54aaa996fb.png">

<img width="852" alt="wx20180611-171333 2x" src="https://user-images.githubusercontent.com/5362142/41223142-8bff1288-6d9b-11e8-97e6-978c51cc0e8b.png">

<img width="597" alt="wx20180611-172140 2x" src="https://user-images.githubusercontent.com/5362142/41223292-f408430e-6d9b-11e8-9b39-433ed6a2287e.png">

**Comment by erha19** [comment]
@rurusmoon Try `weex update weexpack@1.2.4`, I have published a bugfix version.

**Comment by rurusmoon** [comment]
@erha19 更新到1.2.4解决了，十分感谢。
