### ISSUE TITLE
navigator.push

### ISSUE THREAD

**Issue by Panamer** [apache/incubator-weex-cli#414]
请问：
1.怎么访问工程里的静态资源，包括图片和js。如navigator.push 的参数URL该怎么写
2.ios.config 里的 证书和描述文件怎么填

**Comment by erha19** [comment]
@Panamer 
1. [Asset path](http://weex.apache.org/cn/guide/advanced/path.html).
2. We suggest you using Xcode to build your application, the `weex-toolkit` is poor to support package app.

**Comment by Panamer** [comment]
尝试在weex里做微信分享一直没成功，麻烦给下思路。假如在工程里注入sdk，该怎么做。听听您的意见谢谢
