### ISSUE TITLE
mac npm install -g weex-toolkit 失败

### ISSUE THREAD

**Issue by QSFan** [apache/incubator-weex-cli#415]
bogon:~ qishifan$ node -v
v10.4.1
bogon:~ qishifan$ npm -v
6.1.0
bogon:~ qishifan$

bogon:~ qishifan$ npm install -g weex-toolkit
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/package.json'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/README.md'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/LICENSE'
WARN tar ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/wide-align-54bc042f/align.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: engine.io-client@1.8.3 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/engine.io-client):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...nbul":"^1.1.1","gulp-'

npm ERR! Unexpected end of JSON input while parsing near '...st":{"shasum":"6a0cf5'

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/qishifan/.npm/_logs/2018-06-20T18_27_46_280Z-debug.log
bogon:~ qishifan$

**Comment by erha19** [comment]
@QSFan Try 
```
npm cache clean --force
rm -rf ~/.npm
```
then run it again.

**Comment by QSFan** [comment]
@erha19 
OK，Thank you very much.
