### ISSUE TITLE
weex preview 报错

### ISSUE THREAD

**Issue by gqdtl** [apache/incubator-weex-cli#416]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=4(Run `npm --version` and `node --version`).
- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)
- platform (Win/Mac/Ubuntu..)

**Comment by gqdtl** [comment]
![7i7r58 lv7hn j3u5 j q](https://user-images.githubusercontent.com/14305510/41768385-a97c0842-763e-11e8-9392-f371f90a1307.png)

**Comment by erha19** [comment]
@gqdtl please run `weex -v` and then tell me your toolkit versions.

**Comment by loniecc** [comment]
同样的问题

<img width="210" alt="2018-06-26 10 43 53" src="https://user-images.githubusercontent.com/11846011/41886239-1f7d8e5c-792e-11e8-856a-311b4a5f96cc.png">

**Comment by loniecc** [comment]
@erha19 安装过程还有警告
`node@v10.5.0" is incompatible with weex-previewer@1.5.1`

**Comment by gqdtl** [comment]
我的解决了，我是电脑管家拦截的，允许就好了

**Comment by loniecc** [comment]
@gqdtl 拦截了什么？我是mac。。

**Comment by erha19** [comment]
@lonieHu It's there any detail log information?

**Comment by erha19** [comment]
Issue activity is too low, close
