### ISSUE TITLE
用weex-toolkit调试页面报错

### ISSUE THREAD

**Issue by JashonWang** [apache/incubator-weex-cli#42]
![image](https://cloud.githubusercontent.com/assets/7724315/21881855/f0d91ffe-d8e2-11e6-95b5-c228429bc67b.png)

在用weex-toolkit debug的时候报错了，错误信息如上所示，这是否跟我在代码中定义了一个图片相对路劲有关？
`module.exports = {
data: {
      dogUrl : require('./img/dog1.png')
    }
}`
weex-toolkit是否没有对相对路径做响应的处理？

**Comment by JackPu** [comment]
@JashonWang  关于本地图片的问题，我们正在想办法解决，

**Comment by erha19** [comment]
Fiex already, please update to the latest version.
