### ISSUE TITLE
新建项目 tree shaking 没有起作用，使用官方例子

### ISSUE THREAD

**Issue by biaomingzhong** [apache/incubator-weex-cli#423]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [x] Check that your node version is >= 6 and npm version is >=4(Run `npm --version` and `node --version`).
- [x] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [x] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`)

```
$ weex -v
   v1.3.8
 - weexpack : v1.2.3
 - weex-debugger : v1.0.12
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
- platform: Mac

## The key error stack message.

1. tree shaking 没有作用，混淆后的代码依然存在没有调用方法
2. 但同样的例子，不使用 weex tookit 创建的项目，按照官方的步骤就可以起作用，混淆后的代码会去掉没有调用的方法

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

webpack 官方 tree shaking [例子](https://webpack.docschina.org/guides/tree-shaking/)

**Comment by erha19** [comment]
@biaomingzhong We have not upgrade `webpack` to 4.x, and the tree shaking before is almost base on the `uglify` plugin, maybe you can try to create a pull request to our official template, see https://github.com/weex-templates/webpack.
