### ISSUE TITLE
ios 关于 status bar

### ISSUE THREAD

**Issue by Aibric** [apache/incubator-weex-cli#424]
## Your development environment
```
weex -v
   v1.3.8
 - weexpack : v1.2.4
 - weex-debugger : v1.0.19
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
状态栏 android 可以通过 配置解决，iOS 只能通过 调整样式解决吗？ 谢谢。
![image](https://user-images.githubusercontent.com/2859844/42432913-82319e8e-837f-11e8-9017-cb9ed1629874.png)

**Comment by erha19** [comment]
@Aibric You need an iOS developer to help you, you can search for it by keyword `contentInsetAdjustmentBehavior `.
