### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/emitter-93b8b8d0/package.json'

### ISSUE THREAD

**Issue by JasonZengJ** [apache/incubator-weex-cli#425]
➜  ssri npm install -g weex-toolkit
sri: sha512-6sPmrMCDJXDbhXNqFBEleIYAgginONRaGJ1JvIvMCoc/qJTOL8UNSrAdpdzs46rD3HgJ8rZLIlgB+ZGbTmAUMg==
undefined
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/fsevents-6cd1b148/node_modules/strip-ansi' -> '/usr/local/lib/node_modules/.staging/strip-ansi-78f941d3'

npm ERR! path /usr/local/lib/node_modules/.staging/emitter-93b8b8d0/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/emitter-93b8b8d0/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by erha19** [comment]
@JasonZengJ Try to delete the cache file on `/usr/local/lib/node_modules/weex-toolkit` or using `npm@4`.
