### ISSUE TITLE
Create project does nothing

### ISSUE THREAD

**Issue by khalili-mahdi** [apache/incubator-weex-cli#429]
`weex create awesome`
when i execute this command it opens users folder from my drive C 
then shows me this
`? Project name (awesome)`
and its end here without creating project
last out put is this :
```
H:\Vue>weex create awesome
? Project name project22
? Project description (A weex project)
H:\Vue>
```

**Comment by khalili-mahdi** [comment]
is there any way i can create project manually ? this command line thing is not working for me i tried everything

**Comment by erha19** [comment]
@haftado3 
Hi, 

Firstyle, there has not a manual way to create the official project cause it's dependent on some signal flag, to solve your problem, please tell me what's the platform you are working on and which version of `weex-toolkit` you are using? Is there any more detail log message? Maybe you can run the command with a `--verbose` option.

Thanks.

**Comment by JayChenChou** [comment]
@haftado3  I'm the same as you are.

**Comment by khalili-mahdi** [comment]
how can i produce log message? --verbose did nothing ,result is same , cause when you use 
`weex create whatever`
it starts to download some packages or files then it clears screen and asks you for project name("why ?")
if you give it project name its done , no files for you

**Comment by khalili-mahdi** [comment]
```
H:\Vue>npm install -g weex-toolkit
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
C:\Users\Mahdi Khalili\AppData\Roaming\npm\weex -> C:\Users\Mahdi Khalili\AppData\Roaming\npm\node_modules\weex-toolkit\bin\weex.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\weex-builder\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\weex-toolkit\node_modules\weex-previewer\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\weex-builder\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\weex-toolkit\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

```

**Comment by khalili-mahdi** [comment]
```
H:\Vue>weex -v
   v1.3.8
 - weexpack : v1.2.5
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

H:\Vue>npm -v
6.2.0

```

**Comment by haftado3** [comment]
there is files in `C:\Users\Mahdi Khalili\AppData\Roaming\npm\node_modules\weex-toolkit`
can we create project using those ?

**Comment by JayChenChou** [comment]
@haftado3   i have solved this problem. 
follow with me :
Uninstall your current NodeJS, and Download NodeJS LTS version (8.11.3)
and then
open CMD
node -v must be v8.11.3
npm -v must be v5.6.0

this way to download LTS
https://nodejs.org/dist/v8.11.3/node-v8.11.3-x64.msi

**Comment by JayChenChou** [comment]
@haftado3  install **NodeJS LTS v8.11.3**
when you create WEEX project
maybe have a NOTICE  don't Support npm@4,  please ignore this NOTICE

**Comment by khalili-mahdi** [comment]
in windows from `C:\Users\Mahdi Khalili\AppData\Roaming\npm` folder removed everything then installed from begining solved problem
