### ISSUE TITLE
为什么连npm5都不支持，你是在逗我么

### ISSUE THREAD

**Issue by shangxinbo** [apache/incubator-weex-cli#430]

**Comment by shangxinbo** [comment]
PS E:\weex> weex -v
   v1.3.8
 - weexpack : v1.2.5
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

Warning: npm 5 is not supported yet!

It looks like you're using npm 5 which was recently released.
Weex Toolkit doesn't work well with npm 5 yet, unfortunately.

We recommend using npm 4 until some bugs are resolved.
To install npm 4, you can just run `npm i npm@4 -g` or use `n` to manage your npm version with node.

You can follow the known issues with npm 5 at https://github.com/npm/npm/issues/16991

**Comment by wmlgl** [comment]
这个可以写到faq里， 用npm5和npm6出了一堆问题，弄了半天- -!
