### ISSUE TITLE
weex failed to complete on Linux (18.04LTS Ubuntu)

### ISSUE THREAD

**Issue by to1sourceuk** [apache/incubator-weex-cli#431]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [X] Check that your node version is >= 6 and npm version is >=4(Run `npm --version` and `node --version`).
- [X] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [X] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- weex-toolkit verison (Run `weex -v`) --> Version 1.3.8
- platform (Win/Mac/Ubuntu..) --> Ubuntu 18.04 LTS

## The key error stack message.

Run `weex create new-project` or `weex platform` both have the same problem:
```
This command need to install weexpack. Installing...
npm ERR! Unexpected end of JSON input while parsing near '...union","lodash.uniq",'
21:55:46 : Error: fatal error!
```

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

Just run `weex create new-project` on Linux (Ubuntu 18.04LTS) and you will get this problem. (P.S. when on Windows 10 using git-bash, npm report problem with package and failed to complete the command)

**Comment by erha19** [comment]
@joelchucn can you run it again with a `--verbose` option? I want to see more detail logs., thanks.

**Comment by to1sourceuk** [comment]
```
 weex create mobile-nb --verbose
This command need to install weexpack. Installing...
npm ERR! Unexpected end of JSON input while parsing near '...union","lodash.uniq",'



10:50:41 : Error: fatal error!

```

Then I tried

```
weex create --verbose mobile-nb
This command need to install weexpack. Installing...
npm ERR! Unexpected end of JSON input while parsing near '...union","lodash.uniq",'
10:51:46 : Error: fatal error!

```

This was run under vpn using npm.

With or without VPN yield the same result. 

----

Then I changed the registry to taobao 
```
weex config registry https://registry.npm.taobao.org/
```
The command run without problem. 

---

The strange thing is - I tried the same command on Windows 10 (not virtual machine, all real machine) Mac OSX (High Sierra) and Ubuntu 18.04 LTS. The Windows 10 run the command but yield huge amount of security warning (Win 10 using Node.js 10.X) Mac works (also run Node.js 10.x) Ubuntu is running Node.js 8.X LTS
