### ISSUE TITLE
使用官方文档，strem  POST请求，控制台Network看不到相关请求信息？

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#434]
1.环境版本：
    
![image](https://user-images.githubusercontent.com/31499235/43499912-6d288666-9580-11e8-8785-0de4dd3078c6.png)

2.使用知识点：

![image](https://user-images.githubusercontent.com/31499235/43499929-84365c66-9580-11e8-8daf-8217bce89e2f.png)

3.代码编写方式：

![image](https://user-images.githubusercontent.com/31499235/43500055-303fa152-9581-11e8-9851-9fb4396a3dc1.png)

4.问题描述：
    4.1、将所有请求方式，参数请求，都采取url拼接方式，能够在debug  控制台看到接口请求状态。
    4.2、但是根据官方的post请求方式，post请求，body入参，控制台  Network  看不到请求状态。

@erha19 请求大佬帮忙解答，谢谢。

**Comment by erha19** [comment]
@AugTang Android Playground App can't work well with the Network feature, try to use iOS Playground App/

**Comment by AugTang** [comment]
请问   Android Playground App    日后会考虑吗？这个功能蛮重要的。
@erha19
