### ISSUE TITLE
trouble with create project

### ISSUE THREAD

**Issue by cybermerlin** [apache/incubator-weex-cli#435]
Makes sure these boxes are checked befor submitting your issue - thank you!
```cmd
node 10
npm 6

weex -v
   v1.3.8
 - weexpack : v1.2.5
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
win.10

no error
but `weex create myProj` canceled after write proj name. 
He did not ask description, just canceled process after writing the project name and pressing the Enter button.

**Comment by erha19** [comment]
@cybermerlin I need more detail log., please run `weex create myProj --verbose`.

**Comment by cybermerlin** [comment]
nothing more

btw
I try with `set DEBUG=*` n nothing -__-

+ I'm changing name proj to without capital letters

**Comment by cybermerlin** [comment]
`weexpack create myproj` give me same result

**Comment by erha19** [comment]
@cybermerlin The package name was no longer support contain capital letters, you need to use `weex create myproj` or `weex create my-proj` to create your project.

**Comment by cybermerlin** [comment]
I did but the trouble is not resolved;

**Comment by erha19** [comment]
@cybermerlin try to use an admin shell or reinstall `weexpcak` using `weex remove weexpack && weex create my-proj`, I test the command on my windows pc, it works fine.

**Comment by cybermerlin** [comment]
nothing changed

```
r:\>weex remove weexpack
21:15:03 : Remove package `weexpack` successful...

r:\>weex create my-proj
This command need to install weexpack. Installing...
? Project name my-proj
? Project description (A weex project)
r:\>
```

**Comment by cybermerlin** [comment]
I think I'll use RN instead. to be better decision

**Comment by erha19** [comment]
@cybermerlin ok, and I think this is a windows permission issue, I will try to solve this problem in the subsequent version.

**Comment by cybermerlin** [comment]
@erha19 
I did run with admin rights n nothing changed.
I wanna help ya to make better this project, just say what I to do.

**Comment by erha19** [comment]
@cybermerlin try to downgrade your node version to version below 8.0, I find the node v8.0 can work fine, but the node v10.0 can't work, there should be some breaking changed on node or other npm packages, I'm trying to solve it.

**Comment by erha19** [comment]
@cybermerlin you need to upgrade your `weex-toolkit` by `npm i weex-toolkit@latest -g` then run `weex update weexpack` to fix this issue, it causes by the `inquirer` module witch dependence on some node library.

**Comment by cybermerlin** [comment]
wow, ya so cool man
thx

**Comment by cybermerlin** [comment]
super mario
bonus level
