### ISSUE TITLE
npm5 not support yet

### ISSUE THREAD

**Issue by shangxinbo** [apache/incubator-weex-cli#436]
## Your development environment
- weex-toolkit 1.3.8
- platform  Windows
- node  8.11.2
- npm 5.6.0

## The key error stack message.
Warning: npm 5 is not supported yet!

我想知道npm5什么时候能够支持
官方文档说：
>安装前建议你的node版本是 >= 6.0, 推荐使用n 来进行版本管理，由于在npm5版本中还存在诸多未解决的问题，见 npm5 已知问题，在官方还未修复前，建议你使用npm4来进行工具使用，可运行 npm i npm@4 -g 进行安装。

然而weex官方说
> 注意: 在weex-toolkit1.0.8版本后添加了npm5规范的npm-shrinkwrap.json用于锁定包依赖，故npm版本<5的用户需要通过npm i npm@latest -g更新一下npm的版本，使用前请确认版本是否正确。

是因为没有人维护了么，就不管npm5了么，这不相当于直接让我装回xp系统进行开发么

**Comment by erha19** [comment]
@shangxinbo It will be rebuilt on the weex-toolkit@2.0, you can see the branch here https://github.com/weexteam/weex-toolkit/tree/dev.

And `npm5 not support yet` doesn't mean you can't use `npm5` anymore, but you will face the `npm@5` problems when you upgrade some dependencies cause of the feature depend on the global npm, using `npm@4` is a better choice for now.
