### ISSUE TITLE
执行weex compile src dist报错

### ISSUE THREAD

**Issue by rainbowzx** [apache/incubator-weex-cli#437]
npm -v
 4.6.1

weex -v
   v1.3.8
 - weexpack : v1.2.5
 - weex-debugger : v1.1.9
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
 - toolkit-repair : v0.0.5

系统:macos 10.13.3
<img width="1436" alt="1212" src="https://user-images.githubusercontent.com/16997621/44185906-d8b11000-a148-11e8-979f-0e5096212eca.png">

Build Failed!
[ './node_modules/._weex-vue-loader@0.6.11@weex-vue-loader/lib/script-loader.js!/Users/cangshuren/.nvm/versions/node/v7.8.0/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/babel-loader/lib!./node_modules/._weex-vue-loader@0.6.11@weex-vue-loader/lib/selector.js?type=script&index=0!./src/views/withdraw/components/loanUsefulness.vue\nModule not found: Error: Can\'t resolve \'./FormItem\' in \'/Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components\'\nresolve \'./FormItem\' in \'/Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components\'\n  using description file: /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/package.json (relative path: ./src/views/withdraw/components)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/package.json (relative path: ./src/views/withdraw/components)\n    using description file: /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/package.json (relative path: ./src/views/withdraw/components/FormItem)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components/FormItem doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components/FormItem.js doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components/FormItem.json doesn\'t exist\n      as directory\n        /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components/FormItem

@erha19

**Comment by erha19** [comment]
@rainbowzx There has some errors you can see:
```
1. Can't resolve './FormItem' in '/Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components'

2. /Users/cangshuren/YH_PROJECT/winwinmoney-to-weex/src/views/withdraw/components/FormItem.json doesn't exist
```
you should fix it by yourself.
