### ISSUE TITLE
when will version 2.0 publish?

### ISSUE THREAD

**Issue by shangxinbo** [apache/incubator-weex-cli#438]
I wan't use npm5 for package manage.I wender when will 2.0 release publish? And why  version 1.3.8 can't be found in github release tab, I find 1.0.3 only

**Comment by erha19** [comment]
@shangxinbo 
1. when 2.0 release publish?
This is not a certain time release. At present, I have completed the work of `@weex-cli/core`. The rest is to rewrite the original module into the existing architecture through Typescript. Now two colleagues will work with me, the progress will be a lot faster, we will correctly complete this part of the work in these two months.
2. why version 1.3.8 can't be found in github release tab
That's a mistake by the pre repo master, we will release it on release tab after 2.0. Now you can get the package version you need directly through `npm view weex-toolkit versions`.

**Comment by erha19** [comment]
@shangxinbo work is done, you can try it by `npm i weex-toolkit@beta -g` now, hope for your advice.

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
