### ISSUE TITLE
debug：无法定位dom

### ISSUE THREAD

**Issue by AugTang** [apache/incubator-weex-cli#439]
使用审查元素，放在代码上，无法定位到页面模块，老版本能行，为什么升级就不能用了？
![image](https://user-images.githubusercontent.com/31499235/44451070-33ed7180-a625-11e8-81b2-2404e2940274.png)

@erha19

**Comment by erha19** [comment]
@AugTang I have upgraded the inner `chrome devtool`, maybe it causes that problem, let me see...

**Comment by erha19** [comment]
@AugTang upgrade `weex-debugger` to v1.1.12.

**Comment by AugTang** [comment]
已升级，还是不能在定位视图上的dome。
@erha19

**Comment by erha19** [comment]
@AugTang you can provide your demo here, or show me the difference between the old debugger and new debugger, you can downgrade debugger by `weex update weex-debugger@[version]`.

**Comment by AugTang** [comment]
1.weex-debugger模式：

![image](https://user-images.githubusercontent.com/31499235/44502457-263af900-a6c4-11e8-9f18-d19f01536e99.png)

2.期望效果，如谷歌审查元素效果，如下图：

![image](https://user-images.githubusercontent.com/31499235/44502523-6f8b4880-a6c4-11e8-8283-2f6da0a7a21f.png)

注：以前旧版本可以这样展示。

@erha19
