### ISSUE TITLE
v-for指令不能用？

### ISSUE THREAD

**Issue by MichaelGong** [apache/incubator-weex-cli#44]
1、查看了官网的例子，v-for替换成repeat才行
2、`weex.requireModule is not a function` ,查看了weex实例，并没有require相关的方法

**Comment by Hanks10100** [comment]
`v-for` 是 Vue 才支持的指令，`weex.requireModule` 是最新提供的方法，目前 weex-toolkit 还不支持直接编译 `.vue` 文件

**Comment by MichaelGong** [comment]
感觉文档版本有点混乱啊，都搞不清楚了

**Comment by WangXiZhu** [comment]
@Hanks10100 这个文档中写了可以使用 weex xx.vue，但是实际功能又没有，会误导大家。请问新版本大概什么时候上呢？谢谢

**Comment by Jinjiang** [comment]
`weex.requireModule` 的问题我们集中调整过了，对大家非常抱歉，Playground App 因为要进商店送审，所以需要一些时间，大家如果等不及也可以直接从 Weex 的主仓库 build 一个出来，现在 build 出来的肯定都是正常的了。
如果再发现不支持的地方有劳大家开 issue 报一下，我们会及时处理解决。
谢谢。
