### ISSUE TITLE
weex run ios 修改文件路径导致报错；生成工程文件无法开启Development Signing

### ISSUE THREAD

**Issue by RoganZheng** [apache/incubator-weex-cli#444]
weex-toolkit verison (v1.3.11)
platform (Mac)
Xcode (Version 9.4.1)
1. 使用 weex platform add ios 创建 iOS 工程后，项目名称以及文件名手动修改过名，不是默认的WeexDemo，但是 weex 依旧去查找该 WeexDemo 的项目路径。

Error:Error: ENOENT: no such file or directory, open '/Users/xxx/Documents/xxx/platforms/ios/WeexDemo/WeexDemo-Info.plist'

这个路径当前 1.3.11 版本我可以手动修改这个配置吗？如果有提供解决方法的话，在哪里可以修改？

2. 通过运行 weex platform add ios 创建的工程，还发现一个问题，就是一直无法点击选择证书 Signing 中的 Enable Development Sigining 选项，请问这是项目预设的吗？是否可以修改开启这个功能？可以的话，在哪里可以设置？
![image](https://user-images.githubusercontent.com/11712383/44782468-eb502e00-abb9-11e8-8191-7f0809610e26.png)

**Comment by erha19** [comment]
That should be a feature, now it's not supported.

**Comment by erha19** [comment]
@ggice
