### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by ecdiy** [apache/incubator-weex-cli#448]
npm install weex-toolkit -g
安装失败，
...........
emitter@http://github.com/component/emitter/archive/1.0.1.tar.gz
这个URL已经改成了
https://github.com/component/emitter/archive/1.0.1.tar.gz

无论用什么办法也法安装成功呀,能尽快修复吗

**Comment by ecdiy** [comment]
坑，又好了，弄了一下午没有弄好。registry=https://registry.npm.taobao.org       也不管用。

**Comment by Kingbultsea** [comment]
C:\Users\asasasasd\AppData\Roaming\npm\node_modules  删除weex-toolkit  然后npm i weex-toolkit -g

**Comment by misterji** [comment]
WARN node unsupported "node@v10.14.2" is incompatible with weex-previewer@1.5.1 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › boom@0.3.x, expected node@0.8.x
Install fail! Error: GET http://github.com/component/emitter/archive/1.0.1.tar.gz response 404 status
Error: GET http://github.com/component/emitter/archive/1.0.1.tar.gz response 404 status
    at get (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\get.js:57:17)
    at get.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by misterji** [comment]
没有搞定还是没有办法下载 不知怎么处理了
