### ISSUE TITLE
Error: EPERM: operation not permitted, lstat

### ISSUE THREAD

**Issue by ecdiy** [apache/incubator-weex-cli#452]
npm run android

......

09:18:02 : Reloading page...

09:18:02 : Error: EPERM: operation not permitted, unlink 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\my\info.js'
09:18:02 : Error: EPERM: operation not permitted, unlink 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\my\info.js'
09:18:02 : Error: EPERM: operation not permitted, unlink 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\my\info.js'
09:18:02 : Error: EPERM: operation not permitted, unlink 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\my\info.js'
09:18:03 : Error: EPERM: operation not permitted, lstat 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\base\login.js'
09:18:03 : Error: EPERM: operation not permitted, lstat 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\base\login.js'
09:18:03 : Error: EPERM: operation not permitted, lstat 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\base\login.js'
09:18:03 : Error: EPERM: operation not permitted, lstat 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\base\register.js'
09:18:03 : Error: EPERM: operation not permitted, lstat 'D:\dev\loveui\app\platforms\android\app\src\main\assets\dist\base\login.js'
.............

出现大量这种错误，导致在android上无法预览效果

**Comment by erha19** [comment]
@ecdiy please use the command line tool with administrator privileges.
