### ISSUE TITLE
Error: Vue is not defined, when i use vue-router

### ISSUE THREAD

**Issue by Yhspehy** [apache/incubator-weex-cli#463]
weex-toolkit verison:
   v1.3.11 . 
 - weexpack : v1.2.7
 - weex-debugger : v1.1.17
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
- platform: Mac

[As the guide write](https://weex.apache.org/cn/guide/advanced/use-vuex-and-vue-router.html#bian-cheng-shi-dao-hang), when i use vue-router,  errors: Vue is not defined.

> My steps:
> 1.  weex create project and yarn dev & yarn serve
> 2. add route in router.js
> 3. use router in index.vue

```js
// index.vue

<template>
  <div class="wrapper">
    <image :src="logo" class="logo" />
    <text class="greeting">The environment is ready!</text>
    <text @click="jump">Profile</text>
    <router-view/>
  </div>
</template>

<script>
import router from './router'
export default {
  name: 'App',
  data () {
    return {
      logo: 'https://gw.alicdn.com/tfs/TB1yopEdgoQMeJjy1XaXXcSsFXa-640-302.png'
    }
  },
  methods: {
    jump () {
      router.push('about')
    }
  }
}
</script>


// router.js
/*global Vue*/
import Router from 'vue-router'
import HelloWorld from '@/components/HelloWorld'
import About from '@/about'


Vue.use(Router)

module.exports = new Router({
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld
    },
    {
      path: '/about',
      name: 'About',
      component: About
    }
  ]
})
```

if i delete `/*global Vue*/` and add import Vue from 'Vue', errors is '[vue-router] Route with name 'about' does not exist'.   
And if i restart the demo, ERROR in ./.temp/router.js Module build failed: Duplicate declaration "Vue"

**Comment by erha19** [comment]
@Yhspehy something wrong with the path `import About from '@/about'`, the `@` is an alias of the path `src`, you need to check if there has a component file on `src/about.vue`.

**Comment by Yhspehy** [comment]
@erha19 Sorry for replaying this so late. It seems there is something wrong with my env. Today it is all right when i run yarn serve. Thx!
