### ISSUE TITLE
Default Launch Image mistook size

### ISSUE THREAD

**Issue by shinriyo** [apache/incubator-weex-cli#464]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [o] Check that your node version is >= 6 and npm version is >=4(Run `npm --version` and `node --version`).

npm --version                                  1959ms  Sun Oct 14 13:56:12 2018
6.4.1

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).

`weex update weex-toolkit@latest`?

- [o] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

p.s.

not `befor`. correct is `before`.

## Your development environment
- weex-toolkit verison (Run `weex -v`)

weex -v
   v1.3.11

- platform (Win/Mac/Ubuntu..)

Mac

## The key error stack message.

<img width="602" alt="screen shot 2018-10-14 at 13 53 56" src="https://user-images.githubusercontent.com/396927/46912730-c886a700-cfb8-11e8-9dc6-993e9bef5c95.png">

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

it is default.

**Comment by erha19** [comment]
@shinriyo  We will optimize this project recently, for now that's project just a template project for web developer to preview the weex page.

Maybe you can modify this by yourself.
