### ISSUE TITLE
weex run ios 报deviceType错误且code-signing-Identity似乎无效

### ISSUE THREAD

**Issue by DoradoIs90** [apache/incubator-weex-cli#465]
1. node V10.10.0
2. npm V6.4.1
3. weex V1.3.11
4. max os 10.14
运行weex run ios 报错，已经将ios.config.json内的CodeSign及Profile调整成自己的，运行后选择真机报错如图：
![1539498500463](https://user-images.githubusercontent.com/17820303/46913379-66c93b80-cfbe-11e8-830e-80a767de35cd.jpg)

**Comment by erha19** [comment]
@DoradoIs90 This feature is no longer available after a long period of no maintenance, and now we are working for the new version of weex-toolkit on the `dev` branch, for now, you should use Xcode to package your project, it's a better choice.

**Comment by erha19** [comment]
I will close this issue cause it will not be fixed on `1.x` version.
