### ISSUE TITLE
toolkit error

### ISSUE THREAD

**Issue by caolijiang** [apache/incubator-weex-cli#467]
## Your development environment

-bash-3.2$ node -v
v10.9.0
-bash-3.2$ npm -v
6.2.0

## The key error stack message.

WARN node unsupported "node@v10.9.0" is incompatible with weex-previewer@1.5.1 › dns@0.2.2 › winston@0.7.3 › request@2.16.6 › hawk@0.10.2 › sntp@0.1.x, expected node@0.8.x

Error: read ECONNRESET
    at TLSWrap.onread (net.js:660:25)

**Comment by erha19** [comment]
@caolijiang please provide more detail of the reason why it reports `ECONNRESET` error, maybe you can try to using npm@4 to install the toolkit or remove cache file from the local directory.

**Comment by erha19** [comment]
inactive issue, close now
