### ISSUE TITLE
使用rax搭建项目，不能使用weex-toolkit吗？

### ISSUE THREAD

**Issue by RaniHu** [apache/incubator-weex-cli#470]
用rax初始化了一个demo，那如何像创建weex项目一样添加ios和安卓的项目模板呢？
直接weex platform add ios会提示Current working directory is not a weex project.
weex-debugger也不能在rax搭建的项目中使用吗？

**Comment by erha19** [comment]
@RaniHu you can use `weex-debugger` with a rax project, but for other feature, it's support for the official project (which is created by weex-toolkit) now.
