### ISSUE TITLE
Error: Chromium revision is not downloaded. 

### ISSUE THREAD

**Issue by YcDevs** [apache/incubator-weex-cli#473]
Makes sure these boxes are checked befor submitting your issue - thank you!

- ✔️ Check that your node version is >= 6 and npm version is >=4(Run `npm --version` and `node --version`).
- ✔️ If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- ✔️ Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
![image](https://user-images.githubusercontent.com/16175937/47559734-db9a5f00-d948-11e8-891c-73fd004c9c74.png)

- platform (Win/Mac/Ubuntu..)
![image](https://user-images.githubusercontent.com/16175937/47560232-44cea200-d94a-11e8-821c-ca52002faa48.png)

## The key error stack message.
![image](https://user-images.githubusercontent.com/16175937/47559834-26b47200-d949-11e8-881b-859a9036937e.png)

I tried to solve it, but it didn't work.

![image](https://user-images.githubusercontent.com/16175937/47560043-b35f3000-d949-11e8-908f-5cfffeeb10d5.png)

I wonder what is causing this problem. Thank you for your help.

**Comment by erha19** [comment]
@SilentlyYc The remove command is `rm -rf ~/.xtoolkit/node_modules/weex-debugger`.

**Comment by erha19** [comment]
@SilentlyYc I will close this issue cause it can be easily fixed by yourself if you have other questions, you can reopen this issue and comment on it.

**Comment by YcDevs** [comment]
I'm sorry,That's a false example.
This is the problem.
![image](https://user-images.githubusercontent.com/16175937/47632632-e261e580-db85-11e8-8007-ebd6578ba5f3.png)

**Comment by erha19** [comment]
@SilentlyYc run `rm -rf ~/.xtoolkit/ && npm config set PUPPETEER_DOWNLOAD_HOST https://storage.googleapis.com.cnpmjs.org`, then run the command `weex debug` again, the `weex-debugger` needs to install chromium as a runtime container, so you should make sure the chromium has been installed.

**Comment by SilentlyYc** [comment]
yes~ its work for me.
thx a lot

**Comment by YcDevs** [comment]
@erha19 yes~ its work for me.
thx a lot
