### ISSUE TITLE
weex-toolkit 安装失败

### ISSUE THREAD

**Issue by githublvjing** [apache/incubator-weex-cli#475]
node -v
v8.11.3
npm -v
6.4.1

sudo cnpm install -g weex-toolkit

安装报错

Error: write EPROTO 4569482688:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/s23_clnt.c:802:

    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)

**Comment by erha19** [comment]
@githublvjing looks like that's a local environmental issue, you can use `npm` to install the toolkit, before that, you can also delete cache files from `/usr/local/lib/node_modules/weex-toolkit`.

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
