### ISSUE TITLE
WXDebugTool 中 WXDebugrepBundleJS 从哪里能下载？

### ISSUE THREAD

**Issue by hdw09** [apache/incubator-weex-cli#476]
WXDebugTool 提供了：
+ (void)setReplacedJSFramework:(NSURL*)url; 用来下载设置 WXDebugrepJSFramework
这个值会在debug开启时使用：
![image](https://user-images.githubusercontent.com/11420052/47794891-535af600-dd5c-11e8-95a1-8f2e8259af66.png)
但是问题是我从哪里去下载这个所谓的 Debug JSFramework？？
playground demo有一点点提示，但是还是不知道从哪里可以下载？
`
if ([path isEqualToString:@"/dynamic/replace/framework"]){
            for (NSString * param in [[url query] componentsSeparatedByString:@"&"]) {
                NSArray* elts = [param componentsSeparatedByString:@"="];
                if ([elts count] < 2) {
                    continue;
                }
                if ([[elts firstObject] isEqualToString:@"framework"]){
                    [WXDebugTool setReplacedJSFramework:[NSURL URLWithString:[elts lastObject]]];
                }
            }
        }
`

**Comment by erha19** [comment]
@hdw09 Maybe you can find the debug JSFramework source here: https://github.com/apache/incubator-weex/tree/master/packages/weex-js-framework.
