### ISSUE TITLE
weex run ios error

### ISSUE THREAD

**Issue by heymalio** [apache/incubator-weex-cli#479]
node -v
v9.11.1
npm -v
5.6.0

weex run ios

Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=3195D374-4AFA-4BBE-9F9C-6E9A4EC5695D -sdk iphonesimulator -derivedDataPath build clean build
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/amoy/workspace/awesome-app/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/WeexSDK.build/Objects-normal/x86_64/WXBridgeContext.o WeexSDK/ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at _buildOnSimulator (/Users/amoy/.xtoolkit/node_modules/weexpack/lib/run/ios.js:330:18)
    at /Users/amoy/.xtoolkit/node_modules/weexpack/lib/run/ios.js:302:7
    at new Promise (<anonymous>)
    at buildApp (/Users/amoy/.xtoolkit/node_modules/weexpack/lib/run/ios.js:291:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

**Comment by erha19** [comment]
@heymalio did you modify the iOS template project? or have you installed Xcode for your platform?

**Comment by erha19** [comment]
@heymalio it's inactive now, I will close this issue, if you have some more questions, please open a new issue, thanks.
