### ISSUE TITLE
run weex preview throw error

### ISSUE THREAD

**Issue by LionBuer** [apache/incubator-weex-cli#480]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] Check that your node version is >= 6 and npm version is >=4(Run `npm --version` and `node --version`).

XdeMacBook-Pro:~ x$ npm --version
6.2.0
XdeMacBook-Pro:~ x$ node --version
v10.8.0

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment

$ weex -v
   v1.3.8
 - weexpack : v1.2.5
 - weex-debugger : v1.1.4
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

- platform (Win/Mac/Ubuntu..)

Mac

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)

link: [http://dotwe.org/vue/d7792ea0634ae171d8d59eaa47756665](url)

1. weex preview /Users/x/Desktop/weex/src --entry /Users/x/Desktop/weex/src/Map.vue
2. throw error
/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/weex-vue-loader/lib/script-loader.js!/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/babel-loader/lib!/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/weex-vue-loader/lib/selector.js?type=script&index=0!./Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/Map.vue
Module not found: Error: Can't resolve './CustomButton' in '/Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components'
resolve './CustomButton' in '/Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components'
  using description file: /Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/package.json (relative path: ./src/components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/package.json (relative path: ./src/components)
    using description file: /Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/package.json (relative path: ./src/components/CustomButton)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton.json doesn't exist
      as directory
        /Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton doesn't exist
[/Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton]
[/Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton.js]
[/Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton.json]
[/Users/x/Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/CustomButton]
 @ /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/weex-vue-loader/lib/script-loader.js!/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/babel-loader/lib!/usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/weex-vue-loader/lib/selector.js?type=script&index=0!./Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/Map.vue 7:20-45
 @ ./Desktop/weex/EmergencyCommandProjectWithoutVueRouter/src/components/Map.vue?entry=true

运行weex preview 命令就报错，在Playground上可以正确显示

**Comment by LionBuer** [comment]
hhhhh?

**Comment by erha19** [comment]
@LionBuer looks like the `preview` command can't resolve `./CustomButton` module, if your project is created by `weex-toolkit`, you'd better use `npm start` command to preview your page.

**Comment by LionBuer** [comment]
> @LionBuer looks like the `preview` command can't resolve `./CustomButton` module, if your project is created by `weex-toolkit`, you'd better use `npm start` command to preview your page.

当我使用  npm start 命令的时候，不能实现在移动端客户端实时刷新的效果，必须手动退出页面再次重新进入。但是在浏览器上是有实时刷新的效果的。
而 preview 命令能实现在移动端客户端实时刷新的效果。
我怎么才能实现使用`npm start`命令在移动端客户端实时刷新的效果？？？

**Comment by LionBuer** [comment]
？？？

**Comment by erha19** [comment]
@LionBuer It doesn't support now, maybe you can check why the `webpack` can't found your local module.
The previewer and builder function of `weex-toolkit` has many problems, and we have been work on the `weex-toolkit@2.0`, it will come soon.

**Comment by erha19** [comment]
@LionBuer The feature has been supported on latest weex official template, you can re-create your project using the latest weex template and the weex playground app.

No active issue, I will close it.
