### ISSUE TITLE
使用less后，weex preview报css语法错误

### ISSUE THREAD

**Issue by zhenxianchen** [apache/incubator-weex-cli#482]
##  development environment
- weex-toolkit verison  v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.1.19
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
- platform Win10

## The key error stack message.
![image](https://user-images.githubusercontent.com/20765130/48528493-3977f200-e8ca-11e8-9277-1ed19f86c5be.png)
![image](https://user-images.githubusercontent.com/20765130/48528502-45fc4a80-e8ca-11e8-8108-d1305295af03.png)

**Comment by erha19** [comment]
@up-chen If you want to use `less` or other languages, if you use a project created by `weex-toolkit`, you'd better use the built-in module and change your config.

The `weex-toolkit@1.x` is a single tool for just look and practice, we are now working on `weex-toolkit@2.x` now, it will solve this problem with a new compiling system.

**Comment by erha19** [comment]
@up-chen I will close this issue cause it will not fix on this version, some more questions, you can open a new issue.

**Comment by zhenxianchen** [comment]
@erha19 i don`t know how to change the config to fix this problem ,can you offer me some help?

**Comment by erha19** [comment]
@up-chen see https://github.com/weex-templates/webpack#how-to-use-lesssasspug.
