### ISSUE TITLE
weex run ios error

### ISSUE THREAD

**Issue by F46886799** [apache/incubator-weex-cli#484]
## Your development environment
 - v1.3.11
 - weexpack : v1.2.7
 - weex-builder : v0.4.1
 - weex-previewer : v1.5.1

- platform Mac

## The key error stack message.

To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.2

Analyzing dependencies
Downloading dependencies
Using SDWebImage (3.7.5)
Using SocketRocket (0.4.2)
Using WeexPluginLoader (0.0.1.9.1)
Using WeexSDK (0.19.0.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
? Choose one of the following devices iPhone 6 Plus ios: 10.3.1 (Simulator)
10:14:00 : Buiding project...
** BUILD FAILED **

The following build commands failed:
	Ld build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/i386/WeexDemo normal i386
	Ld build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/WeexDemo normal x86_64
(2 failures)
10:14:03 : Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=8F77A917-B0EA-4C43-81FC-96193C5344A5 -sdk iphonesimulator -derivedDataPath build clean build
** BUILD FAILED **

The following build commands failed:
	Ld build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/i386/WeexDemo normal i386
	Ld build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/WeexDemo normal x86_64
(2 failures)

    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at _buildOnSimulator (/Users/Frank/.xtoolkit/node_modules/weexpack/lib/run/ios.js:330:18)
    at /Users/Frank/.xtoolkit/node_modules/weexpack/lib/run/ios.js:302:7
    at new Promise (<anonymous>)
    at buildApp (/Users/Frank/.xtoolkit/node_modules/weexpack/lib/run/ios.js:291:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by F46886799** [comment]
i do not know why this error happens, please give me a hand, thanks!!!

**Comment by erha19** [comment]
@wallace46886799 try to run the `platform/ios` project on XCode and see what's wrong with your environment.

**Comment by shinriyo** [comment]
Didn't you forget `weex platform add ios`?

**Comment by erha19** [comment]
@wallace46886799 @shinriyo we have been published a new version of the `weex-toolkit`, you can install it by `npm i weex-toolkit@beta -g`, maybe it can solve this problem.

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
