### ISSUE TITLE
weex preview 不支持less的mixins和函数特性

### ISSUE THREAD

**Issue by zhenxianchen** [apache/incubator-weex-cli#485]
## Your development environment
weex-toolkit verison v1.3.11
weexpack : v1.2.7
weex-debugger : v1.1.19
weex-builder : v0.4.0
weex-previewer : v1.5.1
platform Win10

## The key error stack message.

![image](https://user-images.githubusercontent.com/20765130/48833358-1f507f00-edb6-11e8-8109-b1d5cced308a.png)

![image](https://user-images.githubusercontent.com/20765130/48833416-45761f00-edb6-11e8-991a-88dfc5d7d53a.png)

**Comment by erha19** [comment]
see weexteam/weex-toolkit/issues/482.
