### ISSUE TITLE
weex-toolkit 安装失败

### ISSUE THREAD

**Issue by 330570902** [apache/incubator-weex-cli#488]
执行 npm install -g weex-toolkit  报错信息如下：

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "weex-toolkit"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path D:\Program Files\nodejs\node_global\node_modules\weex-toolkit\node_modules\acorn
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access

npm ERR! enoent ENOENT: no such file or directory, access 'D:\Program Files\nodejs\node_global\node_modules\weex-toolkit\node_modules\acorn'
npm ERR! enoent ENOENT: no such file or directory, access 'D:\Program Files\nodejs\node_global\node_modules\weex-toolkit\node_modules\acorn'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2018-11-23T10_52_33_549Z-debug.log

文件 D:\Program Files\nodejs\node_global\node_modules\weex-toolkit\node_modules\acorn 不存在，node_modules目录下有_acorn开头的文件夹。

**Comment by erha19** [comment]
@330570902 delete files on `D:\Program Files\nodejs\node_global\node_modules\weex-toolkit`, then try install again.
