### ISSUE TITLE
Error: weex run android

### ISSUE THREAD

**Issue by ukik** [apache/incubator-weex-cli#489]
============Build Config============
AppId        : com.alibaba.weex
AppName      : WeexApp
SplashText   : Hello
Weex
WeexBundle   : index.js
22:02:38 : If you want to change build config.please modify android.config.json
22:02:38 : Building app ...

BUILD FAILED

Total time: 8.752 secs
Error: Command failed: call gradlew.bat  assembleRelease
isLibProject: false, isAppProject: true
weex_plugin: []

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not find support-annotations.jar (com.android.support:support-annotations:26.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    at checkExecSyncError (child_process.js:596:11)
    at Object.execSync (child_process.js:633:13)
    at C:\Users\asuki (agus n ukik)\.xtoolkit\node_modules\weexpack\lib\build\android.js:156:20
    at new Promise (<anonymous>)
    at buildApp (C:\Users\asuki (agus n ukik)\.xtoolkit\node_modules\weexpack\lib\build\android.js:152:10)
    at process._tickCallback (internal/process/next_tick.js:178:7)
Error: Error: Command failed: call gradlew.bat  assembleRelease
isLibProject: false, isAppProject: true
weex_plugin: []

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not find support-annotations.jar (com.android.support:support-annotations:26.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by erha19** [comment]
@ukik maybe you should upgrade your android-tools to the latest version.

**Comment by shinriyo** [comment]
Didn't you forget `weex platform add android`?
