### ISSUE TITLE
Weex debug not work   and page not change

### ISSUE THREAD

**Issue by quanchaoguo** [apache/incubator-weex-cli#493]
## Your development environment
 v1.3.11
 - weex-debugger : v1.2.5
 - weex-builder : v0.4.1
 - weex-previewer : v1.5.1

## The key error stack message.

I update weex-toolkit to v1.3.11 version

old version is ok page：
<img width="641" alt="2018-12-05 7 25 31" src="https://user-images.githubusercontent.com/32917790/49510564-8d6f6880-f8c3-11e8-8afc-af14504c72f3.png">

weex debug page is bad page on:

<img width="1430" alt="2018-12-05 7 23 04" src="https://user-images.githubusercontent.com/32917790/49510450-39648400-f8c3-11e8-989c-d6dfff69003c.png">

 i scan  and Android simulator is not worker

is my dist 
<img width="273" alt="2018-12-05 7 27 45" src="https://user-images.githubusercontent.com/32917790/49510689-f525b380-f8c3-11e8-90cb-b0a084fab9c7.png">

**Comment by rcupid** [comment]
I had the same problem.

**Comment by erha19** [comment]
@quanchaoguo you should make sure the simulator can connect with the local WLAN.
