### ISSUE TITLE
the init project got incorrect env value in production mode

### ISSUE THREAD

**Issue by malin1988** [apache/incubator-weex-cli#496]
## Your development environment
- weex-toolkit verison (Run `weex -v`)  v1.3.11
- platform (Win/Mac/Ubuntu..) mac

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link,)
After run `npm run build:prod`, in jsbundle the process.env.NODE_ENV is 'development'. I think there are bugs in webpack's config

**Comment by erha19** [comment]
@malin1988 thanks for your report, now you can re-run `weex create` command to create a new project, or you can modify your code like the commit above.
