### ISSUE TITLE
weex debug 调试问题

### ISSUE THREAD

**Issue by TingYuLC** [apache/incubator-weex-cli#498]
之前0.19版的android playground js debug无法使用，这几天更新了0.20的，结果控制输出一堆无用的信息，而且每次切换页面都会刷新一遍，自己输出的日志都不知去哪了。。。
还有，network一直不能调试post请求，以及使用weex deubg然后用playground 扫码后一直处于loading状态
调试这块一直没搞通。
![image](https://user-images.githubusercontent.com/13540973/50507034-ae883b00-0ab6-11e9-9711-7673ad42c67d.png)

![image](https://user-images.githubusercontent.com/13540973/50507082-dbd4e900-0ab6-11e9-800d-e371ae34742f.png)

**Comment by erha19** [comment]
@TingYuLC The debugger will output the native log by default, while you open the `JSDebug` switch, the console page will only output the JS log.

**Comment by erha19** [comment]
no longer activated, I will close this issue.
