### ISSUE TITLE
android hot-reload（安卓无法热加载）

### ISSUE THREAD

**Issue by TingYuLC** [apache/incubator-weex-cli#499]
android无法进行热更新，管理员权限方法都试过，只要刷新代码要么卡住，要么operation not permitted
![image](https://user-images.githubusercontent.com/13540973/50507251-ab417f00-0ab7-11e9-9fb3-3707cfa26cd7.png)

![image](https://user-images.githubusercontent.com/13540973/50507255-aed50600-0ab7-11e9-8528-83dd75fbdf5b.png)

**Comment by erha19** [comment]
@TingYuLC you need to use the admin account to run this command.
