### ISSUE TITLE
Postinstall fails with `xtoolkit install weex-builder`

### ISSUE THREAD

**Issue by IniZio** [apache/incubator-weex-cli#50]
When I tried to install weex-toolkit, it seems to error at postinstall

`node -v`: v6.3.1
`npm -v`: 3.10.3

command: `sudo npm i -g weex-toolkit@beta`

Log:
```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/weex -> /usr/local/lib/node_modules/weex-toolkit/bin/weex

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/spawn-sync
> node postinstall


> weex-previewer@1.2.6 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/weex-previewer
> node ./src/hook/post-install.js

Error:permission denied.Please apply the write premission to the directory: "/home/iniz" 

> weex-toolkit@1.0.1-beta.5 postinstall /usr/local/lib/node_modules/weex-toolkit
> xtoolkit install weex-builder

/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/src/util/index.js:8
    let args = ['install', name, '--loglevel=error'];
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/weex-toolkit/node_modules/xtoolkit/bin/xtoolkit.js:6:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
/usr/local/lib
└── (empty)
```

**Comment by n9ti** [comment]
I also got this issue

**Comment by IniZio** [comment]
temporarily using a workaround by setting the prefix of node `npm config set prefix '~/.npm-global'`, such that only owner permission is needed. However since my environment uses oh-my-zsh and nvm, seems to not be working well with the solution. Currently nvm displays an error message that it does not support prefix config.

Looking for better solution/workaround

**Comment by aslinwang** [comment]
check the version on node 
it works when i update node to v7.5.0

**Comment by n9ti** [comment]
I change from npm to cnpm and then it work for me.

**Comment by exolution** [comment]
@IniZio 
very strange
"SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode" this error mean your node version <6.0 (not support es6) but your node version is 6.3,may be you have not only one node

First of all, I recommend not to use “sudo install” .
if the permissions exception occurs,try "sudo chmod 777 /usr/local/lib/node_module"(becasue your node was installed by root)

**Comment by IniZio** [comment]
if just using npm i think setting prefix to make global packages be storeed at `~/.npm-globals` will not require sudo everytime. But since I am using nvm it does not support using prefix

**Comment by exolution** [comment]
in new version 1.0.2 i remove post-install
