### ISSUE TITLE
按照文档初建项目运行成功但是无法初始化界面并且报错

### ISSUE THREAD

**Issue by AbsoluteLayout** [apache/incubator-weex-cli#501]
DONE Compiled successfully in 73ms 11:17:10
I Your application is running here: http://192.168.2.171:8081.

版本
E:ForiPrJSWeekc>weex -v
v1.3.11

weexpack : v1.2.7
weex-builder : v0.4.0
weex-previewer : v1.5.1
E:ForiPrJSWeekc>npm -v
[5.6.0]
![tim 20190104112033](https://user-images.githubusercontent.com/19956719/50680351-6632c500-1042-11e9-8888-961259417221.png)

**Comment by erha19** [comment]
@AbsoluteLayout you can just run `npm i && npm start` in your project or you can use the 2.x version to preview your page, you can install it by `npm i weex-toolkit@alpha -g`, then use the preview command to preview your page.

**Comment by AbsoluteLayout** [comment]
@erha19   谢谢你的帮助 但是没有运行成功是不是我配置或者命令输入有问题

**Comment by AbsoluteLayout** [comment]
![tim 20190105173625](https://user-images.githubusercontent.com/19956719/50722882-ed4e6e80-1110-11e9-8931-0f149caa6a79.png)
![tim 20190105173805](https://user-images.githubusercontent.com/19956719/50722883-efb0c880-1110-11e9-92fd-45da19fbcf48.png)

**Comment by erha19** [comment]
issue https://github.com/webpack/webpack/issues/4039.

**Comment by erha19** [comment]
@AbsoluteLayout you can re-create the project by `weex create [name] --no-cache`, it should be fixed on the latest template.

**Comment by AbsoluteLayout** [comment]
@erha19  谢谢你,可以看到视图了
