### ISSUE TITLE
Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=00F68E92-82A6-4AF6-9AA7-7AB427193D4D -sdk iphonesimulator -derivedDataPath build clean build

### ISSUE THREAD

**Issue by ngogia20** [apache/incubator-weex-cli#505]
============Build Config============
AppName      : WeexApp
Version      : 0.1
BuildVersion : 0.1.0
AppId        : com.alibaba.weex
WeexBundle   : index.js
Ws           : ws://192.168.5.103:8080
CodeSign     : 
Profile      : 
17:14:55 : If you want to change build config.please modify ios.config.json
17:14:55 : pod update
17:14:55 : Hot Reload socket: ws://192.168.5.103:8080
Update all pods
Updating local specs repositories
 10% [1] building modules 4/4 modules 0 active  $ /usr/local/bin/git -C /Users/nikeshgogia/.cocoapods/repos/master fetch origin --progress
 55% [1] Wait Reload...                                                                  
  remote: Enumerating objects: 63, done.                                                 
  remote: Counting objects: 100% (63/63), done.        
  remote: Compressing objects: 100% (32/32), done.        
  remote: Total 45 (delta 27), reused 16 (delta 9), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     d4b96487237..7613052276c  master     -> origin/master
  $ /usr/local/bin/git -C /Users/nikeshgogia/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/nikeshgogia/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 7613052276c [Add] DigiAdzMediation 1.0.10
Analyzing dependencies
Downloading dependencies
Using SDWebImage (3.7.5)
Using SocketRocket (0.4.2)
Using WeexPluginLoader (0.0.1.9.1)
Using WeexSDK (0.20.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
? Choose one of the following devices iPhone SE ios: 10.3.1 (Simulator)
17:16:40 : Buiding project...
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/nikeshgogia/weex/helloworld/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/WeexSDK.build/Objects-normal/x86_64/wson_util.o WeexSDK/weex_core/Source/wson/wson_util.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
17:16:59 : Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=00F68E92-82A6-4AF6-9AA7-7AB427193D4D -sdk iphonesimulator -derivedDataPath build clean build
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/nikeshgogia/weex/helloworld/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/WeexSDK.build/Objects-normal/x86_64/wson_util.o WeexSDK/weex_core/Source/wson/wson_util.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at checkExecSyncError (child_process.js:637:11)
    at Object.execSync (child_process.js:674:13)
    at _buildOnSimulator (/Users/nikeshgogia/.xtoolkit/node_modules/weexpack/lib/run/ios.js:330:18)
    at /Users/nikeshgogia/.xtoolkit/node_modules/weexpack/lib/run/ios.js:302:7
    at new Promise (<anonymous>)
    at buildApp (/Users/nikeshgogia/.xtoolkit/node_modules/weexpack/lib/run/ios.js:291:10)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Nikeshs-MacBook-Pro:helloworld nikeshgogia$

**Comment by erha19** [comment]
@ngogia20 try to use the beta version of the toolkit, you can install it by `npm i weex-toolkit@beta -g`.

**Comment by erha19** [comment]
No longer active, I will close this issue, if have further questions, please open a new issue.
