### ISSUE TITLE
Weex Studio 选择器下拉框没有选项（2018年5月份建的项目）

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#506]
Weex Studio 版本：3.1.0
weex -v
    v1.3.11
 - weexpack : v1.2.7
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

项目是2018年上半年创建的，使用weex studio打开后，选择器里没有项目。如图：
![0745ef60-c8d9-425e-9c76-4c4e58c88fb4](https://user-images.githubusercontent.com/41984848/53401775-6b314680-39eb-11e9-9e10-65572824fbd2.png)

**Comment by erha19** [comment]
@zhongwang2008 look like weex studio doesn't support the old project, you may need to upgrade your project now, maybe @GGICE  can help you.
