### ISSUE TITLE
weex -v 无法下载@weex-cli/core

### ISSUE THREAD

**Issue by hpstream** [apache/incubator-weex-cli#507]
![image](https://user-images.githubusercontent.com/18394192/53470835-ca4f9380-3a9d-11e9-80b4-3134417a64fd.png)

**Comment by erha19** [comment]
@hpstream try `weex repair` again.

**Comment by timeTravelCYN** [comment]
@erha19 
![image](https://user-images.githubusercontent.com/25972282/53778280-22bbe080-3f37-11e9-8c28-0f2301d4b535.png)
hey，I try this. but it doesn't work yet.how should I do？Looking forward to your reply. thanks!

**Comment by erha19** [comment]
@timeTravelCYN can you download package from this link http://registry.npm.taobao.org/@weex-cli/core/download/@weex-cli/core-2.0.0-beta.2.tgz ?

**Comment by erha19** [comment]
No longer active now, I will close this issue, be free to reopen it.
