### ISSUE TITLE
执行weex run android错误信息乱码

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#508]
weex -v
2.0.0-beta.2
- @weex-cli/run : v2.0.0-beta.2
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/debug : v2.0.0-beta.2
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/generator : v2.0.0-beta.2
- @weex-cli/build : v2.0.0-beta.2

新建项目后，执行weex run android命令后，错误提示信息乱码！其他中文不乱码，比如查看文件夹列表；如图
![c92fde87-7638-411a-b970-7ca600d452ad](https://user-images.githubusercontent.com/41984848/53550569-f2102b80-3b71-11e9-9965-3b6518604575.png)

**Comment by erha19** [comment]
@zhongwang2008 upgrade `@weex-cli/core` to `2.0.0-beta.3`, it should be fixed now.  
Try `weex repair @weex-cli/core@latest`.
Details see https://github.com/weexteam/weex-toolkit/commit/d748a4088aa5438b8c7851192abf56ba72dbde95.

Let me know if it work or not, thanks.
