### ISSUE TITLE
$weex debug foo.vue出错了

### ISSUE THREAD

**Issue by ChowYoung** [apache/incubator-weex-cli#51]
weex init 之后，直接 `$weex debug src/foo.vue`，二维码都出来了，但是扫码后报错（debug模式下）

<img width="524" alt="wx20170203-122558 2x" src="https://cloud.githubusercontent.com/assets/17489186/22579550/f5d57f04-ea0b-11e6-8880-5fe1ec5c4f96.png">

**Comment by exolution** [comment]
现有的playground还不支持vue 马上会发布新版的

**Comment by csvwolf** [comment]
@exolution 编译了 iOS 的 playground，扫码开启远程 Debug 也闪退 是因为不支持吗？
