### ISSUE TITLE
weex doctor error

### ISSUE THREAD

**Issue by mario-huang** [apache/incubator-weex-cli#512]
My mac installed xcode 10 and it runs well every day.
But when I run
`weex doctor`
I get this error:
[!] iOS toolchain - develop for iOS devices
    •  Xcode at /Library/Developer/CommandLineTools
    ✗  Weex requires a minimum Xcode version of 9.0.0.

          Download the latest version or update via the Mac App Store.
    ✗  Xcode requires additional components to be installed in order to run.
      '
          Launch Xcode and install additional required components when prompted.
    •  CocoaPods version 1.6.1

✔︎ Weex Cli Environment (v2.0.0-beta.2, on darwin 18.2.0):

weex -v
2.0.0-beta.2
- @weex-cli/generator : v2.0.0-beta.3
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.2
- @weex-cli/run : v2.0.0-beta.2
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.2

**Comment by erha19** [comment]
@myeveryheart Is the `weex run ios` command works fine?

**Comment by mario-huang** [comment]
> @myeveryheart Is the `weex run ios` command works fine?

not ok
```
weex run ios
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
[✔︎] Compile JSBundle done
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
? Select one of the device (Use arrow keys)
```
It can not find my simulaters. And I have installed instruments.

**Comment by mario-huang** [comment]
This is my xcode problem, I have fixed. Thank you for your time.
