### ISSUE TITLE
Sorry, didn't recognize that command!

### ISSUE THREAD

**Issue by manjuk41** [apache/incubator-weex-cli#514]
Hi, Unable to create plugin, After upgrading to v2.0.0-beta.6.

$ weex plugin create pTest

  Sorry, didn't recognize that command!
  Type weex help to view common commands.

**Comment by erha19** [comment]
@manjuk41  name can no longer contain capital letters, try `p-test`.

**Comment by manjuk41** [comment]
@erha19 tried and still its not working. Also tired to downgrade version, still no luck.
The command 'plugin' itself is not recognising.

**Comment by manjuk41** [comment]
@erha19 removed weex-toolkit manually and installing it again worked.

**Comment by shen-lan** [comment]
![image](https://user-images.githubusercontent.com/21122615/54988214-e9840700-4ff0-11e9-9ebd-a14ed628806b.png)
卸载重装一样的报错

**Comment by iusn** [comment]
me too
i delete 
~/.wx/modules/node_modules/
then weex not work

i reinstall
npm i -g weex-toolkit
but not work
![image](https://user-images.githubusercontent.com/11364258/68727937-c8fcd180-0600-11ea-8aba-37b3803326e8.png)

install success
but
![image](https://user-images.githubusercontent.com/11364258/68727967-e3cf4600-0600-11ea-8550-0ab50c67fcd4.png)

![image](https://user-images.githubusercontent.com/11364258/68727986-f34e8f00-0600-11ea-88df-6a6bedc0a434.png)
