### ISSUE TITLE
希望debug加上之前devtool的热更新功能

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex-cli#515]
![image](https://user-images.githubusercontent.com/36951996/54731566-e42a5500-4bc9-11e9-99d1-794a0c40bad9.png)

**Comment by fanlvwen** [comment]
了解了一下 部分开发者是用preview之后ok再打包js到真机run，这样的效率实在是极其极其的低了，而且如果是混合开发，原生需要传参到weex页面这种情况，更不知道如何处理了，所以之前devtool的热更行功能还是很有必要的，大佬帮忙加一下这个功能，辛苦谢谢！

**Comment by erha19** [comment]
@fanlvwen try `weex update @weex-cli/debug`.

**Comment by fanlvwen** [comment]
> @fanlvwen try `weex update @weex-cli/debug`.

thank you very much!

**Comment by fanlvwen** [comment]
@erha19 但是保存weex代码 重复几次之后app崩溃了
