### ISSUE TITLE
Vue packages version mismatch:

### ISSUE THREAD

**Issue by iOSGL** [apache/incubator-weex-cli#516]
![image](https://user-images.githubusercontent.com/8703661/54904881-9c356600-4f1a-11e9-941e-8ec8ab60ab35.png)
![image](https://user-images.githubusercontent.com/8703661/54904921-ae170900-4f1a-11e9-923a-c794ebfc0613.png)

Could you tell me how to solve this prolem? 

but in weex v1.3.11,  its ok

**Comment by fanlvwen** [comment]
weex repair试试，

**Comment by iOSGL** [comment]
> weex repair试试，

不行

**Comment by erha19** [comment]
@geng199200 @fanlvwen I have upgrade `@weex-cli/doctor` module to support auto fit this issue. 
try below command and make sure the version of `@weex-cli/core` need to be `v2.0.0-beta.9+`.
```
$ weex repair @weex-cli/core@latest
$ weex update @weex-cli/doctor
$ weex doctor
```
This script will fix this issue automatically.

**Comment by fanlvwen** [comment]
@erha19 

> $ weex repair @weex-cli/core@latest
> $ weex update @weex-cli/doctor
> $ weex doctor

![1D06E37C-5693-44BA-8CA8-F3B1DC1021EF](https://user-images.githubusercontent.com/36951996/54988374-47b0ea00-4ff1-11e9-8d03-e301b094a60f.png)
![380DF03B-F9CD-4FBC-9C5A-D5537FD1C826](https://user-images.githubusercontent.com/36951996/54988383-4aabda80-4ff1-11e9-955c-4c2b4e1a4c17.png)

会把/Users/tiexing/.wx/modules/node_modules目录下的两个vue-template-compiler@2.5.21和vue-template-compiler@2.6.10都删掉了，到时项目debug src报错

**Comment by erha19** [comment]
@fanlvwen `weex repair @weex-cli/core@latest` 这个命令你没有运行生效（core版本应为 2.0.0-beta.9+），导致安装依赖的脚本无法运行
![image](https://user-images.githubusercontent.com/9823838/55046813-b63b8980-507d-11e9-9672-42742f09b5f2.png)
你可以运行一下 `weex repair @weex-cli/compile` 修复构建的问题
