### ISSUE TITLE
安装成功后除了weex -v以外的命令均提示  不认识命令

### ISSUE THREAD

**Issue by shen-lan** [apache/incubator-weex-cli#518]
安装卸载重复了很多遍。都是一样。
只能执行weex -v。
其他的诸如 weex  doctor/create，
均提示：
```
  Sorry, didn't recognize that command!
  Type weex help to view common commands.
```
【注】：已确定 `C:\Users\xxx\AppData\Roaming\npm` 删掉后重装的。

**Comment by erha19** [comment]
@shen-lan 重新运行一下`npm i weex-toolkit@beta -g`, 运行命令试一下，有问题截图贴一下。

**Comment by cashsay** [comment]
我也是遇到同样的问题。
$ weex -v
2.0.0-beta.9
- @weex-cli/debug : v2.0.0-beta.7
- @weex-cli/compile : v2.0.0-beta.2


$ weex doctor 

  Sorry, didn't recognize that command!
  Type weex help to view common commands.

**Comment by erha19** [comment]
@cashsay 你的使用环境是windows还是mac？你可以尝试使用install命令安装doctor插件，安装前请运行一下 `weex config list` 给我你的配置进行这个问题的定位。

安装doctor插件命令 `weex install @weex-cli/doctor`

**Comment by wbcyclist** [comment]
mac环境 node v8.11.2，一样‘recognize that command’的问题，从昨天升级了bate7后就出现了，之后尝试了bate8、bate9，安装前都进行了清空本地包(`npm uninstall -g weex-toolkit && rm -rf ~/.wx && rm -rf ~/.weex_tmp`) ，问题依旧。

然后发现
```
$ npm install -g weex-toolkit@beta
$ weex -v
2.0.0-beta.9
```
默认是没有安装任何组件的。然后就按照文档上说的系统组件一个一个安装上去
<img width="521" alt="屏幕快照 2019-03-27 上午11 43 06" src="https://user-images.githubusercontent.com/2424522/55049118-cd7e7500-5085-11e9-8a5a-ceed3f27bb52.png">

```
weex install @weex-cli/core
weex install @weex-cli/generator
weex install @weex-cli/compile
weex install @weex-cli/preview
weex install @weex-cli/debug
weex install @weex-cli/doctor
weex install @weex-cli/lint
weex install @weex-cli/device
weex install @weex-cli/run
```
组件安装完后doctor一下 `weex doctor`
```
$ weex -v
2.0.0-beta.9
- @weex-cli/generator : v2.0.0-beta.7
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.2
- @weex-cli/debug : v2.0.0-beta.9
- @weex-cli/doctor : v2.0.0-beta.9
- @weex-cli/lint : v2.0.0-beta.2
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/run : v2.0.0-beta.2
```

这下环境就好了。

**Comment by erha19** [comment]
@cashsay @shen-lan `weex repair @weex-cli/core@latest` 运行一下，后面应该能解决你的问题

**Comment by shen-lan** [comment]
@erha19 感谢你的回复。
1. 执行 `weex repair @weex-cli/core@latest` 后
```
Start checking Core, please wait ...
compelied, cost 37.6s
? May weex-toolkit anonymously report usage statistics to improve the tool over
? Which npm registry you perfer to use? (Use arrow keys)
? Which npm registry you perfer to use? taobao

  Sorry, didn't recognize that command!
  Type weex help to view common commands.
```
仍然不行。
2. 于是再次尝试 @wbcyclist 的方法：
```
weex install @weex-cli/core
weex install @weex-cli/generator
weex install @weex-cli/compile
weex install @weex-cli/preview
weex install @weex-cli/debug
weex install @weex-cli/doctor
weex install @weex-cli/lint
weex install @weex-cli/device
weex install @weex-cli/run
```
报错 
```
$ weex install @weex-cli/doctor
Error: module is locked
```

**Comment by erha19** [comment]
@shen-lan `module is locked` 加上 `-f`参数即可`weex install @weex-cli/doctor -f`,  你可以二次运行一下`weex doctor`, 这个问题我今天修复。

**Comment by shen-lan** [comment]
> @shen-lan `module is locked` 加上 `-f`参数即可`weex install @weex-cli/doctor -f`, 你可以二次运行一下`weex doctor`, 这个问题我今天修复。

加上 `-f `参数仍然报一样的错误 `Error: module is locked`

**Comment by erha19** [comment]
@shen-lan `weex repair @weex-cli/doctor -f` 这个命令修复下

**Comment by shen-lan** [comment]
可以了 谢谢

**Comment by xuegeliu** [comment]
node with npm version mis
