### ISSUE TITLE
问个jsbundle的问题啊

### ISSUE THREAD

**Issue by segatecm** [apache/incubator-weex-cli#52]
用 $weex compile path/to/\*.vue,\*.js . 命令编译，会把所有的js文件都编成了一个。
那我如果要用其中一个文件的js，该怎么写啊：
比如
`<embed
      v-for="item in tabItems"
      :src="item.src"
      type="weex"
      :style="{ visibility: item.visibility }"
      class="content"
      >
</embed>`

这里的:src需要写一个js文件，如果写 src: 'tabcontent.js?itemId=tab1'

这个tabcontent.js已经被编译到一个文件里面了，在ios平台上访问不到了，该怎么办。

**Comment by daizheng521** [comment]
同问

**Comment by exolution** [comment]
记得 转义*  \*
这个命令不会只编译成1个js呀 
整个目录下的都会编译
