### ISSUE TITLE
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#520]
2.0.0-beta.9
- @weex-cli/generator : v2.0.0-beta.7
- @weex-cli/preview : v2.0.0-beta.2
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/core : v2.0.0-beta.10
- @weex-cli/debug : v2.0.0-beta.9

执行weex debug命令，出现以图所示错误：
![menu saveimg savepath20190327161636](https://user-images.githubusercontent.com/41984848/55060149-c5393080-50ab-11e9-801e-bcb232c4a439.jpg)

**Comment by erha19** [comment]
@zhongwang2008 手动到用户目录下，把`puppeteer`这个node_module删了, 然后重新运行一下卸载及安装程序。

**Comment by zhongwang2008** [comment]
@erha19 删除用户目录（C:\Users\VOC\.wx\modules\node_modules）下的puppeteer后，仍然未下载Chromium；
该错误提示还是存在；

**Comment by erha19** [comment]
@zhongwang2008 运行一下 `weex repair @weex-cli/core@latest`,  同时删`C:\Users\VOC.wx\modules`目录内容，然后运行一下 `set DEBUG=weex && weex debug`，如果还有问题，请把日志截图给我

**Comment by zhongwang2008** [comment]
@erha19 问题已解决！
