### ISSUE TITLE
执行weex run android提示信息乱码

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#521]
2.0.0-beta.9
- @weex-cli/debug : v2.0.0-beta.9
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/run : v2.0.0-beta.2
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.10

执行weex run android提示信息乱码，如下图所示：
![menu saveimg savepath20190328161221](https://user-images.githubusercontent.com/41984848/55141140-b1a5cc80-5174-11e9-9d7a-ed5055178dba.jpg)

**Comment by erha19** [comment]
@zhongwang2008 try `weex update @weex-cli/run`, the problem will be fixed.
