### ISSUE TITLE
Weex模板下载问题，Download from weex-templates/weex-playground-android repo ...

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#523]
2.0.0-beta.13
- @weex-cli/generator : v2.0.0-beta.7

执行weex platform add android命令后，weex-templates一直处在下载状态；如图所示：
![9993D5D3-3DFC-4b88-9538-17624E57D798](https://user-images.githubusercontent.com/41984848/55206127-5c1efd80-5210-11e9-98c0-3069632a49df.png)

**Comment by erha19** [comment]
@zhongwang2008 检查一下你的网络是否能正常克隆远程仓库，是否支持git操作，找个空目录试一下 `git clone https://github.com/weex-templates/weex-playground-android.git`。

**Comment by zhongwang2008** [comment]
@erha19 公司网络问题，重启电脑后就可以正常克隆远程仓库，下载比较慢；
![9E0AA6F1-0A68-4ff1-AA3E-7915AD46BF3F](https://user-images.githubusercontent.com/41984848/55207214-3eec2e00-5214-11e9-91da-67eb4eec648f.png)

**Comment by erha19** [comment]
@zhongwang2008 网络正常后尝试一下上面操作，操作一次后后续都会有缓存的。

**Comment by zhongwang2008** [comment]
@erha19 模板正常下载完成，问题已解决！
