### ISSUE TITLE
[Android][Weex Devtools] 0.20.3.0-beta环境下连上Weex Devtools Android Module函数返回的值类型错误

### ISSUE THREAD

**Issue by ken-iheha** [apache/incubator-weex-cli#524]
# **Describe the bug**

在 0.20.3.0-beta环境下连接Weex Devtools工具进行js debug，在Android机器上出现 module中的函数返回值(Map)在js代码中变成string类型的情况，如果断开Devtools连接，又会恢复正常。

# **Environment**

Device: [华为mate10]
OS: [emui 9.0]
WEEX SDK版本
0.20.3.0-beta
weex inspector版本
0.20.3.0-beta

### **代码**

测试代码如下：

**Android module**
![54982128-fb5fad00-4fe4-11e9-9db9-68361b7e3b36](https://user-images.githubusercontent.com/16402510/55300182-efeb0680-5468-11e9-913f-a9db753a677c.png)

**weex 测试代码**
![54982136-00246100-4fe5-11e9-9f79-e8bcb4db7520](https://user-images.githubusercontent.com/16402510/55300175-e8c3f880-5468-11e9-9e61-3e92b1b64a46.png)

### **运行结果**

**不连 Weex Devtools**
![54982048-cc493b80-4fe4-11e9-96b8-e8f912f2c09d](https://user-images.githubusercontent.com/16402510/55300172-dd70cd00-5468-11e9-8cfb-6e8be8ffa063.png)

**连上Weex Devtools**
![54982049-cce1d200-4fe4-11e9-9ade-2f0fc41ca5ba](https://user-images.githubusercontent.com/16402510/55300166-d8ac1900-5468-11e9-89d4-fc50a767e9fc.png)

**环境**
![54982493-eb949880-4fe5-11e9-8784-e31e7b3c55a7](https://user-images.githubusercontent.com/16402510/55300155-ce8a1a80-5468-11e9-90e8-37b5975e8d52.png)

p.s. Same problem has been reported in the [incubator-weex](https://github.com/apache/incubator-weex/issues/2246) and redirected here.

**Comment by erha19** [comment]
@ken-iheha 目前调试这块的消息通信主要是通过websocket实现的，所有的值传递（如你这里的weex.requireModule('test')）在数据传输过程中都会转换为`string`类型，故无法实现 ` Map`类型值的转化，建议调试环境下通过其他方式绕开这层判断或不依赖客户端回传值的类型判断

**Comment by ken-iheha** [comment]
@erha19 这个问题在之前的weex 版本 0.19.x 都没出现是什麽原因呢？

**Comment by erha19** [comment]
@ken-iheha `0.20.+`版本开始使用weex开发的weex core替换了原先使用的javascript core，可能也是这部分改造导致的与V8（调试环境）不对齐。

**Comment by erha19** [comment]
@ken-iheha maybe you can use a judge block to solve this issue.
```
if (typeof test === 'string') {
  test = JSON.parse(test)
}
```

Invalid issue, any other questions you can create a new issue.
