### ISSUE TITLE
@weex/core is missing 'lib' dir in v2.0.0-beta.15

### ISSUE THREAD

**Issue by NickeyLin** [apache/incubator-weex-cli#526]
The version 2.0.0-beta.15 you published, missing the 'lib' dir. That cause whatever command of weex I run , it is always been repairing.  @erha19 

update: `genertator` has no 'lib' too.

**Comment by erha19** [comment]
@NickeyLin try `weex repair @weex-cli/core@2.0.0-beta.14 && weex repair @weex-cli/genertator@2.0.0-beta.14`, I will fix this issue soon.
