### ISSUE TITLE
weex-cli/core from 2.0.0-beta.2 -> 2.0.0-beta.16 ...upgrade error

### ISSUE THREAD

**Issue by cyabc** [apache/incubator-weex-cli#527]
New version detected 2.0.0-beta.16, the local version is 2.0.0-beta.2, upgrade now？[Y/n]y
upgrading @weex-cli/core from 2.0.0-beta.2 -> 2.0.0-beta.16 ...
Upgrading @weex-cli/core, please wait ...
√ Installed 1 packages
√ Linked 301 latest versions
√ Run 0 scripts
deprecate @weex-cli/core@2.0.0-beta.16 › npminstall@3.20.2 › urllib@2.33.2 › proxy-agent@2.3.1 › socks-proxy-agent@3.0.1 › socks@^1.1.10 If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
Recently updated (since 2019-03-27): 4 packages (detail see file C:\Users\tdxypf\.wx\core\node_modules\.recently_updates.txt)
  2019-04-02
    → @weex-cli/core@2.0.0-beta.16(2.0.0-beta.16) (17:44:45)
  2019-04-01
    → @weex-cli/core@2.0.0-beta.16 › npminstall@3.20.2 › urllib@2.33.2 › proxy-agent@2.3.1 › pac-proxy-agent@2.0.2 › get-uri@2.0.3 › readable-stream@3(3.3.0) (15:11:42)
  2019-03-28
    → @weex-cli/core@2.0.0-beta.16 › npminstall@3.20.2 › binary-mirror-config@^1.19.0(1.20.0) (22:13:12)
    → @weex-cli/core@2.0.0-beta.16 › npminstall@3.20.2 › urllib@2.33.2 › proxy-agent@2.3.1 › pac-proxy-agent@2.0.2 › pac-resolver@3.0.0 › degenerator@1.0.4 › ast-types@0.x.x(0.12.3) (08:24:14)
√ All packages installed (334 packages installed from npm registry, used 42s(network 42s), speed 166.9kB/s, json 302(551.59kB), tarball 6.31MB)

Start checking Core, please wait ...
compelied, cost 63.673s
Time: 14:28:56, verify if there is an update
TypeError: Cannot read property 'error' of null
    at <anonymous> (C:\Users\tdxypf\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.16@@weex-cli\core\src\cli\cli.ts:537:22)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\tdxypf\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.16@@weex-cli\core\lib\cli\cli.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by erha19** [comment]
@cyabc try `weex repair` command. If it does not work, please try another command `set DEBUG=weex&&weex repair` and show me the errors.

**Comment by cyabc** [comment]
> @cyabc try `weex repair` command. If it does not work, please try another command `set DEBUG=weex&&weex repair` and show me the errors.

$ weex debug
Time: 15:27:37, verify if there is an update
TypeError: Cannot read property 'error' of null
    at <anonymous> (C:\Users\tdxypf\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.16@@weex-cli\core\src\cli\cli.ts:537:22)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\tdxypf\.wx\core\node_modules\_@weex-cli_core@2.0.0-beta.16@@weex-cli\core\lib\cli\cli.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
the same error info

**Comment by erha19** [comment]
@cyabc try `weex config set registry https://registry.npm.taobao.org/`, then try it again.

**Comment by erha19** [comment]
upgrade `@weex-cli/core` by `weex repair`.
