### ISSUE TITLE
weex run android命令选择手机设备建议

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#528]
2.0.0-beta.16
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.15
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.10
- @weex-cli/run : v2.0.0-beta.15
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.16
- @weex-cli/lint : v2.0.0-beta.2
实际开发时只使用一个手机设备，建议检测到只有一个设备时，自动运行这个设备，这样又方便使用，又节省时间。如果没有检测到设备，自动退出本些运行（Ctrl+ C）。如图下所示：
![4AC967FB-C43D-4432-818A-A527D0C419DE](https://user-images.githubusercontent.com/41984848/55464256-47d26a80-562d-11e9-8650-31ac7ba010eb.png)

**Comment by erha19** [comment]
@zhongwang2008 done, try `weex update @weex-cli/run`.
