### ISSUE TITLE
weex run --entry参数设置子目录的页面，热重载不起作用

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#529]
2.0.0-beta.16
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.15
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.10
- @weex-cli/run : v2.0.0-beta.15
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.16
- @weex-cli/lint : v2.0.0-beta.2
直接举例说明，weex run android --entry omms/signed/todo.js 这样设置执行后，代码保存后页面没有刷新。

**Comment by erha19** [comment]
@zhongwang2008 我这边测试正常，你检查下你的路径下是否有`src/omms/signed/todo.vue`这个文件

**Comment by zhongwang2008** [comment]
@erha19 我换了个简单的页面试了一下，页面还是不刷新；不过，终端日志里一行change null的记录；
测试页面路径：omms\statistics\statistics.js
如图所示：
![QQ截图20190404092938](https://user-images.githubusercontent.com/41984848/55523499-2f5d6100-56bc-11e9-88d1-10535b2991f6.png)

2.0.0-beta.16
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.17
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.10
- @weex-cli/run : v2.0.0-beta.17
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.17
- @weex-cli/lint : v2.0.0-beta.2

**Comment by erha19** [comment]
@zhongwang2008 `weex run android`这个命令默认是通过执行预构建命令`npm run dev`运行项目内的构建脚本（可以通过`--precmd`自定义）, 同时默认监听产物目录`dist`（可以通过`--target`自定义）, 文件夹内有文件变化才会触发热更新逻辑。

如果还有问题，请提供一下简单的demo让我本地复现一下，目前我更改了跟你一样的目录结构同样没有问题

**Comment by zhongwang2008** [comment]
@erha19 
2.0.0-beta.20 (Core 2.0.0-beta.18)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.17
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/run : v2.0.0-beta.17
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.17
- @weex-cli/lint : v2.0.0-beta.2
Demo项目是通过weex create命令报建，为了上传方便奉压缩包内有node_modules文件夹下的依赖；安卓工程也是通过weex platform add android命令创建，而且没有做任何更改。
[demo.zip](https://github.com/weexteam/weex-toolkit/files/3067136/demo.zip)
