### ISSUE TITLE
weex debug ,网页控制台无法滚动

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex-cli#535]
weex debug somedir -e somefile启动debug,在弹出的网页，选择”页面“，出现的weex页面列表无法滚动，也返回不到刚才的页面了。
![image](https://user-images.githubusercontent.com/7556537/56260857-72332600-610b-11e9-89c9-a9f98a496db2.png)

**Comment by erha19** [comment]
@chenzefeng09 你可以运行一下`weex update @weex-cli/debug` 更新一下，发布了小版本修复了这个问题。
