### ISSUE TITLE
[Android][Dev-tool] open debug in application at the beginning,then app crashed 

### ISSUE THREAD

**Issue by fanlvwen** [apache/incubator-weex-cli#538]
https://weex.apache.org/zh/guide/debug/integrate-devtool-to-android.html#android%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%

my environment:
`
C:\Users\flw>weex -v
2.0.0-beta.25 (Core 2.0.0-beta.25)
- @weex-cli/preview : v2.0.0-beta.1
- @weex-cli/compile : v2.0.0-beta.2
- @weex-cli/generator : v2.0.0-beta
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/debug : v2.0.0-beta.25

`

1. weex create myApp & add android, then run it in android studio,it seems well

2.weex debug  --port 8888 --channelid 1,chrome opened

3.in android studio :
![image](https://user-images.githubusercontent.com/36951996/56416794-7fdfdb80-62c4-11e9-9f15-6875c16a05eb.png)

just the same as the official document said,but the app crached,whether enable is true or false

here is the logcat:

![image](https://user-images.githubusercontent.com/36951996/56416922-ed8c0780-62c4-11e9-8624-620c7830ec4a.png)

**Comment by erha19** [comment]
@fanlvwen That may be a question for `weex-android-devtool` SDK, I can't deal with it.

Maybe @YorkShen can help you.

**Comment by miomin** [comment]
@fanlvwen The reason for this problem is that the version of weex-inspector does not match the version of weex. I've fixed the wrong version of weex-inspector on the master branch of apache/incubator-weex, and then you can use it.
apache/incubator-weex：https://github.com/apache/incubator-weex

**Comment by fanlvwen** [comment]
@miomin thanks，but my project is created with this command`weex create myPro`，not clone from apache/incubator-weex，the same problem？

**Comment by azamat-sharapov** [comment]
@miomin unfortunately version upgrade doesn't help. I have also built latest SDK version from incubator-weex@master and that didn't help.

![image](https://user-images.githubusercontent.com/3023661/56714751-3b828e80-674f-11e9-9ee8-2a4663f0d44f.png)

Also, I don't see latest source code for weex-inspector (version 0.24.2.4 for example) on github. Do you know where I can find it?

**Comment by YorkShen** [comment]
Have you tried the latest commit on master branch, it looks good to me.

**Comment by azamat-sharapov** [comment]
@YorkShen I have tried every possible version that I could find. Could never get it working. I don't know what else to try.

Can you try to create project with weex-toolkit and then add devtool just like docs describe? I don't think it works.
