### ISSUE TITLE
Feature: provide template for android and ios

### ISSUE THREAD

**Issue by gengjiawen** [apache/incubator-weex-cli#54]
RT

**Comment by exolution** [comment]
什么意思 能说具体些么

**Comment by gengjiawen** [comment]
就是生成android和ios的native的template啊

**Comment by gengjiawen** [comment]
类似[weex-hackernews]( https://github.com/weexteam/weex-hackernews)里面的native模板

**Comment by exolution** [comment]
我们有专门的打包android ios app的工具
https://github.com/weexteam/weex-pack 
另外这些工具的命令也无缝接入到weex-toolkit里了

**Comment by gengjiawen** [comment]
这个是不是不支持后缀为.vue的这种工程,我用了没有成功生成native代码
