### ISSUE TITLE
使用weex update 命令升级模块后，版本号没有变化！

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#541]
2.0.0-beta.25 (Core 2.0.0-beta.25)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.25
- @weex-cli/compile : v2.0.0-beta.24
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.17
- @weex-cli/lint : v2.0.0-beta.2
执行weex update @weex-cli/debug命令后，debug版本号没变化；weex repair命令也有这个问题。
如下图所示
![QQ截图20190424105543](https://user-images.githubusercontent.com/41984848/56629342-a2d10d80-667f-11e9-8f17-874810ec3245.png)

**Comment by erha19** [comment]
@zhongwang2008 你使用的是taobao镜像进行安装，npm发布后的模块在taobao镜像上的同步不是实时的，下次遇到这种问题可以手动到这里 https://npm.taobao.org/package/@weex-cli/debug 同步包（点击SYNC按钮）。
