### ISSUE TITLE
weex build android 命令报错，Packaging a project which is used for preview is meaningless. We are thinking about how to better define this module. Please do not use this command for the time being.请问这是什么原因呢

### ISSUE THREAD

**Issue by cheersonVan** [apache/incubator-weex-cli#544]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
- Detact what's wrong with your environment (Run `weex doctor`)
- Which platform (Win/Mac/Ubuntu..)

**Comment by cyr297** [comment]
怎么解决的呢

**Comment by bhgx** [comment]
有解吗？

**Comment by yjouyang** [comment]
@congchivan why did you close this issue? Could you please tell me how to solve this

**Comment by gdoudeng** [comment]
？？？怎么解决

**Comment by gdoudeng** [comment]
？？？？
