### ISSUE TITLE
weex preview 命令提示找不到谷歌浏览器

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#545]
2.0.0-beta.26 (Core 2.0.0-beta.26)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.26
- @weex-cli/compile : v2.0.0-beta.24
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.17
- @weex-cli/lint : v2.0.0-beta.2

Windows 找不到文件 'chrome'。请确定文件名是否正确后，再试一次。
![QQ截图20190430141747](https://user-images.githubusercontent.com/41984848/56943585-c3530900-6b52-11e9-8db2-730f10661b30.png)

**Comment by erha19** [comment]
@zhongwang2008 你的电脑是否安装了chrome浏览器，如果没有，可以安装一下，或者使用你自己的浏览器手动打开日志上的链接也可以进行预览。
