### ISSUE TITLE
weex run --entry xxx.js 命令，页面代码保存后，真机端不刷新

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#547]
2.0.0-beta.26 (Core 2.0.0-beta.27)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.27
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/preview : v2.0.0-beta.17
- @weex-cli/lint : v2.0.0-beta.2

执行该命令后，命令行里一切正常，但是代码保存后，真机端就是不刷新；如下图所示：
![QQ截图20190509142239](https://user-images.githubusercontent.com/41984848/57432271-f76fad80-7267-11e9-8ee4-647293027b2f.png)

**Comment by erha19** [comment]
@zhongwang2008 if you have open the `safe write` setting on your IDE, close it, see https://medium.com/@pmarcus93/if-webpack-doesnt-rebuild-reload-your-project-on-code-changes-try-to-disable-safe-write-in-your-1de91fe6e053.

It works fine on my platform.

**Comment by zhongwang2008** [comment]
@erha19 本地编辑器“safe write”如何查看，提供的连接打开不；
现在情况导致页面编译失效，已经无法正常进行开发工作；希望通过钉钉直接沟通处理，特别紧急；已经影响项目进度了；

**Comment by erha19** [comment]
@zhongwang2008 
1. 检查路径是否指定正确，默认相对于`src`目录
2. 查看是否打开了自己使用的IDE`safe write`选项，找不到，把你用的IDE发出来
3. 尝试`weex compile src dist -w`命令是否能正常监听文件变化并正确编译。

**Comment by zhongwang2008** [comment]
@erha19 刷新问题可以使用了；但是weex run android命令还有一个其它问题，我再提一个issue吧！
