### ISSUE TITLE
weex compile 生成的js文件，真机端应用启动报错

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#551]
2.0.0-beta.27 (Core 2.0.0-beta.27)
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/debug : v2.0.0-beta.27
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/preview : v2.0.0-beta.17
- @weex-cli/build : v2.0.0-beta.15
- @weex-cli/generator : v2.0.0-beta.16

执行命令：weex compile src platforms\android\app\src\main\assets\dist -w
然后，使用android studio运行安装到真机后报以下错误：
![QQ截图20190514134431](https://user-images.githubusercontent.com/41984848/57673468-b18f5c80-764e-11e9-837a-92f34c912d54.png)
![Screenshot_2019-05-14-13-51-47](https://user-images.githubusercontent.com/41984848/57673743-a5f06580-764f-11e9-9317-96ca812d7a2a.jpg)

**Comment by zhongwang2008** [comment]
开发环境信息：
window 10 LTSC 企业版
node v10.15.3
npm 6.4.1

**Comment by erha19** [comment]
@zhongwang2008 直接通过`andoird studio` 运行，你需要手动修改启动配置来指向要启动的页面，找到 `/platforms/android/app/src/main/res/xml/app_config.xml` 文件，对`local_url`值进行修改。

官方模板项目不建议通过这种方式进行调试，目前根据我本地windows的运行情况无法定位`weex run android`的问题，你可以使用同事的电脑试一下，如果依旧有问题，运行命令前时加入`set DEBUG=*`,如 `set DEBUG=* && weex run android` 将完整的日志提供一下。

**Comment by zhongwang2008** [comment]
@erha19 执行weex repair @weex-cli/compile@2.0.0-beta.24命令后，好像解决该问题；现在可以正常使用；

**Comment by jcsl12** [comment]
> @erha19 执行weex repair @weex-cli/compile@2.0.0-beta.24命令后，好像解决该问题；现在可以正常使用；

这个真的解决了  3q
