### ISSUE TITLE
 connect ETIMEDOUT 124.67.215.5:443

### ISSUE THREAD

**Issue by louisscrew** [apache/incubator-weex-cli#553]
weex-toolkit已经安装成功，但是运行weex create awesome-project时，出现如下错误
![image](https://user-images.githubusercontent.com/16482242/58946297-22421880-87b8-11e9-9c7c-84ef9aa51ee2.png)

···
Start installing Core, please wait ...
| [0/1] Installing @weex-cli/core@latest[npminstall:get] retry GET https://regis
try.npm.taobao.org/@weex-cli%2Fcore after 100ms, retry left 4, error: RequestErr
or: connect ETIMEDOUT 124.67.215.5:443, GET https://registry.npm.taobao.org/@wee
x-cli%2Fcore -1 (connected: false, keepalive socket: false, agent status: {"crea
teSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCou
nt":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"regis
try.npm.taobao.org:443:::::::true::":1},"requests":{}}, socketHandledRequests: 1
, socketHandledResponses: 0)
headers: {}, status: -1, headers: {},
stack: Error: connect ETIMEDOUT 124.67.215.5:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
···

我这个是公司网络，公司网络需要设置代理服务器才可以使用，比如nodejs 我需要配置proxy才可以使用。但是weex哪里可以配置这个吗？

**Comment by erha19** [comment]
@louisscrew weex工具可以通过 `weex config set ENVS.[npm配置] [value]`的方式来进行`npm`配置, 如代理需要认证的话可以这样来设置：
```
$ weex config set ENVS.proxy http://username:password@server:port
$ weex config set ENVS.https-proxy http://server:port
```
单独设置 `npm registry`:
```
$ weex config set registry "http://registry.npmjs.org/"
```

**Comment by qieting** [comment]
我按照上面说的没有任何作用 @erha19
