### ISSUE TITLE
使用 weex debug 断点调试功能 ，ios手机闪退

### ISSUE THREAD

**Issue by githbq** [apache/incubator-weex-cli#554]
使用 weex debug 断点调试功能 ，ios手机闪退 ，使用的是官方提供的 ios 版的 weex playground App

**Comment by erha19** [comment]
@githbq 提供一下你使用的`weex-toolkit`版本，运行一下`weex -v`

**Comment by githbq** [comment]
New version detected 2.0.0-beta.31, the local version is 2.0.0-beta.27, upgrade now？[Y/n]
