### ISSUE TITLE
weex run android无法运行

### ISSUE THREAD

**Issue by chenyiqi** [apache/incubator-weex-cli#555]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
awesome-app weex -v
2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/build : v2.0.0-beta.15
- @weex-cli/plugin : v2.0.0-beta.22
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/doctor : v2.0.0-beta.20

- Detact what's wrong with your environment (Run `weex doctor`)

weex doctor
✔ Android and iOS Environment:

[✓] Android toolchain - develop for Android devices
    •  Android SDK at /Users/chenyiqi/Library/Android/sdk
    •  Platform android-29, build-tools 29.0.0
    •  ANDROID_HOME = /Users/chenyiqi/Library/Android/sdk
      
    •  Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08).

[✓] iOS toolchain - develop for iOS devices
    •  Xcode at /Applications/Xcode.app/Contents/Developer
    •  Xcode 9.2
    •  CocoaPods version 1.7.1

✔ Weex Cli Environment (v2.0.0-beta.31, on darwin 16.7.0):

[✔] @weex-cli/core  - core module for the weex-toolkit
[✔] @weex-cli/generator - Generator for weex-toolkit
[✔] @weex-cli/run - module for running iOS/Android/Web platform with weex-toolkit
[✔] @weex-cli/device - module for lanuch device with weex-toolkit
[✔] @weex-cli/build - Build module for weex-toolkit
[✔] @weex-cli/plugin - Module for manage weex plugin and create plugin project
[✔] @weex-cli/compile - Plugin for compile weex file.
[✔] @weex-cli/doctor - Doctor module for weex-toolkit

[vue environment] check if there has Vue packages version mismatch issue

  - AutoFix vue mismatch issue

- Which platform (Win/Mac/Ubuntu..)
mac

## Steps to reproduce the problem.(Maybe a [dotwe](http://dotwe.org/vue) link)
我的项目在android studio中可以运行，但是在命令行执行weex run android会报错
以下是错误信息
 Error: Command failed: ./gradlew clean assembleDebug

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.3.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:2.3.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom'.
> Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom'. Received status code 400 from server: Bad Request
      > Could not resolve com.android.tools.build:gradle:2.3.2.
         > Could not get resource 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom'.
            > Could not GET 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom'. Received status code 400 from server: Bad Request
      > Could not resolve com.android.tools.build:gradle:2.3.2.
         > Could not get resource 'https://maven.google.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom'.
            > Could not GET 'https://maven.google.com/com/android/tools/build/gradle/2.3.2/gradle-2.3.2.pom'. Received status code 400 from server: Bad Request
   > Could not resolve com.taobao.android:weexplugin-gradle-plugin:1.3.
     Required by:
         project :
      > Could not resolve com.taobao.android:weexplugin-gradle-plugin:1.3.
         > Could not get resource 'https://jcenter.bintray.com/com/taobao/android/weexplugin-gradle-plugin/1.3/weexplugin-gradle-plugin-1.3.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/taobao/android/weexplugin-gradle-plugin/1.3/weexplugin-gradle-plugin-1.3.pom'. Received status code 400 from server: Bad Request
      > Could not resolve com.taobao.android:weexplugin-gradle-plugin:1.3.
         > Could not get resource 'https://repo1.maven.org/maven2/com/taobao/android/weexplugin-gradle-plugin/1.3/weexplugin-gradle-plugin-1.3.pom'.
            > Could not HEAD 'https://repo1.maven.org/maven2/com/taobao/android/weexplugin-gradle-plugin/1.3/weexplugin-gradle-plugin-1.3.pom'. Received status code 400 from server: Bad Request
      > Could not resolve com.taobao.android:weexplugin-gradle-plugin:1.3.
         > Could not get resource 'https://maven.google.com/com/taobao/android/weexplugin-gradle-plugin/1.3/weexplugin-gradle-plugin-1.3.pom'.
            > Could not HEAD 'https://maven.google.com/com/taobao/android/weexplugin-gradle-plugin/1.3/weexplugin-gradle-plugin-1.3.pom'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by erha19** [comment]
@chenyiqi 使用命令行工具请使用命令行工具创建的项目搭配使用，目前两套工具部分不兼容

**Comment by chenyiqi** [comment]
我就是用的命令行工具创建的项目呀
1、weex create awesome-project
2、cd awesome-app
3、npm install
4、weex platform add android
5、weex run android
