### ISSUE TITLE
weex preview url 不能访问

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#556]
2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/preview : v2.0.0-beta.17

![QQ截图20190626105701](https://user-images.githubusercontent.com/41984848/60147746-3dc1a180-9801-11e9-8c44-eb5eda48e7fe.png)
![QQ截图20190626105733](https://user-images.githubusercontent.com/41984848/60147755-42865580-9801-11e9-9c27-2006aa2d8472.png)

**Comment by erha19** [comment]
@zhongwang2008 检查下本地是否开启了代理，如果开启了需要关闭

**Comment by oneness0** [comment]
确定不是http-server版本问题?[https://github.com/indexzero/http-server/issues/525](https://github.com/indexzero/http-server/issues/525)

**Comment by zhongwang2008** [comment]
@erha19 没有设置代理，该问题目前仍然存在！
