### ISSUE TITLE
weex run android --entry xxx.js Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by zhongwang2008** [apache/incubator-weex-cli#557]
2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/preview : v2.0.0-beta.17
Windows 10 企业版 LTSC

保存代码后，报以下错误：
![QQ截图20190702162458](https://user-images.githubusercontent.com/41984848/60497006-8d630a00-9ce6-11e9-9b4a-f372475f9d52.png)
![QQ截图20190702162434](https://user-images.githubusercontent.com/41984848/60497016-92c05480-9ce6-11e9-83db-ca1fc25ca943.png)

**Comment by erha19** [comment]
@zhongwang2008 这周的版本发布会解决这个问题
