### ISSUE TITLE
华为手机weex debug 报错：Warning:The session with native was closed,please restart your native app!

### ISSUE THREAD

**Issue by zcl0001** [apache/incubator-weex-cli#56]
后端错误如下：
You can visit we file(s) use http://192.168.11.16:8088/weex/tmprovence.js
Also you can use Playground App to scan the qrcode on device list page.

The websocket address for native is ws://192.168.11.16:8088/debugProxy/native
Launching Dev Tools...
 can not join session,unknown sessionId[null]
@(D:\Program Files\nodejs\npm-global\node_modules\weex-toolkit\node_modules\weex
-devtool\lib\components\P2PSession.js:218:24)

**Comment by exolution** [comment]
你自己的app还是playground?
自己的app的话 说明WxDevtool的接入方式不对
playground的话 请说明什么系统 在哪下载的

**Comment by zcl0001** [comment]
playground，使用playground debug自己编写的.we 文件，playground版本是v0.94，weex-toolkit 版本 v0.2.76，手机是华为荣耀4A，android 5.1 @exolution

**Comment by zcl0001** [comment]
而且我使用 playground v0.95 则看不到设备列表，playgroud在weex官网下载和下载weex项目源码，然后编译都试过，都不能debug
在weex里面也有相同问题的Issue（#2277）：https://github.com/alibaba/weex/issues/2277

**Comment by exolution** [comment]
看不到设备列表 一般是因为你手机跟电脑 不在一个网段或无法互通
红字这个错误 很奇怪 你尝试升级至最新的weex-toolkit试试 1.0正式版已经发布

**Comment by erha19** [comment]
Fixed, PR: https://github.com/weexteam/weex-devtool/pull/84
