### ISSUE TITLE
why donnot have  @weex-cli/lint ？

### ISSUE THREAD

**Issue by huanghao1234** [apache/incubator-weex-cli#560]
appledeMacBook-Air:~ apple$ sudo npm i weex-toolkit -g
/usr/local/bin/weex -> /usr/local/lib/node_modules/weex-toolkit/bin/weex.js

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/weex-toolkit/node_modules/spawn-sync
> node postinstall

+ weex-toolkit@2.0.0-beta.31
added 381 packages from 238 contributors in 13.042s
appledeMacBook-Air:~ apple$ weex -v
2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/debug : v2.0.0-beta.31
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/preview : v2.0.0-beta.17

why donnot have  @weex-cli/lint ？

**Comment by erha19** [comment]
@huanghao1234  Try `weex lint --help`, if you have not installed it, it will installing automatically.
