### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by youmu178** [apache/incubator-weex-cli#58]
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/nvm/0.29.0/versions/node/v5.3.0/bin/node" "/usr/local/Cellar/nvm/0.29.0/versions/node/v5.3.0/bin/npm" "install" "weex-toolkit@beta" "-g"
npm ERR! node v5.3.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! weex-toolkit@1.0.1-beta.5 postinstall: `xtoolkit install weex-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weex-toolkit@1.0.1-beta.5 postinstall script 'xtoolkit install weex-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the weex-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xtoolkit install weex-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs weex-toolkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls weex-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/youzehong/npm-debug.log
npm ERR! code 1

**Comment by exolution** [comment]
请升级node 到6.0以上
建议使用官方的长效稳定版 6.9.x
5.x已失去维护

**Comment by mario-huang** [comment]
使用node 6.x最新版依旧报错，已经加上sudo
