### ISSUE TITLE
weex create error

### ISSUE THREAD

**Issue by kuangyanit** [apache/incubator-weex-cli#580]
when i use weex create weex-demo， there is a error like Error: [.babelrc] Missing helper: "if_eq", how can i solve it?

weex --version

2.0.0-beta.31 (Core 2.0.0-beta.31)

- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.31
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/doctor : v2.0.0-beta.20

**Comment by aromameng** [comment]
Did you find a solution?

**Comment by kuangyanit** [comment]
> Did you find a solution?

I don't :(

**Comment by erha19** [comment]
@kuangyanit @aromameng try `weex create [project-name] --no-cache`, that caused by the old template cache on your platform.

**Comment by kuangyanit** [comment]
> @kuangyanit @aromameng try `weex create [project-name] --no-cache`, that caused by the old template cache on your platform.

It works. Thank you for your reply.
