### ISSUE TITLE
How to create android project with weex_sdk:0.26.0

### ISSUE THREAD

**Issue by lvshuchengyin** [apache/incubator-weex-cli#582]
Hi, I want to ask how to create android project with weex_sdk:0.26.0?
Now I use weex_sdk:0.16.0, and it can't build 64bit apk, so I have to upgrade to weex_sdk:0.26.0.
But show error:
error : can't find symbol
symbol:   class IWXDebugProxy
position:  com.taobao.weex.common
Any information could help me solve that problem?
Thanks!

**Comment by lvshuchengyin** [comment]
I copy the https://github.com/apache/incubator-weex-playground and change the uri to local asset solve the problem.

**Comment by LwLuna** [comment]
解决了吗
我也遇到这个问题
