### ISSUE TITLE
why can not run npm run pack:android

### ISSUE THREAD

**Issue by housuchuan** [apache/incubator-weex-cli#583]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
- Detact what's wrong with your environment (Run `weex doctor`)
- Which platform (Win/Mac/Ubuntu..)

**Comment by erha19** [comment]
@housuchuan The android or ios project created by `weex-toolkit` is only used for preview page quickly, we don't provide tools to pack it, you can pack it using `Android Studios` by yourself.
