### ISSUE TITLE
Weex Vue Render does not render responsive web css (Bootstrap)

### ISSUE THREAD

**Issue by donwilly2010** [apache/incubator-weex-cli#587]
Weex Toolkit is a very wonderful tool. I have successful run the tool on our development environment and it was fine.

But then I noticed a bug. I believe the main purpose of Weex is to share same code based from Vuejs  for Web and Mobile development.

However, Weex Vue Render used in latest verwsion of Weex does not render existing mobile responsive web css  such as Bootstrap. This means that existing Vuejs codes on vue cli cannot be migrated to Weex. This is a bug and a major set back as its not realistic for every Weex developer to develop Vue application from ground up on Weex as there are a lot of existing Vue applications that needs to be migrated to Weex.

Please how can this issue be resolved.

Makes sure these boxes are checked befor submitting your issue - thank you!

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
- Detact what's wrong with your environment (Run `weex doctor`)
- Which platform (Win/Mac/Ubuntu..)

**Comment by erha19** [comment]
@donwilly2010 I have no idea about this issue, maybe you can put an issue to https://github.com/weexteam/vue-render-for-apache-weex project. If it can support this feature, I can just update the toolkit template to support it.
