### ISSUE TITLE
Bug: Selecting different Form Select Option removes Input field Text

### ISSUE THREAD

**Issue by donwilly2010** [apache/incubator-weex-cli#588]
Hi,
Only again. I am very happy with this project. However, I discovered a Bug.
When you have an Input text field above a Select list with multiple options, when the different Select Options are selected, the text that was typed into the Input field above the Selection field becomes empty.

This is actually a bug and can easily be reproduced. with this code below:

<template>
<div>
<input type="text" v-model="name"></input>
<select v-model="selectOption">
<option value="1">First Option</option>
<option value="2">Second Option</option>
</select>
</div>
</template>

<script>
export default{
data (){
return{
name: "",
selectOption: "1",
}
}
}
</script>

if you make a text input into the name field and then select Second Option. The text input made into name field  disappears. when you select the first option. The text input that was made into name field appears again in the name field.

**Comment by erha19** [comment]
@donwilly2010  as I know, that should be a question or feature request on https://github.com/apache/incubator-weex issues.
