### ISSUE TITLE
Using Weex for Production App very Difficult. Render Error 1001 on APK

### ISSUE THREAD

**Issue by donwilly2010** [apache/incubator-weex-cli#589]
Weex is supposed to be an open source platform. But its actually closed to the open community.
Weex community in China and in Alibaba does not respond to most issues raised in English Language. This is very unfair and very un-professional.

secondly, after many months of hard work of using weex to buid an app on the web preview, I decided to generate an apk app. After so much work and bug fixing. The app generated was a piece of crap.
It wan named Weex App and Branded with Weex Logo and was build with Weex playground and also gave me a render error 1001 on blank screen.

This is a total joke. I expected an app for production that looks exactly the way it looks on the browser preview.
Has anyone who speaks English used Weex to create an app for Production??

Regards,
Toch

**Comment by erha19** [comment]
@donwilly2010  

I have recently invested in a new job and neglected to maintain this project, sorry for the delay getting back to you.

The `weex-cli` was originally designed to help weex developers quickly develop weex script. The implementation of the packaged application is incomplete. If you want to package an application, we still recommend using Xcode or Android Studio to package the application.

The latest weex playground app should be updated on this project https://github.com/apache/incubator-weex.
