### ISSUE TITLE
Missing 'prompt' dependency in weex-toolkit@beta

### ISSUE THREAD

**Issue by tralves** [apache/incubator-weex-cli#60]
Hello!

I installed `weex-toolkit` globally, but the got the error:

```
$ weex init hello-weex
{ Error: Cannot find module 'prompt'
    at Function.Module._resolveFilename (module.js:440:15)
    ...
```

I had to install `prompt` "manually" in the global package:

```
$ cd ~/.nodebrew/node/v6.2.2/lib/node_modules/weex-toolkit
$ npm install prompt
```

And then it worked.

Is it a missing dependency, or do I have something wrong here?

**Comment by exolution** [comment]
please try 1.0.2+ version
