### ISSUE TITLE
weex打包andriod包失败

### ISSUE THREAD

**Issue by zgLiuBing** [apache/incubator-weex-cli#604]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
- Detact what's wrong with your environment (Run `weex doctor`)
- Which platform (Win/Mac/Ubuntu..)

**Comment by YorkShen** [comment]
The issues is closed due to the repoerter didn't follow the issue template and there is nothing I can do with such litte information.
