### ISSUE TITLE
[Android]WMIC path win32_process get Name,Processid,ParentProcessId,Commandline,ExecutablePath' terminated with code: 44213

### ISSUE THREAD

**Issue by webliving** [apache/incubator-weex-cli#606]
## Describe the bug
weex run android 命令不能启动模拟器，一直在等待中。

## Screenshots
![image](https://user-images.githubusercontent.com/3808577/70788226-63e8f700-1dcb-11ea-92e5-a6ef966060dc.png)

**Comment by cnryb** [comment]
考虑下国内网络情况，建议你第一次使用Android studio打开目录下 platform/android 的安卓工程。这里能够更详细的看到具体异常。

**Comment by webliving** [comment]
在 Android Studio 中是可以打开啊，这种情况不太像是网络不行呢？

![image](https://user-images.githubusercontent.com/3808577/70789642-5c771d00-1dce-11ea-9fee-ea8b80734b23.png)

**Comment by cnryb** [comment]
很抱歉，是我没有仔细看图。看样子是抛了个异常挂掉了。
如果你有兴趣可以帮助我们改进这个功能，谢谢。
