### ISSUE TITLE
How can we compile Weex more effective ？

### ISSUE THREAD

**Issue by zsmjhtn** [apache/incubator-weex-cli#607]
As weex hold most of business in Our App, about 200-300 pages, nearly 90% of App.
When the files grew faster, compile  weex file cost more time.
Even if I separated all files into 5 packages,  the spending time can not reduce any more.
Please give some suggestions, Thanks!

**Comment by cnryb** [comment]
I use weex as single page. So I can only compile pages that have changed.

**Comment by zsmjhtn** [comment]
> changed

I don not understand it. Do u mean  instant-compile ？ 
Such as i have 100 pages，and change a little。You can  **realize** compile those files which have been changed？
Or do you mean there is only **one page**，others just like  child-pages/compoment？

**Comment by cnryb** [comment]
For example, you have 100 pages, and modify or add 10 pages to the current sprints. Then just compile these 10 pages.
Of course, we also welcome you to help weex improve compilation efficiency.

**Comment by zsmjhtn** [comment]
> For example, you have 100 pages, and modify or add 10 pages to the current sprints. Then just compile these 10 pages.
> Of course, we also welcome you to help weex improve compilation efficiency.

It sounds wonderful！I have no think about to improve “weex-builder” yet。
Just change python script, in order to  distribute more threads  for the commond of  “weex-builder” in Physical-Machine.
Can you share the build-tools or scripts, or tell more details about your “instant-compile”？
Is the secret in Cli? (Because of still using V0.18, some "we" files need to modify, so i just tried a little off Weex-CLi for "Vue" files) 
Thanks.

**Comment by cnryb** [comment]
No secret. Just a little trick in project management. If interested, we can exchange ideas, use faster channels, Email or others
