### ISSUE TITLE
v 0.24.0 - iOS (inspector 0.24.0)调试，无法显示js文件，以及预览(debug,can't display js file and preview)

### ISSUE THREAD

**Issue by pigheartCN** [apache/incubator-weex-cli#617]
![image](https://user-images.githubusercontent.com/26181029/76204453-64aaf100-6233-11ea-9869-9e697652b826.png)

to see: https://www.jianshu.com/p/372a43a3477b

详情请看：https://www.jianshu.com/p/372a43a3477b

**Comment by pigheartCN** [comment]
> ![image](https://user-images.githubusercontent.com/26181029/76204453-64aaf100-6233-11ea-9869-9e697652b826.png)
> 
> to see: https://www.jianshu.com/p/372a43a3477b
> 
> 详情请看：https://www.jianshu.com/p/372a43a3477b

**Comment by cnryb** [comment]
chrome v80 之后不支持 document.registerElement() 了。可以先降级 chrome 版本来使用这个功能。
如果有时间的话，也请你帮忙修复一下。
出问题的代码在 
https://github.com/apache/incubator-weex-cli/blob/master/packages/%40weex/plugins/debug/frontend/src/assets/inspector/ui/UIUtils.js#L1175

有两个方案供你参考
1、按照现行 [ChromeDevTools frontend](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/ui/utils/register-custom-element.js)  版本同步修改。
2、尝试 polyfill 。

**Comment by pigheartCN** [comment]
document.registerElement()  我说咋老是报错。。

**Comment by cnryb** [comment]
element.createShadowRoot() 也不支持了。

**Comment by zymxxxs** [comment]
@cnryb 将最新 devtools-frontend 重新编译之后，放入工程中是否可行？

一定要同步修改么？

**Comment by fancyboynet** [comment]
这个修复了吗？低版本chrome哪里可以下载到啊。。。

**Comment by pigheartCN** [comment]
百度


在2020年09月14日 18:43，Fancy 写道：

这个修复了吗？低版本chrome哪里可以下载到啊。。。

**Comment by cnryb** [comment]
> @cnryb 将最新 devtools-frontend 重新编译之后，放入工程中是否可行？
> 
> 一定要同步修改么？

这个当然是更好的选择。有时间的话你可以试试看，来个PR呀。

**Comment by MountainHill** [comment]
这个问题还没解决,还有人维护吗?

**Comment by cnryb** [comment]
solved in #630

**Comment by lvdeyang** [comment]
document.registerElement() 用了document-register-element.js, element.createShadowRoot() 换成了 element.attatchShadowRoot()仍然会有问题，源码中的label  button都不支持shadowRoot，除此之外还有别的问题
