### ISSUE TITLE
npm start 后打开的 preview 页面如何改掉

### ISSUE THREAD

**Issue by aowuR** [apache/incubator-weex-cli#619]
就是如何将进入页面换做直接进入项目的页面

**Comment by cnryb** [comment]
这个不知道能不能解决你的问题。https://webpack.js.org/configuration/dev-server/#devserveropenpage
使用weex create 创建的工程中，npm start 是使用webpack-dev-server启动的。更详细的你可以看package.json

**Comment by aowuR** [comment]
> 这个不知道能不能解决你的问题。https://webpack.js.org/configuration/dev-server/#devserveropenpage
> 使用weex create 创建的工程中，npm start 是使用webpack-dev-server启动的。更详细的你可以看package.json

是在 dev 里面配置去掉了 感谢回复!!!
