### ISSUE TITLE
weex debug 命令后，调试面板不显示

### ISSUE THREAD

**Issue by morrain** [apache/incubator-weex-cli#626]
Makes sure these boxes are checked befor submitting your issue - thank you!

- [] If you encounter any problems using the tool, please check if there has a new version to update(Run `weex update [pluginname]@latest`).
- [] Check the [FAQ](https://github.com/weexteam/weex-toolkit#faq), make sure there have not the same issue.

## Your development environment
- Check weex-toolkit verison (Run `weex -v`)
- @weex-cli/debug : v2.0.0-beta.31
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/doctor : v2.0.0-beta.20
- Detact what's wrong with your environment (Run `weex doctor`)
- Which platform (Win/Mac/Ubuntu..)
Mac

## The key error stack message.

![v消息20200630-103920](https://user-images.githubusercontent.com/9381634/86077103-f8901980-babd-11ea-8caf-137eb9393acd.jpg)

**Comment by cnryb** [comment]
参考这个  #617

**Comment by cnryb** [comment]
solved in #630
