### ISSUE TITLE
多个vue文件build之后会生成一个js文件，url怎么写

### ISSUE THREAD

**Issue by segatecm** [apache/incubator-weex-cli#65]
多个vue文件build之后会生成一个js文件，但是做页面跳转的时候需要url，那请问url怎么写呢？

**Comment by JackPu** [comment]
你可以通过page查询来写，这个在新版的weex-toolkit中会支持了，

**Comment by segatecm** [comment]
新版的weex-toolkit发布了吗？能给个page查询的教程吗。

**Comment by JackPu** [comment]
嗯，你可以参考[weex-amap](https://github.com/weex-plugins/weex-amap/tree/search-feature)里demo的路由设置。

**Comment by segatecm** [comment]
我打算在web版里面使用，我看你说的路由指的是这段代码？
在example-list.vue里面created函数里面的这一段是吗？
如果是h5的话路径是“./weex.html?page=” + name + ".js"是吗？
那这个name是怎么注册进去的？

**Comment by segatecm** [comment]
weex-amap是用weexpack的吧，我是想要weex-toolkit的。

**Comment by JackPu** [comment]
@segatecm  weex-toolkit也是支持的，只是目前这个版本没发，如果你要用的话，可以clone 新的分支代码来体验，

**Comment by segatecm** [comment]
谢谢，能否给个qq之类的联系方式想直接请教。
终于能有人回答下问题了。现在研究了下，给weex-toolkit加了一个新的入口，编译后生成了2个js文件了。一个叫app.web.js，一个叫webview.web.js。我想从app跳到webview。
但是用你给的项目中的代码尝试跳转，但是发现不能跳转成功只是app这个页面重刷了一下：

代码是这么写的：
var base = getBaseURL(this);
        var h5Base = './index.html?page=./dist/webview.web.js';

        event.openURL(h5Base);

**Comment by segatecm** [comment]
这是web项目，所以我尝试了直接event.openURL(h5Base);

**Comment by segatecm** [comment]
但是不能成功，页面就刷新了下，还是app.web.js的内容。

**Comment by JackPu** [comment]
@segatecm  这个没问题的， 760341479 qq／微信都可以，
