### ISSUE TITLE
$weex xxxxx.vue报错

### ISSUE THREAD

**Issue by xl20071926** [apache/incubator-weex-cli#66]
请教下$weex xxxxx.vue报错. 版本: info 1.0.1-alpha  node版本:v7.2.0
![24a4a7e4-f177-4e40-8459-51590bd7e9c4](https://cloud.githubusercontent.com/assets/11495547/23329868/0a47c1dc-fb7c-11e6-94a5-db19582c08f0.png)

**Comment by JackPu** [comment]
你的vue文件有语法错误，你自己看下吧，

**Comment by xl20071926** [comment]
@JackPu 直接用的weex 里面的demo都是这样的...

**Comment by exolution** [comment]
请升级至1.0.2正式版 后尝试 之前的alpha版 不支持vue
