### ISSUE TITLE
weex-toolkit的开发者说句话好吗

### ISSUE THREAD

**Issue by segatecm** [apache/incubator-weex-cli#67]
weex-toolkit打包的时候只生成了一个js文件。如果我要做vue页面跳转，跳转的url该怎么写怎么实现？
这个问题问了好久都没人回答。
开发者说句话好。问的问题能回答下吗，贴个代码好吗。对你们来说很简单的事情，贴个代码就马上能回答的问题。

**Comment by JackPu** [comment]
@segatecm  刚刚已经回复了，参考代码页发给你了，就是通过查询参数，然后动态创建script标签实现的。
