### ISSUE TITLE
安装还需要使用 @beta 吗？

### ISSUE THREAD

**Issue by leohxj** [apache/incubator-weex-cli#70]
`npm i -g weex-toolkit` 安装后的版本是 `1.0.3`

`npm i -g weex-toolkit@beta` 安装后的版本是 `1.0.1-beta.6`

beta 比正常安装的版本还低？这两者目前使用哪个？

**Comment by exolution** [comment]
正式版已经发布了 忘了beta版吧
不过beta的遗留数据有可能影响正式版 
如果发现有异常 请回复

**Comment by leohxj** [comment]
@exolution https://weex-project.io/guide/
guide 中应该更新下了，不然新手很多都直接安装了 beta

**Comment by bacy** [comment]
之前装的beta，昨天更新后1.0.3后报错，vue文件无法编译了
![image](https://cloud.githubusercontent.com/assets/5163569/23639414/9d9f1720-0322-11e7-9efb-1651c54f97c9.png)

**Comment by JackPu** [comment]
@bacy  您能说下你的 toolkit版本么？

**Comment by JackPu** [comment]
@bacy  这应该是模块未找到，我们修复后告诉你。

**Comment by bacy** [comment]
@JackPu 好的 3Q
