### ISSUE TITLE
weex-toolkit 安装报错

### ISSUE THREAD

**Issue by varandrew** [apache/incubator-weex-cli#75]
尊敬的weexteam,我在安装weex-toolkit遇到了麻烦，希望能得到你们的协助。

我先说明下我的环境
```js
{
"os": "macOS Sierra Version10.12.3",
"node": "v7.4.0",
"npm": "4.0.5",
"cnpm": "4.5.0",
"yarn": "0.21.3" 
}
```
我按照官方文档尝试安装weex-toolkit  在zsh里输入的命令如下：
1. `sudo npm install -g weex-toolkit`
2. `sudo cnpm install -g weex-toolkit`

都出现了如下报错： `requires a peer of vue@^2.1.5 but none was installed` 
<img width="567" alt="screen shot 2017-03-09 at 2 48 11 am" src="https://cloud.githubusercontent.com/assets/23582216/23731264/852c48da-04a7-11e7-9177-70202545bcfc.png">

输入weex  报错：`File not found!`   
<img width="559" alt="screen shot 2017-03-09 at 2 48 50 am" src="https://cloud.githubusercontent.com/assets/23582216/23722282/bf70b008-047f-11e7-834f-e579fdaf1268.png">

然后我尝试用yarn安装 命令如下: `sudo yarn global add weex-toolkit` 
<img width="593" alt="screen shot 2017-03-09 at 2 53 57 am" src="https://cloud.githubusercontent.com/assets/23582216/23731737/2dd33136-04aa-11e7-98ad-542739f6f654.png">

还是一样的问题：`"weex-vue-render@0.2.0" has unmet peer dependency "vue@^2.1.5".`

我想问下这个报错的原因是我个人的环境问题吗？
weex-toolkit支持yarn安装吗？
谢谢！

**Comment by varandrew** [comment]
I tried again too, uninstalled everything and then tried to install it again. Same results as earlier.

**Comment by VarAndrewChen** [comment]
这个报错的原因是npm 3+不再自动安装peerDependencies，应用需要明确的依赖它（添加到 package.json 的 dependencies 等地方）
