### ISSUE TITLE
weex 把path目录下的所有文件编译到哪个目录下

### ISSUE THREAD

**Issue by MacSzh** [apache/incubator-weex-cli#77]
weex debug your/we/path    这个会把path目录下的所有文件编译到哪个目录下  然后部署到debug服务器上

**Comment by JackPu** [comment]
参考文档 weex compile https://github.com/weexteam/weex-toolkit

**Comment by MacSzh** [comment]
@JackPu 看了之后还是不明白

**Comment by JackPu** [comment]
就是这样子 比如我的源码目录是 src 我的生成后打包文件目录在 dist

你只需要这样用:

```
weex compile src dist
```
