### ISSUE TITLE
遇到vue dismatch错误等常见问题 先看这里~

### ISSUE THREAD

**Issue by exolution** [apache/incubator-weex-cli#80]
首先vue dismatch是vue-template-compiler的坑 他会强制检查当前的vue和vue-template-compiler的版本是否严格匹配，所以一旦你系统中以前装过vue（最常见的情况就是不小心全局安装过vue）所以就会干扰 weex-toolkit。
我做了一个在线修复工具专门修复这种问题 
食用方式 
weex xbind repair toolkit-repair
然后执行 weex repair就行了~
这个问题也会检测一些环境和权限的问题，做出相应的提示
具体相关问题可以统一在这个issue里回复，

**Comment by Jiunsr** [comment]
大兄弟很强

**Comment by hongxiangWang** [comment]
大兄弟很强+1

**Comment by NoraGithub** [comment]
不生效哦。怎么破？一样报错。无法解决。求救。

**Comment by NoraGithub** [comment]
**错误日志**
Build Failed!
[webpack errors]


Vue packages version mismatch:

- vue@2.5.3
- vue-template-compiler@2.4.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


**重复执行的结果是一样的，污染一直存在，无效。**
$ weex repair
检测环境中...
环境正常!
检测是否有不匹配的vue污染...
search: /Users/NoraChan/.xtoolkit
search: /Users/NoraChan/.nave/installed/weex/lib/node_modules/weex-toolkit/node_modules/weex-builder/node_modules/vue-template-compiler
/Users/NoraChan/.nave/installed/weex/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/weex-builder/node_modules/vue-template-compiler
发现版本不匹配的vue污染: /Users/NoraChan/.nave/installed/weex/lib/node_modules/weex-toolkit/node_modules/weex-previewer/node_modules/vue/dist/vue.runtime.common.js
卸载中...
up to date in 11.344s

修复完成

**看起来是weex-toolkit自己导致的冲突，但我的weex-toolkit是稳定版本的。请问如何解决**
$ weex -v
   v1.0.7
 - weex-builder : v0.2.12
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13
 - weexpack : v0.4.7-beta.11
 - toolkit-repair : v0.0.5


$ npm list -g -depth=0
/Users/NoraChan/.nave/installed/weex/lib
├── npm@5.5.1
└── weex-toolkit@1.0.7

 **运行的项目的package.json**
{
  "name": "yanxuan-weex",
  "version": "1.0.0",
  "description": "a weex project",
  "main": "index.js",
  "scripts": {
    "build": "webpack",
    "build_plugin": "webpack --config ./tools/webpack.config.plugin.js --color",
    "dev": "weex-builder src dist -w",
    "serve": "webpack-dev-server --config webpack.dev.js -p --open"
  },
  "keywords": [
    "weex"
  ],
  "author": "zwwill",
  "license": "MIT",
  "dependencies": {
    "fs-extra": "^4.0.2",
    "vue": "^2.4.2",
    "vue-router": "^2.7.0",
    "vuex": "^2.1.1",
    "vuex-router-sync": "^4.3.0",
    "weex-html5": "^0.4.1",
    "weex-vue-render": "^0.12.14"
  },
  "devDependencies": {
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-runtime": "^6.9.2",
    "css-loader": "^0.26.1",
    "history": "^4.7.2",
    "quick-local-ip": "^1.0.7",
    "vue-loader": "^13.3.0",
    "vue-template-compiler": "^2.4.2",
    "webpack": "^2.7.0",
    "webpack-dev-server": "^2.4.2",
    "weex-builder": "^0.2.7",
    "weex-loader": "^0.4.5",
    "weex-router": "0.0.1"
  },
  "optionalDependencies": {
    "ios-deploy": "^1.9.0"
  }
}

**Comment by erha19** [comment]
@NoraGithub Run `npm i weex-toolkit@latest -g` to update your `weex-toolkit`.
If you have other problem while installing, see [FAQ](https://github.com/weexteam/weex-toolkit#faq) for some help.

**Comment by NoraGithub** [comment]
@erha19  
After`weex repair`, It doesn't repeat reminding me of version dismatch now. But when I run `npm run dev`, the error below still comes to me.It's so confusing. I read many answers for several days, but they don't help. Would you please help me for that?

Vue packages version mismatch:

- vue@2.5.3
- vue-template-compiler@2.4.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by erha19** [comment]
@NoraGithub Here is a simple way that you can just update `vue-template-compiler` by `npm update vue-template-compiler --save` on your project, the vue-template-compiler@2.5.3 would be the correct version.

**Comment by NoraGithub** [comment]
Thx @erha19 
However, It doesn't work. Still the same error.


$ npm list -l -depth=0

yanxuan-weex@1.0.0
│ /Users/NoraChan/Desktop/移动端开发/yanxuan-weex-demo
│ a weex project
├── babel-core@6.26.0
│   Babel compiler core.
│   https://github.com/babel/babel/tree/master/packages/babel-core
│   https://babeljs.io/
├── babel-loader@6.4.1
│   babel module loader for webpack
│   git+https://github.com/babel/babel-loader.git
│   https://github.com/babel/babel-loader
├── babel-plugin-add-module-exports@0.2.1
│   Fix babel/babel#2212
│   git+https://github.com/59naga/babel-plugin-add-module-exports.git
│   https://github.com/59naga/babel-plugin-add-module-exports#readme
├── babel-plugin-transform-runtime@6.23.0
│   Externalise references to helpers and builtins, automatically polyfilling your code without polluting globals
│   https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime
├── babel-preset-es2015@6.24.1
│   Babel preset for all es2015 plugins.
│   https://github.com/babel/babel/tree/master/packages/babel-preset-es2015
│   https://babeljs.io/
├── babel-runtime@6.26.0
│   babel selfContained runtime
│   https://github.com/babel/babel/tree/master/packages/babel-runtime
├── css-loader@0.26.4
│   css loader module for webpack
│   git+ssh://git@github.com/webpack/css-loader.git
│   https://github.com/webpack/css-loader#readme
├── fs-extra@4.0.2
│   fs-extra contains methods that aren't included in the vanilla Node.js fs package. Such as mkdir -p, cp -r, and rm -rf.
│   git+https://github.com/jprichardson/node-fs-extra.git
│   https://github.com/jprichardson/node-fs-extra
├── history@4.7.2
│   Manage session history with JavaScript
│   git+https://github.com/ReactTraining/history.git
│   https://github.com/ReactTraining/history#readme
├── ios-deploy@1.9.2
│   launch iOS apps iOS devices from the command line (Xcode 7)
│   git+https://github.com/phonegap/ios-deploy.git
│   https://github.com/phonegap/ios-deploy#readme
├── quick-local-ip@1.0.7
│   This is a tiny utility to get local ip address with in node applications.
│   git+https://github.com/aloksguha/myip.git
│   https://github.com/aloksguha/myip#readme
├── vue@2.5.3
│   Reactive, component-oriented view layer for modern web interfaces.
│   git+https://github.com/vuejs/vue.git
│   https://github.com/vuejs/vue#readme
├── vue-loader@13.4.0
│   Vue single-file component loader for Webpack
│   git+https://github.com/vuejs/vue-loader.git
│   https://github.com/vuejs/vue-loader
├── vue-router@2.8.1
│   Official router for Vue.js 2
│   git+https://github.com/vuejs/vue-router.git
│   https://github.com/vuejs/vue-router#readme
├── vue-template-compiler@2.5.3
│   template compiler for Vue 2.0
│   git+https://github.com/vuejs/vue.git
│   https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#readme
├── vuex@2.5.0
│   state management for Vue.js
│   git+https://github.com/vuejs/vuex.git
│   https://github.com/vuejs/vuex#readme
├── vuex-router-sync@4.3.2
│   Effortlessly keep vue-router and vuex store in sync.
│   git+https://github.com/vuejs/vuex-router-sync.git
│   https://github.com/vuejs/vuex-router-sync#readme
├── webpack@2.7.0
│   Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
│   git+https://github.com/webpack/webpack.git
│   https://github.com/webpack/webpack
├── webpack-dev-server@2.9.4
│   Serves a webpack app. Updates the browser on changes.
│   git+https://github.com/webpack/webpack-dev-server.git
│   https://github.com/webpack/webpack-dev-server
├── weex-builder@0.2.12
│   a weex compiler tool  used by weex-toolkit (bind on "weex compile")
├── weex-html5@0.4.1
│   Weex HTML5 Renderer
│   git+ssh://git@github.com/alibaba/weex.git
│   https://alibaba.github.io/weex
├── weex-loader@0.4.5
│   a webpack loader for weex
│   git+https://github.com/weexteam/weex-loader.git
│   https://github.com/weexteam/weex-loader#readme
├── weex-router@0.0.1
│   weex router
│   git+https://github.com/weexteam/weex-components.git
│   https://github.com/weexteam/weex-components#readme
└── weex-vue-render@0.12.25
    Weex built-in components for Vue 2.x.
    git+ssh://git@github.com/apache/incubator-weex.git
    http://weex.apache.org/

**Comment by NoraGithub** [comment]
@erha19  It's already the version 2.5.3 as info described above.  I am reading other's code to quickly start up my own project. It would be great if you could give me a hand for the issue.

This is [the repo-yanxuan-weex-demo](https://github.com/zwwill/yanxuan-weex-demo) which I am reading, hope it would help us.

**Comment by erha19** [comment]
@NoraGithub Have you update your `weex-toolkit` to the latest version? The latest version is above `v1.1.0`.
If you develop your own project, you should update your weex dependence of `weexpack` by `weex update weexpack` and re-create your weex project.

**Comment by NoraGithub** [comment]
@erha19 
Yes, I already did it, though there are some errors. 
And I am not clear about re-create project. I clone project [here](https://github.com/zwwill/yanxuan-weex-demo). 
How many steps does re-create mean? 
Does that mean I need to delete some files and `create project command` may re-create those files   or any other steps?
If I need to delete , which files are affected?

Here is some info:


$ npm list -g -depth=0
/Users/NoraChan/.nave/installed/weex/lib
├── npm@5.5.1
└── weex-toolkit@1.1.0-beta.6

npm ERR! missing: loader-utils@^1.1.0, required by vue-loader@12.2.0
npm ERR! peer dep missing: webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc, required by babel-loader@6.4.1

$ weex -v
   v1.1.0-beta.6
 - weexpack : v0.4.7-beta.19
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.8
 - toolkit-repair : v0.0.5

**Comment by erha19** [comment]
This does not seem to be a problem for `weex-toolkit`, I try to help you
look at your problem，please wait a moment!

2017-11-07 15:58 GMT+08:00 NoraGithub <notifications@github.com>:

**Comment by erha19** [comment]
@NoraGithub I have created a PR to fix this issue, see https://github.com/zwwill/yanxuan-weex-demo/pull/20.

**Comment by NoraGithub** [comment]
@erha19 
Many many thanks.
You are super nice and helpful.
Hope the mention symbol `@` doesn't disturb you.

**Comment by imfenghuang** [comment]
use
```
weex xbind repair toolkit-repair
weex repair
```

it still not work 

01:09:05 : Bundling source...
01:09:07 : ./views/auto/1.0/index.vue?entry=true
Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.13
- vue-template-compiler@2.5.15

**Comment by belivar** [comment]
感谢救命之恩
