### ISSUE TITLE
weex debug start debugger server at http://10.0.75.1:8088

### ISSUE THREAD

**Issue by zhangyanan151** [apache/incubator-weex-cli#82]
![Uploading image.png…]()

我在win10上面执行安装npm install -g weex-toolkit
然后进行debug
D:\weex\product_profile_weex>weex debug
start debugger server at http://10.0.75.1:8088

The websocket address for native is ws://10.0.75.1:8088/debugProxy/native
Launching Dev Tools...
  我的手机 playground扫码无法打开调试模式 chrome 设备列表没有设备  
我的IP是172.16.0.45

**Comment by damnright** [comment]
我也是，完全没处问，issue也没人理

**Comment by exolution** [comment]
说明手机跟电脑不在一个网段上
先保证在一个网段上
可以使用手机浏览器访问http://10.0.75.1:8088 如果能访问那说明在一个网段

**Comment by zhangyanan151** [comment]
我那个问题已经解决了。是因为docker的NAT网络配置影响了 大家如果有一样的问题存在可以看下自己的网络适配器是不是有其他的网络应用开启

**Comment by lerit** [comment]
是啊，我也是docker的导致，难道没地方指定ip吗，我看依赖库里面weex-previewer取得是第一个ip地址
