### ISSUE TITLE
weex init 创建的项目如何打包到真机？

### ISSUE THREAD

**Issue by zsea** [apache/incubator-weex-cli#83]
我按照文档，使用weex init 创建了一个项目，开发完成需要打包的时候，按文档运行weex platform add ios，但是提示Current working directory is not a weexpack project。

**Comment by Derek-X-Wang** [comment]
weex-toolkit和weexpack是两个工具啊

> 现在使用 weex-toolkit 同样支持对 weexpack 的命令调用,如果你当前的项目与 weexpack 生成的项目目录一致，那么你可以直接实现对于 platform 的操作，从而构建具体的 Android/IOS app 

weex platform add ios应该只支持用weexpack创建的项目

**Comment by zsea** [comment]
谢谢，我是初次尝试，完全按照文档来，前面是用的weex init，后面就陡然转为weexpack了，我思维没跟上。

**Comment by JackPu** [comment]
@zsea  这是我们的问题，确实我们内部在争论目录一致性，后期我们希望让两者的目录保持一致性，或者通过检查的形式自动补全缺损的目录，从而让它们一致。

**Comment by zsea** [comment]
很想找个从项目创建到打包在真机上运行的详细例子或文档。

**Comment by JackPu** [comment]
你可以参考这个项目： 最近写的 [amap-running-app](https://github.com/weex-plugins/amap-running-app) 里面有步骤教你如何创建一个三端都运行的应用。

**Comment by feng-fu** [comment]
个人理解weex-toolkit可以用来开发时调试，weexpack用作打包，但是怎么把weex-toolkit开发完成的文件放进weexpack进行打包呢

**Comment by JackPu** [comment]
你只需要把你的vue 或者 .we文件放到src下面。

**Comment by zzetao** [comment]
@JackPu `amap-running-app` iOS 运行后闪退

**Comment by JackPu** [comment]
@zzetao  这个我昨天才用ios 打包后运行了😢

你能贴下错误或者weex debug调试下

![image](https://cloud.githubusercontent.com/assets/4744967/24386954/cfdeda62-13a4-11e7-98c8-8a6d5e23856a.png)

**Comment by nepaul** [comment]
遇到同样的问题：按照官方文档一步步下来的。
建议统一下 weex init 和 weex create。

**Comment by napolees** [comment]
乱

**Comment by czy66545360** [comment]
在添加插件的时候总是报错  网上找了 说是要授权  授权后再试了 还是这个问题 
![image](https://user-images.githubusercontent.com/22144777/34716138-ecfd4e6a-f569-11e7-8af0-03a3ab07c203.png)

  @JackPu

**Comment by qld-cf** [comment]
旧项目都无法添加platform了
@JackPu

**Comment by qld-cf** [comment]
Current working directory is not a weex project.
