### ISSUE TITLE
Warning:The session with native was closed,please restart your native app!

### ISSUE THREAD

**Issue by dreamerff** [apache/incubator-weex-cli#87]
下载完最新的weex-toolkit后，运行 weex debug，提醒安装weex-devtool，安装完成后，再运行，打开weex devtool-applist页面，扫码，显示app信息
![image](https://cloud.githubusercontent.com/assets/6531639/24388661/ba7de78a-13ae-11e7-9a4f-9392f7238c2e.png)

点击debugger之后，新窗口弹出js debugger页面，如下：

![image](https://cloud.githubusercontent.com/assets/6531639/24388696/f6718314-13ae-11e7-9333-228a9aa15adf.png)

错误提示如下：
![image](https://cloud.githubusercontent.com/assets/6531639/24388835/da4541b6-13af-11e7-9937-dd0b1c38c690.png)

**Comment by exolution** [comment]
检查下浏览器版本是不是过低~建议升级至最新的chrome

**Comment by dreamerff** [comment]
更新至最新版，已解决～谢谢～
