### ISSUE TITLE
预览的提示升级到weex-previewer : v1.3.7之后，预览失败

### ISSUE THREAD

**Issue by Taeyss** [apache/incubator-weex-cli#88]
在执行weex --version时，提示更新，更新成功后，weex-previewer升级到了1.3.7，之后，再执行预览命令：weex xx/xx.vue时，报错如下：
ERR! [webpack errors]

Vue packages version mismatch:

- vue@2.2.6
- vue-template-compiler@2.2.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by JackPu** [comment]
@Taeyss  可以看这里修复https://github.com/weexteam/weex-toolkit/issues/80

**Comment by focuswei** [comment]
最近终端一直提示weex-previewer : v1.3.8，安装了也是出现问题， weex repair没有效果。后来重启后再跑一边weex repair 就好了，建议多跑几次，直到出现提示 “未发现问题!”。就可以了。
