### ISSUE TITLE
用这个工具生成的weex项目，修改代码后不能实时预览？

### ISSUE THREAD

**Issue by shenfu1991** [apache/incubator-weex-cli#89]
1·如题，每次修改代码之后要npm run build,然后运行npm rum serve，之后刷新浏览器才能看到修改后的效果。是我操作不对吗？  
   
2.还有编译后的项目只需要dist文件夹下的js文件，然后在xcode下运行iOS项目。虽然可以将js文件建立关联，但是还是需要重复1的步骤。不能直接在xcode中改代码？

**Comment by shenfu1991** [comment]
补充一下，.we文件是可以实时预览的。

**Comment by exolution** [comment]
weex xxx.we/xxx.vue是支持实时预览的~
你可以试试npm run dev&npm run serve

**Comment by ruixiu** [comment]
找到webpack.dev.js，把publicPath: '/dist/'的注释去掉，修改.vue文件后，手动刷新浏览器就可以了。自动刷新的方式还没找到

**Comment by ruixiu** [comment]
找到原因了：webpack.dev.js中的public: ip + ':8080/web'，会把所有请求都转为请求/web，导致hmr会请求/web/info，而/web/info并不存在，因为webpack提供的是/sockjs-node/info

**Comment by ruixiu** [comment]
解决方法：注释掉devServer的public配置，在package.json中修改script
 "serve": "webpack-dev-server --config webpack.dev.js -p --open --open-page=/web --hot"
注意：--open-page=/web，只是每次修改代码页面都会刷新，我用的初始项，没加其他东西，编译一次竟然需要2秒
