### ISSUE TITLE
npm install -g weex-tookit

### ISSUE THREAD

**Issue by duanzonglong** [apache/incubator-weex-cli#9]
win10和win7都安装报错
C:\Users\test>cnpm install -g weex-toolkit
[fsevents@1.0.14] download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://npm.taobao.org/mirrors/fsevents"}
[fsevents@1.0.14](.AppDataRoamingnpmnode_modules.weex-toolkit_npminstallchokidar1.6.0chokidarnode_modulesfsevents) unsupported: Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
[weex-toolkit@0.4.3] link C:\Users\test\AppData\Roaming\npm\weex@ -> C:\Users\test\AppData\Roaming\npm\weex
[weex-toolkit@*] installed at node_modules.weex-toolkit_npminstall\weex-toolkit\0.4.3\weex-toolkit (432 packages, use 17s, speed 170.71kB/s, json 2.8MB, tarball 0B)
excute post install scripts...
[bufferutil@1.2.1] scripts.install: "node-gyp rebuild" at .\AppData\Roaming\npm\node_modules.weex-toolkit_npminstall\bufferutil\1.2.1\bufferutil
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB6006: "VCBuild.exe" exited with code -1. [C:\Users\test\AppData\Roaming\npm\node_modules.we
ex-toolkit_npminstall\bufferutil\1.2.1\bufferutil\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\test\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "D:\developtool\tools\nodejs\node.exe" "C:\Users\test\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\test\AppData\Roaming\npm\node_modules.weex-toolkit_npminstall\bufferutil\1.2.1\bufferutil
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
[Error: Run "C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.<anonymous> (C:\Users\test\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:87:13)

**Comment by lvscar** [comment]
建议升级下node为当前最新稳定版本。  升级npm后，用npm安装试一下.
