### ISSUE TITLE
安装完weex-toolkit后，执行weex报错，Error: resolve path error:/usr/local/lib/node_modules/weex-toolkit/node_modules/._weex-previewer

### ISSUE THREAD

**Issue by hong4cong** [apache/incubator-weex-cli#91]
/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^

Error: resolve path error:/usr/local/lib/node_modules/weex-toolkit/node_modules/._weex-previewer
    at NpmPackage.resolve (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50:23)
    at Command.run (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/Command.js:43:13)
    at XToolkit._done (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:149:36)
    at process.nextTick (/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

**Comment by JackPu** [comment]
@hong4cong  你能执行下 `weex -v`么看是什么样的内容输出？

**Comment by hong4cong** [comment]
@JackPu 奇怪了！我第二天在执行weex 错误没有了！

**Comment by JackPu** [comment]
好吧，你后面遇到再贴出来。

**Comment by ondev** [comment]
我遇到同样的错，没法解决
weex -v
1.0.4

**Comment by JackPu** [comment]
@ondev  你重新安装下就好

**Comment by nashxk** [comment]
已经解决了，卸载了以后，重新安装，提示.xtoolkit/config.json没有权限，更改这个文件的权限之后重新安装就可以了。这次没有使用cnpm，直接使用的npm

node v6.3.1
npm v3.10.3
weex v1.0.5
同样的问题，卸载weex重装也不行
用的是cnpm

**Comment by ghost** [comment]
我遇到同样的错，没法解决.卸载重装也同样报错，求求解？
weex -v
v1.0.5

**Comment by hupanfeng** [comment]
我也碰到了，我的环境是window7_x64,报错信息如下：
C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_module
s\._xtoolkit@0.2.7@xtoolkit\src\package\NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^
Error: resolve path error:C:\Users\Administrator\AppData\Roaming\npm\node_module
s\weex-toolkit\node_modules\._weex-previewer
    at NpmPackage.resolve (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\package\NpmPackage.js
:50:23)
    at Command.run (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex
-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\Command.js:43:13)
    at XToolkit._done (C:\Users\Administrator\AppData\Roaming\npm\node_modules\w
eex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\xtoolkit.js:149:36)
    at process.nextTick (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\weex-toolkit\node_modules\._xtoolkit@0.2.7@xtoolkit\src\xtoolkit.js:90:22)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by JOJOyh** [comment]
一样哦,我也是这个问题

**Comment by ilyp** [comment]
.nvm/versions/node/v6.10.2/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
mac卸载重装了也没用，sudo也没用，weex -v只显示v1.0.5，weex直接报错，能给个解决方案吗？

## 暂时解决了，node 版本换成v7就没问题了

**Comment by doubleTotoo** [comment]
问题 同楼上 有什么解决方案吗

**Comment by casperSNSN** [comment]
遇到了同样的问题 怎么解决？

**Comment by JackPu** [comment]
``` bash
npm uninstall -g weex-toolkit
npm install weex-toolkit -g
```

**Comment by linyang520** [comment]
我也遇到了这样的问题，镜像装几遍都不管用。后来非镜像装成功了~

**Comment by linyang520** [comment]
npm uninstall -g weex-toolkit
我是直接装这个成功的

**Comment by wangmingquan** [comment]
mark一下，install，uninstall，npm，cnpm折腾半天没好的飘过

**Comment by luoei** [comment]
用cnpm安装的的，出现这个问题。换成npm就没问题了
```
cnpm uninstall -g weex-toolkit
npm install weex-toolkit -g
```

版本：
weex   ： v1.0.5
node   ： v7.9.0
npm     ：  4.2.0

**Comment by guoshengwang** [comment]
@JackPu 怎么卸 weex 我怎么执行 uninstall 命令不管用啊

**Comment by guoshengwang** [comment]
@JackPu 
➜  ~ weex -v
   v1.0.5
 - weex-builder : v0.2.6
➜  ~ node -v 
v7.10.0
➜  ~ npm -v
4.2.0
➜  ~ cnpm -v
cnpm@4.5.0 (/usr/local/lib/node_modules/cnpm/parse_argv.js)
npm@3.10.10 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@7.10.0 (/usr/local/bin/node)
npminstall@2.29.2 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 16.4.0 
registry=https://registry.npm.taobao.org

**Comment by guoshengwang** [comment]
@JackPu 
sudo npm uninstall -g weex-toolkit
......
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "-g" "weex-toolkit"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /usr/local/lib/node_modules/weex-toolkit/node_modules/_browserify-rsa@4.0.1@browserify-rsa/node_modules/randombytes
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access

npm ERR! enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/weex-toolkit/node_modules/_browserify-rsa@4.0.1@browserify-rsa/node_modules/randombytes'
npm ERR! enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/weex-toolkit/node_modules/_browserify-rsa@4.0.1@browserify-rsa/node_modules/randombytes'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wangguosheng/.npm/_logs/2017-05-09T07_34_47_875Z-debug.log
➜  ~

**Comment by BoySun** [comment]
@nashxk “permission denied, open '/Users/liuwenliang/.xtoolkit/config.json”，请问你是怎么改变文件的权限

**Comment by guoshengwang** [comment]
@BoySun 
sudo chmod -R 777 /Users/liuwenliang/.xtoolkit
我也遇到这个了

**Comment by shawvyu** [comment]
cnpm安装确实是有问题

**Comment by junnlee** [comment]
http://www.jianshu.com/p/a5e3b3709d62   ，这篇文章解决了，可以看一下

**Comment by eajon** [comment]
@guoshengwang 我也是这个问题 请问解决没有 现在删么删不掉 装么装不了

**Comment by junnlee** [comment]
@eajon 你的是什么平台的，windows还是mac？删除的话就用 npm uninstall -g weex-toolkit，

**Comment by angieming** [comment]
参考：http://www.jianshu.com/p/71ab584ebea2 
在mac上运行 sudo cnpm  install -g weex-toolkit@beta
问题解决了
