### ISSUE TITLE
如何在同一个项目里面开发多页应用？

### ISSUE THREAD

**Issue by elover** [apache/incubator-weex-cli#92]
这里的示例似乎都是只有一个页面，想了解下，但是一个具体的项目通常不可能只有一个页面，如何能够做到像一个普通的web项目一样，支持多页开发呢？

看了下weex-pack，感觉对前端来讲，稍微有点重，我们想试验的场景和淘宝类似，通过广告投放出去的页面，所以想了解下如何做到，底层编译工具结合webpack如何做到支持多页开发，并且能够同时编译出支持web、ios和安卓的页面？

或者说这块有具体的实现demo吗？

**Comment by JackPu** [comment]
@elover  可以参考这个项目 https://github.com/weex-plugins/weex-app-seed

**Comment by elover** [comment]
@JackPu 感谢回答，顺便想了解下 weex的发版周期大概是什么样的？这边客户端需要集成，考虑到后续的兼容处理，能够集成比较新的版本可能会比较好一点。

**Comment by JackPu** [comment]
目前是一个月一个版本，月底发一般情况下。

**Comment by elover** [comment]
weex-app-seed这个demo在web下显示正常，但是通过ios playground二维码扫一扫，点击页面底部的链接页面会白屏

**Comment by JackPu** [comment]
嗯 如果你是多页面预览的话，你需要 预览整个目录，应该是远程没有build后的JS Bundle。这个issue 移除到这里吧 https://github.com/weex-plugins/weex-app-seed/issues/2
