### ISSUE TITLE
报告0.11.2版本的几个bug

### ISSUE THREAD

**Issue by segatecm** [apache/incubator-weex-cli#93]
以下问题都是h5版本问题：
1.在ios手机浏览器里面运行的时候，slider的图片有时候不显示，需要等到第一次滑动结束后，图片才显示。
2.slider里面的indicator不能使用，颜色位置都不受代码控制。
3.body不知道为什么多了margin：8px。
4.在使用loading功能的时候，scroller的性能表现太差，动态加载了20多条数据后就卡顿得无法滑动。
5.在使用loading方式动态加载内容的时候，如果其中有image的内容，并且image在屏幕中出现的时候，它的图片不会显示。

希望能尽快修复这些bug，因为在项目中急用。

**Comment by JackPu** [comment]
请移步 https://github.com/apache/incubator-weex 这里反馈

**Comment by segatecm** [comment]
这个网址没法发issue啊。

**Comment by JackPu** [comment]
好吧，居然完全关掉了issue. 你可以订阅邮件的。

**Comment by erha19** [comment]
@MrRaindrop
