### ISSUE TITLE
控制台输入 weex 报错 

### ISSUE THREAD

**Issue by GWCodeN** [apache/incubator-weex-cli#95]
gywdeMacBook-Pro:~ my_gyw$ weex
/usr/local/lib/node_modules/weex-toolkit/node_modules/._xtoolkit@0.2.7@xtoolkit/src/package/NpmPackage.js:50
                throw new Error('resolve path error:'+this.path)
                ^

Error: resolve path error:/usr/local/lib/node_modules/weex-toolkit/node_modules/._weex-previewer
gywdeMacBook-Pro:~ my_gyw$ weex -v
   v1.0.4

**Comment by ondev** [comment]
我也遇到同样的错误。无法解决。

**Comment by Masquerade6** [comment]
Win7上也遇到了这个问题，Mark一下

**Comment by JackPu** [comment]
@ondev  @Liuyaowu  你们卸载后，重新安装一下尝试过没？
``` bash
npm uninstall -g weex-toolkit
npm install -g weex-toolkit
```

**Comment by GWCodeN** [comment]
@JackPu 试过了  weex 可以用

**Comment by Masquerade6** [comment]
@JackPu 具体原因我没找到，我看到这个错误“('resolve path error:'+this.path)”的时候在想是不是安装node.js时是不是不能指定其他安装目录（我指定安装在了D盘自己创建的一个nodejs的目录下），然后卸载，使用默认的安装位置重装（用的“npm install -g weex-toolkit”这个，没用淘宝镜像，淘宝镜像安装完后使用weex -v命令好像不会出现weex-builder和weex-previewer的版本号，当然这个具体是不是跟我前面说的安装位置有关系也有待测试），然后用默认的重装后现在已经成功了

**Comment by GWCodeN** [comment]
我卸载node 重装后就好了

**Comment by exolution** [comment]
windows下node老出这种幺蛾子
以前类似的问题是node安装的时候配置全局目录
导致-g安装的目录都很奇怪
你们这个也是的 weex-previewer变成了._weex-previewer 不觉得奇怪么
这种问题只能重装node了
