### ISSUE TITLE
win10 安装好weex-toolkit之后   并且按照文档操作 直到执行weex index.we 进入到浏览器显示不了效果

### ISSUE THREAD

**Issue by to686312** [apache/incubator-weex-cli#99]

**Comment by JackPu** [comment]
@to686312  麻烦贴下 index.we 文件

**Comment by to686312** [comment]
<template>
	<div class="wrapper">
		<<div class="box box1">
			
		</div>

		<<div class="box box2">
			
		</div>

		<<div class="box box3">
			
		</div>
	</div>
</template>

<style scoped>
	.wrapper{
		position: absolute;
		top: 0;bottom: 0;right: 0;left: 0;
		background-color: #cccccc
	}
	.box{
		width: 400px;
		height: 400px;
		position: absolute;
	}
	.box1{
		top: 0;left: 0;background-color: #0055dd;
	}
	.box2{
		top: 150;left: 150;background-color: #ff0000;
	}
	.box3{
		top:300;left: 300;background-color: #00ff49;
	}
</style>

**Comment by to686312** [comment]
<template>
	<div class="wrapper">
		<div class="box box1">
		</div>
		<div class="box box2">	
		</div>
		<div class="box box3">
		</div>
	</div>
</template>
<style scoped>
	.wrapper{position: absolute;top: 0;bottom: 0;right: 0;left: 0;background-color: #cccccc}
	.box{width: 400px;height: 400px;position: absolute;}
	.box1{top: 0;left: 0;background-color: #0055dd;}
	.box2{top: 150;left: 150;background-color: #ff0000;}
	.box3{top:300;left: 300;background-color: #00ff49;}
</style>

**Comment by to686312** [comment]
<template>
	<div class="wrapper">
		<div class="box box1">
			
		</div>

		<div class="box box2">
			
		</div>

		<div class="box box3">
			
		</div>
	</div>
</template>

<style scoped>
	.wrapper{
		position: absolute;
		top: 0;bottom: 0;right: 0;left: 0;
		background-color: #cccccc
	}
	.box{
		width: 400px;
		height: 400px;
		position: absolute;
	}
	.box1{
		top: 0;left: 0;background-color: #0055dd;
	}
	.box2{
		top: 150;left: 150;background-color: #ff0000;
	}
	.box3{
		top:300;left: 300;background-color: #00ff49;
	}
</style>`

**Comment by erha19** [comment]
Upgrade your `weex-toolkit` to the latest version and re-create your project.
